-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26282', 'Krzesło do jadalni tapicerowane szare K360', 'Krzesła/Krzesła do jadalni', 269.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k360-26282.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26291', 'Krzesło do jadalni tapicerowane bordowe K366', 'Krzesła/Krzesła do jadalni', 336.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bordowe-k366-26291.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26292', 'Krzesło do jadalni tapicerowane zielone K366', 'Krzesła/Krzesła do jadalni', 336.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k366-26292.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26293', 'Krzesło do jadalni tapicerowane szare K366', 'Krzesła/Krzesła do jadalni', 336.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k366-26293.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26298', 'Krzesło do jadalni tapicerowane beżowe K373', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k373-26298.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26299', 'Krzesło do jadalni tapicerowane szare K373', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k373-26299.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26302', 'Krzesło do jadalni tapicerowane beżowe K377', 'Krzesła/Krzesła do jadalni', 339.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k377-26302.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26304', 'Krzesło do jadalni tapicerowane szare K377', 'Krzesła/Krzesła do jadalni', 339.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k377-26304.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26307', 'Krzesło do jadalni tapicerowane zielone K379', 'Krzesła/Krzesła do jadalni', 176.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k379-26307.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26308', 'Krzesło do jadalni tapicerowane szare K379', 'Krzesła/Krzesła do jadalni', 176.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k379-26308.feed10009', 'HALMAR');
