-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27453', 'Krzesło do jadalni tapicerowane granatowe / dąb miodowy Diego 3', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-dab-miodowy-diego-3-27453.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27454', 'Krzesło do jadalni tapicerowane szare / dąb miodowy Diego 3', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-dab-miodowy-diego-3-27454.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27455', 'Krzesło do jadalni tapicerowane szare / białe Diego', 'Krzesła/Krzesła do jadalni', 335.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-biale-diego-27455.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27458', 'Krzesło do jadalni tapicerowane beżowe / dąb sonoma Diego', 'Krzesła/Krzesła do jadalni', 335.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-dab-sonoma-diego-27458.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27459', 'Ława kawowa biała mat 110 x 60 cm Nea', 'Stoliki kawowe i ławy/Ławy', 233.0, 'https://www.meblepumo.pl/pl/products/lawa-kawowa-biala-mat-110-x-60-cm-nea-27459.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27469', 'Fotel wypoczynkowy tapicerowany beżowy / dąb miodowy Filo', 'Fotele/Fotele wypoczynkowe', 549.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-bezowy-dab-miodowy-filo-27469.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27470', 'Krzesło do jadalni drewniane tapicerowane szare / białe Gerard 2', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-biale-gerard-2-27470.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27471', 'Krzesło do jadalni drewniane tapicerowane beżowe / ciemny orzech Gerard 2', 'Krzesła/Krzesła do jadalni', 295.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-ciemny-orzech-gerard-2-27471.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27475', 'Krzesło do jadalni drewniane tapicerowane beżowe / dąb sonoma Gerard 2', 'Krzesła/Krzesła do jadalni', 295.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-dab-sonoma-gerard-2-27475.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27486', 'Krzesło do jadalni drewniane tapicerowane beżowe / białe Hubert 8', 'Krzesła/Krzesła do jadalni', 255.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-biale-hubert-8-27486.feed10009', 'HALMAR');
