-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23700', 'Stolik kawowy kwadratowy dąb sękaty mat 75 x 75 cm Caldwell', 'Stoliki kawowe i ławy/Stoliki kawowe', 1099.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-dab-sekaty-mat-75-x-75-cm-caldwell-23700.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23727', 'Krzesło na płozie drewniane tapicerowane brązowe / dąb złoty K265', 'Krzesła/Krzesła na płozie', 419.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-drewniane-tapicerowane-brazowe-dab-zloty-k265-23727.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23728', 'Krzesło do jadalni ekoskóra szare Adelardo', 'Krzesła/Krzesła do jadalni', 315.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-szare-adelardo-23728.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23729', 'Krzesło do jadalni tapicerowane szare Adolfo', 'Krzesła/Krzesła do jadalni', 219.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-adolfo-23729.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23730', 'Krzesło ogrodowe rattanowe naturalne K336', 'Krzesła/Krzesła ogrodowe', 539.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-rattanowe-naturalne-k336-23730.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23732', 'Krzesło do jadalni tapicerowane szare K332', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k332-23732.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23733', 'Krzesło do jadalni tapicerowane zielone K332', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k332-23733.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23734', 'Krzesło do jadalni rattanowe naturalne K337', 'Krzesła/Krzesła do jadalni', 389.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-rattanowe-naturalne-k337-23734.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23735', 'Krzesło do jadalni rattanowe naturalne K335', 'Krzesła/Krzesła do jadalni', 469.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-rattanowe-naturalne-k335-23735.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23736', 'Krzesło do jadalni tapicerowane szare K316', 'Krzesła/Krzesła do jadalni', 199.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k316-23736.feed10009', 'HALMAR');
