-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28039', 'Łóżeczko dziecięce Dreamland 140 x 70 cm, biały mat, lite drewno bukowe ', 'Łóżka dziecięce', 899.0, 'https://www.meblepumo.pl/pl/products/lozeczko-dzieciece-dreamland-140-x-70-cm-bialy-mat-lite-drewno-bukowe-28039.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28040', 'Komoda z przewijakiem Dreamland, biały mat, lite drewno bukowe', 'Komody/Komody z drzwiami', 799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-przewijakiem-dreamland-bialy-mat-lite-drewno-bukowe-28040.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28041', 'Szafa trzydrzwiowa biała mat 130 x 190 cm Dreamland', 'Szafy/Szafy uchylne', 1869.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-biala-mat-130-x-190-cm-dreamland-28041.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28042', 'Biurko z szufladami Function Plus 2, 102 cm, jackson hickory, biały mat', 'Biurka/Biurka z szufladami i drzwiami', 599.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-function-plus-2-102-cm-jackson-hickory-bialy-mat-28042.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28044', 'Biurko z szufladami Function Plus, 100 cm, jackson hickory', 'Biurka/Biurka z szufladami i drzwiami', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-function-plus-100-cm-jackson-hickory-28044.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28047', 'Nadstawka do biurka jackson hickory 149 cm Function Plus', 'Biurka/Części do biurek', 429.0, 'https://www.meblepumo.pl/pl/products/nadstawka-do-biurka-jackson-hickory-149-cm-function-plus-28047.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28048', 'Biurko z szufladami, drzwiami jackson hickory 149 cm Function Plus', 'Biurka/Biurka z szufladami i drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-drzwiami-jackson-hickory-149-cm-function-plus-28048.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28050', 'Nadstawka do biurka biały wysoki połysk 149 cm Function Plus', 'Biurka/Części do biurek', 429.0, 'https://www.meblepumo.pl/pl/products/nadstawka-do-biurka-bialy-wysoki-polysk-149-cm-function-plus-28050.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28051', 'Biurko z szufladami, drzwiami biały wysoki połysk 149 cm Function Plus', 'Biurka/Biurka z szufladami i drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-drzwiami-bialy-wysoki-polysk-149-cm-function-plus-28051.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28053', 'Regał biurowy szary mat 80 x 34 x 205 cm Sign', 'Regały', 679.0, 'https://www.meblepumo.pl/pl/products/regal-biurowy-szary-mat-80-x-34-x-205-cm-sign-28053.feed10009', 'Tvilum');
