-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27895', 'Szafa czterodrzwiowa jackson hickory mat 195 x 200 cm Billund', 'Szafy/Szafy uchylne', 1919.0, 'https://www.meblepumo.pl/pl/products/szafa-czterodrzwiowa-jackson-hickory-mat-195-x-200-cm-billund-27895.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27896', 'Regał biurowy jackson hickory / biały mat 80 x 34 x 205 cm Sign', 'Regały', 699.0, 'https://www.meblepumo.pl/pl/products/regal-biurowy-jackson-hickory-bialy-mat-80-x-34-x-205-cm-sign-27896.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27897', 'Regał biurowy szary / jackson hickory mat 80 x 34 x 205 cm Sign', 'Regały', 649.0, 'https://www.meblepumo.pl/pl/products/regal-biurowy-szary-jackson-hickory-mat-80-x-34-x-205-cm-sign-27897.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27898', 'Kontenerek pod biurko jackson hickory / biały mat 41 x 48 x 61 cm Sign', 'Kontenerki', 429.0, 'https://www.meblepumo.pl/pl/products/kontenerek-pod-biurko-jackson-hickory-bialy-mat-41-x-48-x-61-cm-sign-27898.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27899', 'Kontenerek pod biurko szary / jackson hickory mat 41 x 48 x 61 cm Sign', 'Kontenerki', 449.0, 'https://www.meblepumo.pl/pl/products/kontenerek-pod-biurko-szary-jackson-hickory-mat-41-x-48-x-61-cm-sign-27899.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27900', 'Komoda z szufladami i drzwiami szara mat 147 cm Bodo', 'Komody/Komody z szufladami i drzwiami', 839.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-szara-mat-147-cm-bodo-27900.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27901', 'Komoda z szufladami i drzwiami biała mat 147 cm Bodo', 'Komody/Komody z szufladami i drzwiami', 769.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-mat-147-cm-bodo-27901.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27902', 'Szafka na buty biała mat 70 cm Bodo', 'Szafki na buty', 579.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-biala-mat-70-cm-bodo-27902.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27903', 'Szafka na buty szara mat 70 cm Bodo', 'Szafki na buty', 599.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-szara-mat-70-cm-bodo-27903.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27904', 'Szafka RTV biała / dąb mat 117 cm Bodo', 'Szafki RTV', 423.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-mat-117-cm-bodo-27904.feed10009', 'Tvilum');
