-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24459', 'Materac piankowy 160x200 cm Siesta', 'Materace/Materace piankowe', 829.0, 'https://www.meblepumo.pl/pl/products/materac-piankowy-160x200-cm-siesta-24459.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24460', 'Materac piankowy 180x200 cm Siesta', 'Materace/Materace piankowe', 929.0, 'https://www.meblepumo.pl/pl/products/materac-piankowy-180x200-cm-siesta-24460.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24461', 'Materac sprężynowy kieszeniowy 90x200 cm Set', 'Materace/Materace sprężynowe kieszeniowe', 1199.0, 'https://www.meblepumo.pl/pl/products/materac-sprezynowy-kieszeniowy-90x200-cm-set-24461.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24462', 'Materac sprężynowy kieszeniowy 140x190 cm Set', 'Materace/Materace sprężynowe kieszeniowe', 1799.0, 'https://www.meblepumo.pl/pl/products/materac-sprezynowy-kieszeniowy-140x190-cm-set-24462.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24463', 'Materac sprężynowy kieszeniowy 140x200 cm Set', 'Materace/Materace sprężynowe kieszeniowe', 1799.0, 'https://www.meblepumo.pl/pl/products/materac-sprezynowy-kieszeniowy-140x200-cm-set-24463.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24464', 'Materac sprężynowy kieszeniowy 160x200 cm Set', 'Materace/Materace sprężynowe kieszeniowe', 1899.0, 'https://www.meblepumo.pl/pl/products/materac-sprezynowy-kieszeniowy-160x200-cm-set-24464.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24465', 'Materac sprężynowy kieszeniowy 180x200 cm Set', 'Materace/Materace sprężynowe kieszeniowe', 1999.0, 'https://www.meblepumo.pl/pl/products/materac-sprezynowy-kieszeniowy-180x200-cm-set-24465.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24475', 'Szafka RTV biała mat / połysk 200 cm Sierra', 'Szafki RTV', 1069.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-polysk-200-cm-sierra-24475.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24476', 'Szafka RTV biała mat / połysk 150 cm Sierra', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-polysk-150-cm-sierra-24476.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24477', 'Komoda z drzwiami biała mat / wysoki połysk 150 cm Sierra', 'Komody/Komody z drzwiami', 1069.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-wysoki-polysk-150-cm-sierra-24477.feed10009', 'High Glossy Furniture');
