-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10440', 'Oświetlenie 5 LED białe High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 109.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-5-led-biale-high-glossy-furniture-10440.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10441', 'Oświetlenie LED 6 punktowe białe, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 119.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-6-punktowe-biale-high-glossy-furniture-10441.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10442', 'Oświetlenie LED 6 punktowe zielone, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 119.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-6-punktowe-zielone-high-glossy-furniture-10442.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10443', 'Oświetlenie LED 6 punktowe czerwone, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 119.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-6-punktowe-czerwone-high-glossy-furniture-10443.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10444', 'Oświetlenie LED 6 punktowe niebieskie, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 119.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-6-punktowe-niebieskie-high-glossy-furniture-10444.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10445', 'Oświetlenie 7 LED niebieskie High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-7-led-niebieskie-high-glossy-furniture-10445.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10446', 'Oświetlenie 7 LED czerwone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-7-led-czerwone-high-glossy-furniture-10446.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10447', 'Oświetlenie 7 LED zielone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-7-led-zielone-high-glossy-furniture-10447.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10448', 'Oświetlenie 7 LED białe High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-7-led-biale-high-glossy-furniture-10448.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10461', 'LED klejony niebieski + zasilacz High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 99.0, 'https://www.meblepumo.pl/pl/products/led-klejony-niebieski-zasilacz-high-glossy-furniture-10461.feed10009', 'High Glossy Furniture');
