-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28190', 'Witryna jednodrzwiowa miętowa mat 40 x 102 cm Milton', 'Witryny i kredensy/Witryny', 789.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-mietowa-mat-40-x-102-cm-milton-28190.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28191', 'Witryna dwudrzwiowa miętowa mat 80 x 102 cm Milton', 'Witryny i kredensy/Witryny', 1489.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-mietowa-mat-80-x-102-cm-milton-28191.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28192', 'Witryna dwudrzwiowa miętowa mat 80 x 160 cm Milton', 'Witryny i kredensy/Witryny', 1979.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-mietowa-mat-80-x-160-cm-milton-28192.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28193', 'Komoda z szufladami i drzwiami zielona mat 100 cm Aurelia', 'Komody/Komody z szufladami i drzwiami', 899.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-zielona-mat-100-cm-aurelia-28193.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28194', 'Komoda z drzwiami zielona mat 100 cm Aurelia', 'Komody/Komody z drzwiami', 1049.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-zielona-mat-100-cm-aurelia-28194.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28195', 'Komoda z szufladami zielona mat 50 cm Aurelia', 'Komody/Komody z szufladami', 879.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-zielona-mat-50-cm-aurelia-28195.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28196', 'Szafka RTV zielona mat 150 cm Aurelia', 'Szafki RTV', 839.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-zielona-mat-150-cm-aurelia-28196.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28197', 'Komplet szafek nocnych zielony mat 44 cm Aurelia', 'Szafki nocne', 669.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-zielony-mat-44-cm-aurelia-28197.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28198', 'Stolik kawowy zielony mat 100 x 60 cm Aurelia', 'Stoliki kawowe i ławy/Stoliki kawowe', 599.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-zielony-mat-100-x-60-cm-aurelia-28198.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28199', 'Stolik kawowy beżowy mat 100 x 60 cm Aurelia', 'Stoliki kawowe i ławy/Stoliki kawowe', 589.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-bezowy-mat-100-x-60-cm-aurelia-28199.feed10009', 'High Glossy Furniture');
