-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26419', 'Krzesło do jadalni tapicerowane granatowe K443', 'Krzesła/Krzesła do jadalni', 328.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k443-26419.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26425', 'Krzesło do jadalni tapicerowane granatowe K446', 'Krzesła/Krzesła do jadalni', 319.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k446-26425.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26426', 'Krzesło do jadalni tapicerowane szare K446', 'Krzesła/Krzesła do jadalni', 319.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k446-26426.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26433', 'Krzesło do jadalni tapicerowane granatowe K450', 'Krzesła/Krzesła do jadalni', 235.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k450-26433.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26434', 'Krzesło do jadalni tapicerowane musztardowe K450', 'Krzesła/Krzesła do jadalni', 235.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k450-26434.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26435', 'Krzesło do jadalni tapicerowane szare K450', 'Krzesła/Krzesła do jadalni', 235.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k450-26435.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26439', 'Krzesło do jadalni tapicerowane granatowe K453', 'Krzesła/Krzesła do jadalni', 242.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k453-26439.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26442', 'Krzesło do jadalni tapicerowane zielone K455', 'Krzesła/Krzesła do jadalni', 325.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k455-26442.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26449', 'Krzesło do jadalni tapicerowane szare K460', 'Krzesła/Krzesła do jadalni', 316.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k460-26449.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26450', 'Krzesło do jadalni tapicerowane różowe K460', 'Krzesła/Krzesła do jadalni', 316.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-rozowe-k460-26450.feed10009', 'HALMAR');
