-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19324', 'Wieszak stojący miedziany połysk 180 cm W57', 'Wieszaki na ubrania/Wieszaki stojące', 539.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-miedziany-polysk-180-cm-w57-19324.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19328', 'Wieszak stojący czarny mat 180 cm W56', 'Wieszaki na ubrania/Wieszaki stojące', 399.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-czarny-mat-180-cm-w56-19328.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19330', 'Wieszak stojący biały mat 176 cm W33', 'Wieszaki na ubrania/Wieszaki stojące', 229.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-bialy-mat-176-cm-w33-19330.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19331', 'Wieszak stojący czarny mat 176 cm W33', 'Wieszaki na ubrania/Wieszaki stojące', 209.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-czarny-mat-176-cm-w33-19331.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19333', 'Wieszak drewniany stojący olcha mat 188 cm W30', 'Wieszaki na ubrania/Wieszaki stojące', 196.0, 'https://www.meblepumo.pl/pl/products/wieszak-drewniany-stojacy-olcha-mat-188-cm-w30-19333.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19334', 'Wieszak stojący srebrny mat 180 cm W46', 'Wieszaki na ubrania/Wieszaki stojące', 159.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-srebrny-mat-180-cm-w46-19334.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19335', 'Wieszak stojący srebrny połysk 181 cm W24', 'Wieszaki na ubrania/Wieszaki stojące', 216.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-srebrny-polysk-181-cm-w24-19335.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19371', 'Fotel obrotowy młodzieżowy tapicerowany graffiti Ibis Freestyle', 'Fotele/Fotele młodzieżowe', 299.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-graffiti-ibis-freestyle-19371.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19388', 'Fotel biurowy siatka szary / czarny Valor', 'Fotele/Fotele do biurka', 349.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-szary-czarny-valor-19388.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19396', 'Fotel biurowy siatka szary / czarny Vire 2', 'Fotele/Fotele do biurka', 369.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-szary-czarny-vire-2-19396.feed10009', 'HALMAR');
