-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26365', 'Krzesło do jadalni tapicerowane szare K417', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k417-26365.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26378', 'Krzesło do jadalni tapicerowane zielone K426', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k426-26378.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26379', 'Krzesło do jadalni tapicerowane czarne K426', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k426-26379.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26380', 'Krzesło do jadalni tapicerowane szare K426', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k426-26380.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26384', 'Krzesło do jadalni tapicerowane zielone K429', 'Krzesła/Krzesła do jadalni', 349.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k429-26384.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26386', 'Krzesło do jadalni tapicerowane szare K429', 'Krzesła/Krzesła do jadalni', 349.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k429-26386.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26387', 'Krzesło do jadalni tapicerowane zielone K430', 'Krzesła/Krzesła do jadalni', 332.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k430-26387.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26388', 'Krzesło do jadalni tapicerowane granatowe K430', 'Krzesła/Krzesła do jadalni', 332.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k430-26388.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26389', 'Krzesło do jadalni tapicerowane musztardowe K430', 'Krzesła/Krzesła do jadalni', 332.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k430-26389.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26390', 'Krzesło do jadalni tapicerowane szare K430', 'Krzesła/Krzesła do jadalni', 332.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k430-26390.feed10009', 'HALMAR');
