-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28593', 'Witryna dwudrzwiowa z szufladami biała wysoki połysk 119 x 192 cm Roma', 'Witryny i kredensy/Witryny', 1599.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-biala-wysoki-polysk-119-x-192-cm-roma-28593.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28594', 'Witryna jednodrzwiowa z szufladami biała wysoki połysk 59 x 192 cm Roma', 'Witryny i kredensy/Witryny', 1099.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-biala-wysoki-polysk-59-x-192-cm-roma-28594.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28595', 'Szafka RTV biała wysoki połysk 179 cm Roma', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-wysoki-polysk-179-cm-roma-28595.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28596', 'Szafka RTV beżowoszara / drewno akacjowe mat 200 cm Cavo', 'Szafki RTV', 2349.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowoszara-drewno-akacjowe-mat-200-cm-cavo-28596.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28597', 'Szafka RTV beżowoszara / drewno akacjowe mat 173 cm Cavo', 'Szafki RTV', 2029.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowoszara-drewno-akacjowe-mat-173-cm-cavo-28597.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28598', 'Komoda z szufladami i drzwiami beżowoszara / drewno akacjowe mat 200 cm Cavo', 'Komody/Komody z szufladami i drzwiami', 2649.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-bezowoszara-drewno-akacjowe-mat-200-cm-cavo-28598.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28599', 'Komoda z szufladami i drzwiami beżowoszara / drewno akacjowe mat 150 cm Cavo', 'Komody/Komody z szufladami i drzwiami', 2339.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-bezowoszara-drewno-akacjowe-mat-150-cm-cavo-28599.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28600', 'Komoda z szufladami i drzwiami beżowoszara / drewno akacjowe mat 100 cm Cavo', 'Komody/Komody z szufladami i drzwiami', 1829.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-bezowoszara-drewno-akacjowe-mat-100-cm-cavo-28600.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28601', 'Komoda wysoka z drzwiami beżowoszara / drewno akacjowe mat 113 cm Cavo', 'Komody/Komody z drzwiami', 1839.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-bezowoszara-drewno-akacjowe-mat-113-cm-cavo-28601.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28602', 'Komoda z drzwiami kaszmir mat 200 cm Linoa', 'Komody/Komody z drzwiami', 1379.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-200-cm-linoa-28602.feed10009', 'High Glossy Furniture');
