-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27488', 'Krzesło do jadalni drewniane tapicerowane szare / dąb miodowy Hubert 8', 'Krzesła/Krzesła do jadalni', 239.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-dab-miodowy-hubert-8-27488.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27497', 'Krzesło do jadalni drewniane tapicerowane szare / dąb miodowy Konrad', 'Krzesła/Krzesła do jadalni', 339.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-dab-miodowy-konrad-27497.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27498', 'Krzesło do jadalni drewniane tapicerowane beżowe / dąb sonoma Konrad', 'Krzesła/Krzesła do jadalni', 339.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-dab-sonoma-konrad-27498.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27508', 'Krzesło do jadalni tapicerowane beżowe / dąb sonoma Paweł', 'Krzesła/Krzesła do jadalni', 229.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-dab-sonoma-pawel-27508.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27520', 'Krzesło do jadalni tapicerowane zielone / dąb miodowy Toledo 2', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-dab-miodowy-toledo-2-27520.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27521', 'Krzesło do jadalni tapicerowane granatowe / dąb miodowy Toledo 2', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-dab-miodowy-toledo-2-27521.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27523', 'Krzesło do jadalni tapicerowane szare / dąb miodowy Toledo 2', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-dab-miodowy-toledo-2-27523.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27525', 'Krzesło do jadalni tapicerowane szare / grafitowe Toledo 2', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-grafitowe-toledo-2-27525.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27526', 'Krzesło do jadalni tapicerowane zielone / czarne Toledo 3', 'Krzesła/Krzesła do jadalni', 517.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-czarne-toledo-3-27526.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27529', 'Krzesło do jadalni tapicerowane szare / białe Toledo', 'Krzesła/Krzesła do jadalni', 469.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-biale-toledo-27529.feed10009', 'HALMAR');
