-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24083', 'Komoda z szufladami i drzwiami dąb / antracyt mat 164 cm Forest', 'Komody/Komody z szufladami i drzwiami', 1359.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-antracyt-mat-164-cm-forest-24083.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24154', 'Krzesło na płozie tapicerowane ciemnoszare Loreto', 'Krzesła/Krzesła na płozie', 749.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-ciemnoszare-loreto-24154.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24155', 'Krzesło na płozie tapicerowane szare Loreto', 'Krzesła/Krzesła na płozie', 749.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-szare-loreto-24155.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24156', 'Krzesło na płozie tapicerowane bordowe Loreto', 'Krzesła/Krzesła na płozie', 749.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-bordowe-loreto-24156.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24187', 'Szafka RTV dąb / antracyt mat 160 cm Denver', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-antracyt-mat-160-cm-denver-24187.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24190', 'Komoda z drzwiami biała wysoki połysk 180 cm Pure', 'Komody/Komody z drzwiami', 1499.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-180-cm-pure-24190.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24191', 'Komoda z szufladami i drzwiami biała wysoki połysk 210 cm Pure', 'Komody/Komody z szufladami i drzwiami', 1619.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-210-cm-pure-24191.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24192', 'Szafka RTV biała połysk 139 cm Pure', 'Szafki RTV', 799.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-139-cm-pure-24192.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24193', 'Komoda z drzwiami biała wysoki połysk 92 cm Pure', 'Komody/Komody z drzwiami', 1199.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-92-cm-pure-24193.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24220', 'Witryna jednodrzwiowa z szufladami dąb lefkas mat 60 x 192 cm Site', 'Witryny i kredensy/Witryny', 789.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-dab-lefkas-mat-60-x-192-cm-site-24220.feed10009', 'Style Furniture');
