-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25579', 'FLEX system szaf modułowych - KORPUS K2 biały', 'halmar tymczasowa', 498.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-korpus-k2-bialy-25579.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25582', 'FLEX system szaf modułowych - KORPUS K4 dąb artisan', 'halmar tymczasowa', 813.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-korpus-k4-dab-artisan-25582.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25583', 'FLEX system szaf modułowych - KORPUS K4 biały', 'halmar tymczasowa', 743.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-korpus-k4-bialy-25583.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25584', 'FLEX system szaf modułowych - KORPUS K5 dąb artisan', 'halmar tymczasowa', 1159.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-korpus-k5-dab-artisan-25584.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25586', 'FLEX system szaf modułowych - KORPUS K6 dąb artisan', 'halmar tymczasowa', 1124.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-korpus-k6-dab-artisan-25586.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25590', 'FLEX system szaf modułowych - UCHWYT U1 biały', 'halmar tymczasowa', 5.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-uchwyt-u1-bialy-25590.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25591', 'FLEX system szaf modułowych - UCHWYT U1 czarny', 'halmar tymczasowa', 5.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-uchwyt-u1-czarny-25591.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25593', 'Zestaw mebli kuchennych dąb sonoma / orzech / kaszmir 240 cm Tatiana', 'Zestawy mebli/Zestawy mebli kuchennych', 1729.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-dab-sonoma-orzech-kaszmir-240-cm-tatiana-25593.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25594', 'Szafka RTV biała mat 200 cm Lukka', 'Szafki RTV', 1169.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-200-cm-lukka-25594.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25595', 'Komoda z drzwiami biała mat 200 cm Lukka', 'Komody/Komody z drzwiami', 1098.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-200-cm-lukka-25595.feed10009', 'High Glossy Furniture');
