-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28340', 'Stolik kawowy okrągły szklany / dąb 75 x 40 cm Luno', 'Stoliki kawowe i ławy/Stoliki kawowe', 549.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-szklany-dab-75-x-40-cm-luno-28340.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28341', 'Komoda z drzwiami dąb 170 cm Loftis', 'Komody/Komody z drzwiami', 1249.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-170-cm-loftis-28341.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28342', 'Stół nierozkładany dąb 160 x 90 cm Loftis', 'Stoly/Stoły nierozkładane', 1499.0, 'https://www.meblepumo.pl/pl/products/stol-nierozkladany-dab-160-x-90-cm-loftis-28342.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28343', 'Szafka RTV dąb 180 cm Loftis', 'Szafki RTV', 1169.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-180-cm-loftis-28343.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28344', 'Regał do salonu dąb 80 x 40 x 172 cm Loftis', 'Regały', 779.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-dab-80-x-40-x-172-cm-loftis-28344.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28346', 'Stół okrągły dąb 121 cm Loftis', 'Stoly/Stoły nierozkładane', 1109.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-dab-121-cm-loftis-28346.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28347', 'Stół nierozkładany dąb 200 x 90 cm Loftis', 'Stoly/Stoły nierozkładane', 1709.0, 'https://www.meblepumo.pl/pl/products/stol-nierozkladany-dab-200-x-90-cm-loftis-28347.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28348', 'Stolik kawowy okrągły dąb mat 80 cm Loftis', 'Stoliki kawowe i ławy/Stoliki kawowe', 679.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dab-mat-80-cm-loftis-28348.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28349', 'Zestaw 2 stolików kawowych okrągłych dąb / czarny mat 70 cm, 50 cm Loftis', 'Stoliki kawowe i ławy/Stoliki kawowe', 469.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-dab-czarny-mat-70-cm-50-cm-loftis-28349.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28350', 'Komoda z drzwiami jesion czarny 170 cm Loftis', 'Komody/Komody z drzwiami', 1249.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-jesion-czarny-170-cm-loftis-28350.feed10009', 'TT-furniture');
