-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25523', 'Zagłówek do łóżka beżowy 175x120 cm Modulo W4', 'Łóżka i części/Części do łóżek', 739.0, 'https://www.meblepumo.pl/pl/products/zaglowek-do-lozka-bezowy-175x120-cm-modulo-w4-25523.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25526', 'Zagłówek do łóżka musztardowy 175x120 cm Modulo W4', 'Łóżka i części/Części do łóżek', 739.0, 'https://www.meblepumo.pl/pl/products/zaglowek-do-lozka-musztardowy-175x120-cm-modulo-w4-25526.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25528', 'Zagłówek do łóżka beżowy 175x120 cm Modulo W5', 'Łóżka i części/Części do łóżek', 739.0, 'https://www.meblepumo.pl/pl/products/zaglowek-do-lozka-bezowy-175x120-cm-modulo-w5-25528.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25533', 'MURANO S-1 szafa dąb artisan/czarny', 'halmar tymczasowa', 1899.0, 'https://www.meblepumo.pl/pl/products/murano-s-1-szafa-dab-artisan-czarny-25533.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25535', 'Krzesło do jadalni tapicerowane brązowe Clarion 2', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-brazowe-clarion-2-25535.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25537', 'Krzesło do jadalni tapicerowane brązowe Diego 3', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-brazowe-diego-3-25537.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25545', 'Krzesło do jadalni velvet szare / dąb Vermont', 'Krzesła/Krzesła do jadalni', 468.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-velvet-szare-dab-vermont-25545.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25552', 'RANDOM RTV-3 stolik RTV 200 cm dąb wotan/czarny', 'halmar tymczasowa', 949.0, 'https://www.meblepumo.pl/pl/products/random-rtv-3-stolik-rtv-200-cm-dab-wotan-czarny-25552.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25554', 'RANDOM S-1 szafa dąb wotan/czarny', 'halmar tymczasowa', 1459.0, 'https://www.meblepumo.pl/pl/products/random-s-1-szafa-dab-wotan-czarny-25554.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25555', 'Stół rozkładany dąb craft / biały mat 102 - 142 x 102 cm Ringo', 'Stoly/Stoły rozkładane', 685.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-craft-bialy-mat-102-142-x-102-cm-ringo-25555.feed10009', 'HALMAR');
