-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23525', 'Fotel obrotowy młodzieżowy ekoskóra czarny Tirol', 'Fotele/Fotele młodzieżowe', 349.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-ekoskora-czarny-tirol-23525.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23538', 'Sofa 3-osobowa tapicerowana fioletowa Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-fioletowa-holly-23538.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23539', 'Sofa 3-osobowa tapicerowana brązowa Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-brazowa-holly-23539.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23540', 'Sofa 3-osobowa tapicerowana różowa Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-rozowa-holly-23540.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23541', 'Sofa 3-osobowa tapicerowana błękitna Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-blekitna-holly-23541.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23542', 'Sofa 3-osobowa tapicerowana niebieska Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-niebieska-holly-23542.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23543', 'Sofa 3-osobowa tapicerowana miętowa Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-mietowa-holly-23543.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23544', 'Sofa 3-osobowa tapicerowana szara Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-szara-holly-23544.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23546', 'Sofa 3-osobowa tapicerowana grafitowa Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-grafitowa-holly-23546.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23547', 'Sofa 3-osobowa tapicerowana zielona Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-zielona-holly-23547.feed10009', 'Scandinavian Style Design');
