-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28257', 'Komoda z drzwiami kaszmir mat 150 cm Aria', 'Komody/Komody z drzwiami', 1159.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-150-cm-aria-28257.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28258', 'Komoda z drzwiami czarna mat 150 cm Aria', 'Komody/Komody z drzwiami', 1159.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-150-cm-aria-28258.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28259', 'Komoda z drzwiami biała mat 190 cm Aria', 'Komody/Komody z drzwiami', 1339.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-190-cm-aria-28259.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28260', 'Komoda z drzwiami kaszmir mat 190 cm Aria', 'Komody/Komody z drzwiami', 1369.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-190-cm-aria-28260.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28261', 'Komoda z drzwiami czarna mat 190 cm Aria', 'Komody/Komody z drzwiami', 1369.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-190-cm-aria-28261.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28262', 'Witryna czterodrzwiowa biała mat 110 x 40 x 160 cm Aria', 'Witryny i kredensy/Witryny', 1849.0, 'https://www.meblepumo.pl/pl/products/witryna-czterodrzwiowa-biala-mat-110-x-40-x-160-cm-aria-28262.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28263', 'Witryna czterodrzwiowa kaszmir mat 110 x 40 x 160 cm Aria', 'Witryny i kredensy/Witryny', 1869.0, 'https://www.meblepumo.pl/pl/products/witryna-czterodrzwiowa-kaszmir-mat-110-x-40-x-160-cm-aria-28263.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28264', 'Witryna czterodrzwiowa czarna mat 110 x 40 x 160 cm Aria', 'Witryny i kredensy/Witryny', 1869.0, 'https://www.meblepumo.pl/pl/products/witryna-czterodrzwiowa-czarna-mat-110-x-40-x-160-cm-aria-28264.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28265', 'Szafka RTV biała mat 190 cm Aria', 'Szafki RTV', 969.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-190-cm-aria-28265.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28266', 'Szafka RTV kaszmir mat 190 cm Aria', 'Szafki RTV', 979.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-190-cm-aria-28266.feed10009', 'High Glossy Furniture');
