-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25661', 'Fotel wypoczynkowy velvet szary Angelo', 'Fotele/Fotele wypoczynkowe', 814.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-szary-angelo-25661.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25662', 'Fotel wypoczynkowy velvet różowy / czarny Angelo', 'Fotele/Fotele wypoczynkowe', 814.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-rozowy-czarny-angelo-25662.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25663', 'Łóżko tapicerowane z pojemnikiem szare 160x200 cm Annabel', 'Łóżka i części/Łóżka', 1599.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-pojemnikiem-szare-160x200-cm-annabel-25663.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25665', 'Stolik kawowy okrągły czarny marmur / czarny mat 80 cm Antica', 'Stoliki kawowe i ławy/Stoliki kawowe', 419.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-czarny-marmur-czarny-mat-80-cm-antica-25665.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25666', 'Stolik kawowy okrągły biały marmur / czarny mat 55 cm Antica', 'Stoliki kawowe i ławy/Stoliki kawowe', 287.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bialy-marmur-czarny-mat-55-cm-antica-25666.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25669', 'Stół szklany czarny połysk 140 x 80 cm Anton', 'Stoly/Stoły nierozkładane', 719.0, 'https://www.meblepumo.pl/pl/products/stol-szklany-czarny-polysk-140-x-80-cm-anton-25669.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25671', 'Pufa Aqua tkanina velvet jasny różowy, podstawa stal nierdzewna srebrna', 'Pufy', 277.0, 'https://www.meblepumo.pl/pl/products/pufa-aqua-tkanina-velvet-jasny-rozowy-podstawa-stal-nierdzewna-srebrna-25671.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25673', 'Fotel biurowy tapicerowany szary Arctic', 'Fotele/Fotele do biurka', 423.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-szary-arctic-25673.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25674', 'Fotel gabinetowy tapicerowany szary Arezzo', 'Fotele/Fotele do biurka', 619.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-szary-arezzo-25674.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25681', 'Stolik kawowy z pólką dąb złoty / czarny mat 105 x 55 cm Artiga', 'Stoliki kawowe i ławy/Stoliki kawowe', 389.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-zloty-czarny-mat-105-x-55-cm-artiga-25681.feed10009', 'HALMAR');
