-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28277', 'Biurko Madrid 120 x 48 x 76 cm, 3 szuflady, jackson hickory', 'Biurka/Biurka z szufladami i drzwiami', 899.0, 'https://www.meblepumo.pl/pl/products/biurko-madrid-120-x-48-x-76-cm-3-szuflady-jackson-hickory-28277.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28278', 'Szafka na buty jackson hickory mat 102 cm Madrid', 'Szafki na buty', 929.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-jackson-hickory-mat-102-cm-madrid-28278.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28279', 'Komoda z szufladami i drzwiami jackson hickory 151 cm Madrid', 'Komody/Komody z szufladami i drzwiami', 1129.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-jackson-hickory-151-cm-madrid-28279.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28280', 'Witryna dwudrzwiowa z szufladami jackson hickory mat 78 x 199 cm Madrid', 'Witryny i kredensy/Witryny', 1529.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-jackson-hickory-mat-78-x-199-cm-madrid-28280.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28281', 'Stolik kawowy z półką jackson hickory mat 81 x 81 cm Madrid', 'Stoliki kawowe i ławy/Stoliki kawowe', 539.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-jackson-hickory-mat-81-x-81-cm-madrid-28281.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28282', 'Szafka RTV jackson hickory mat 151 cm Madrid', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-jackson-hickory-mat-151-cm-madrid-28282.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28283', 'Regał na książki jackson hickory 78 x 33 x 199 cm Madrid', 'Regały', 999.0, 'https://www.meblepumo.pl/pl/products/regal-na-ksiazki-jackson-hickory-78-x-33-x-199-cm-madrid-28283.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28284', 'Szafka na buty jackson hickory mat 54 cm Madrid', 'Szafki na buty', 529.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-jackson-hickory-mat-54-cm-madrid-28284.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28285', 'Komoda z szufladami jackson hickory mat 159 cm Madrid', 'Komody/Komody z szufladami', 1429.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-jackson-hickory-mat-159-cm-madrid-28285.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28286', 'Szafka nocna jackson hickory mat 44 cm Madrid', 'Szafki nocne', 439.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-jackson-hickory-mat-44-cm-madrid-28286.feed10009', 'Tvilum');
