-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18425', 'Sofa 2-osobowa z funkcją spania tapicerowana pomarańczowa Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-pomaranczowa-derry-18425.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18426', 'Sofa 2-osobowa z funkcją spania tapicerowana różowa Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-rozowa-derry-18426.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18427', 'Stolik kawowy z półką biały / dąb sonoma mat 60 x 60 cm Livorno', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-bialy-dab-sonoma-mat-60-x-60-cm-livorno-18427.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18429', 'Szafa dwudrzwiowa z szufladami biała / dąb sonoma mat 110 x 190 cm Livorno', 'Szafy/Szafy uchylne', 1129.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-z-szufladami-biala-dab-sonoma-mat-110-x-190-cm-livorno-18429.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18451', 'Sofa 2-osobowa z funkcją spania tapicerowana turkusowa Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3599.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-turkusowa-derry-18451.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18457', 'Komoda wysoka z drzwiami biała mat 106 cm Paradise', 'Pozostałe produkty', 2199.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-mat-106-cm-paradise-18457.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18458', 'Komoda wysoka z drzwiami beton / biała mat 106 cm Paradise', 'Pozostałe produkty', 2279.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-beton-biala-mat-106-cm-paradise-18458.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18459', 'Komoda szeroka z drzwiami biała mat 207 cm Paradise', 'Pozostałe produkty', 2049.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-biala-mat-207-cm-paradise-18459.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18460', 'Komoda szeroka z drzwiami beton / biała mat 207 cm Paradise', 'Pozostałe produkty', 2399.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-beton-biala-mat-207-cm-paradise-18460.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18467', 'Witryna dwudrzwiowa biała / szara mat 106 x 171 cm Paradise', 'Pozostałe produkty', 1236.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-biala-szara-mat-106-x-171-cm-paradise-18467.feed10009', 'Italia Trend');
