-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28414', 'Komoda wysoka z szufladami i drzwiami kaszmir / dąb mat 93 cm Avolo', 'Komody/Komody z szufladami i drzwiami', 1149.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-i-drzwiami-kaszmir-dab-mat-93-cm-avolo-28414.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28415', 'Szafka wisząca kaszmir / dąb mat 40 cm Avolo', 'Szafki', 465.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-kaszmir-dab-mat-40-cm-avolo-28415.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28416', 'Półka wisząca kaszmir / dąb Evoke mat 140 x 20 cm Avolo', 'Półki wiszące', 179.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-kaszmir-dab-evoke-mat-140-x-20-cm-avolo-28416.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28417', 'Szafka RTV kaszmir / dąb mat 200 cm Avolo', 'Szafki RTV', 1099.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-dab-mat-200-cm-avolo-28417.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28418', 'Stolik kawowy z szufladą kaszmir / dąb mat 110 x 68 cm Avolo', 'Stoliki kawowe i ławy/Stoliki kawowe', 679.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-kaszmir-dab-mat-110-x-68-cm-avolo-28418.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28419', 'Stolik kawowy okrągły niebieski połysk 80 cm Soraya', 'Stoliki kawowe i ławy/Stoliki kawowe', 669.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-niebieski-polysk-80-cm-soraya-28419.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28420', 'Stolik kawowy okrągły bordowy połysk 50 cm Loca', 'Stoliki kawowe i ławy/Stoliki kawowe', 335.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bordowy-polysk-50-cm-loca-28420.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28422', 'Toaletka z lustrem LED kaszmir mat 120 cm Hollywood 2 XL', 'Toaletki i konsole/Toaletki', 1219.0, 'https://www.meblepumo.pl/pl/products/toaletka-z-lustrem-led-kaszmir-mat-120-cm-hollywood-2-xl-28422.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28423', 'Biurko z szufladami i półkami białe mat 124 cm Bega', 'Biurka/Biurka narożne', 389.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-polkami-biale-mat-124-cm-bega-28423.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28424', 'Stolik kawowy okrągły cynamonowy / naturalny mat 40 cm Gina', 'Stoliki kawowe i ławy/Stoliki kawowe', 209.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-cynamonowy-naturalny-mat-40-cm-gina-28424.feed10009', 'HALMAR');
