-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24270', 'Lustro do przedpokoju dąb 50 x 120 cm Mango', 'Lustra', 329.0, 'https://www.meblepumo.pl/pl/products/lustro-do-przedpokoju-dab-50-x-120-cm-mango-24270.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24271', 'Stolik kawowy z szufladami czarny mat 120 x 60 cm Lavre', 'Stoliki kawowe i ławy/Stoliki kawowe', 1199.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szufladami-czarny-mat-120-x-60-cm-lavre-24271.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24274', 'Komoda z szufladami czarna mat 154 cm Naia', 'Komody/Komody z szufladami', 1159.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-mat-154-cm-naia-24274.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24275', 'Komoda z szufladami i drzwiami czarna mat 121 cm Naia', 'Komody/Komody z szufladami i drzwiami', 1299.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-czarna-mat-121-cm-naia-24275.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24276', 'Komoda z szufladami czarna mat 40 cm Naia', 'Komody/Komody z szufladami', 449.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-mat-40-cm-naia-24276.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24279', 'Stolik kawowy z półką dąb wotan / czarny mat 110 x 60 cm North', 'Stoliki kawowe i ławy/Stoliki kawowe', 479.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-wotan-czarny-mat-110-x-60-cm-north-24279.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24281', 'Wieszak ścienny dąb mat 22 cm Mango', 'Wieszaki na ubrania/Wieszaki ścienne', 319.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-mat-22-cm-mango-24281.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24292', 'Stolik kawowy okrągły drewno akacjowe / czarny mat 90 cm Marawi', 'Stoliki kawowe i ławy/Stoliki kawowe', 919.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-drewno-akacjowe-czarny-mat-90-cm-marawi-24292.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24298', 'Stolik kawowy z szufladami biały / czarny mat 120 x 60 cm Lavre', 'Stoliki kawowe i ławy/Stoliki kawowe', 1199.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szufladami-bialy-czarny-mat-120-x-60-cm-lavre-24298.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24299', 'Krzesło do jadalni drewniane tapicerowane dąb / czarne Snug', 'Krzesła/Krzesła do jadalni', 899.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-dab-czarne-snug-24299.feed10009', 'Manufaktura polskiego designu ');
