-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16955', 'Sofa 2-osobowa tapicerowana żółta Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-zolta-lily-16955.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16956', 'Sofa 2-osobowa tapicerowana turkusowa Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-turkusowa-lily-16956.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16958', 'Szezlong lewostronny tapicerowany welurowy beżowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-welurowy-bezowy-lily-16958.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16959', 'Szezlong prawostronny tapicerowany welurowy czerwony Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-welurowy-czerwony-lily-16959.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16960', 'Lily szezlong lewy, czerwony', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-welurowy-czerwony-lily-16960.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16961', 'Szezlong prawostronny tapicerowany welurowy fioletowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-welurowy-fioletowy-lily-16961.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16962', 'Szezlong lewostronny tapicerowany welurowy fioletowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-welurowy-fioletowy-lily-16962.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16963', 'Szezlong lewostronny tapicerowany turkusowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-turkusowy-lily-16963.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16964', 'Szezlong lewostronny tapicerowany morski Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-morski-lily-16964.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16965', 'Szezlong prawostronny tapicerowany zielony Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-zielony-lily-16965.feed10009', 'Scandinavian Style Design');
