-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19732', 'Pudełko do przechowywania beżowe 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-bezowe-32-x-32-x-31-cm-meg-19732.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19733', 'Pudełko do przechowywania białe 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-biale-32-x-32-x-31-cm-meg-19733.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19734', 'Pudełko do przechowywania brązowe 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-brazowe-32-x-32-x-31-cm-meg-19734.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19735', 'Pudełko do przechowywania czarne 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-czarne-32-x-32-x-31-cm-meg-19735.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19736', 'Pudełko do przechowywania czerwone 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-czerwone-32-x-32-x-31-cm-meg-19736.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19737', 'Pudełko do przechowywania niebieskie 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-niebieskie-32-x-32-x-31-cm-meg-19737.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19739', 'Pudełko do przechowywania szare 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-szare-32-x-32-x-31-cm-meg-19739.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19740', 'Pudełko do przechowywania różowe 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-rozowe-32-x-32-x-31-cm-meg-19740.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19741', 'Pudełko do przechowywania zielone 32 x 32 x 31 cm Meg', 'Pozostałe produkty', 17.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-zielone-32-x-32-x-31-cm-meg-19741.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19743', 'Regał na książki biały mat 139 x 33 x 144 cm Caboto', 'Regały', 415.0, 'https://www.meblepumo.pl/pl/products/regal-na-ksiazki-bialy-mat-139-x-33-x-144-cm-caboto-19743.feed10009', 'HALMAR');
