-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25101', 'Front do szafki RTV biały 50 x 41 cm Malia', 'Dodatki do mebli/Części do mebli', 149.0, 'https://www.meblepumo.pl/pl/products/front-do-szafki-rtv-bialy-50-x-41-cm-malia-25101.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25102', 'Front do szafki RTV czarny 50 x 41 cm Malia', 'Dodatki do mebli/Części do mebli', 149.0, 'https://www.meblepumo.pl/pl/products/front-do-szafki-rtv-czarny-50-x-41-cm-malia-25102.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25104', 'Front do regału biały 55 x 50 cm Malia', 'Dodatki do mebli/Części do mebli', 349.0, 'https://www.meblepumo.pl/pl/products/front-do-regalu-bialy-55-x-50-cm-malia-25104.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25105', 'Front do regału czarny 55 x 50 cm Malia', 'Dodatki do mebli/Części do mebli', 369.0, 'https://www.meblepumo.pl/pl/products/front-do-regalu-czarny-55-x-50-cm-malia-25105.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25106', 'Biurko z regałem Grosso149x50x105 cm,  dąb wotan, antracyt', 'Biurka/Biurka z szufladami i drzwiami', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regalem-grosso149x50x105-cm-dab-wotan-antracyt-25106.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25107', 'Biurko z szufladami i drzwiami dąb wotan / antracyt mat 120 cm Elmo', 'Biurka/Biurka z szufladami i drzwiami', 376.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-drzwiami-dab-wotan-antracyt-mat-120-cm-elmo-25107.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25108', 'Biurko modułowe olcha mat 80 cm B6', 'Biurka/Biurka proste', 329.0, 'https://www.meblepumo.pl/pl/products/biurko-modulowe-olcha-mat-80-cm-b6-25108.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25109', 'Stolik kawowy okrągły dąb naturalny mat 80 cm Brooklyn', 'Stoliki kawowe i ławy/Stoliki kawowe', 626.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dab-naturalny-mat-80-cm-brooklyn-25109.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25110', 'Stolik kawowy okrągły dąb naturalny mat 45 cm Queens', 'Stoliki kawowe i ławy/Stoliki kawowe', 354.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dab-naturalny-mat-45-cm-queens-25110.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25111', 'Stolik kawowy okrągły orzech mat 60 cm Rezzo', 'Stoliki kawowe i ławy/Stoliki kawowe', 347.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-orzech-mat-60-cm-rezzo-25111.feed10009', 'HALMAR');
