-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27881', 'Szafka RTV dąb / czarna mat 147 cm Bergu', 'Szafki RTV', 599.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-czarna-mat-147-cm-bergu-27881.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27882', 'Stolik kawowy z szufladą dąb / czarny mat 100 x 60 cm Bergen', 'Stoliki kawowe i ławy/Stoliki kawowe', 499.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-dab-czarny-mat-100-x-60-cm-bergen-27882.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27883', 'Komoda z drzwiami czarna / artisan mat 200 cm Noir', 'Komody/Komody z drzwiami', 1779.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-artisan-mat-200-cm-noir-27883.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27884', 'Produkt do testu', 'Pozostałe produkty', 1.0, 'https://www.meblepumo.pl/pl/products/produkt-do-testu-27884.feed10009', 'marka niezdefiniowana');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27885', 'Szafka RTV czarna / dąb artisan mat 200 cm Noir', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-dab-artisan-mat-200-cm-noir-27885.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27886', 'Regał do salonu czarny / artisan mat 98 x 45 x 127 cm Noir', 'Regały', 979.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-czarny-artisan-mat-98-x-45-x-127-cm-noir-27886.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27888', 'Komplet szafek nocnych czarny / artisan mat 50 cm Noir', 'Szafki nocne', 769.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-artisan-mat-50-cm-noir-27888.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27892', 'Szafa trzydrzwiowa biała mat 147 x 200 cm Billund', 'Szafy/Szafy uchylne', 1549.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-biala-mat-147-x-200-cm-billund-27892.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27893', 'Szafa trzydrzwiowa jackson hickory mat 147 x 200 cm Billund', 'Szafy/Szafy uchylne', 1729.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-jackson-hickory-mat-147-x-200-cm-billund-27893.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27894', 'Szafa czterodrzwiowa biała mat 195 x 200 cm Billund', 'Szafy/Szafy uchylne', 2199.0, 'https://www.meblepumo.pl/pl/products/szafa-czterodrzwiowa-biala-mat-195-x-200-cm-billund-27894.feed10009', 'Tvilum');
