-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27442', 'Krzesło do jadalni drewniane ciemny orzech Dariusz 2', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-ciemny-orzech-dariusz-2-27442.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27443', 'Krzesło do jadalni drewniane dąb miodowy Dariusz 2', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-dab-miodowy-dariusz-2-27443.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27444', 'Krzesło do jadalni drewniane dąb sonoma Dariusz 2', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-dab-sonoma-dariusz-2-27444.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27445', 'Krzesło do jadalni drewniane tapicerowane beżowe / białe Dariusz', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-biale-dariusz-27445.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27447', 'Krzesło do jadalni drewniane tapicerowane szare / dąb miodowy Dariusz', 'Krzesła/Krzesła do jadalni', 245.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-dab-miodowy-dariusz-27447.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27448', 'Krzesło do jadalni drewniane tapicerowane beżowe / dąb sonoma Dariusz', 'Krzesła/Krzesła do jadalni', 245.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-dab-sonoma-dariusz-27448.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27449', 'Krzesło do jadalni tapicerowane zielone / czarne Diego 2', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-czarne-diego-2-27449.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27450', 'Krzesło do jadalni tapicerowane granatowe / czarne Diego 2', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-czarne-diego-2-27450.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27451', 'Krzesło do jadalni tapicerowane szare / czarne Diego 2', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-czarne-diego-2-27451.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27452', 'Krzesło do jadalni tapicerowane zielone / dąb miodowy Diego 3', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-dab-miodowy-diego-3-27452.feed10009', 'HALMAR');
