-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25316', 'Krzesło do jadalni tapicerowane beżowe / czarne K493', 'Krzesła/Krzesła do jadalni', 216.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-czarne-k493-25316.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25317', 'Krzesło do jadalni tapicerowane musztardowe K493', 'Krzesła/Krzesła do jadalni', 216.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k493-25317.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25318', 'Krzesło do jadalni tapicerowane szare K493', 'Krzesła/Krzesła do jadalni', 216.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k493-25318.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25319', 'Krzesło obrotowe do jadalni tapicerowane szare / czarne K494', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-obrotowe-do-jadalni-tapicerowane-szare-czarne-k494-25319.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25323', 'Krzesło do jadalni tapicerowane musztardowe K496', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k496-25323.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25326', 'Krzesło do jadalni tapicerowane kremowe K497', 'Krzesła/Krzesła do jadalni', 293.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-kremowe-k497-25326.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25328', 'Krzesło obrotowe do jadalni tapicerowane szare K498', 'Krzesła/Krzesła do jadalni', 579.0, 'https://www.meblepumo.pl/pl/products/krzeslo-obrotowe-do-jadalni-tapicerowane-szare-k498-25328.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25329', 'Krzesło do jadalni tapicerowane beżowe K499', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k499-25329.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25330', 'Krzesło do jadalni tapicerowane szare K499', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k499-25330.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25331', 'Krzesło do jadalni tapicerowane różowe K499', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-rozowe-k499-25331.feed10009', 'HALMAR');
