-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28028', 'Komoda z drzwiami kaszmir mat 200 cm Silk', 'Komody/Komody z drzwiami', 1199.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-200-cm-silk-28028.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28029', 'Szafka RTV kaszmir mat 200 cm Silk', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-200-cm-silk-28029.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28030', 'Komoda Noir 200 cm, 4 drzwi, zielony mat z frezowanym frontem, blat artisan', 'Komody/Komody z drzwiami', 1799.0, 'https://www.meblepumo.pl/pl/products/komoda-noir-200-cm-4-drzwi-zielony-mat-z-frezowanym-frontem-blat-artisan-28030.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28031', 'Szafka RTV z frezowanym frontem zielona / dąb artisan mat 200 cm Noir', 'Szafki RTV', 1349.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-frezowanym-frontem-zielona-dab-artisan-mat-200-cm-noir-28031.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28032', 'Regał do salonu zielony / artisan mat 98 x 45 x 127 cm Noir', 'Regały', 1329.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-zielony-artisan-mat-98-x-45-x-127-cm-noir-28032.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28033', 'Komoda Noir 98 cm, 2 drzwi, zielony mat z frezowanym frontem, blat artisan', 'Komody/Komody z drzwiami', 1079.0, 'https://www.meblepumo.pl/pl/products/komoda-noir-98-cm-2-drzwi-zielony-mat-z-frezowanym-frontem-blat-artisan-28033.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28034', 'Szafka nocna Noir 50 cm, 1 drzwi, zielony mat z frezowanym frontem, blat artisan, komplet 2 sztuki', 'Szafki nocne', 939.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-noir-50-cm-1-drzwi-zielony-mat-z-frezowanym-frontem-blat-artisan-komplet-2-sztuki-28034.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28035', 'Łóżeczko dziecięce Dreamland 140 x 70 cm, szary mat, lite drewno bukowe ', 'Łóżka dziecięce', 899.0, 'https://www.meblepumo.pl/pl/products/lozeczko-dzieciece-dreamland-140-x-70-cm-szary-mat-lite-drewno-bukowe-28035.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28036', 'Komoda z przewijakiem Dreamland, szary mat, lite drewno bukowe', 'Komody/Komody z drzwiami', 799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-przewijakiem-dreamland-szary-mat-lite-drewno-bukowe-28036.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28038', 'Szafa trzydrzwiowa szara mat 130 x 190 cm Dreamland', 'Szafy/Szafy uchylne', 1869.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-szara-mat-130-x-190-cm-dreamland-28038.feed10009', 'TT-furniture');
