-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18837', 'Witryna jednodrzwiowa z szufladami szara mat / połysk 60 x 192 cm Simple', 'Witryny i kredensy/Witryny', 929.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-szara-mat-polysk-60-x-192-cm-simple-18837.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18840', 'Witryna dwudrzwiowa z szufladami szara mat / połysk 80 x 192 cm Simple', 'Witryny i kredensy/Witryny', 999.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-szara-mat-polysk-80-x-192-cm-simple-18840.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18844', 'Zestaw 2 półek wiszących szarych mat 125 x 20 cm Simple', 'Półki wiszące', 229.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-polek-wiszacych-szarych-mat-125-x-20-cm-simple-18844.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18869', 'Sofa 2-osobowa tapicerowana szara Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-szara-tana-18869.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18874', 'Witryna wisząca przeszklona szara mat / połysk 60 x 115,5 cm Simple', 'Pozostałe produkty', 439.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-przeszklona-szara-mat-polysk-60-x-115-5-cm-simple-18874.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19072', 'Fotel kubełkowy tapicerowany czerwony Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-czerwony-tana-19072.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19073', 'Sofa 2-osobowa tapicerowana beżowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-bezowa-tana-19073.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19074', 'Sofa 2-osobowa tapicerowana zielona Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-zielona-tana-19074.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19075', 'Sofa 2-osobowa tapicerowana jasnozielona Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-jasnozielona-tana-19075.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19076', 'Sofa 2-osobowa tapicerowana różowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-rozowa-tana-19076.feed10009', 'Scandinavian Style Design');
