-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26454', 'Krzesło do jadalni tapicerowane zielone K462', 'Krzesła/Krzesła do jadalni', 199.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k462-26454.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26470', 'Krzesło do jadalni tapicerowane zielone K473', 'Krzesła/Krzesła do jadalni', 306.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k473-26470.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26471', 'Krzesło do jadalni tapicerowane szare K473', 'Krzesła/Krzesła do jadalni', 274.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k473-26471.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26472', 'Krzesło do jadalni tapicerowane kremowe K474', 'Krzesła/Krzesła do jadalni', 394.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-kremowe-k474-26472.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26476', 'Krzesło do jadalni tapicerowane kremowe K477', 'Krzesła/Krzesła do jadalni', 389.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-kremowe-k477-26476.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26481', 'Krzesło do jadalni tapicerowane zielone K480', 'Krzesła/Krzesła do jadalni', 376.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k480-26481.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26482', 'Krzesło do jadalni tapicerowane szare K480', 'Krzesła/Krzesła do jadalni', 376.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k480-26482.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26487', 'Krzesło ogrodowe plastikowe naturalne / czarne K483', 'Krzesła/Krzesła ogrodowe', 184.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-naturalne-czarne-k483-26487.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26488', 'Krzesło do jadalni tapicerowane beżowe / białe K486', 'Krzesła/Krzesła do jadalni', 309.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-biale-k486-26488.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26493', 'Krzesło do jadalni tapicerowane szare K487', 'Krzesła/Krzesła do jadalni', 311.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k487-26493.feed10009', 'HALMAR');
