-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27306', 'Komoda z drzwiami biała mat / wysoki połysk 100 cm Livo', 'Komody/Komody z drzwiami', 653.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-wysoki-polysk-100-cm-livo-27306.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27307', 'Oświetlenie do szafki RTV białe   Livo', 'Dodatki do mebli/Oświetlenie LED', 38.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafki-rtv-biale-livo-27307.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27308', 'Oświetlenie do szafki RTV czerwone   Livo', 'Dodatki do mebli/Oświetlenie LED', 38.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafki-rtv-czerwone-livo-27308.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27309', 'Oświetlenie do szafki RTV niebieskie   Livo', 'Dodatki do mebli/Oświetlenie LED', 38.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafki-rtv-niebieskie-livo-27309.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27310', 'Oświetlenie do szafki RTV zielone   Livo', 'Dodatki do mebli/Oświetlenie LED', 38.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafki-rtv-zielone-livo-27310.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27329', 'Łóżko dziecięce białe 80x160 cm Marinella', 'Łóżka dziecięce', 899.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-biale-80x160-cm-marinella-27329.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27330', 'Łóżko dziecięce sosna 80x160 cm Marinella', 'Łóżka dziecięce', 724.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-sosna-80x160-cm-marinella-27330.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27331', 'Przedłużki do blatu jasny dąb mat 45 x 90 cm Massive', 'Stoly/Stoły nierozkładane', 723.0, 'https://www.meblepumo.pl/pl/products/przedluzki-do-blatu-jasny-dab-mat-45-x-90-cm-massive-27331.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27332', 'Stół rozkładany jasny dąb / czarny mat 160 - 250 x 90 cm Massive', 'Stoly/Stoły rozkładane', 2999.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-jasny-dab-czarny-mat-160-250-x-90-cm-massive-27332.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27333', 'Mata ochronna pod krzesło mleczna 80 x 100 cm', 'Dodatki do mebli/Akcesoria ', 73.0, 'https://www.meblepumo.pl/pl/products/mata-ochronna-pod-krzeslo-mleczna-80-x-100-cm-27333.feed10009', 'HALMAR');
