-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27294', 'Regał na książki dąb sonoma mat 40 x 40 x 200 cm Lima', 'Regały', 259.0, 'https://www.meblepumo.pl/pl/products/regal-na-ksiazki-dab-sonoma-mat-40-x-40-x-200-cm-lima-27294.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27295', 'Szafka nocna biała wysoki połysk 40 cm Lima', 'Szafki nocne', 259.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-wysoki-polysk-40-cm-lima-27295.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27296', 'Szafka nocna dąb sonoma / biała mat / wysoki połysk 40 cm Lima', 'Szafki nocne', 228.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-dab-sonoma-biala-mat-wysoki-polysk-40-cm-lima-27296.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27297', 'Szafka nocna dąb sonoma mat 40 cm Lima', 'Szafki nocne', 228.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-dab-sonoma-mat-40-cm-lima-27297.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27298', 'Szafka na buty biała wysoki połysk 32 cm Lima', 'Szafki na buty', 319.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-biala-wysoki-polysk-32-cm-lima-27298.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27301', 'Stelaż do łóżka 120x198 cm Lima', 'Łóżka i części/Stelaże do łóżek', 180.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-120x198-cm-lima-27301.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27302', 'Stelaż do łóżka 90x198 cm Lima', 'Łóżka i części/Stelaże do łóżek', 149.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-90x198-cm-lima-27302.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27303', 'Witryna jednodrzwiowa z szufladami biała połysk 40 x 200 cm Lima', 'Witryny i kredensy/Witryny', 777.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-biala-polysk-40-x-200-cm-lima-27303.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27304', 'Witryna jednodrzwiowa z szufladami biała / dąb sonoma mat / połysk 40 x 200 cm Lima', 'Witryny i kredensy/Witryny', 744.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-biala-dab-sonoma-mat-polysk-40-x-200-cm-lima-27304.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27305', 'Witryna jednodrzwiowa z szufladami dąb sonoma mat 40 x 200 cm Lima', 'Witryny i kredensy/Witryny', 744.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-dab-sonoma-mat-40-x-200-cm-lima-27305.feed10009', 'HALMAR');
