-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23979', 'Sofa 2-osobowa tapicerowana żółta Derpik', 'Sofy i narożniki/Sofy 2-osobowe', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-zolta-derpik-23979.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23980', 'Sofa 2-osobowa tapicerowana beżowa Derpik', 'Sofy i narożniki/Sofy 2-osobowe', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-bezowa-derpik-23980.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23981', 'Sofa 2-osobowa tapicerowana zielona Derpik', 'Sofy i narożniki/Sofy 2-osobowe', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-zielona-derpik-23981.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23982', 'Sofa 2-osobowa tapicerowana grafitowa Derpik', 'Sofy i narożniki/Sofy 2-osobowe', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-grafitowa-derpik-23982.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23983', 'Sofa 2-osobowa tapicerowana błękitna Derpik', 'Sofy i narożniki/Sofy 2-osobowe', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-blekitna-derpik-23983.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23984', 'Sofa 2-osobowa tapicerowana granatowa Derpik', 'Sofy i narożniki/Sofy 2-osobowe', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-granatowa-derpik-23984.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23985', 'Sofa 2-osobowa tapicerowana szara Derpik', 'Sofy i narożniki/Sofy 2-osobowe', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-szara-derpik-23985.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24009', 'Szafka nocna czarna / sosna lakierowana 44 cm Nola', 'Szafki nocne', 192.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-czarna-sosna-lakierowana-44-cm-nola-24009.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24021', 'Pudełko do przechowywania graffiti 32 x 32 x 31 cm Max', 'Pozostałe produkty', 19.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-graffiti-32-x-32-x-31-cm-max-24021.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24024', 'Pudełko do przechowywania beżowe 32 x 32 x 31 cm Max', 'Pozostałe produkty', 26.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-bezowe-32-x-32-x-31-cm-max-24024.feed10009', 'Fontini ');
