-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25252', 'Hoker z oparciem tapicerowany beżowy / czarny H101', 'Hokery', 249.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bezowy-czarny-h101-25252.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25259', 'Hoker z oparciem tapicerowany szary / złoty H112', 'Hokery', 439.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-zloty-h112-25259.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25260', 'Hoker z oparciem tapicerowany biały / czarny / złoty H113', 'Hokery', 369.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bialy-czarny-zloty-h113-25260.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25266', 'Hoker z oparciem tapicerowany szary / złoty H116', 'Hokery', 419.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-zloty-h116-25266.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25267', 'Hoker z oparciem tapicerowany zielony / czarny H117', 'Hokery', 323.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-czarny-h117-25267.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25268', 'Hoker z oparciem tapicerowany szary / czarny H117', 'Hokery', 323.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h117-25268.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25269', 'Hoker z oparciem tapicerowany beżowy / czarny H118', 'Hokery', 559.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bezowy-czarny-h118-25269.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25270', 'Hoker z oparciem tapicerowany szary / czarny H118', 'Hokery', 559.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h118-25270.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25272', 'Hoker z oparciem tapicerowany beżowy / czarny H119', 'Hokery', 299.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bezowy-czarny-h119-25272.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25273', 'Hoker z oparciem tapicerowany szary / złoty H120', 'Hokery', 329.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-zloty-h120-25273.feed10009', 'HALMAR');
