-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19406', 'Fotel biurowy siatka czarny / biały Socket', 'Fotele/Fotele do biurka', 409.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-czarny-bialy-socket-19406.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19411', 'Fotel biurowy siatka szary / czarny Admiral', 'Fotele/Fotele do biurka', 739.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-szary-czarny-admiral-19411.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19416', 'Fotel biurowy ekoskóra czarny Quad', 'Fotele/Fotele do biurka', 949.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-czarny-quad-19416.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19430', 'Fotel gamingowy ekoskóra czarny / czerwony Defender', 'Fotele/Fotele do biurka', 689.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-ekoskora-czarny-czerwony-defender-19430.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19434', 'Fotel biurowy tapicerowany szary / turkusowy Cayman', 'Fotele/Fotele do biurka', 729.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-szary-turkusowy-cayman-19434.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19439', 'Fotel gamingowy ekoskóra czarny / czerwony Honor', 'Fotele/Fotele do biurka', 659.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-ekoskora-czarny-czerwony-honor-19439.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19440', 'Fotel gamingowy tapicerowany szary / czarny Lotus', 'Fotele/Fotele do biurka', 659.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-tapicerowany-szary-czarny-lotus-19440.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19444', 'Fotel gamingowy ekoskóra szary / czarny / czerwony Scroll', 'Fotele/Fotele do biurka', 513.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-ekoskora-szary-czarny-czerwony-scroll-19444.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19447', 'Fotel gamingowy ekoskóra czarny / czerwony Rubin', 'Fotele/Fotele do biurka', 639.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-ekoskora-czarny-czerwony-rubin-19447.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19451', 'Fotel biurowe ekoskóra czarny Mantus', 'Fotele/Fotele do biurka', 614.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowe-ekoskora-czarny-mantus-19451.feed10009', 'HALMAR');
