-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28247', 'Komoda z drzwiami beżowa / dąb mat 150 cm Olmo', 'Komody/Komody z drzwiami', 1449.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bezowa-dab-mat-150-cm-olmo-28247.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28248', 'Komoda z drzwiami oliwkowa / dąb mat 150 cm Olmo', 'Komody/Komody z drzwiami', 1449.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-oliwkowa-dab-mat-150-cm-olmo-28248.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28249', 'Komplet szafek nocnych beżowy / dąb mat 40 cm Olmo', 'Szafki nocne', 979.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-bezowy-dab-mat-40-cm-olmo-28249.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28250', 'Komplet szafek nocnych oliwkowy / dąb mat 40 cm Olmo', 'Szafki nocne', 979.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-oliwkowy-dab-mat-40-cm-olmo-28250.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28251', 'Biurko z kontenerkiem białe mat 159 cm Prima', 'Biurka/Biurka z szufladami i drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/biurko-z-kontenerkiem-biale-mat-159-cm-prima-28251.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28252', 'Szafa z lustrem dwudrzwiowa biała mat 102 x 199 cm Madrid', 'Szafy/Szafy uchylne', 1849.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-dwudrzwiowa-biala-mat-102-x-199-cm-madrid-28252.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28253', 'Szafa z lustrem dwudrzwiowa czarna mat 102 x 199 cm Madrid', 'Szafy/Szafy uchylne', 2059.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-dwudrzwiowa-czarna-mat-102-x-199-cm-madrid-28253.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28254', 'Szafa z lustrem trzydrzwiowa biała mat 150 x 199 cm Madrid', 'Szafy/Szafy uchylne', 2169.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-trzydrzwiowa-biala-mat-150-x-199-cm-madrid-28254.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28255', 'Szafa z lustrem trzydrzwiowa czarna mat 150 x 199 cm Madrid', 'Szafy/Szafy uchylne', 2399.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-trzydrzwiowa-czarna-mat-150-x-199-cm-madrid-28255.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28256', 'Komoda z drzwiami biała mat 150 cm Aria', 'Komody/Komody z drzwiami', 1149.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-150-cm-aria-28256.feed10009', 'High Glossy Furniture');
