-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19258', 'Krzesło do jadalni tapicerowane białe / dąb miodowy K247', 'Krzesła/Krzesła do jadalni', 349.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-biale-dab-miodowy-k247-19258.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19259', 'Krzesło do jadalni tapicerowane szare / dąb miodowy K247', 'Krzesła/Krzesła do jadalni', 349.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-dab-miodowy-k247-19259.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19260', 'Krzesło do jadalni tapicerowane szare Rois', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-rois-19260.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19262', 'Krzesło do jadalni tapicerowane cappuccino Toledo', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-cappuccino-toledo-19262.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19263', 'Krzesło do jadalni tapicerowane beżowe Toledo', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-toledo-19263.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19264', 'Krzesło do jadalni tapicerowane szare Toledo', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-toledo-19264.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19266', 'Krzesło do jadalni drewniane tapicerowane białe / szare Verdi', 'Krzesła/Krzesła do jadalni', 649.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-biale-szare-verdi-19266.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19319', 'Fotel wypoczynkowy welurowy grafitowy Gryf', 'Fotele/Fotele wypoczynkowe', 1769.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-welurowy-grafitowy-gryf-19319.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19320', 'Sofa 2-osobowa tapicerowana grafitowa Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2099.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-grafitowa-gryf-19320.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19321', 'Sofa 3-osobowa tapicerowana grafitowa Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-grafitowa-gryf-19321.feed10009', 'Scandinavian Style Design');
