-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28351', 'Szafka RTV jesion czarny 180 cm Loftis', 'Szafki RTV', 1169.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-jesion-czarny-180-cm-loftis-28351.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28352', 'Stół nierozkładany jesion czarny 200 x 90 cm Loftis', 'Stoly/Stoły nierozkładane', 1709.0, 'https://www.meblepumo.pl/pl/products/stol-nierozkladany-jesion-czarny-200-x-90-cm-loftis-28352.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28353', 'Stół nierozkładany jesion czarny 160 x 90 cm Loftis', 'Stoly/Stoły nierozkładane', 1499.0, 'https://www.meblepumo.pl/pl/products/stol-nierozkladany-jesion-czarny-160-x-90-cm-loftis-28353.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28354', 'Regał do salonu jesion czarny 80 x 40 x 172 cm Loftis', 'Regały', 779.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-jesion-czarny-80-x-40-x-172-cm-loftis-28354.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28355', 'Stolik kawowy okrągły jesion czarny 80 cm Loftis', 'Stoliki kawowe i ławy/Stoliki kawowe', 679.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-jesion-czarny-80-cm-loftis-28355.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28356', 'Zestaw 2 stolików kawowych okrągłych jesion czarny  70 cm, 50 cm Loftis', 'Stoliki kawowe i ławy/Stoliki kawowe', 469.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-jesion-czarny-70-cm-50-cm-loftis-28356.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28357', 'Komoda z szufladami i drzwiami biała wysoki połysk 241 cm Sorelle', 'Komody/Komody z szufladami i drzwiami', 1959.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-241-cm-sorelle-28357.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28358', 'Komoda z szufladami i drzwiami dąb mercure 241 cm Sorelle', 'Komody/Komody z szufladami i drzwiami', 1959.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-mercure-241-cm-sorelle-28358.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28359', 'Komoda z drzwiami biała wysoki połysk 241 cm Sorelle', 'Komody/Komody z drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-241-cm-sorelle-28359.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28360', 'Komoda z drzwiami dąb mercure 241 cm Sorelle', 'Komody/Komody z drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-mercure-241-cm-sorelle-28360.feed10009', 'Italia Trend');
