-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25830', 'Fotel biurowy velvet szary / orzech Colt', 'Fotele/Fotele do biurka', 609.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-velvet-szary-orzech-colt-25830.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25835', 'Zestaw mebli do jadalni naturalny / mokka 120 x 80 cm Cordoba', 'Zestawy mebli/Zestawy mebli do jadalni', 1089.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-do-jadalni-naturalny-mokka-120-x-80-cm-cordoba-25835.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25858', 'Fotel wypoczynkowy tapicerowany zielony Crown', 'Fotele/Fotele wypoczynkowe', 789.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-crown-25858.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25859', 'Fotel wypoczynkowy tapicerowany czarny Crown', 'Fotele/Fotele wypoczynkowe', 789.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-czarny-crown-25859.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25861', 'Stół okrągły szklany transparentny / chrom mat 80 cm Cyryl', 'Stoly/Stoły nierozkładane', 299.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-szklany-transparentny-chrom-mat-80-cm-cyryl-25861.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25870', 'Stół okrągły biały marmur / biały mat 80 cm Denver', 'Stoly/Stoły nierozkładane', 419.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-bialy-marmur-bialy-mat-80-cm-denver-25870.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25874', 'Fotel gabinetowy tapicerowany szary Desmond 2', 'Fotele/Fotele do biurka', 599.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-szary-desmond-2-25874.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25875', 'Fotel gabinetowy ekoskóra beżowy Desmond', 'Fotele/Fotele do biurka', 599.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-bezowy-desmond-25875.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25876', 'Fotel gabinetowy ekoskóra brązowy Desmond', 'Fotele/Fotele do biurka', 599.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-brazowy-desmond-25876.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25877', 'Fotel gabinetowy ekoskóra czarny Desmond', 'Fotele/Fotele do biurka', 599.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-czarny-desmond-25877.feed10009', 'HALMAR');
