-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8098', 'Stelaż do łóżka 120x200 cm Futura NV', 'Łóżka i części/Stelaże do łóżek', 599.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-120x200-cm-futura-nv-8098.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8666', 'Fotel z podnóżkiem tapicerowany ekoskóra brązowy Cork', 'Fotele/Fotele wypoczynkowe', 2499.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-ekoskora-brazowy-cork-8666.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8667', 'Fotel z podnóżkiem tapicerowany ekoskóra ciemnobrązowy Cork', 'Fotele/Fotele wypoczynkowe', 2499.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-ekoskora-ciemnobrazowy-cork-8667.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8668', 'Fotel z podnóżkiem tapicerowany kremowy / różowy Cork', 'Fotele/Fotele wypoczynkowe', 2499.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-kremowy-rozowy-cork-8668.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8669', 'Komoda Simple', 'Pozostałe produkty', 1039.0, 'https://www.meblepumo.pl/pl/products/komoda-simple-8669.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8689', 'Sofa 2-osobowa z funkcją spania tapicerowana kremowa w jesienne kwiaty Ennis', 'Pozostałe produkty', 3199.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-kremowa-w-jesienne-kwiaty-ennis-8689.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8690', 'Sofa 2-osobowa z funkcją spania tapicerowana wielokolorowa w szare kwiaty Ennis', 'Pozostałe produkty', 3199.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-wielokolorowa-w-szare-kwiaty-ennis-8690.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8691', 'Sofa 2-osobowa z funkcją spania tapicerowana wielokolorowa w czerwone kwiaty Ennis', 'Pozostałe produkty', 3199.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-wielokolorowa-w-czerwone-kwiaty-ennis-8691.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10280', 'Biurko narożne białe / dąb sonoma mat 145 cm Function', 'Biurka/Biurka narożne', 769.0, 'https://www.meblepumo.pl/pl/products/biurko-narozne-biale-dab-sonoma-mat-145-cm-function-10280.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10281', 'Biurko narożne białe / dąb trufla mat 145 cm Function', 'Biurka/Biurka narożne', 769.0, 'https://www.meblepumo.pl/pl/products/biurko-narozne-biale-dab-trufla-mat-145-cm-function-10281.feed10009', 'Tvilum');
