-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26706', 'Ława szklana transparentny / szary mat 130 x 70 cm Nina 5', 'Stoliki kawowe i ławy/Ławy', 813.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-szary-mat-130-x-70-cm-nina-5-26706.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26714', 'Stół rozkładany biały / czarny połysk 140 - 180 x 80 cm Nord', 'Stoly/Stoły rozkładane', 1783.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-czarny-polysk-140-180-x-80-cm-nord-26714.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26717', 'Stolik kawowy okrągły orzech / czarny mat 40 cm Nubira S', 'Stoliki kawowe i ławy/Stoliki kawowe', 239.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-orzech-czarny-mat-40-cm-nubira-s-26717.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26730', 'Fotel rozkładany ekoskóra beżowy Optima', 'Fotele/Fotele rozkładane', 1025.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-ekoskora-bezowy-optima-26730.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26731', 'Fotel rozkładany ekoskóra cappuccino Optima', 'Fotele/Fotele rozkładane', 1025.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-ekoskora-cappuccino-optima-26731.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26732', 'Fotel rozkładany ekoskóra czarny Optima', 'Fotele/Fotele rozkładane', 1025.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-ekoskora-czarny-optima-26732.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26733', 'Fotel rozkładany ekoskóra szary Optima', 'Fotele/Fotele rozkładane', 1025.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-ekoskora-szary-optima-26733.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26734', 'Zestaw 2 stolików kawowych okrągłych biały marmur / czarny mat 53 cm, 43 cm Oreo', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-bialy-marmur-czarny-mat-53-cm-43-cm-oreo-26734.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26736', 'Zestaw 2 stolików kawowych okrągłych dąb złoty / czarny mat 53 cm, 43 cm Oreo', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-dab-zloty-czarny-mat-53-cm-43-cm-oreo-26736.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26739', 'Fotel rozkładany tapicerowany szary Oslo', 'Fotele/Fotele rozkładane', 1049.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-tapicerowany-szary-oslo-26739.feed10009', 'HALMAR');
