-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24587', 'Komplet szafek nocnych czarny mat 44 cm Ikon', 'Szafki nocne', 849.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-mat-44-cm-ikon-24587.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24588', 'Komplet szafek nocnych granatowy mat 44 cm Ikon', 'Szafki nocne', 849.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-granatowy-mat-44-cm-ikon-24588.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24591', 'Szafka RTV grafitowa połysk 184 cm Sally', 'Szafki RTV', 979.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-grafitowa-polysk-184-cm-sally-24591.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24600', 'Lustro w ramie dąb sonoma 80 x 70 cm Bali', 'Lustra', 299.0, 'https://www.meblepumo.pl/pl/products/lustro-w-ramie-dab-sonoma-80-x-70-cm-bali-24600.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24603', 'Szafka RTV dąb sonoma mat 150 cm Bali', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-sonoma-mat-150-cm-bali-24603.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24605', 'Komoda z szufladami i drzwiami biała mat 179 cm Edinburgh', 'Komody/Komody z szufladami i drzwiami', 2849.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-mat-179-cm-edinburgh-24605.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24606', 'Komoda wysoka z drzwiami biała mat 100 cm Edinburgh', 'Komody/Komody z drzwiami', 1759.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-mat-100-cm-edinburgh-24606.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24607', 'Szafka RTV biała mat 179 cm Edinburgh', 'Szafki RTV', 1299.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-179-cm-edinburgh-24607.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24609', 'Regał do salonu antracyt / dekor bambus mat 84 x 40 x 165 cm Sumatra', 'Regały', 1199.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-antracyt-dekor-bambus-mat-84-x-40-x-165-cm-sumatra-24609.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24610', 'Biurko z szufladami i drzwiami antracyt / brązowe mat 120 cm Sumatra', 'Biurka/Biurka z szufladami i drzwiami', 1079.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-drzwiami-antracyt-brazowe-mat-120-cm-sumatra-24610.feed10009', 'Fontini ');
