-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25944', 'Stół rozkładany szary mat 160 - 220 x 90 cm Fangor', 'Stoly/Stoły rozkładane', 3233.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-szary-mat-160-220-x-90-cm-fangor-25944.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25947', 'FAUST zestaw stół + 4 krzesła dąb sonoma (1p=1kpl)', 'Zestawy mebli/Zestawy mebli do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/faust-zestaw-stol-4-krzesla-dab-sonoma-1p-1kpl-25947.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25950', 'Fotel rozkładany velvet beżowy Felipe 2', 'Fotele/Fotele rozkładane', 879.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-bezowy-felipe-2-25950.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25951', 'Fotel rozkładany velvet czarny Felipe 2', 'Fotele/Fotele rozkładane', 879.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-czarny-felipe-2-25951.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25952', 'Fotel rozkładany velvet granatowy Felipe 2', 'Fotele/Fotele rozkładane', 879.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-granatowy-felipe-2-25952.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25953', 'Fotel rozkładany velvet musztardowy Felipe 2', 'Fotele/Fotele rozkładane', 879.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-musztardowy-felipe-2-25953.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25954', 'Fotel rozkładany velvet szary Felipe 2', 'Fotele/Fotele rozkładane', 879.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-szary-felipe-2-25954.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25955', 'Fotel rozkładany tapicerowany beżowy Felipe', 'Fotele/Fotele rozkładane', 799.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-tapicerowany-bezowy-felipe-25955.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25956', 'Fotel rozkładany tapicerowany szary Felipe', 'Fotele/Fotele rozkładane', 799.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-tapicerowany-szary-felipe-25956.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25962', 'Szafka nocna czereśnia antyczna / czarna 37 cm Fiona', 'Szafki nocne', 479.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-czeresnia-antyczna-czarna-37-cm-fiona-25962.feed10009', 'HALMAR');
