-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19877', 'Komoda szeroka z drzwiami i szufladami dąb sonoma mat 241 cm Vero', 'Komody/Komody z szufladami i drzwiami', 1919.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-i-szufladami-dab-sonoma-mat-241-cm-vero-19877.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19878', 'Komoda szeroka z drzwiami i szufladami antracyt wysoki połysk 241 cm Vero', 'Komody/Komody z szufladami i drzwiami', 2129.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-i-szufladami-antracyt-wysoki-polysk-241-cm-vero-19878.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19880', 'Komoda z szufladami i drzwiami dąb sonoma mat 181 cm Vero', 'Pozostałe produkty', 1419.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-sonoma-mat-181-cm-vero-19880.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19881', 'Komoda z szufladami i drzwiami antracyt wysoki połysk 181 cm Vero', 'Pozostałe produkty', 1569.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-antracyt-wysoki-polysk-181-cm-vero-19881.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19882', 'Komoda z drzwiami biała wysoki połysk 181 cm Vero', 'Komody/Komody z drzwiami', 909.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-181-cm-vero-19882.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19883', 'Komoda z drzwiami dąb sonoma mat 181 cm Vero', 'Komody/Komody z drzwiami', 1129.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-sonoma-mat-181-cm-vero-19883.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19884', 'Komoda z drzwiami antracyt wysoki połysk 181 cm Vero', 'Komody/Komody z drzwiami', 1319.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-antracyt-wysoki-polysk-181-cm-vero-19884.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19885', 'Komoda wysoka z drzwiami biała wysoki połysk 121 cm Vero', 'Komody/Komody z drzwiami', 1309.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-wysoki-polysk-121-cm-vero-19885.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19886', 'Komoda wysoka z drzwiami dąb sonoma mat 121 cm Vero', 'Komody/Komody z drzwiami', 1249.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-dab-sonoma-mat-121-cm-vero-19886.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19887', 'Komoda wysoka z drzwiami antracyt wysoki połysk 121 cm Vero', 'Komody/Komody z drzwiami', 1379.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-antracyt-wysoki-polysk-121-cm-vero-19887.feed10009', 'Italia Trend');
