-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19077', 'Sofa 2-osobowa tapicerowana czerwona Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-czerwona-tana-19077.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19084', 'Fotel kubełkowy tapicerowany pomarańczowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-pomaranczowy-tana-19084.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19085', 'Sofa 2-osobowa tapicerowana pomarańczowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-pomaranczowa-tana-19085.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19086', 'Fotel kubełkowy tapicerowany żółty Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-zolty-tana-19086.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19087', 'Sofa 2-osobowa tapicerowana żółta Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-zolta-tana-19087.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19088', 'Komoda z szufladami wielokolorowa mat 59 cm Deco', 'Komody/Komody z szufladami', 449.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-wielokolorowa-mat-59-cm-deco-19088.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19090', 'Komoda z szufladami i drzwiami wielokolorowa mat 100 cm Deco', 'Komody/Komody z szufladami i drzwiami', 1199.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-wielokolorowa-mat-100-cm-deco-19090.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19091', 'Komoda z szufladami i drzwiami wielokolorowa mat 93 cm Deco', 'Komody/Komody z szufladami i drzwiami', 599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-wielokolorowa-mat-93-cm-deco-19091.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19093', 'Regał do salonu wielobarwny mat 60 x 29 x 180 cm Deco', 'Regały', 849.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-wielobarwny-mat-60-x-29-x-180-cm-deco-19093.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19095', 'Biurko z szufladami wielokolorowe mat 120 cm Mezo', 'Biurka/Biurka z szufladami i drzwiami', 569.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-wielokolorowe-mat-120-cm-mezo-19095.feed10009', 'HALMAR');
