-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12173', 'AMARETTO oświetlenie LED niebieskie do witryny', 'Dodatki do mebli/Oświetlenie LED', 185.0, 'https://www.meblepumo.pl/pl/products/amaretto-oswietlenie-led-niebieskie-do-witryny-12173.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12327', 'Stół rozkładany biały połysk 130 - 210 x 80 cm Cambridge', 'Stoly/Stoły rozkładane', 2115.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-polysk-130-210-x-80-cm-cambridge-12327.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12863', 'Fotel z podnóżkiem tapicerowany ekoskóra grafitowy Cork', 'Fotele/Fotele wypoczynkowe', 2499.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-ekoskora-grafitowy-cork-12863.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12864', 'Fotel z podnóżkiem tapicerowany ekoskóra szary Cork', 'Fotele/Fotele wypoczynkowe', 2499.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-ekoskora-szary-cork-12864.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12881', 'Fotel z podnóżkiem tapicerowany beżowy Cork', 'Fotele/Fotele wypoczynkowe', 2349.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-bezowy-cork-12881.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12882', 'Fotel z podnóżkiem tapicerowany ekoskóra czarny Cork', 'Fotele/Fotele wypoczynkowe', 2499.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-ekoskora-czarny-cork-12882.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15661', 'Komoda z szufladami biała / dąb sonoma mat 99 cm Oslo', 'Pozostałe produkty', 799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-dab-sonoma-mat-99-cm-oslo-15661.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15662', 'Szafka nocna biała / dąb sonoma mat 50 cm Oslo', 'Szafki nocne', 429.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-dab-sonoma-mat-50-cm-oslo-15662.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15667', 'Stół okrągły biały / dąb sonoma mat 100 cm Oslo', 'Pozostałe produkty', 675.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-bialy-dab-sonoma-mat-100-cm-oslo-15667.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15955', 'Komoda wysoka z szufladami biała wysoki połysk 77 cm Naia', 'Komody/Komody z szufladami', 879.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-biala-wysoki-polysk-77-cm-naia-15955.feed10009', 'Tvilum');
