-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28235', 'Szafka RTV sosna czekoladowa 200 cm Velar', 'Szafki RTV', 888.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-sosna-czekoladowa-200-cm-velar-28235.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28236', 'Szafka na buty kaszmir mat 60 cm Verto', 'Szafki na buty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-kaszmir-mat-60-cm-verto-28236.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28237', 'Szafka na buty czarna mat 60 cm Verto', 'Szafki na buty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-czarna-mat-60-cm-verto-28237.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28238', 'Stolik pomocniczy dąb olejowany  35 x 60 cm Elan', 'Stoliki kawowe i ławy/Stoliki pomocnicze', 919.0, 'https://www.meblepumo.pl/pl/products/stolik-pomocniczy-dab-olejowany-35-x-60-cm-elan-28238.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28241', 'Szafka RTV beżowa / dąb mat 200 cm Olmo', 'Szafki RTV', 1379.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-dab-mat-200-cm-olmo-28241.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28242', 'Szafka RTV oliwkowa / dąb mat 200 cm Olmo', 'Szafki RTV', 1379.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-oliwkowa-dab-mat-200-cm-olmo-28242.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28243', 'Szafka RTV beżowa / dąb mat 150 cm Olmo', 'Szafki RTV', 1149.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-dab-mat-150-cm-olmo-28243.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28244', 'Szafka RTV oliwkowa / dąb mat 150 cm Olmo', 'Szafki RTV', 1149.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-oliwkowa-dab-mat-150-cm-olmo-28244.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28245', 'Komoda z drzwiami beżowa / dąb mat 200 cm Olmo', 'Komody/Komody z drzwiami', 1739.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bezowa-dab-mat-200-cm-olmo-28245.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28246', 'Komoda z drzwiami oliwkowa / dąb mat 200 cm Olmo', 'Komody/Komody z drzwiami', 1739.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-oliwkowa-dab-mat-200-cm-olmo-28246.feed10009', 'High Glossy Furniture');
