-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28520', 'Stelaż do łóżka 160x200 cm Natura NV', 'Stelaże', 389.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-160x200-cm-natura-nv-28520.feed10009', 'Fra-Mar');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28521', 'Szafka RTV kaszmir / orzech warmia mat 180 cm Reno', 'Szafki RTV', 799.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-orzech-warmia-mat-180-cm-reno-28521.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28522', 'Komplet szafek nocnych kaszmir / orzech warmia mat 44 cm Reno', 'Szafki nocne', 679.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-kaszmir-orzech-warmia-mat-44-cm-reno-28522.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28523', 'Szafka RTV dąb Meringa/dąb Cadiz 211 cm Avina', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-meringa-dab-cadiz-211-cm-avina-28523.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28524', 'Komoda z drzwiami dąb Meringa/dąb Cadiz mat 164 cm Avina', 'Komody/Komody z drzwiami', 1359.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-meringa-dab-cadiz-mat-164-cm-avina-28524.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28525', 'Komoda z szufladami i drzwiami dąb Meringa/dąb Cadiz mat 211 cm Avina', 'Komody/Komody z drzwiami', 1649.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-meringa-dab-cadiz-mat-211-cm-avina-28525.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28526', 'Komoda z drzwiami dąb Meringa/dąb Cadiz mat 211 cm Avina', 'Komody/Komody z drzwiami', 1549.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-meringa-dab-cadiz-mat-211-cm-avina-28526.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28527', 'Komoda wysoka z drzwiami dąb Meringa/dąb Cadiz mat 118 cm Avina', 'Komody/Komody z drzwiami', 1549.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-dab-meringa-dab-cadiz-mat-118-cm-avina-28527.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28528', 'Komoda wysoka z drzwiami i szufladami dąb Meringa/dąb Cadiz mat 118 cm Avina', 'Komody/Komody z szufladami i drzwiami', 1649.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-i-szufladami-dab-meringa-dab-cadiz-mat-118-cm-avina-28528.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28529', 'Witryna jednodrzwiowa dąb Meringa/dąb Cadiz mat 72 x 192 cm Avina', 'Witryny i kredensy/Witryny', 1479.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-dab-meringa-dab-cadiz-mat-72-x-192-cm-avina-28529.feed10009', 'Italia Trend');
