-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27817', 'Szafka górna biała mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 219.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-mat-wysoki-polysk-60-cm-vento-27817.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27818', 'Szafka górna biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 219.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-dab-miodowy-mat-60-cm-vento-27818.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27820', 'Szafka górna okapowa biała mat 60 cm Vento', 'Szafki kuchenne', 366.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-okapowa-biala-mat-60-cm-vento-27820.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27821', 'Szafka górna okapowa dąb craft mat 60 cm Vento', 'Szafki kuchenne', 374.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-okapowa-dab-craft-mat-60-cm-vento-27821.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27822', 'Szafka górna lewa biała mat 40 cm Vento', 'Szafki kuchenne', 410.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-lewa-biala-mat-40-cm-vento-27822.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27824', 'Szafka górna lewa dąb craft mat 40 cm Vento', 'Szafki kuchenne', 423.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-lewa-dab-craft-mat-40-cm-vento-27824.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27825', 'Szafka górna prawa dąb craft mat 40 cm Vento', 'Szafki kuchenne', 423.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-prawa-dab-craft-mat-40-cm-vento-27825.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27826', 'VENTO LK listwa kątowa (1p=5szt)', 'halmar tymczasowa', 17.0, 'https://www.meblepumo.pl/pl/products/vento-lk-listwa-katowa-1p-5szt-27826.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27827', 'VENTO LS listwa szczelinowa (1p=5szt)', 'halmar tymczasowa', 10.0, 'https://www.meblepumo.pl/pl/products/vento-ls-listwa-szczelinowa-1p-5szt-27827.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27828', 'VENTO LZL listwa zakończeniowa lewa (1p=5szt)', 'halmar tymczasowa', 10.0, 'https://www.meblepumo.pl/pl/products/vento-lzl-listwa-zakonczeniowa-lewa-1p-5szt-27828.feed10009', 'HALMAR');
