-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23591', 'Fotel wypoczynkowy tapicerowany różowy Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-rozowy-holly-23591.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23592', 'Fotel wypoczynkowy tapicerowany błękitny Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-blekitny-holly-23592.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23593', 'Fotel wypoczynkowy tapicerowany niebieski Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-niebieski-holly-23593.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23594', 'Fotel wypoczynkowy tapicerowany miętowy Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-mietowy-holly-23594.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23595', 'Fotel wypoczynkowy tapicerowany ciemnoszary Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-ciemnoszary-holly-23595.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23596', 'Fotel wypoczynkowy tapicerowany grafitowy Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-grafitowy-holly-23596.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23598', 'Fotel wypoczynkowy tapicerowany szary Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-holly-23598.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23599', 'Fotel wypoczynkowy tapicerowany fioletowy Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-fioletowy-holly-23599.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23600', 'Fotel wypoczynkowy tapicerowany zielony Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-holly-23600.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23603', 'Biurko z regałem białe / dąb złoty mat 149 cm Grosso', 'Biurka/Biurka z szufladami i drzwiami', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regalem-biale-dab-zloty-mat-149-cm-grosso-23603.feed10009', 'HALMAR');
