-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23738', 'Krzesło do jadalni ekoskora czarne K201', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-czarne-k201-23738.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23740', 'Krzesło do jadalni ekoskora szare K201', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-szare-k201-23740.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23764', 'Krzesło do jadalni tapicerowane szare K303', 'Krzesła/Krzesła do jadalni', 289.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k303-23764.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23765', 'Krzesło do jadalni tapicerowane zielone K303', 'Krzesła/Krzesła do jadalni', 289.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k303-23765.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23766', 'Krzesło do jadalni tapicerowane ciemnoszare K303', 'Krzesła/Krzesła do jadalni', 289.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-ciemnoszare-k303-23766.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23768', 'Krzesło do jadalni tapicerowane beżowe K303', 'Krzesła/Krzesła do jadalni', 289.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k303-23768.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23772', 'Łóżko dwuosobowe beżowe / orzech 160x200 cm Solomo', 'Łóżka i części/Łóżka', 1899.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-bezowe-orzech-160x200-cm-solomo-23772.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23773', 'Łóżko tapicerowane z pojemnikiem szare 160x200 cm Padva', 'Łóżka i części/Łóżka', 1899.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-pojemnikiem-szare-160x200-cm-padva-23773.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23774', 'Łóżko tapicerowane szare 160x200 cm Samatra 2', 'Łóżka i części/Łóżka', 1509.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-160x200-cm-samatra-2-23774.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23775', 'Łóżko tapicerowane z szufladą szare 160x200 cm Avanti', 'Łóżka i części/Łóżka', 2369.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-avanti-23775.feed10009', 'HALMAR');
