-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24505', 'Komoda z drzwiami czarna mat / wysoki połysk 150 cm Sierra', 'Komody/Komody z drzwiami', 1069.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-wysoki-polysk-150-cm-sierra-24505.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24507', 'Szafka RTV rożowa mat 186 cm Ikon', 'Pozostałe produkty', 1119.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-rozowa-mat-186-cm-ikon-24507.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24508', 'Komoda z drzwiami biała mat 200 cm Malia', 'Komody/Komody z drzwiami', 1349.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-200-cm-malia-24508.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24529', 'Czarna komoda Malia 200 cm z frezowanym frontem, 4 drzwi, mat', 'Komody/Komody z drzwiami', 1569.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-malia-24529.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24533', 'Komoda z drzwiami i szufladami biała mat 150 cm Malia', 'Komody/Komody z szufladami i drzwiami', 1159.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-biala-mat-150-cm-malia-24533.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24534', 'Komoda z drzwiami i szufladami czarna mat 150 cm Malia', 'Komody/Komody z szufladami i drzwiami', 1089.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-czarna-mat-150-cm-malia-24534.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24535', 'Szafka RTV czarna mat 200 cm Malia', 'Szafki RTV', 1129.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-malia-24535.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24536', 'Szafka RTV biała mat 200 cm Malia', 'Szafki RTV', 1049.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-200-cm-malia-24536.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24537', 'Szafka RTV czarna mat 150 cm Malia', 'Szafki RTV', 989.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-150-cm-malia-24537.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24538', 'Szafka RTV biała mat 150 cm Malia', 'Szafki RTV', 939.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-150-cm-malia-24538.feed10009', 'High Glossy Furniture');
