-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28383', 'Szafka na buty miętowa mat 70 cm Vigo', 'Szafki na buty', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-mietowa-mat-70-cm-vigo-28383.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28384', 'Szafka na buty capuccino mat 70 cm Vigo', 'Szafki na buty', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-capuccino-mat-70-cm-vigo-28384.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28385', 'Szafka RTV capuccino mat 175 cm Arona', 'Szafki RTV', 1099.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-capuccino-mat-175-cm-arona-28385.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28386', 'Komoda z szufladami i drzwiami capuccino mat 135 cm Arona', 'Komody/Komody z szufladami i drzwiami', 1499.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-capuccino-mat-135-cm-arona-28386.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28387', 'Komoda z szufladami i drzwiami capuccino mat 175 cm Arona', 'Komody/Komody z szufladami i drzwiami', 2059.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-capuccino-mat-175-cm-arona-28387.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28389', 'Komoda z drzwiami capuccino mat 90 cm Arona', 'Komody/Komody z szufladami i drzwiami', 979.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-capuccino-mat-90-cm-arona-28389.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28390', 'Komoda wysoka z drzwiami i szufladami capuccino mat 90 cm Arona', 'Komody/Komody z szufladami i drzwiami', 1739.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-i-szufladami-capuccino-mat-90-cm-arona-28390.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28391', 'Stolik kawowy z szufladami capuccino mat 94 x 55 cm Arona', 'Stoliki kawowe i ławy/Stoliki kawowe', 759.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szufladami-capuccino-mat-94-x-55-cm-arona-28391.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28392', 'Witryna dwudrzwiowa z szufladami capuccino mat 60 x 200 cm Arona', 'Witryny i kredensy/Witryny', 1739.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-capuccino-mat-60-x-200-cm-arona-28392.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28393', 'Szafa z lustrem dwudrzwiowa biała mat 100 x 200 cm Sento', 'Szafy/Szafy uchylne', 809.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-dwudrzwiowa-biala-mat-100-x-200-cm-sento-28393.feed10009', 'Vivaladesign');
