-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28287', 'Szafka nocna jackson hickory mat 44 cm Madrid', 'Szafki nocne', 549.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-jackson-hickory-mat-44-cm-madrid-28287.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28288', 'Szafka nocna jackson hickory mat 40 cm Madrid', 'Szafki nocne', 319.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-jackson-hickory-mat-40-cm-madrid-28288.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28289', 'Komoda wysoka z szufladami jackson hickory mat 82 cm Madrid', 'Komody/Komody z szufladami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-jackson-hickory-mat-82-cm-madrid-28289.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28290', 'Komoda z szufladami jackson hickory mat 82 cm Madrid', 'Komody/Komody z szufladami', 729.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-jackson-hickory-mat-82-cm-madrid-28290.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28292', 'Szafa dwudrzwiowa jackson hickory mat 102 x 199 cm Madrid', 'Szafy/Szafy uchylne', 1599.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-jackson-hickory-mat-102-x-199-cm-madrid-28292.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28293', 'Szafa trzydrzwiowa jackson hickory mat 150 x 199 cm Madrid', 'Szafy/Szafy uchylne', 1979.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-jackson-hickory-mat-150-x-199-cm-madrid-28293.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28294', 'Szafa z lustrem trzydrzwiowa kaszmir mat 150 x 199 cm Madrid', 'Szafy/Szafy uchylne', 2399.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-trzydrzwiowa-kaszmir-mat-150-x-199-cm-madrid-28294.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28296', 'Szafka na buty kaszmir mat 54 cm Madrid', 'Szafki na buty', 529.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-kaszmir-mat-54-cm-madrid-28296.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28297', 'Szafka RTV kaszmir mat 151 cm Madrid', 'Szafki RTV', 959.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-151-cm-madrid-28297.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28298', 'Witryna dwudrzwiowa z szufladami kaszmir mat 78 x 199 cm Madrid', 'Witryny i kredensy/Witryny', 1529.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-kaszmir-mat-78-x-199-cm-madrid-28298.feed10009', 'Tvilum');
