-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19746', 'Szafka wisząca antracyt / dąb wotan mat 38 cm Rock', 'Szafki modułowe', 341.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-antracyt-dab-wotan-mat-38-cm-rock-19746.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19747', 'Szafka wisząca otwarta czarna mat 113 cm Rock', 'Szafki modułowe', 199.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-otwarta-czarna-mat-113-cm-rock-19747.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19748', 'Szafka wisząca otwarta biała mat 113 cm Rock', 'Szafki modułowe', 389.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-otwarta-biala-mat-113-cm-rock-19748.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19749', 'Szafka wisząca otwarta antracyt mat 113 cm Rock', 'Szafki modułowe', 208.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-otwarta-antracyt-mat-113-cm-rock-19749.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19750', 'Szafka wisząca czarna mat 75 cm Rock', 'Szafki modułowe', 299.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-czarna-mat-75-cm-rock-19750.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19751', 'Szafka wisząca biała mat 75 cm Rock', 'Szafki modułowe', 429.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-biala-mat-75-cm-rock-19751.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19752', 'Szafka wisząca antracyt / dąb wotan mat 75 cm Rock', 'Szafki modułowe', 429.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-antracyt-dab-wotan-mat-75-cm-rock-19752.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19754', 'Szafka wisząca otwarta biała mat 75 cm Rock', 'Szafki modułowe', 319.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-otwarta-biala-mat-75-cm-rock-19754.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19755', 'Szafka wisząca otwarta antracyt mat 75 cm Rock', 'Szafki modułowe', 164.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-otwarta-antracyt-mat-75-cm-rock-19755.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19756', 'Szafka wisząca czarna mat 37 cm Rock', 'Szafki modułowe', 359.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-czarna-mat-37-cm-rock-19756.feed10009', 'High Glossy Furniture');
