-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17504', 'Stół drewniany dąb lity bassano mat 220 x 100 cm Zamek', 'Pozostałe produkty', 4349.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-lity-bassano-mat-220-x-100-cm-zamek-17504.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17505', 'Stół drewniany dąb lity bassano mat 260 x 100 cm Zamek', 'Pozostałe produkty', 4849.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-lity-bassano-mat-260-x-100-cm-zamek-17505.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17508', 'Stół drewniany dąb dziki mat 180 x 100 cm Zamek', 'Pozostałe produkty', 3899.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-dziki-mat-180-x-100-cm-zamek-17508.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17509', 'Stół drewniany dąb dziki mat 200 x 100 cm Zamek', 'Pozostałe produkty', 4119.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-dziki-mat-200-x-100-cm-zamek-17509.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17510', 'Stół drewniany dąb dziki mat 220 x 100 cm Zamek', 'Pozostałe produkty', 4299.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-dziki-mat-220-x-100-cm-zamek-17510.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17511', 'Stół drewniany dąb dziki mat 260 x 100 cm Zamek', 'Pozostałe produkty', 4799.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-dziki-mat-260-x-100-cm-zamek-17511.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17665', 'Szafka RTV biała / dąb mat 169 cm Malmo', 'Szafki RTV', 784.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-mat-169-cm-malmo-17665.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17669', 'Sekretarzyk z szufladą i drzwiami biały mat 97 cm Malmo', 'Biurka/Biurka z szufladami i drzwiami', 1429.0, 'https://www.meblepumo.pl/pl/products/sekretarzyk-z-szuflada-i-drzwiami-bialy-mat-97-cm-malmo-17669.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17762', 'Sofa 2-osobowa z funkcją spania tapicerowana grafitowa Derry', 'Pozostałe produkty', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-grafitowa-derry-17762.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17763', 'Sofa 2-osobowa z funkcją spania tapicerowana miękka ciemnobrązowa Derry', 'Pozostałe produkty', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-miekka-ciemnobrazowa-derry-17763.feed10009', 'Meble tapicerowane');
