-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24235', 'Szafka na buty czarna mat 102 cm Madrid', 'Szafki na buty', 799.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-czarna-mat-102-cm-madrid-24235.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24236', 'Komoda z szufladami czarna mat 82 cm Madrid', 'Komody/Komody z szufladami', 639.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-mat-82-cm-madrid-24236.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24237', 'Szafka RTV czarna mat 151 cm Madrid', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-151-cm-madrid-24237.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24238', 'Stolik kawowy z półką czarny mat 81 x 81 cm Madrid', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-czarny-mat-81-x-81-cm-madrid-24238.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24239', 'Witryna dwudrzwiowa z szufladami czarna mat 78 x 199 cm Madrid', 'Witryny i kredensy/Witryny', 1399.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-czarna-mat-78-x-199-cm-madrid-24239.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24240', 'Komoda z szufladami i drzwiami czarna mat 151 cm Madrid', 'Komody/Komody z szufladami i drzwiami', 1039.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-czarna-mat-151-cm-madrid-24240.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24241', 'Komoda z drzwiami i szufladami czarna mat 82 cm Madrid', 'Komody/Komody z szufladami i drzwiami', 579.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-czarna-mat-82-cm-madrid-24241.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24242', 'Komoda z szufladami biała mat 159 cm Madrid', 'Komody/Komody z szufladami', 1199.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-mat-159-cm-madrid-24242.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24243', 'Komoda wysoka z szufladami biała mat 82 cm Madrid', 'Komody/Komody z szufladami', 849.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-biala-mat-82-cm-madrid-24243.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24244', 'Szafka nocna biała mat 44 cm Madrid', 'Szafki nocne', 369.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-mat-44-cm-madrid-24244.feed10009', 'Tvilum');
