-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18475', 'Szafka RTV biała / szara mat 156 cm Paradise', 'Pozostałe produkty', 787.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-szara-mat-156-cm-paradise-18475.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18481', 'Stół nierozkładany biały mat 180 x 90 cm Paradise', 'Stoly/Stoły nierozkładane', 1139.0, 'https://www.meblepumo.pl/pl/products/stol-nierozkladany-bialy-mat-180-x-90-cm-paradise-18481.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18497', 'Totality białe oświetlenie do półki', 'Dodatki do mebli/Oświetlenie LED', 199.0, 'https://www.meblepumo.pl/pl/products/totality-biale-oswietlenie-do-polki-18497.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18509', 'Stelaż do łóżka 90x200 cm Natura Slim', 'Łóżka i części/Stelaże do łóżek', 299.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-90x200-cm-natura-slim-18509.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18510', 'Stelaż do łóżka 140x200 cm Natura Slim', 'Łóżka i części/Stelaże do łóżek', 399.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-140x200-cm-natura-slim-18510.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18511', 'Stelaż do łóżka 160x200 cm Natura Slim', 'Łóżka i części/Stelaże do łóżek', 499.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-160x200-cm-natura-slim-18511.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18700', 'Stolik kawowy prostokątny biały mat / połysk 120 x 60 cm Tucson', 'Pozostałe produkty', 459.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bialy-mat-polysk-120-x-60-cm-tucson-18700.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18701', 'Stolik kawowy prostokątny biały / czarny mat / połysk 120 x 60 cm Tucson', 'Pozostałe produkty', 459.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bialy-czarny-mat-polysk-120-x-60-cm-tucson-18701.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18704', 'Stolik kawowy prostokątny czarny / biały mat / połysk 120 x 60 cm Tucson', 'Pozostałe produkty', 459.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-czarny-bialy-mat-polysk-120-x-60-cm-tucson-18704.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18705', 'Stolik kawowy prostokątny czarny / czarny mat / połysk 120 x 60 cm Tucson', 'Pozostałe produkty', 349.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-czarny-czarny-mat-polysk-120-x-60-cm-tucson-18705.feed10009', 'High Glossy Furniture');
