-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25274', 'Hoker z oparciem tapicerowany zielony / złoty H120', 'Hokery', 329.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-zloty-h120-25274.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25275', 'Hoker z oparciem tapicerowany czarny / złoty H120', 'Hokery', 329.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-czarny-zloty-h120-25275.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25276', 'Hoker z oparciem tapicerowany beżowy / czarny H95', 'Hokery', 252.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bezowy-czarny-h95-25276.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25277', 'Hoker z oparciem tapicerowany beżowy / czarny H96', 'Hokery', 259.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bezowy-czarny-h96-25277.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25278', 'Fotel gabinetowy tapicerowany ekoskóra szary / czarny Hamlet', 'Fotele/Fotele do biurka', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-ekoskora-szary-czarny-hamlet-25278.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25282', 'Stolik kawowy okrągły czarny marmur / złoty mat 42 cm Harissa B', 'Stoliki kawowe i ławy/Stoliki kawowe', 72.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-czarny-marmur-zloty-mat-42-cm-harissa-b-25282.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25285', 'Łóżko tapicerowane z szufladą szare 160x200 cm Harriet', 'Łóżka i części/Łóżka', 2135.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-harriet-25285.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25286', 'Stół okrągły orzech mat 136 cm Henderson', 'Stoly/Stoły nierozkładane', 3299.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-orzech-mat-136-cm-henderson-25286.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25288', 'Fotel gabinetowy tapicerowany ekoskóra kremowy / orzech Ignazio', 'Fotele/Fotele do biurka', 799.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-ekoskora-kremowy-orzech-ignazio-25288.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25289', 'Fotel wypoczynkowy tapicerowany naturalny / czarny Ilario', 'Fotele/Fotele wypoczynkowe', 737.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-naturalny-czarny-ilario-25289.feed10009', 'HALMAR');
