-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17768', 'Witryna dwudrzwiowa biała mat 89 x 203 cm Roomers', 'Witryny i kredensy/Witryny', 1399.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-biala-mat-89-x-203-cm-roomers-17768.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17769', 'Witryna dwudrzwiowa czarna mat 89 x 203 cm Roomers', 'Witryny i kredensy/Witryny', 1379.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-czarna-mat-89-x-203-cm-roomers-17769.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17772', 'Szafka RTV biała / dąb sonoma mat 156 cm Roomers', 'Szafki RTV', 1369.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-sonoma-mat-156-cm-roomers-17772.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17773', 'Szafka RTV czarna / orzech mat 156 cm Roomers', 'Szafki RTV', 1369.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-orzech-mat-156-cm-roomers-17773.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17774', 'Komoda z szufladami i drzwiami biała / dąb sonoma mat 176 cm Roomers', 'Komody/Komody z szufladami i drzwiami', 1599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-sonoma-mat-176-cm-roomers-17774.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17775', 'Komoda z szufladami i drzwiami biała / dąb sonoma mat 176 cm Roomers', 'Komody/Komody z szufladami i drzwiami', 1599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-sonoma-mat-176-cm-roomers-17775.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17777', 'Komoda wysoka z szufladami i drzwiami czarna / orzech mat 89 cm Roomers', 'Pozostałe produkty', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-i-drzwiami-czarna-orzech-mat-89-cm-roomers-17777.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17778', 'Półka wisząca kostka dąb sonoma mat 44 x 25 cm Roomers', 'Półki wiszące', 169.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-kostka-dab-sonoma-mat-44-x-25-cm-roomers-17778.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17779', 'Półka wisząca kostka orzech mat 44 x 25 cm Roomers', 'Półki wiszące', 169.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-kostka-orzech-mat-44-x-25-cm-roomers-17779.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18119', 'Komoda z drzwiami biała / dąb sonoma mat 110 cm Livorno', 'Komody/Komody z drzwiami', 939.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-dab-sonoma-mat-110-cm-livorno-18119.feed10009', 'High Glossy Furniture');
