-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26546', 'Fotel bujany na płozie kremowy Liberto 2', 'Fotele/Fotele bujane', 954.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-na-plozie-kremowy-liberto-2-26546.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26547', 'Fotel bujany na płozie kremowy Liberto', 'Fotele/Fotele bujane', 979.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-na-plozie-kremowy-liberto-26547.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26553', 'Stół okrągły szklany transparentny / złoty mat / połysk 120 cm Liverpool', 'Stoly/Stoły nierozkładane', 925.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-szklany-transparentny-zloty-mat-polysk-120-cm-liverpool-26553.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26555', 'Stół owalny orzech / czarny mat 170 x 90 cm Locarno', 'Stoly/Stoły nierozkładane', 1169.0, 'https://www.meblepumo.pl/pl/products/stol-owalny-orzech-czarny-mat-170-x-90-cm-locarno-26555.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26571', 'Stół okrągły szklany brązowy / złoto antyczne mat 120 cm Lungo', 'Stoly/Stoły nierozkładane', 1249.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-szklany-brazowy-zloto-antyczne-mat-120-cm-lungo-26571.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26580', 'Stolik kawowy okrągły biały marmur / złoty mat 60 cm Madison', 'Stoliki kawowe i ławy/Stoliki kawowe', 539.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bialy-marmur-zloty-mat-60-cm-madison-26580.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26583', 'Zestaw 2 stolików kawowych okrągłych naturalny / czarny mat 51 cm, 41 cm Manado 2', 'Stoliki kawowe i ławy/Stoliki kawowe', 546.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-naturalny-czarny-mat-51-cm-41-cm-manado-2-26583.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26595', 'Stół rozkładany biały marmur / czarny mat 160 - 200 x 90 cm Marley', 'Stoly/Stoły rozkładane', 1869.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-marmur-czarny-mat-160-200-x-90-cm-marley-26595.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26601', 'Fotel wypoczynkowy tapicerowany zielony Marvel', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-marvel-26601.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26602', 'Fotel wypoczynkowy tapicerowany szary Marvel', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-marvel-26602.feed10009', 'HALMAR');
