-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28142', 'Komoda z drzwiami czarna mat 150 cm Milo', 'Komody/Komody z drzwiami', 1089.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-150-cm-milo-28142.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28143', 'Komoda z drzwiami beżowa mat 200 cm Milo', 'Komody/Komody z drzwiami', 1389.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bezowa-mat-200-cm-milo-28143.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28144', 'Komoda z drzwiami czarna mat 200 cm Milo', 'Komody/Komody z drzwiami', 1329.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-milo-28144.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28145', 'Szafka RTV beżowa mat 200 cm Milo', 'Szafki RTV', 1139.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-mat-200-cm-milo-28145.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28146', 'Szafka RTV czarna mat 200 cm Milo', 'Szafki RTV', 1059.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-milo-28146.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28147', 'Szafka RTV beżowa mat 150 cm Milo', 'Szafki RTV', 879.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-mat-150-cm-milo-28147.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28148', 'Szafka RTV czarna mat 150 cm Milo', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-150-cm-milo-28148.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28149', 'Komplet szafek nocnych beżowy mat 45 cm Milo', 'Szafki nocne', 669.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-bezowy-mat-45-cm-milo-28149.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28150', 'Komplet szafek nocnych czarny mat 45 cm Milo', 'Szafki nocne', 639.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-mat-45-cm-milo-28150.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28159', 'Stolik kawowy okrągły antracyt / czarny mat 80 cm Urban', 'Stoliki kawowe i ławy/Stoliki kawowe', 1529.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-antracyt-czarny-mat-80-cm-urban-28159.feed10009', 'Fato Luxmeble');
