-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19889', 'Szafka RTV dąb sonoma mat 181 cm Vero', 'Pozostałe produkty', 1159.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-sonoma-mat-181-cm-vero-19889.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19890', 'Szafka RTV antracyt połysk 181 cm Vero', 'Pozostałe produkty', 1279.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-antracyt-polysk-181-cm-vero-19890.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19891', 'Witryna dwudrzwiowa biała połysk 121 x 166 cm Vero', 'Witryny i kredensy/Witryny', 2059.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-biala-polysk-121-x-166-cm-vero-19891.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19892', 'Witryna dwudrzwiowa dąb sonoma mat 121 x 166 cm Vero', 'Witryny i kredensy/Witryny', 1999.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-dab-sonoma-mat-121-x-166-cm-vero-19892.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19893', 'Witryna dwudrzwiowa antracyt połysk 121 x 166 cm Vero', 'Witryny i kredensy/Witryny', 2129.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-antracyt-polysk-121-x-166-cm-vero-19893.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19979', 'Oświetlenie LED białe 80 cm do szafek RTV i komody', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-biale-80-cm-do-szafek-rtv-i-komody-19979.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19989', 'Stół rozkładany biały mat 140-180 x 80 cm Rossini', 'Stoly/Stoły rozkładane', 1529.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-140-180-x-80-cm-rossini-19989.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19990', 'Stół rozkładany biały mat 160-240 x 90 cm Rossini', 'Stoly/Stoły rozkładane', 1859.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-160-240-x-90-cm-rossini-19990.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19996', 'Stół loftowy dąb san remo / czarny mat 170 x 90 cm Yohann', 'Stoly/Stoły nierozkładane', 1029.0, 'https://www.meblepumo.pl/pl/products/stol-loftowy-dab-san-remo-czarny-mat-170-x-90-cm-yohann-19996.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20007', 'Fotel z podnóżkiem tapicerowany ekoskóra jasnobrązowy Cork', 'Fotele/Fotele wypoczynkowe', 2499.0, 'https://www.meblepumo.pl/pl/products/fotel-z-podnozkiem-tapicerowany-ekoskora-jasnobrazowy-cork-20007.feed10009', 'Meble tapicerowane');
