-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24539', 'Witryna dwudrzwiowa z szufladami dąb wotan / czarna mat 120 x 160 cm Livorno', 'Witryny i kredensy/Witryny', 1289.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-dab-wotan-czarna-mat-120-x-160-cm-livorno-24539.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24540', 'Szafka RTV dąb wotan / czarna mat 160 cm Livorno', 'Szafki RTV', 529.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-wotan-czarna-mat-160-cm-livorno-24540.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24541', 'Komoda z drzwiami dąb wotan / czarna mat 110 cm Livorno', 'Komody/Komody z drzwiami', 889.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-wotan-czarna-mat-110-cm-livorno-24541.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24542', 'Szafa dwudrzwiowa z szufladami dąb wotan / czarna mat 110 x 190 cm Livorno', 'Szafy/Szafy uchylne', 1079.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-z-szufladami-dab-wotan-czarna-mat-110-x-190-cm-livorno-24542.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24546', 'Stolik kawowy z półkami dąb wotan / czarny mat 110 x 60 cm Livorno', 'Stoliki kawowe i ławy/Stoliki kawowe', 469.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polkami-dab-wotan-czarny-mat-110-x-60-cm-livorno-24546.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24547', 'Szafka RTV dąb wotan / czarna mat 140 cm Livorno', 'Szafki RTV', 639.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-wotan-czarna-mat-140-cm-livorno-24547.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24548', 'Stolik kawowy z półkami dąb wotan / czarny mat 60 x 60 cm Livorno', 'Stoliki kawowe i ławy/Stoliki kawowe', 389.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polkami-dab-wotan-czarny-mat-60-x-60-cm-livorno-24548.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24549', 'Komoda z szufladami i drzwiami dąb wotan / czarna mat 110 cm Livorno', 'Komody/Komody z szufladami i drzwiami', 1069.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-wotan-czarna-mat-110-cm-livorno-24549.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24550', 'Komoda z szufladami i drzwiami dąb wotan / czarna mat 150 cm Livorno', 'Komody/Komody z szufladami i drzwiami', 879.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-wotan-czarna-mat-150-cm-livorno-24550.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24551', 'Komoda z drzwiami dąb wotan / czarna mat 150 cm Livorno', 'Komody/Komody z drzwiami', 739.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-wotan-czarna-mat-150-cm-livorno-24551.feed10009', 'High Glossy Furniture');
