-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28160', 'Stolik kawowy okrągły antracyt / czarny mat 60 cm Urban', 'Stoliki kawowe i ławy/Stoliki kawowe', 1139.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-antracyt-czarny-mat-60-cm-urban-28160.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28161', 'Konsola dąb olejowany 100 cm Soline', 'Toaletki i konsole/Konsole ', 739.0, 'https://www.meblepumo.pl/pl/products/konsola-dab-olejowany-100-cm-soline-28161.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28162', 'Konsola z półką dąb olejowany 99 cm Soline', 'Toaletki i konsole/Konsole ', 689.0, 'https://www.meblepumo.pl/pl/products/konsola-z-polka-dab-olejowany-99-cm-soline-28162.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28163', 'Ławka do przedpokoju dąb olejowany 95 cm Soline', 'Ławki do przedpokoju', 699.0, 'https://www.meblepumo.pl/pl/products/lawka-do-przedpokoju-dab-olejowany-95-cm-soline-28163.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28164', 'Ławka z półką dąb olejowany 88 cm Soline', 'Ławki do przedpokoju', 429.0, 'https://www.meblepumo.pl/pl/products/lawka-z-polka-dab-olejowany-88-cm-soline-28164.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28165', 'Wieszak ścienny czarny 38 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 169.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-czarny-38-cm-soline-28165.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28166', 'Wieszak ścienny czarny 58 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 279.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-czarny-58-cm-soline-28166.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28167', 'Wieszak ścienny dąb olejowany 58 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 269.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-olejowany-58-cm-soline-28167.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28168', 'Wieszak ścienny dąb olejowany 38 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 169.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-olejowany-38-cm-soline-28168.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28169', 'Wieszak ścienny czarny 30 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 85.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-czarny-30-cm-soline-28169.feed10009', 'Fato Luxmeble');
