-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23260', 'Komoda z szufladami i drzwiami antracyt / drewno postarzane mat 207 cm Factory', 'Komody/Komody z szufladami i drzwiami', 1356.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-antracyt-drewno-postarzane-mat-207-cm-factory-23260.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23261', 'Komoda z szufladami i drzwiami antracyt / jasne drewno postarzane mat 119 cm Factory', 'Komody/Komody z szufladami i drzwiami', 945.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-antracyt-jasne-drewno-postarzane-mat-119-cm-factory-23261.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23265', 'Komoda z drzwiami biała wysoki połysk 181 cm Solo', 'Komody/Komody z drzwiami', 1389.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-181-cm-solo-23265.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23266', 'Komoda z szufladami i drzwiami biała wysoki połysk 181 cm Solo', 'Komody/Komody z szufladami i drzwiami', 1549.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-181-cm-solo-23266.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23267', 'Komoda z szufladami i drzwiami biała wysoki połysk 241 cm Solo', 'Komody/Komody z szufladami i drzwiami', 2069.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-241-cm-solo-23267.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23268', 'Komoda z drzwiami antracyt wysoki połysk 181 cm Solo', 'Komody/Komody z drzwiami', 1519.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-antracyt-wysoki-polysk-181-cm-solo-23268.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23269', 'Komoda z szufladami i drzwiami antracyt wysoki połysk 241 cm Solo', 'Komody/Komody z szufladami i drzwiami', 2249.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-antracyt-wysoki-polysk-241-cm-solo-23269.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23270', 'Komoda z szufladami i drzwiami antracyt wysoki połysk 181 cm Solo', 'Komody/Komody z szufladami i drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-antracyt-wysoki-polysk-181-cm-solo-23270.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23271', 'Komoda wysoka z drzwiami biała wysoki połysk 121 cm Solo', 'Komody/Komody z drzwiami', 1389.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-wysoki-polysk-121-cm-solo-23271.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23272', 'Komoda wysoka z drzwiami antracyt wysoki połysk 121 cm Solo', 'Komody/Komody z drzwiami', 1519.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-antracyt-wysoki-polysk-121-cm-solo-23272.feed10009', 'Italia Trend');
