-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25462', 'BULLET KM-2 komoda czarny, nogi: złoty', 'halmar tymczasowa', 999.0, 'https://www.meblepumo.pl/pl/products/bullet-km-2-komoda-czarny-nogi-zloty-25462.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25463', 'BULLET LAW-1 ława czarny, nogi: złoty', 'halmar tymczasowa', 456.0, 'https://www.meblepumo.pl/pl/products/bullet-law-1-lawa-czarny-nogi-zloty-25463.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25466', 'Ławostół rozkładany dąb wotan mat 126 - 167 x 70 cm Baretti', 'Stoliki kawowe i ławy/Ławostoły', 1499.0, 'https://www.meblepumo.pl/pl/products/lawostol-rozkladany-dab-wotan-mat-126-167-x-70-cm-baretti-25466.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25468', 'Łóżko kontynentalne z pojemnikiem szare 160x200 cm Continental 1', 'Łóżka i części/Łóżka', 3689.0, 'https://www.meblepumo.pl/pl/products/lozko-kontynentalne-z-pojemnikiem-szare-160x200-cm-continental-1-25468.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25469', 'Łóżko kontynentalne z pojemnikiem beżowe 160x200 cm Continental 2', 'Łóżka i części/Łóżka', 3689.0, 'https://www.meblepumo.pl/pl/products/lozko-kontynentalne-z-pojemnikiem-bezowe-160x200-cm-continental-2-25469.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25470', 'Łóżko kontynentalne z pojemnikiem szare 160x200 cm Continental 2', 'Łóżka i części/Łóżka', 3689.0, 'https://www.meblepumo.pl/pl/products/lozko-kontynentalne-z-pojemnikiem-szare-160x200-cm-continental-2-25470.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25471', 'Stół okrągły dąb naturalny mat 120 cm Elefante', 'Stoly/Stoły nierozkładane', 2499.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-dab-naturalny-mat-120-cm-elefante-25471.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25472', 'Stół rozkładany dąb naturalny mat 160 - 240 x 100 cm Elefante', 'Stoly/Stoły rozkładane', 3499.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-mat-160-240-x-100-cm-elefante-25472.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25475', 'Krzesło do jadalni tapicerowane granatowe / wielobarwne Endo', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-wielobarwne-endo-25475.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25478', 'Fotel wypoczynkowy tapicerowany szary / naturalny Freedom', 'Fotele/Fotele wypoczynkowe', 1489.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-naturalny-freedom-25478.feed10009', 'HALMAR');
