-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23576', 'Szafka na buty czterodrzwiowa biała mat 70 cm Roma', 'Szafki na buty', 619.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-czterodrzwiowa-biala-mat-70-cm-roma-23576.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23578', 'Szafka na buty czterodrzwiowa czarna mat 70 cm Roma', 'Szafki na buty', 659.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-czterodrzwiowa-czarna-mat-70-cm-roma-23578.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23579', 'Szafka na buty czterodrzwiowa dąb sonoma / biała mat / wysoki połysk 99 cm Roma', 'Szafki na buty', 759.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-czterodrzwiowa-dab-sonoma-biala-mat-wysoki-polysk-99-cm-roma-23579.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23580', 'Szafka na buty pięciodrzwiowa dąb sonoma / biała mat / wysoki połysk 99 cm Roma', 'Szafki na buty', 1079.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-pieciodrzwiowa-dab-sonoma-biala-mat-wysoki-polysk-99-cm-roma-23580.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23581', 'Szafka na buty biała mat 70 cm Roma', 'Szafki na buty', 959.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-biala-mat-70-cm-roma-23581.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23582', 'Szafka na buty dąb sonoma mat 70 cm Roma', 'Szafki na buty', 767.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-dab-sonoma-mat-70-cm-roma-23582.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23586', 'Komoda Orlando 2D3S', 'Komody/Komody z szufladami i drzwiami', 644.0, 'https://www.meblepumo.pl/pl/products/komoda-orlando-2d3s-23586.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23587', 'Szafka RTV biała / dąb / szara mat 160 cm Orlando', 'Szafki RTV', 465.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-szara-mat-160-cm-orlando-23587.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23589', 'Fotel wypoczynkowy tapicerowany beżowy Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-bezowy-holly-23589.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23590', 'Fotel wypoczynkowy tapicerowany brązowy Holly', 'Fotele/Fotele wypoczynkowe', 1689.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-brazowy-holly-23590.feed10009', 'Scandinavian Style Design');
