-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28214', 'Szafka RTV czarna mat 150 cm Modena', 'Szafki RTV', 889.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-150-cm-modena-28214.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28215', 'Stolik kawowy z półką biały mat 110 x 60 cm Modena', 'Stoliki kawowe i ławy/Stoliki kawowe', 519.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-bialy-mat-110-x-60-cm-modena-28215.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28216', 'Stolik kawowy z półką czarny mat 110 x 60 cm Modena', 'Stoliki kawowe i ławy/Stoliki kawowe', 539.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-czarny-mat-110-x-60-cm-modena-28216.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28217', 'Komoda z drzwiami biały mat 150 cm Modena', 'Komody/Komody z drzwiami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bialy-mat-150-cm-modena-28217.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28218', 'Komoda z drzwiami czarny mat 150 cm Modena', 'Komody/Komody z drzwiami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarny-mat-150-cm-modena-28218.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28219', 'Komoda wysoka z drzwiami biała mat 100 x 166 cm Modena', 'Komody/Komody z drzwiami', 1269.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-mat-100-x-166-cm-modena-28219.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28220', 'Komoda wysoka z drzwiami czarna mat 100 x 166 cm Modena', 'Komody/Komody z drzwiami', 1329.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-czarna-mat-100-x-166-cm-modena-28220.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28221', 'Komoda z drzwiami dąb cremona / czarna mat 190 cm Monolit', 'Komody/Komody z drzwiami', 1069.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-cremona-czarna-mat-190-cm-monolit-28221.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28222', 'Komoda z drzwiami dąb cremona / czarna mat 150 cm Monolit', 'Komody/Komody z drzwiami', 859.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-cremona-czarna-mat-150-cm-monolit-28222.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28223', 'Szafka RTV dąb cremona / czarna mat 190 cm Monolit', 'Szafki RTV', 789.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-cremona-czarna-mat-190-cm-monolit-28223.feed10009', 'High Glossy Furniture');
