-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28132', 'Komoda z drzwiami beżowa mat 200 cm Linea', 'Komody/Komody z drzwiami', 1389.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bezowa-mat-200-cm-linea-28132.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28133', 'Szafka RTV beżowa mat 150 cm Linea', 'Szafki RTV', 879.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-mat-150-cm-linea-28133.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28134', 'Szafka RTV beżowa mat 200 cm Linea', 'Szafki RTV', 1139.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-mat-200-cm-linea-28134.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28135', 'Komplet szafek nocnych beżowy mat 45 cm Linea', 'Szafki nocne', 468.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-bezowy-mat-45-cm-linea-28135.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28136', 'Komplet szafek nocnych czarny mat 45 cm Linea', 'Szafki nocne', 447.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-mat-45-cm-linea-28136.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28137', 'Szafka RTV czarna mat 200 cm Linea', 'Szafki RTV', 1059.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-linea-28137.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28138', 'Szafka RTV czarna mat 150 cm Linea', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-150-cm-linea-28138.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28139', 'Komoda z drzwiami czarna mat 200 cm Linea', 'Komody/Komody z drzwiami', 1329.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-linea-28139.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28140', 'Komoda z drzwiami czarna mat 150 cm Linea', 'Komody/Komody z drzwiami', 1089.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-150-cm-linea-28140.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28141', 'Komoda z drzwiami beżowa mat 150 cm Milo', 'Komody/Komody z drzwiami', 1139.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bezowa-mat-150-cm-milo-28141.feed10009', 'High Glossy Furniture');
