-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10413', 'Zestaw 2 półek wiszących czarnych mat 125 x 20 cm Simple', 'Pozostałe produkty', 160.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-polek-wiszacych-czarnych-mat-125-x-20-cm-simple-10413.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10421', 'Oświetlenie 1 LED niebieskie High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 59.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-1-led-niebieskie-high-glossy-furniture-10421.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10422', 'Oświetlenie 1 LED czerwone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 59.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-1-led-czerwone-high-glossy-furniture-10422.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10423', 'Oświetlenie 1 LED zielone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 59.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-1-led-zielone-high-glossy-furniture-10423.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10424', 'Oświetlenie 1 LED białe High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 59.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-1-led-biale-high-glossy-furniture-10424.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10425', 'Oświetlenie 2 LED białe High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 69.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-2-led-biale-high-glossy-furniture-10425.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10426', 'Oświetlenie 2 LED zielone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 69.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-2-led-zielone-high-glossy-furniture-10426.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10427', 'Oświetlenie 2 LED czerwone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 69.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-2-led-czerwone-high-glossy-furniture-10427.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10428', 'Oświetlenie 2 LED niebieskie High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 69.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-2-led-niebieskie-high-glossy-furniture-10428.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10429', 'Oświetlenie LED 3 punktowe niebieskie, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 79.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-3-punktowe-niebieskie-high-glossy-furniture-10429.feed10009', 'High Glossy Furniture');
