-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28497', 'Łóżko jednoosobowe szare 90 x 200 cm Russo', 'Łóżka dziecięce', 1229.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-szare-90-x-200-cm-russo-28497.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28500', 'Szafa dwudrzwiowa antracyt / grafit mat 90 x 210 cm Teo', 'Szafy/Szafy uchylne', 999.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-antracyt-grafit-mat-90-x-210-cm-teo-28500.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28501', 'Szafa trzydrzwiowa antracyt / grafit mat 134 x 210 cm Teo', 'Szafy/Szafy uchylne', 1399.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-antracyt-grafit-mat-134-x-210-cm-teo-28501.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28502', 'Szafa czterodrzwiowa antracyt / grafit mat 179 x 210 cm Teo', 'Szafy/Szafy uchylne', 1729.0, 'https://www.meblepumo.pl/pl/products/szafa-czterodrzwiowa-antracyt-grafit-mat-179-x-210-cm-teo-28502.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28503', 'Komoda z szufladami antracyt / grafit mat 110 cm Teo', 'Komody/Komody z szufladami', 699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-antracyt-grafit-mat-110-cm-teo-28503.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28504', 'Komoda z szufladami antracyt / grafit mat 140 cm Teo', 'Komody/Komody z szufladami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-antracyt-grafit-mat-140-cm-teo-28504.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28505', 'Komoda  z drzwiami i szufladami antracyt / grafit mat 120 cm Teo', 'Komody/Komody z szufladami', 839.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-antracyt-grafit-mat-120-cm-teo-28505.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28506', 'Biurko z szufladami antracyt / grafit mat 120 cm Teo', 'Biurka/Biurka z szufladami i drzwiami', 693.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-antracyt-grafit-mat-120-cm-teo-28506.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28507', 'Szafka nocna antracyt / grafit mat 50 cm Teo', 'Szafki nocne', 429.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-antracyt-grafit-mat-50-cm-teo-28507.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28509', 'Nadstawka na szafę antracyt / grafit mat 90 x 55 cm Teo', 'Szafy/Nadstawki na szafę', 299.0, 'https://www.meblepumo.pl/pl/products/nadstawka-na-szafe-antracyt-grafit-mat-90-x-55-cm-teo-28509.feed10009', 'MiroMark');
