-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26095', 'Sofa ogrodowa 2-osobowa naturalna / szara Ikaro X', 'Sofy i narożniki/Sofy ogrodowe', 899.0, 'https://www.meblepumo.pl/pl/products/sofa-ogrodowa-2-osobowa-naturalna-szara-ikaro-x-26095.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26096', 'Fotel ogrodowy rattanowy naturalny / szary Ikaro', 'Fotele/Fotele ogrodowe', 459.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-rattanowy-naturalny-szary-ikaro-26096.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26103', 'Ława Infinity srebrny, szkło, prostokątna', 'Stoliki kawowe i ławy/Stoliki kawowe', 1169.0, 'https://www.meblepumo.pl/pl/products/lawa-infinity-srebrny-szklo-prostokatna-26103.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26107', 'Stolik kawowy szklany ciemny marmur / złoty mat 60 cm Isabelle', 'Stoliki kawowe i ławy/Stoliki kawowe', 409.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-ciemny-marmur-zloty-mat-60-cm-isabelle-26107.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26108', 'Stolik kawowy okrągły szklany czarny / złoty mat 80 cm Ismena', 'Stoliki kawowe i ławy/Stoliki kawowe', 405.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-szklany-czarny-zloty-mat-80-cm-ismena-26108.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26110', 'Stół loftowy dąb złoty / czarny mat 160 x 90 cm Jackson', 'Stoly/Stoły nierozkładane', 1129.0, 'https://www.meblepumo.pl/pl/products/stol-loftowy-dab-zloty-czarny-mat-160-x-90-cm-jackson-26110.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26112', 'Fotel rozkładany ekoskóra brązowy Jeff', 'Fotele/Fotele rozkładane', 1189.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-ekoskora-brazowy-jeff-26112.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26113', 'Fotel rozkładany ekoskóra czarny Jeff', 'Fotele/Fotele rozkładane', 1189.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-ekoskora-czarny-jeff-26113.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26121', 'Biurko z regulowaną wysokością i kątem nachylenia sosna naturalna wysoki połysk 109 cm Julia', 'Biurka/Biurka z regulacją wysokości', 679.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulowana-wysokoscia-i-katem-nachylenia-sosna-naturalna-wysoki-polysk-109-cm-julia-26121.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26125', 'Krzesło na płozie ekoskóra białe / czarne K104', 'Krzesła/Krzesła na płozie', 423.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-biale-czarne-k104-26125.feed10009', 'HALMAR');
