-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24944', 'Półka wisząca biała mat 94 x 22 cm Bruno', 'Półki wiszące', 219.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-biala-mat-94-x-22-cm-bruno-24944.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24945', 'Biurko z szufladą białe mat 100 cm Bruno', 'Biurka/Biurka z szufladami i drzwiami', 1089.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-biale-mat-100-cm-bruno-24945.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24947', 'Szafa do pokoju dziecięcego biała mat 100 x 180 cm Bruno', 'Szafy/Szafy uchylne', 1679.0, 'https://www.meblepumo.pl/pl/products/szafa-do-pokoju-dzieciecego-biala-mat-100-x-180-cm-bruno-24947.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24951', 'Szafka nocna biała mat 46 cm Bruno', 'Szafki nocne', 559.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-mat-46-cm-bruno-24951.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24952', 'Komoda z szufladami biała mat 100 cm Bruno', 'Komody/Komody z szufladami', 1429.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-mat-100-cm-bruno-24952.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24955', 'Łóżko dziecięce białe / dąb 80x180 cm Bruno', 'Łóżka dziecięce', 1229.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-biale-dab-80x180-cm-bruno-24955.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24956', 'Łóżko dziecięce z szufladą białe / dąb 80x180 cm Bruno', 'Łóżka dziecięce', 1679.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-z-szuflada-biale-dab-80x180-cm-bruno-24956.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24961', 'Komoda z szufladami i drzwiami dekor bambusa mat 180 cm Boobang', 'Komody/Komody z szufladami i drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dekor-bambusa-mat-180-cm-boobang-24961.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24965', 'Szafka RTV dekor bambusa mat 140 cm Boobang', 'Szafki RTV', 1099.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dekor-bambusa-mat-140-cm-boobang-24965.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24976', 'Komoda z drzwiami przesuwnymi old wood mat 160 cm Windsor', 'Komody/Komody z drzwiami', 1079.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-przesuwnymi-old-wood-mat-160-cm-windsor-24976.feed10009', 'High Glossy Furniture');
