-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24480', 'Szafka RTV czarna mat 186 cm Ikon', 'Pozostałe produkty', 1149.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-186-cm-ikon-24480.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24482', 'Komoda z drzwiami rożowa mat 155 cm Ikon', 'Komody/Komody z drzwiami', 1469.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-rozowa-mat-155-cm-ikon-24482.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24483', 'Komoda z drzwiami granat mat 155 cm Ikon', 'Komody/Komody z drzwiami', 1549.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-granat-mat-155-cm-ikon-24483.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24491', 'Komoda z drzwiami czarna mat 155 cm Ikon', 'Komody/Komody z drzwiami', 1549.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-155-cm-ikon-24491.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24492', 'Komoda z drzwiami biała mat 155 cm Ikon', 'Komody/Komody z drzwiami', 1399.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-155-cm-ikon-24492.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24496', 'Łóżko dwuosobowe szare / orzech 160x200 cm Gorashi', 'Łóżka i części/Łóżka', 3269.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-szare-orzech-160x200-cm-gorashi-24496.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24497', 'Szafka RTV czarna mat / połysk 150 cm Sierra', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-polysk-150-cm-sierra-24497.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24502', 'Szafka RTV szara mat / połysk 150 cm Sierra', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-szara-mat-polysk-150-cm-sierra-24502.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24503', 'Szafka RTV czarna mat / połysk 200 cm Sierra', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-polysk-200-cm-sierra-24503.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24504', 'Szafka RTV grafitowa mat / połysk 200 cm Sierra', 'Szafki RTV', 1069.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-grafitowa-mat-polysk-200-cm-sierra-24504.feed10009', 'High Glossy Furniture');
