-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25341', 'Krzesło do jadalni tapicerowane czarne / wielobarwne K506', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-wielobarwne-k506-25341.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25343', 'Krzesło do jadalni tapicerowane rattan zielone / naturalne K508', 'Krzesła/Krzesła do jadalni', 383.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-rattan-zielone-naturalne-k508-25343.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25344', 'Krzesło do jadalni tapicerowane rattan szare / naturalne K508', 'Krzesła/Krzesła do jadalni', 383.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-rattan-szare-naturalne-k508-25344.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25346', 'Krzesło do jadalni tapicerowane szare K509', 'Krzesła/Krzesła do jadalni', 229.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k509-25346.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25347', 'Krzesło na płozie tapicerowane zielone K510', 'Krzesła/Krzesła na płozie', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-zielone-k510-25347.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25348', 'Krzesło na płozie tapicerowane musztardowe K510', 'Krzesła/Krzesła na płozie', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-musztardowe-k510-25348.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25351', 'Krzesło do jadalni plastikowe czarne / brązowe K512', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-plastikowe-czarne-brazowe-k512-25351.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25353', 'Krzesło ogrodowe plastikowe białe K514', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-biale-k514-25353.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25354', 'Krzesło ogrodowe plastikowe czarne K514', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-czarne-k514-25354.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25355', 'Krzesło ogrodowe plastikowe niebieskie K514', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-niebieskie-k514-25355.feed10009', 'HALMAR');
