-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24977', 'Szafka RTV drewno postarzane mat 200 cm Windsor', 'Pozostałe produkty', 1029.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-drewno-postarzane-mat-200-cm-windsor-24977.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24978', 'Szafka RTV dąb wotan mat 200 cm Windsor', 'Pozostałe produkty', 1099.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-wotan-mat-200-cm-windsor-24978.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24979', 'Szafka RTV czarna mat / połysk 200 cm Windsor', 'Pozostałe produkty', 1079.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-polysk-200-cm-windsor-24979.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24980', 'Szafka RTV biała mat / połysk 200 cm Windsor', 'Pozostałe produkty', 1059.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-polysk-200-cm-windsor-24980.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24981', 'Komoda z drzwiami przesuwnymi dąb wotan mat 160 cm Windsor', 'Komody/Komody z drzwiami', 1329.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-przesuwnymi-dab-wotan-mat-160-cm-windsor-24981.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24982', 'Komoda z drzwiami przesuwnymi czarna mat / wysoki połysk 160 cm Windsor', 'Komody/Komody z drzwiami', 1189.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-przesuwnymi-czarna-mat-wysoki-polysk-160-cm-windsor-24982.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24983', 'Komoda z drzwiami przesuwnymi biała mat / wysoki połysk 160 cm Windsor', 'Komody/Komody z drzwiami', 1159.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-przesuwnymi-biala-mat-wysoki-polysk-160-cm-windsor-24983.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24988', 'Fotel obrotowy młodzieżowy velvet zielony Gonzo 4', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-velvet-zielony-gonzo-4-24988.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24989', 'Fotel obrotowy młodzieżowy velvet szary Gonzo 4', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-velvet-szary-gonzo-4-24989.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24990', 'Fotel obrotowy młodzieżowy velvet różowy Gonzo 4', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-velvet-rozowy-gonzo-4-24990.feed10009', 'HALMAR');
