-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27427', 'Krzesło do jadalni drewniane białe / buk Buggi', 'Krzesła/Krzesła do jadalni', 328.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-biale-buk-buggi-27427.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27428', 'Krzesło do jadalni drewniane tapicerowane beżowe / białe Citrone', 'Krzesła/Krzesła do jadalni', 319.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-biale-citrone-27428.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27431', 'Krzesło do jadalni drewniane tapicerowane szare / dąb miodowy Citrone', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-dab-miodowy-citrone-27431.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27433', 'Krzesło do jadalni drewniane tapicerowane beżowe / dąb sonoma Citrone', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-dab-sonoma-citrone-27433.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27434', 'Krzesło do jadalni tapicerowane zielone / czarne Clarion 2', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-czarne-clarion-2-27434.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27435', 'Krzesło do jadalni tapicerowane granatowe / czarne Clarion 2', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-czarne-clarion-2-27435.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27436', 'Krzesło do jadalni tapicerowane szare / czarne Clarion 2', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-czarne-clarion-2-27436.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27437', 'Krzesło do jadalni tapicerowane szare / białe Clarion', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-biale-clarion-27437.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27438', 'Krzesło do jadalni tapicerowane szare / dąb miodowy Clarion', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-dab-miodowy-clarion-27438.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27440', 'Krzesło do jadalni drewniane białe Dariusz 2', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-biale-dariusz-2-27440.feed10009', 'HALMAR');
