-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27963', 'Blat do biurka jackson hickory 120 x 60 cm Sign', 'Biurka/Części do biurek', 239.0, 'https://www.meblepumo.pl/pl/products/blat-do-biurka-jackson-hickory-120-x-60-cm-sign-27963.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27964', 'Paski podporowe do blatów białe 120 cm Sign', 'Dodatki do mebli/Części do mebli', 189.0, 'https://www.meblepumo.pl/pl/products/paski-podporowe-do-blatow-biale-120-cm-sign-27964.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27966', 'Paski podporowe dla blatów do biurka Sign 120 x 6 x 2 cm, szary mat', 'Dodatki do mebli/Części do mebli', 189.0, 'https://www.meblepumo.pl/pl/products/paski-podporowe-dla-blatow-do-biurka-sign-120-x-6-x-2-cm-szary-mat-27966.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27968', 'Blat narożny do biurka z kontenerkiem jackson hickory / biały 150 x 100 x 76 cm Sign', 'Biurka/Części do biurek', 789.0, 'https://www.meblepumo.pl/pl/products/blat-narozny-do-biurka-z-kontenerkiem-jackson-hickory-bialy-150-x-100-x-76-cm-sign-27968.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27970', 'Blat narożny do biurka z kontenerkiem szary / jackson hickory 150 x 100 x 76 cm Sign', 'Biurka/Części do biurek', 819.0, 'https://www.meblepumo.pl/pl/products/blat-narozny-do-biurka-z-kontenerkiem-szary-jackson-hickory-150-x-100-x-76-cm-sign-27970.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27972', 'Biurko loftowe białe mat 150 cm Sign', 'Biurka/Biurka proste', 279.0, 'https://www.meblepumo.pl/pl/products/biurko-loftowe-biale-mat-150-cm-sign-27972.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27973', 'Biurko loftowe szare mat 150 cm Sign', 'Biurka/Biurka proste', 309.0, 'https://www.meblepumo.pl/pl/products/biurko-loftowe-szare-mat-150-cm-sign-27973.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27976', 'Stół ogrodowy brązowy / czarny mat 150 x 90 x 74 cm Master', 'Stoly/Stoły ogrodowe', 622.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-brazowy-czarny-mat-150-x-90-x-74-cm-master-27976.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27977', 'Krzesło ogrodowe tapicerowane rattan naturalne / szare / czarne K541', 'Krzesła/Krzesła ogrodowe', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-tapicerowane-rattan-naturalne-szare-czarne-k541-27977.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27978', 'Krzesło ogrodowe plastikowe czarne / naturalne K529', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-czarne-naturalne-k529-27978.feed10009', 'HALMAR');
