-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24624', 'Komoda z szufladami i drzwiami biała / dąb sonoma mat 200 cm Göteborg', 'Komody/Komody z szufladami i drzwiami', 1799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-sonoma-mat-200-cm-goteborg-24624.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24625', 'Szafka nocna biała mat 40 cm Göteborg', 'Szafki nocne', 519.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-mat-40-cm-goteborg-24625.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24626', 'Szafa dwudrzwiowa z szufladami biała mat 90 x 180 cm Göteborg', 'Pozostałe produkty', 1569.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-z-szufladami-biala-mat-90-x-180-cm-goteborg-24626.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24627', 'Witryna jednodrzwiowa biała mat 60 x 182 cm Malia', 'Witryny i kredensy/Witryny', 1039.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-biala-mat-60-x-182-cm-malia-24627.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24628', 'Witryna jednodrzwiowa czarna mat 60 x 182 cm Malia', 'Witryny i kredensy/Witryny', 1159.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-czarna-mat-60-x-182-cm-malia-24628.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24629', 'Stolik kawowy prostokątny biały mat 120 x 57 cm Malia', 'Stoliki kawowe i ławy/Stoliki kawowe', 629.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bialy-mat-120-x-57-cm-malia-24629.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24630', 'Stolik kawowy prostokątny czarny mat 120 x 57 cm Malia', 'Stoliki kawowe i ławy/Stoliki kawowe', 639.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-czarny-mat-120-x-57-cm-malia-24630.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24631', 'Komplet szafek nocnych czarny mat 44 cm Malia', 'Szafki nocne', 699.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-mat-44-cm-malia-24631.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24632', 'Komplet szafek nocnych biała mat 44 cm Malia', 'Szafki nocne', 649.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-biala-mat-44-cm-malia-24632.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24633', 'Nóżka do mebli złota 12 cm Malia', 'Dodatki do mebli/Części do mebli', 15.0, 'https://www.meblepumo.pl/pl/products/nozka-do-mebli-zlota-12-cm-malia-24633.feed10009', 'High Glossy Furniture');
