-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27121', 'Fotel biurowy tapicerowany czarny Sonata XXL', 'Fotele/Fotele do biurka', 2799.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-czarny-sonata-xxl-27121.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27122', 'Stopki do fotela biurowego czarne', 'Dodatki do mebli/Części do mebli', 6.0, 'https://www.meblepumo.pl/pl/products/stopki-do-fotela-biurowego-czarne-27122.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27134', 'Przedłużki do blatu dąb naturalny mat 85 x 40 cm Apex & Radus', 'Stoly/Stoły nierozkładane', 894.0, 'https://www.meblepumo.pl/pl/products/przedluzki-do-blatu-dab-naturalny-mat-85-x-40-cm-apex-radus-27134.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27142', 'Fotel wypoczynkowy tapicerowany szary Bishop', 'Fotele/Fotele wypoczynkowe', 989.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-bishop-27142.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27144', 'Ławostół rozkładany biały połysk 126 - 167 x 70 cm Busetti', 'Stoliki kawowe i ławy/Ławostoły', 1499.0, 'https://www.meblepumo.pl/pl/products/lawostol-rozkladany-bialy-polysk-126-167-x-70-cm-busetti-27144.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27145', 'Ławostół rozkładany dąb wotan / czarny mat 126 - 167 x 70 cm Busetti', 'Stoliki kawowe i ławy/Ławostoły', 1499.0, 'https://www.meblepumo.pl/pl/products/lawostol-rozkladany-dab-wotan-czarny-mat-126-167-x-70-cm-busetti-27145.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27156', 'Fotel wypoczynkowy tapicerowany szary / dąb  Chillout', 'Fotele/Fotele wypoczynkowe', 2289.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-dab-chillout-27156.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27162', 'Fotel wypoczynkowy Clubby tkanina popielata, nóżki lite drewno naturalne', 'Fotele/Fotele wypoczynkowe', 459.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-clubby-tkanina-popielata-nozki-lite-drewno-naturalne-27162.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27163', 'Stół do jadalni dąb wotan / czarny mat 120 x 68 cm Cobalt', 'Stoly/Stoły nierozkładane', 549.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-dab-wotan-czarny-mat-120-x-68-cm-cobalt-27163.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27170', 'Fotel wypoczynkowy tapicerowany zielony Delgado', 'Fotele/Fotele wypoczynkowe', 1119.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-delgado-27170.feed10009', 'HALMAR');
