-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27768', 'Szafka górna biała / dąb miodowy mat 30 cm Vento', 'Szafki kuchenne', 168.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-dab-miodowy-mat-30-cm-vento-27768.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27771', 'Szafka górna biała / beżowa mat / wysoki połysk 40 cm Vento', 'Szafki kuchenne', 199.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-bezowa-mat-wysoki-polysk-40-cm-vento-27771.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27774', 'Szafka górna biała / jasnoszara mat / wysoki połysk 40 cm Vento', 'Szafki kuchenne', 199.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-jasnoszara-mat-wysoki-polysk-40-cm-vento-27774.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27776', 'Szafka górna biała / beżowy mat 45 cm Vento', 'Szafki kuchenne', 214.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-bezowy-mat-45-cm-vento-27776.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27778', 'Szafka górna biała / dąb miodowy mat 45 cm Vento', 'Szafki kuchenne', 214.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-dab-miodowy-mat-45-cm-vento-27778.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27781', 'Szafka górna biała / beż mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 267.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-bez-mat-wysoki-polysk-60-cm-vento-27781.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27786', 'Szafka górna biała / beżowa mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 359.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-bezowa-mat-wysoki-polysk-80-cm-vento-27786.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27792', 'Szafka górna z ociekaczem biała mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 299.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-z-ociekaczem-biala-mat-wysoki-polysk-60-cm-vento-27792.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27793', 'Szafka górna z ociekaczem biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 299.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-z-ociekaczem-biala-dab-miodowy-mat-60-cm-vento-27793.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27794', 'Szafka górna z ociekaczem biała / jasnoszara mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 299.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-z-ociekaczem-biala-jasnoszara-mat-wysoki-polysk-60-cm-vento-27794.feed10009', 'HALMAR');
