-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23917', 'Fotel wypoczynkowy tapicerowany ciemnozielony Osso', 'Fotele/Fotele wypoczynkowe', 1899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-ciemnozielony-osso-23917.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23918', 'Fotel wypoczynkowy tapicerowany turkusowy Osso', 'Fotele/Fotele wypoczynkowe', 1899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-turkusowy-osso-23918.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23919', 'Fotel wypoczynkowy tapicerowany ciemnoszary Osso', 'Fotele/Fotele wypoczynkowe', 1899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-ciemnoszary-osso-23919.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23920', 'Pufa okrągła tapicerowana jasno zielona Osso', 'Pufy', 489.0, 'https://www.meblepumo.pl/pl/products/pufa-okragla-tapicerowana-jasno-zielona-osso-23920.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23921', 'Pufa okrągła tapicerowana żółta Osso', 'Pufy', 489.0, 'https://www.meblepumo.pl/pl/products/pufa-okragla-tapicerowana-zolta-osso-23921.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23922', 'Pufa okrągła tapicerowana szara Osso', 'Pufy', 489.0, 'https://www.meblepumo.pl/pl/products/pufa-okragla-tapicerowana-szara-osso-23922.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23923', 'Pufa okrągła tapicerowana zielona Osso', 'Pufy', 489.0, 'https://www.meblepumo.pl/pl/products/pufa-okragla-tapicerowana-zielona-osso-23923.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23924', 'Pufa okrągła tapicerowana turkusowa Osso', 'Pufy', 489.0, 'https://www.meblepumo.pl/pl/products/pufa-okragla-tapicerowana-turkusowa-osso-23924.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23925', 'Pufa okrągła tapicerowana ciemnoszara Osso', 'Pufy', 489.0, 'https://www.meblepumo.pl/pl/products/pufa-okragla-tapicerowana-ciemnoszara-osso-23925.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23930', 'Biurko z szufladami i drzwiami białe mat 109 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 489.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-drzwiami-biale-mat-109-cm-function-23930.feed10009', 'Tvilum');
