-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28267', 'Szafka RTV czarna mat 190 cm Aria', 'Szafki RTV', 979.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-190-cm-aria-28267.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28268', 'Komoda z szufladami i drzwiami kaszmir / orzech warmia mat 156 cm Reno', 'Komody/Komody z szufladami i drzwiami', 1199.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-orzech-warmia-mat-156-cm-reno-28268.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28269', 'Komoda z szufladami i drzwiami kaszmir / orzech warmia mat 104 cm Reno', 'Komody/Komody z szufladami i drzwiami', 959.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-orzech-warmia-mat-104-cm-reno-28269.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28270', 'Witryna trzydrzwiowa kaszmir / orzech warmia mat 165 x 42 x 90 cm Reno', 'Witryny i kredensy/Witryny', 1089.0, 'https://www.meblepumo.pl/pl/products/witryna-trzydrzwiowa-kaszmir-orzech-warmia-mat-165-x-42-x-90-cm-reno-28270.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28271', 'Witryna jednodrzwiowa kaszmir / orzech warmia mat 60 x 42 x 185 cm Reno', 'Witryny i kredensy/Witryny', 839.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-kaszmir-orzech-warmia-mat-60-x-42-x-185-cm-reno-28271.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28272', 'Szafa dwudrzwiowa kaszmir / orzech warmia mat 90 x 185 cm Reno', 'Szafy/Szafy uchylne', 1499.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-kaszmir-orzech-warmia-mat-90-x-185-cm-reno-28272.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28273', 'Łóżko dziecięce białe 80x160 cm Tim', 'Łóżka dziecięce', 999.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-biale-80x160-cm-tim-28273.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28274', 'Łóżko dziecięce białe 80x180 cm Tim', 'Łóżka dziecięce', 1029.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-biale-80x180-cm-tim-28274.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28275', 'Stolik kawowy okrągły antracyt / czarny mat 80 cm Marlon', 'Stoliki kawowe i ławy/Stoliki kawowe', 1369.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-antracyt-czarny-mat-80-cm-marlon-28275.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28276', 'Łóżko dziecięce białe 90x200 cm Modi', 'Łóżka dziecięce', 1259.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-biale-90x200-cm-modi-28276.feed10009', 'KidsBox');
