-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28439', 'Łóżko jednoosobowe z wysuwanym dodatkowym materacem białe 90 x 200 cm Ariza', 'Łóżka dziecięce', 819.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-z-wysuwanym-dodatkowym-materacem-biale-90-x-200-cm-ariza-28439.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28440', 'Materac piankowy składany 90 - 180 x 200 cm, Piza', 'Materace/Materace piankowe', 519.0, 'https://www.meblepumo.pl/pl/products/materac-piankowy-skladany-90-180-x-200-cm-piza-28440.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28441', 'Witryna dwudrzwiowa z szufladami kaszmir mat 80 x 192 cm Simple', 'Witryny i kredensy/Witryny', 1199.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-kaszmir-mat-80-x-192-cm-simple-28441.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28442', 'Komoda z szufladami i drzwiami kaszmir mat 120 cm Simple', 'Komody/Komody z szufladami i drzwiami', 749.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-mat-120-cm-simple-28442.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28443', 'Witryna jednodrzwiowa z szufladami kaszmir mat 60 x 192 cm Simple', 'Witryny i kredensy/Witryny', 949.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-kaszmir-mat-60-x-192-cm-simple-28443.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28444', 'Witryna wisząca przeszklona kaszmir mat 60 x 112 cm Simple', 'Pozostałe produkty', 439.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-przeszklona-kaszmir-mat-60-x-112-cm-simple-28444.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28445', 'Zestaw 2 półek wiszących kaszmir / czarna mat 125 x 20 cm Simple', 'Pozostałe produkty', 249.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-polek-wiszacych-kaszmir-czarna-mat-125-x-20-cm-simple-28445.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28446', 'Szafka RTV kaszmir / czarna mat 140 cm Simple', 'Pozostałe produkty', 489.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-czarna-mat-140-cm-simple-28446.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28447', 'Szafka RTV kaszmir / czarna mat 180 cm Simple', 'Pozostałe produkty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-czarna-mat-180-cm-simple-28447.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28448', 'Szafka na buty z siedziskiem jasnoszara / dąb artisan 91 cm Tosca', 'Szafki na buty', 549.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-z-siedziskiem-jasnoszara-dab-artisan-91-cm-tosca-28448.feed10009', 'TT-furniture');
