-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25797', 'Stół okrągły biały marmur / złoty mat 90 cm Casemiro', 'Stoly/Stoły nierozkładane', 899.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-bialy-marmur-zloty-mat-90-cm-casemiro-25797.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25798', 'Łóżko tapicerowane białe / czarne 120x200 cm Cassandra', 'Łóżka i części/Łóżka', 1429.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-biale-czarne-120x200-cm-cassandra-25798.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25800', 'Łóżko tapicerowane z szufladą białe / czarne 140x200 cm Cassandra S', 'Łóżka i części/Łóżka', 2149.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-biale-czarne-140x200-cm-cassandra-s-25800.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25801', 'Łóżko tapicerowane z szufladą białe / czarne 160x200 cm Cassandra S', 'Łóżka i części/Łóżka', 2283.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-biale-czarne-160x200-cm-cassandra-s-25801.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25803', 'Szafka nocna naturalna mat 40 cm Cassina', 'Szafki nocne', 489.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-naturalna-mat-40-cm-cassina-25803.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25804', 'Szafka nocna orzech mat 40 cm Cassina', 'Szafki nocne', 489.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-orzech-mat-40-cm-cassina-25804.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25812', 'Fotel wypoczynkowy tapicerowany zielony Castel', 'Fotele/Fotele wypoczynkowe', 765.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-castel-25812.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25814', 'Fotel wypoczynkowy tapicerowany musztardowy Castel', 'Fotele/Fotele wypoczynkowe', 765.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-musztardowy-castel-25814.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25826', 'Fotel biurowy tapicerowany szary Colin', 'Fotele/Fotele do biurka', 495.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-szary-colin-25826.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25829', 'Stół rozkładany dąb złoty / czarny mat 120 - 160 x 80 cm Colorado', 'Stoly/Stoły rozkładane', 739.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-zloty-czarny-mat-120-160-x-80-cm-colorado-25829.feed10009', 'HALMAR');
