-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27829', 'VENTO LZP listwa zakończeniowa prawa (1p=5szt)', 'halmar tymczasowa', 10.0, 'https://www.meblepumo.pl/pl/products/vento-lzp-listwa-zakonczeniowa-prawa-1p-5szt-27829.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27830', 'Zestaw mebli kuchennych biały / dąb sonoma 260 cm Viola', 'Zestawy mebli/Zestawy mebli kuchennych', 1799.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-bialy-dab-sonoma-260-cm-viola-27830.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27831', 'Zestaw mebli kuchennych beżowy / dąb sonoma / biały 260 cm Viola', 'Zestawy mebli/Zestawy mebli kuchennych', 1439.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-bezowy-dab-sonoma-bialy-260-cm-viola-27831.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27833', 'Zestaw mebli kuchennych szary marmur / czarny  240 cm Tamara', 'Zestawy mebli/Zestawy mebli kuchennych', 1969.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-szary-marmur-czarny-240-cm-tamara-27833.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27855', 'Szafka RTV czarna / dąb craft mat 200 cm Visione', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-dab-craft-mat-200-cm-visione-27855.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27856', 'Szafka RTV czarna / dąb craft mat 150 cm Visione', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-dab-craft-mat-150-cm-visione-27856.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27858', 'Witryna jednodrzwiowa czarna / dąb craft mat 60 x 190 cm Visione', 'Witryny i kredensy/Witryny', 1059.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-czarna-dab-craft-mat-60-x-190-cm-visione-27858.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27859', 'Komplet szafek nocnych czarny / dąb craft mat 44 cm Visione', 'Szafki nocne', 819.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-dab-craft-mat-44-cm-visione-27859.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27860', 'Szafka RTV biała mat 200 cm Harmony', 'Szafki RTV', 1059.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-200-cm-harmony-27860.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27861', 'Szafka RTV kaszmir mat 200 cm Harmony', 'Szafki RTV', 1139.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-200-cm-harmony-27861.feed10009', 'High Glossy Furniture');
