-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26818', 'Fotel gabinetowy ekoskóra brązowy Relax', 'Fotele/Fotele do biurka', 449.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-brazowy-relax-26818.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26819', 'Fotel gabinetowy ekoskóra czarny Relax', 'Fotele/Fotele do biurka', 449.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-czarny-relax-26819.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26820', 'Fotel gabinetowy ekoskóra szary Relax', 'Fotele/Fotele do biurka', 449.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-szary-relax-26820.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26828', 'Stół rozkładany szary marmur / szary mat 120 - 160 x 76 cm Ricardo', 'Stoly/Stoły rozkładane', 2519.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-szary-marmur-szary-mat-120-160-x-76-cm-ricardo-26828.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26832', 'Fotel gabinetowy tapicerowany szary Rino', 'Fotele/Fotele do biurka', 473.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-szary-rino-26832.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26837', 'Stół do jadalni biały mat 120 cm Roland', 'Stoly/Stoły nierozkładane', 699.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-bialy-mat-120-cm-roland-26837.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26840', 'Stół okrągły szklany złoty mat 110 x 110 cm Rondo', 'Stoly/Stoły nierozkładane', 699.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-szklany-zloty-mat-110-x-110-cm-rondo-26840.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26845', 'Pufa kwadratowa tapicerowana zielona Rubik', 'Pufy', 229.0, 'https://www.meblepumo.pl/pl/products/pufa-kwadratowa-tapicerowana-zielona-rubik-26845.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26848', 'Fotel gabinetowy tapicerowany szary Rubio', 'Fotele/Fotele do biurka', 679.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-szary-rubio-26848.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26853', 'Stół rozkładany szary mat 160 - 200 x 90 cm Salvador', 'Stoly/Stoły rozkładane', 2109.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-szary-mat-160-200-x-90-cm-salvador-26853.feed10009', 'HALMAR');
