-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28224', 'Szafka RTV dąb cremona / czarna mat 150 cm Monolit', 'Szafki RTV', 629.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-cremona-czarna-mat-150-cm-monolit-28224.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28225', 'Półka wisząca dąb cremona / czarna mat 150 x 18 cm Monolit', 'Półki wiszące', 219.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-dab-cremona-czarna-mat-150-x-18-cm-monolit-28225.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28226', 'Stolik kawowy z półką dąb cremona / czarny mat 100 x 50 cm Monolit', 'Stoliki kawowe i ławy/Stoliki kawowe', 429.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-cremona-czarny-mat-100-x-50-cm-monolit-28226.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28228', 'Witryna jednodrzwiowa dąb cremona / czarna mat 59 x 180 cm Monolit', 'Witryny i kredensy/Witryny', 919.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-dab-cremona-czarna-mat-59-x-180-cm-monolit-28228.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28229', 'Komoda wysoka z drzwiami dąb cremona / czarna mat 100 cm Monolit', 'Komody/Komody z drzwiami', 1069.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-dab-cremona-czarna-mat-100-cm-monolit-28229.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28230', 'Stelaż do łóżka 90x190 cm Futura NV', 'Łóżka i części/Stelaże do łóżek', 379.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-90x190-cm-futura-nv-28230.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28231', 'Szafka RTV biała mat 200 cm Silk', 'Szafki RTV', 849.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-200-cm-silk-28231.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28232', 'Szafka RTV wisząca czarna mat 200 cm Nero', 'Szafki RTV', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-czarna-mat-200-cm-nero-28232.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28233', 'Szafka RTV wisząca kaszmir mat 200 cm Silk', 'Szafki RTV', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-kaszmir-mat-200-cm-silk-28233.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28234', 'Komoda z drzwiami sosna czekoladowa 200 cm Velar', 'Komody/Komody z drzwiami', 1119.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-sosna-czekoladowa-200-cm-velar-28234.feed10009', 'Vivaladesign');
