-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27915', 'Biurko z regulacją wysokości elektryczne czarne mat 121 cm Luna', 'Biurka/Biurka z regulacją wysokości', 769.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-czarne-mat-121-cm-luna-27915.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27916', 'Biurko z regulacją wysokości elektryczne białe mat 121 cm Luna', 'Biurka/Biurka z regulacją wysokości', 1099.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-biale-mat-121-cm-luna-27916.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27917', 'Biurko z regulacją wysokości elektryczne antracyt  mat 121 cm Luna', 'Biurka/Biurka z regulacją wysokości', 1099.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-antracyt-mat-121-cm-luna-27917.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27918', 'Biurko z regulacją wysokości elektryczne dąb wotan mat 150 cm Luna', 'Biurka/Biurka z regulacją wysokości', 1149.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-dab-wotan-mat-150-cm-luna-27918.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27919', 'Biurko z regulacją wysokości elektryczne czarne mat 150 cm Luna', 'Biurka/Biurka z regulacją wysokości', 804.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-czarne-mat-150-cm-luna-27919.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27920', 'Biurko z regulacją wysokości elektryczne białe mat 150 cm Luna', 'Biurka/Biurka z regulacją wysokości', 804.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-biale-mat-150-cm-luna-27920.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27921', 'Biurko z regulacją wysokości elektryczne antracyt mat 150 cm Luna', 'Biurka/Biurka z regulacją wysokości', 1149.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-antracyt-mat-150-cm-luna-27921.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27922', 'Komoda z drzwiami garanatowa mat 80 cm Caracas', 'Komody/Komody z drzwiami', 799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-garanatowa-mat-80-cm-caracas-27922.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27924', 'Stolik kawowy z szufladą niebieski mat 110 x 60 cm Caracas', 'Stoliki kawowe i ławy/Stoliki kawowe', 829.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-niebieski-mat-110-x-60-cm-caracas-27924.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27925', 'Szafka RTV niebieska mat 160 cm Caracas', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-niebieska-mat-160-cm-caracas-27925.feed10009', 'Fontini ');
