-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24354', 'Szafka wysoka antracyt / dąb mat 50 cm Caro', 'Regały', 758.0, 'https://www.meblepumo.pl/pl/products/szafka-wysoka-antracyt-dab-mat-50-cm-caro-24354.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24356', 'Komoda wysoka z drzwiami dąb / antracyt mat 100 cm Caro', 'Komody/Komody z drzwiami', 1089.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-dab-antracyt-mat-100-cm-caro-24356.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24357', 'Komoda wysoka z drzwiami i szufladami szara / biała mat 180 cm Vasco', 'Komody/Komody z szufladami i drzwiami', 1635.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-i-szufladami-szara-biala-mat-180-cm-vasco-24357.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24359', 'Komoda z szufladami i drzwiami szara / biała mat 93 cm Vasco', 'Komody/Komody z szufladami i drzwiami', 1043.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-szara-biala-mat-93-cm-vasco-24359.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24361', 'Komoda wysoka z drzwiami szara / biała mat 80 cm Vasco', 'Komody/Komody z drzwiami', 823.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-szara-biala-mat-80-cm-vasco-24361.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24372', 'Stolik kawowy loftowy biały / czarny mat 40 x 35 cm Joko', 'Stoliki kawowe i ławy/Stoliki kawowe', 319.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-bialy-czarny-mat-40-x-35-cm-joko-24372.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24373', 'Stolik kawowy loftowy dąb olejowany / czarny mat 40 x 35 cm Joko', 'Stoliki kawowe i ławy/Stoliki kawowe', 329.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-dab-olejowany-czarny-mat-40-x-35-cm-joko-24373.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24374', 'Stolik kawowy loftowy dąb olejowany / czarny mat 120 x 60 cm Joko', 'Stoliki kawowe i ławy/Stoliki kawowe', 799.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-dab-olejowany-czarny-mat-120-x-60-cm-joko-24374.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24375', 'Stolik kawowy loftowy biały / czarny mat 120 x 60 cm Joko', 'Stoliki kawowe i ławy/Stoliki kawowe', 669.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-bialy-czarny-mat-120-x-60-cm-joko-24375.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24380', 'Stolik kawowy drewniany dąb lity sękaty / czarny mat 70 x 70 cm Seku', 'Stoliki kawowe i ławy/Stoliki kawowe', 599.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-drewniany-dab-lity-sekaty-czarny-mat-70-x-70-cm-seku-24380.feed10009', 'Fato Luxmeble');
