-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27749', 'Maskownica boku szafki antracyt mat 72 x 31,6 cm Vento', 'Dodatki do mebli/Części do mebli', 65.0, 'https://www.meblepumo.pl/pl/products/maskownica-boku-szafki-antracyt-mat-72-x-31-6-cm-vento-27749.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27750', 'Maskownica boku szafki beżowa wysoki połysk 72 x 31,6 cm Vento', 'Dodatki do mebli/Części do mebli', 65.0, 'https://www.meblepumo.pl/pl/products/maskownica-boku-szafki-bezowa-wysoki-polysk-72-x-31-6-cm-vento-27750.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27751', 'Maskownica boku szafki biała wysoki połysk 72 x 31,6 cm Vento', 'Dodatki do mebli/Części do mebli', 65.0, 'https://www.meblepumo.pl/pl/products/maskownica-boku-szafki-biala-wysoki-polysk-72-x-31-6-cm-vento-27751.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27752', 'VENTO DZ-72/31 maskownica boku szafki dąb miodowy (1p=1szt)', 'halmar tymczasowa', 65.0, 'https://www.meblepumo.pl/pl/products/vento-dz-72-31-maskownica-boku-szafki-dab-miodowy-1p-1szt-27752.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27753', 'VENTO DZ-72/31 maskownica boku szafki jasny popiel (1p=1szt)', 'halmar tymczasowa', 65.0, 'https://www.meblepumo.pl/pl/products/vento-dz-72-31-maskownica-boku-szafki-jasny-popiel-1p-1szt-27753.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27754', 'Maskownica boku szafki antracyt mat 72 x 57,6 cm Vento', 'Dodatki do mebli/Części do mebli', 117.0, 'https://www.meblepumo.pl/pl/products/maskownica-boku-szafki-antracyt-mat-72-x-57-6-cm-vento-27754.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27755', 'Maskownica boku szafki beżowa wysoki połysk 72 x 57,6 cm Vento', 'Dodatki do mebli/Części do mebli', 117.0, 'https://www.meblepumo.pl/pl/products/maskownica-boku-szafki-bezowa-wysoki-polysk-72-x-57-6-cm-vento-27755.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27756', 'Maskownica boku szafki biała wysoki połysk 72 x 57,6 cm Vento', 'Dodatki do mebli/Części do mebli', 117.0, 'https://www.meblepumo.pl/pl/products/maskownica-boku-szafki-biala-wysoki-polysk-72-x-57-6-cm-vento-27756.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27757', 'VENTO DZ-72/57 maskownica boku szafki dąb miodowy (1p=1szt)', 'halmar tymczasowa', 117.0, 'https://www.meblepumo.pl/pl/products/vento-dz-72-57-maskownica-boku-szafki-dab-miodowy-1p-1szt-27757.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27758', 'VENTO DZ-72/57 maskownica boku szafki jasny popiel (1p=1szt)', 'halmar tymczasowa', 117.0, 'https://www.meblepumo.pl/pl/products/vento-dz-72-57-maskownica-boku-szafki-jasny-popiel-1p-1szt-27758.feed10009', 'HALMAR');
