-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18252', 'Narożnik 3-osobowy lewostronny tapicerowany jasnozielony Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-lewostronny-tapicerowany-jasnozielony-sampras-18252.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18253', 'Narożnik 3-osobowy prawostronny tapicerowany jasnozielony Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-prawostronny-tapicerowany-jasnozielony-sampras-18253.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18254', 'Narożnik 3-osobowy lewostronny tapicerowany różowy Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-lewostronny-tapicerowany-rozowy-sampras-18254.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18255', 'Narożnik 3-osobowy prawostronny tapicerowany różowy Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-prawostronny-tapicerowany-rozowy-sampras-18255.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18301', 'Szafka nocna z szufladami czarna mat 40 cm Naia', 'Szafki nocne', 349.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-z-szufladami-czarna-mat-40-cm-naia-18301.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18302', 'Szafka nocna czarna mat 40 cm Naia', 'Szafki nocne', 259.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-czarna-mat-40-cm-naia-18302.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18304', 'Komoda wysoka z szufladami czarna mat 77 cm Naia', 'Komody/Komody z szufladami', 629.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-czarna-mat-77-cm-naia-18304.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18305', 'Komoda wysoka z szufladami czarna mat 40 cm Naia', 'Komody/Komody z szufladami', 679.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-czarna-mat-40-cm-naia-18305.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18306', 'Komoda z szufladami czarna mat 77 cm Naia', 'Komody/Komody z szufladami', 599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-mat-77-cm-naia-18306.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18309', 'Komoda z szufladami i drzwiami czarna mat 80 cm Naia', 'Komody/Komody z szufladami i drzwiami', 799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-czarna-mat-80-cm-naia-18309.feed10009', 'Tvilum');
