-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26054', 'Hoker z oparciem ekoskóra czarny / srebrny H69', 'Hokery', 299.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-czarny-srebrny-h69-26054.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26056', 'Hoker z oparciem tapicerowany biały / szary H86', 'Hokery', 289.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bialy-szary-h86-26056.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26058', 'Hoker z oparciem ekoskóra brązowy / czarny H88', 'Hokery', 299.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-brazowy-czarny-h88-26058.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26059', 'Hoker z oparciem ekoskóra brązowy / czarny H89', 'Hokery', 242.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-brazowy-czarny-h89-26059.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26061', 'Hoker z oparciem tapicerowany szary / orzech H93', 'Hokery', 359.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-orzech-h93-26061.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26062', 'Hoker z oparciem tapicerowany zielony / orzech H93', 'Hokery', 359.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-orzech-h93-26062.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26064', 'Hoker z oparciem tapicerowany zielony / czarny H95', 'Hokery', 252.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-czarny-h95-26064.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26065', 'Hoker z oparciem tapicerowany czarny H95', 'Hokery', 252.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-czarny-h95-26065.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26066', 'Hoker z oparciem tapicerowany granatowy / czarny H95', 'Hokery', 252.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-granatowy-czarny-h95-26066.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26067', 'Hoker z oparciem tapicerowany szary / czarny H95', 'Hokery', 252.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h95-26067.feed10009', 'HALMAR');
