-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23380', 'Biurko z szufladą białe / dąb sonoma mat 130 cm Function Plus', 'Biurka/Biurka z szufladami i drzwiami', 300.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-biale-dab-sonoma-mat-130-cm-function-plus-23380.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23381', 'Biurko z szufladą białe / dąb sonoma mat 110 cm Function Plus Small', 'Biurka/Biurka z szufladami i drzwiami', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-biale-dab-sonoma-mat-110-cm-function-plus-small-23381.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23402', 'Biurko narożne czarne / dąb sonoma mat 145 cm Function', 'Biurka/Biurka narożne', 799.0, 'https://www.meblepumo.pl/pl/products/biurko-narozne-czarne-dab-sonoma-mat-145-cm-function-23402.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23514', 'Fotel obrotowy młodzieżowy ekoskóra biały Gonzo 2', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-ekoskora-bialy-gonzo-2-23514.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23515', 'Fotel obrotowy młodzieżowy ekoskóra czarny Gonzo 2', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-ekoskora-czarny-gonzo-2-23515.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23516', 'Fotel obrotowy młodzieżowy ekoskóra fioletowy Gonzo 2', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-ekoskora-fioletowy-gonzo-2-23516.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23517', 'Fotel obrotowy młodzieżowy ekoskóra różowy Gonzo 2', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-ekoskora-rozowy-gonzo-2-23517.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23518', 'Fotel obrotowy młodzieżowy ekoskóra szary Gonzo 3', 'Fotele/Fotele młodzieżowe', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-ekoskora-szary-gonzo-3-23518.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23519', 'Fotel obrotowy młodzieżowy velvet szary Doral', 'Fotele/Fotele młodzieżowe', 292.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-velvet-szary-doral-23519.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23520', 'Fotel obrotowy młodzieżowy velvet zielony Doral', 'Fotele/Fotele młodzieżowe', 292.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-velvet-zielony-doral-23520.feed10009', 'HALMAR');
