-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24245', 'Szafa trzydrzwiowa biała mat 150 x 199 cm Madrid', 'Szafy/Szafy uchylne', 1699.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-biala-mat-150-x-199-cm-madrid-24245.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24246', 'Szafka na buty biała mat 102 cm Madrid', 'Szafki na buty', 799.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-biala-mat-102-cm-madrid-24246.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24247', 'Szafa dwudrzwiowa biała mat 102 x 199 cm Madrid', 'Szafy/Szafy uchylne', 1399.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-biala-mat-102-x-199-cm-madrid-24247.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24249', 'Komoda z szufladami biała mat 82 cm Madrid', 'Komody/Komody z szufladami', 599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-mat-82-cm-madrid-24249.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24250', 'Szafka RTV biała mat 151 cm Madrid', 'Szafki RTV', 769.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-151-cm-madrid-24250.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24251', 'Stolik kawowy z półką biały mat 81 x 81 cm Madrid', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-bialy-mat-81-x-81-cm-madrid-24251.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24252', 'Witryna dwudrzwiowa z szufladami biała mat 78 x 199 cm Madrid', 'Witryny i kredensy/Witryny', 1329.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-biala-mat-78-x-199-cm-madrid-24252.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24254', 'Komoda z szufladami i drzwiami biała mat 151 cm Madrid', 'Komody/Komody z szufladami i drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-mat-151-cm-madrid-24254.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24255', 'Komoda z drzwiami i szufladami biała mat 82 cm Madrid', 'Komody/Komody z szufladami i drzwiami', 529.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-biala-mat-82-cm-madrid-24255.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24256', 'Komoda z szufladami i drzwiami dąb sonoma mat 180 cm Bali', 'Komody/Komody z szufladami i drzwiami', 1799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-sonoma-mat-180-cm-bali-24256.feed10009', 'Fontini ');
