-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28449', 'Lustro w ramie jasnoszarej / dąb artisan 91 x 89 cm Tosca', 'Lustra', 439.0, 'https://www.meblepumo.pl/pl/products/lustro-w-ramie-jasnoszarej-dab-artisan-91-x-89-cm-tosca-28449.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28450', 'Wieszak ścienny z półką jasnoszary / dąb artisan mat 91 cm Tosca', 'Wieszaki na ubrania/Wieszaki ścienne', 489.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-z-polka-jasnoszary-dab-artisan-mat-91-cm-tosca-28450.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28452', 'Szafa jednodrzwiowa jasnoszara / dąb artisan mat 65 x 201 cm Tosca', 'Szafy/Szafy uchylne', 1329.0, 'https://www.meblepumo.pl/pl/products/szafa-jednodrzwiowa-jasnoszara-dab-artisan-mat-65-x-201-cm-tosca-28452.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28453', 'Zestaw 3 stolików kawowych drewnianych dąb sękaty mat 50 x 50 cm, 35 x 35 cm, 30 x 30 cm Loopi', 'Stoliki kawowe i ławy/Stoliki kawowe', 489.0, 'https://www.meblepumo.pl/pl/products/zestaw-3-stolikow-kawowych-drewnianych-dab-sekaty-mat-50-x-50-cm-35-x-35-cm-30-x-30-cm-loopi-28453.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28454', 'Stolik kawowy okrągły szklany szary / czarny  80 x 45 cm Axis', 'Stoliki kawowe i ławy/Stoliki kawowe', 519.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-szklany-szary-czarny-80-x-45-cm-axis-28454.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28455', 'Stolik kawowy okrągły szklany / czarny  80 x 45 cm Axis', 'Stoliki kawowe i ławy/Stoliki kawowe', 499.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-szklany-czarny-80-x-45-cm-axis-28455.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28456', 'Stolik kawowy okrągły dąb mat 80 cm Bona', 'Stoliki kawowe i ławy/Stoliki kawowe', 799.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dab-mat-80-cm-bona-28456.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28459', 'Hoker z oparciem tapicerowany szary / czarny H121', 'Hokery', 369.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h121-28459.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28461', 'Hoker z oparciem ekoskóra szary / orzech / srebrny H123', 'Hokery', 529.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-szary-orzech-srebrny-h123-28461.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28494', 'Biurko z drzwiami naturalne / czarne mat 120 cm B51', 'Biurka/Biurka z szufladami i drzwiami', 467.0, 'https://www.meblepumo.pl/pl/products/biurko-z-drzwiami-naturalne-czarne-mat-120-cm-b51-28494.feed10009', 'HALMAR');
