-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28054', 'Regał biurowy jackson hickory mat 80 x 34 x 205 cm Sign', 'Regały', 629.0, 'https://www.meblepumo.pl/pl/products/regal-biurowy-jackson-hickory-mat-80-x-34-x-205-cm-sign-28054.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28055', 'Front do regału jackson hickory 75 x 82 cm Sign', 'Dodatki do mebli/Części do mebli', 149.0, 'https://www.meblepumo.pl/pl/products/front-do-regalu-jackson-hickory-75-x-82-cm-sign-28055.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28058', 'Drzwi do regału biurowego Sign 80 cm, biały mat', 'Dodatki do mebli/Części do mebli', 139.0, 'https://www.meblepumo.pl/pl/products/drzwi-do-regalu-biurowego-sign-80-cm-bialy-mat-28058.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28060', 'Regał Sign 41 x 34 x 205 cm, 4 półki, szary mat, półki jackson hickory', 'Regały', 549.0, 'https://www.meblepumo.pl/pl/products/regal-sign-41-x-34-x-205-cm-4-polki-szary-mat-polki-jackson-hickory-28060.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28061', 'Regał Sign 41 x 34 x 205 cm, 4 półki, jackson hickory, biały mat', 'Regały', 549.0, 'https://www.meblepumo.pl/pl/products/regal-sign-41-x-34-x-205-cm-4-polki-jackson-hickory-bialy-mat-28061.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28062', 'Regał niski Sign, 80 x 34 x 124 cm, 2 półki, szary mat ', 'Regały', 449.0, 'https://www.meblepumo.pl/pl/products/regal-niski-sign-80-x-34-x-124-cm-2-polki-szary-mat-28062.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28063', 'Regał niski Sign, 80 x 34 x 124 cm, 2 półki, jackson hickory', 'Regały', 419.0, 'https://www.meblepumo.pl/pl/products/regal-niski-sign-80-x-34-x-124-cm-2-polki-jackson-hickory-28063.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28127', 'Komoda z drzwiami kaszmir mat 150 cm Sole', 'Komody/Komody z drzwiami', 1379.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-150-cm-sole-28127.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28128', 'Komoda z drzwiami czarny mat 150 cm Sole', 'Komody/Komody z drzwiami', 1369.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarny-mat-150-cm-sole-28128.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28131', 'Komoda z drzwiami beżowa mat 150 cm Linea', 'Komody/Komody z drzwiami', 1139.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bezowa-mat-150-cm-linea-28131.feed10009', 'High Glossy Furniture');
