-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27201', 'Stół rozkładany dąb wotan / czarny mat 124 - 168 x 74 cm Greg', 'Stoly/Stoły rozkładane', 709.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-wotan-czarny-mat-124-168-x-74-cm-greg-27201.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27208', 'Stół rozkładany jasny dąb / czarny mat 126 - 206 x 80 cm Horus', 'Stoly/Stoły rozkładane', 1899.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-jasny-dab-czarny-mat-126-206-x-80-cm-horus-27208.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27209', 'Konsola industrialna dąb / czarna mat 106 cm Inferno', 'Toaletki i konsole/Konsole ', 889.0, 'https://www.meblepumo.pl/pl/products/konsola-industrialna-dab-czarna-mat-106-cm-inferno-27209.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27214', 'Krzesło do jadalni tapicerowane zielone K454', 'Krzesła/Krzesła do jadalni', 589.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k454-27214.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27216', 'Krzesło do jadalni tapicerowane zielone K458', 'Krzesła/Krzesła do jadalni', 689.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k458-27216.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27218', 'Krzesło do jadalni tapicerowane zielone K485', 'Krzesła/Krzesła do jadalni', 699.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k485-27218.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27220', 'Zestaw mebli kuchennych dąb artisan / czarny 240 cm Alina', 'Zestawy mebli/Zestawy mebli kuchennych', 1629.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-dab-artisan-czarny-240-cm-alina-27220.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27221', 'Zestaw mebli kuchennych akacja / wenge 260 cm Amanda', 'Zestawy mebli/Zestawy mebli kuchennych', 1689.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-akacja-wenge-260-cm-amanda-27221.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27222', 'Zestaw mebli kuchennych akacja / dąb / wenge 260 cm Amanda', 'Zestawy mebli/Zestawy mebli kuchennych', 1649.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-akacja-dab-wenge-260-cm-amanda-27222.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27224', 'Zestaw mebli kuchennych orzech 260 cm Margaret', 'Zestawy mebli/Zestawy mebli kuchennych', 2599.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-orzech-260-cm-margaret-27224.feed10009', 'HALMAR');
