-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26741', 'Sofa 2-osobowa z funkcją rozkładania tapicerowana szara Oslo 2', 'Sofy i narożniki/Sofy 2-osobowe', 1659.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-rozkladania-tapicerowana-szara-oslo-2-26741.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26747', 'Stół rozkładany biały mat 140 - 180 x 80 cm Palermo', 'Stoly/Stoły rozkładane', 2249.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-140-180-x-80-cm-palermo-26747.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26748', 'Ława z pufami Pampa orzech, czarny, popiel', 'Stoliki kawowe i ławy/Ławy', 569.0, 'https://www.meblepumo.pl/pl/products/lawa-z-pufami-pampa-orzech-czarny-popiel-26748.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26751', 'Łóżko dziecięce białe 90x200 cm Panama', 'Łóżka dziecięce', 609.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-biale-90x200-cm-panama-26751.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26755', 'Fotel z fukcją elektrycznego rozkładania oraz fukcją kołyski ekoskóra kremowy Paradise', 'Fotele/Fotele wypoczynkowe', 1669.0, 'https://www.meblepumo.pl/pl/products/fotel-z-fukcja-elektrycznego-rozkladania-oraz-fukcja-kolyski-ekoskora-kremowy-paradise-26755.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26756', 'Stół do jadalni biały / czarny mat 160 x 90 cm Pascal', 'Stoly/Stoły nierozkładane', 1379.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-bialy-czarny-mat-160-x-90-cm-pascal-26756.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26759', 'Fotel wypoczynkowy tapicerowany beżowy / orzech Pastore', 'Fotele/Fotele wypoczynkowe', 679.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-bezowy-orzech-pastore-26759.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26763', 'Stół rozkładany czarny / szary mat 160 - 200 x 90 cm Patrizio', 'Stoly/Stoły rozkładane', 3659.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-czarny-szary-mat-160-200-x-90-cm-patrizio-26763.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26764', 'Łóżko tapicerowane z szufladą szare 160x200 cm Percy', 'Łóżka i części/Łóżka', 2199.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-percy-26764.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26769', 'Stół okrągły dąb złoty / czarny mat 120 cm Pixel 2', 'Stoly/Stoły nierozkładane', 969.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-dab-zloty-czarny-mat-120-cm-pixel-2-26769.feed10009', 'HALMAR');
