-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26968', 'Fotel wypoczynkowy tapicerowany bordowy Tyrion', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-bordowy-tyrion-26968.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26969', 'Fotel wypoczynkowy tapicerowany zielony Tyrion', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-tyrion-26969.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26970', 'Fotel wypoczynkowy tapicerowany granatowy Tyrion', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-granatowy-tyrion-26970.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26971', 'Fotel wypoczynkowy tapicerowany żółty Tyrion', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zolty-tyrion-26971.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26972', 'Fotel wypoczynkowy tapicerowany szary Tyrion', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-tyrion-26972.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26976', 'Ława kwadratowa szary marmur / czarna mat 120 x 60 cm Universe 2', 'Stoliki kawowe i ławy/Ławy', 729.0, 'https://www.meblepumo.pl/pl/products/lawa-kwadratowa-szary-marmur-czarna-mat-120-x-60-cm-universe-2-26976.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26979', 'Ława szklana dymiona / srebrna mat / połysk 120 x 60 cm Universe', 'Stoliki kawowe i ławy/Ławy', 885.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-dymiona-srebrna-mat-polysk-120-x-60-cm-universe-26979.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26980', 'Ława szklana dymiona / złota mat / połysk 120 x 60 cm Universe', 'Stoliki kawowe i ławy/Ławy', 999.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-dymiona-zlota-mat-polysk-120-x-60-cm-universe-26980.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26982', 'Fotel biurowy siatka czarny Valdez', 'Fotele/Fotele do biurka', 369.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-czarny-valdez-26982.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26984', 'Fotel biurowy siatka szary / czarny Valdez', 'Fotele/Fotele do biurka', 369.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-szary-czarny-valdez-26984.feed10009', 'HALMAR');
