-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16504', 'Sofa 2-osobowa tapicerowana beżowa Sampras', 'Sofy i narożniki/Sofy 2-osobowe', 1649.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-bezowa-sampras-16504.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16505', 'Sofa 2-osobowa tapicerowana jasnozielona Sampras', 'Sofy i narożniki/Sofy 2-osobowe', 1649.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-jasnozielona-sampras-16505.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16506', 'Sofa 2-osobowa tapicerowana zielona Sampras', 'Sofy i narożniki/Sofy 2-osobowe', 1649.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-zielona-sampras-16506.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16507', 'Sofa 2-osobowa tapicerowana szara Sampras', 'Sofy i narożniki/Sofy 2-osobowe', 1649.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-szara-sampras-16507.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16509', 'Sofa 3-osobowa tapicerowana różowa Sampras', 'Sofy i narożniki/Sofy 3-osobowe', 1829.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-rozowa-sampras-16509.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16510', 'Sofa 3-osobowa tapicerowana beżowa Sampras', 'Sofy i narożniki/Sofy 3-osobowe', 1829.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-bezowa-sampras-16510.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16511', 'Sofa 3-osobowa tapicerowana zielona Sampras', 'Sofy i narożniki/Sofy 3-osobowe', 1829.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-zielona-sampras-16511.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16512', 'Sofa 3-osobowa tapicerowana ciemnozielona Sampras', 'Sofy i narożniki/Sofy 3-osobowe', 1829.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-ciemnozielona-sampras-16512.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16513', 'Sofa 3-osobowa tapicerowana szara Sampras', 'Sofy i narożniki/Sofy 3-osobowe', 1829.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-szara-sampras-16513.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16514', 'Sofa 3-osobowa tapicerowana cappuccino  Sampras', 'Sofy i narożniki/Sofy 3-osobowe', 1299.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-cappuccino-sampras-16514.feed10009', 'Scandinavian Style Design');
