-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24300', 'Konsola z szufladą dąb mat 80 cm Huglo', 'Toaletki i konsole/Konsole ', 799.0, 'https://www.meblepumo.pl/pl/products/konsola-z-szuflada-dab-mat-80-cm-huglo-24300.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24301', 'Taboret okrągły drewniany dąb Huglo', 'Krzesła/Krzesła do jadalni', 269.0, 'https://www.meblepumo.pl/pl/products/taboret-okragly-drewniany-dab-huglo-24301.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24302', 'Lustro okrągłe dąb 75 cm Huglo', 'Lustra', 375.0, 'https://www.meblepumo.pl/pl/products/lustro-okragle-dab-75-cm-huglo-24302.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24303', 'Lustro okrągłe dąb 40 cm Huglo', 'Lustra', 149.0, 'https://www.meblepumo.pl/pl/products/lustro-okragle-dab-40-cm-huglo-24303.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24304', 'Wieszak ścienny z półką dąb / czarny mat 42 cm Huglo', 'Wieszaki na ubrania/Wieszaki ścienne', 519.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-z-polka-dab-czarny-mat-42-cm-huglo-24304.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24305', 'Szafka nocna dąb mat 42 cm Huglo', 'Szafki nocne', 679.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-dab-mat-42-cm-huglo-24305.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24306', 'Stolik kawowy z szufladą dąb sonoma mat 100 x 60 cm Bali', 'Stoliki kawowe i ławy/Stoliki kawowe', 899.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-dab-sonoma-mat-100-x-60-cm-bali-24306.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24309', 'Krzesło do jadalni tapicerowane zielone Glamour', 'Pozostałe produkty', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-glamour-24309.feed10009', 'Manufaktura polskiego designu ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24311', 'Szafka na buty dąb sonoma 70 cm Bali', 'Szafki na buty', 769.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-dab-sonoma-70-cm-bali-24311.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24314', 'Komoda z drzwiami dąb sonoma mat 150 cm Bali', 'Komody/Komody z drzwiami', 1429.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-sonoma-mat-150-cm-bali-24314.feed10009', 'Fontini ');
