-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17016', 'Sofa tapicerowana Leya, 3 osobowa, zielona, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-zielona-nozki-wenge-17016.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17043', 'Szafka RTV biała / czarna mat 117 cm Oslo', 'Szafki RTV', 350.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-czarna-mat-117-cm-oslo-17043.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17048', 'Stolik kawowy z szufladami buk mat 115 x 70 cm Ramzey', 'Stoliki kawowe i ławy/Stoliki kawowe', 1599.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szufladami-buk-mat-115-x-70-cm-ramzey-17048.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17050', 'Zestaw 3 stolików kawowych drewnianych dąb dziki mat 60 x 60 cm, 60 x 60 cm, 80 x 80 cm Kamila', 'Stoliki kawowe i ławy/Stoliki kawowe', 929.0, 'https://www.meblepumo.pl/pl/products/zestaw-3-stolikow-kawowych-drewnianych-dab-dziki-mat-60-x-60-cm-60-x-60-cm-80-x-80-cm-kamila-17050.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17195', 'Stół rozkładany biały wysoki połysk 137 - 185 x 90 cm Sorelle', 'Stoly/Stoły rozkładane', 1119.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-wysoki-polysk-137-185-x-90-cm-sorelle-17195.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17203', 'Szafka RTV biała połysk 140 cm Basic', 'Szafki RTV', 869.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-140-cm-basic-17203.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17206', 'Szafka RTV biała połysk 181 cm Basic', 'Szafki RTV', 1079.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-181-cm-basic-17206.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17209', 'Komoda wysoka z drzwiami biała wysoki połysk 102 cm Basic', 'Komody/Komody z drzwiami', 1599.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-wysoki-polysk-102-cm-basic-17209.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17214', 'Witryna czterodrzwiowa biała wysoki połysk 102 cm Basic', 'Witryny i kredensy/Witryny', 1699.0, 'https://www.meblepumo.pl/pl/products/witryna-czterodrzwiowa-biala-wysoki-polysk-102-cm-basic-17214.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17217', 'Komoda z szufladami i drzwiami biała wysoki połysk 210 cm Basic', 'Komody/Komody z szufladami i drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-210-cm-basic-17217.feed10009', 'Italia Trend');
