-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17219', 'Witryna dwudrzwiowa biała połysk 61 x 162 cm Basic', 'Witryny i kredensy/Witryny', 1269.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-biala-polysk-61-x-162-cm-basic-17219.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17222', 'Oświetlenie LED RGB zmienne pilotem', 'Dodatki do mebli/Oświetlenie LED', 269.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-rgb-zmienne-pilotem-17222.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17233', 'Biurko proste białe mat 140 cm Penno', 'Biurka/Biurka proste', 899.0, 'https://www.meblepumo.pl/pl/products/biurko-proste-biale-mat-140-cm-penno-17233.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17281', 'Sofa 3-osobowa tapicerowana oliwkowa Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-oliwkowa-lily-17281.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17288', 'Sofa 2-osobowa z funkcją spania tapicerowana zielona Derry', 'Pozostałe produkty', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-zielona-derry-17288.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17291', 'Półka wisząca szara mat 90 x 18 cm Joker', 'Półki wiszące', 40.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-szara-mat-90-x-18-cm-joker-17291.feed10009', 'Formatti');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17305', 'Uchwyty do półki metalowe szare 2,5 cm Joker', 'Dodatki do mebli/Części do mebli', 49.0, 'https://www.meblepumo.pl/pl/products/uchwyty-do-polki-metalowe-szare-2-5-cm-joker-17305.feed10009', 'Formatti');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17306', 'Uchwyty do półki metalowe białe 2,5 cm Joker', 'Dodatki do mebli/Części do mebli', 24.0, 'https://www.meblepumo.pl/pl/products/uchwyty-do-polki-metalowe-biale-2-5-cm-joker-17306.feed10009', 'Formatti');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17336', 'Uchwyty do półki metalowe pomarańczowe 28 cm Biblo280', 'Dodatki do mebli/Części do mebli', 44.0, 'https://www.meblepumo.pl/pl/products/uchwyty-do-polki-metalowe-pomaranczowe-28-cm-biblo280-17336.feed10009', 'Formatti');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17337', 'Uchwyty do półki metalowe zielone 28 cm Biblo280', 'Dodatki do mebli/Części do mebli', 31.0, 'https://www.meblepumo.pl/pl/products/uchwyty-do-polki-metalowe-zielone-28-cm-biblo280-17337.feed10009', 'Formatti');
