-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27534', 'Krzesło do jadalni tapicerowane szare / dąb sonoma Toledo', 'Krzesła/Krzesła do jadalni', 469.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-dab-sonoma-toledo-27534.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27539', 'Krzesło do jadalni tapicerowane morskie / dąb miodowy Wenanty', 'Krzesła/Krzesła do jadalni', 769.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-morskie-dab-miodowy-wenanty-27539.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27541', 'Fotel wypoczynkowy tapicerowany zielony / wielokolorowy Pagoni', 'Fotele/Fotele wypoczynkowe', 1019.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-wielokolorowy-pagoni-27541.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27542', 'Fotel wypoczynkowy tapicerowany czarny / wielokolorowy Pagoni', 'Fotele/Fotele wypoczynkowe', 1019.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-czarny-wielokolorowy-pagoni-27542.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27543', 'Fotel wypoczynkowy velvet granatowy Pagoni', 'Fotele/Fotele wypoczynkowe', 1019.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-granatowy-pagoni-27543.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27545', 'Stolik kawowy z szufladą dąb wotan / czarny mat 110 x 60 cm Pantera', 'Stoliki kawowe i ławy/Stoliki kawowe', 439.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-dab-wotan-czarny-mat-110-x-60-cm-pantera-27545.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27567', 'Stół okrągły rozkładany dąb artisan / czarny mat 102 - 142 x 102 cm Ringo', 'Stoly/Stoły rozkładane', 685.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-rozkladany-dab-artisan-czarny-mat-102-142-x-102-cm-ringo-27567.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27568', 'Stół rozkładany biały mat 102 - 142 x 102 cm Ringo', 'Stoly/Stoły rozkładane', 685.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-102-142-x-102-cm-ringo-27568.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27572', 'Stół rozkładany dąb artisan / czarny mat 102 - 142 x 102 cm Ruben', 'Stoly/Stoły rozkładane', 795.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-artisan-czarny-mat-102-142-x-102-cm-ruben-27572.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27573', 'Stół rozkładany biały / dąb miodowy mat 102 - 142 x 102 cm Ruben', 'Stoly/Stoły rozkładane', 795.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-dab-miodowy-mat-102-142-x-102-cm-ruben-27573.feed10009', 'HALMAR');
