-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27926', 'Komoda z szufladami i drzwiami beż piaskowy mat 180 cm Eden', 'Komody/Komody z szufladami i drzwiami', 1029.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-bez-piaskowy-mat-180-cm-eden-27926.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27927', 'Komoda z szufladami i drzwiami beż piaskowy mat 120 cm Eden', 'Komody/Komody z szufladami i drzwiami', 799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-bez-piaskowy-mat-120-cm-eden-27927.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27928', 'Komoda z drzwiami beż piaskowy mat 180 cm Eden', 'Komody/Komody z drzwiami', 969.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bez-piaskowy-mat-180-cm-eden-27928.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27929', 'Komoda z drzwiami beż piaskowy mat 100 cm Eden', 'Komody/Komody z drzwiami', 1029.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bez-piaskowy-mat-100-cm-eden-27929.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27930', 'Stolik kawowy z półką beżowy mat 100 x 55 cm Eden', 'Stoliki kawowe i ławy/Stoliki kawowe', 499.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-bezowy-mat-100-x-55-cm-eden-27930.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27931', 'Witryna dwudrzwiowa z szufladami beżowa mat 90 x 170 cm Eden', 'Witryny i kredensy/Witryny', 1239.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-bezowa-mat-90-x-170-cm-eden-27931.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27932', 'Szafka RTV z półkami beżowa mat 180 cm Eden', 'Szafki RTV', 599.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-polkami-bezowa-mat-180-cm-eden-27932.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27933', 'Szafka RTV beżowa mat 180 cm Eden', 'Szafki RTV', 799.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-mat-180-cm-eden-27933.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27934', 'Szafka RTV beżowa mat 150 cm Eden', 'Szafki RTV', 599.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-mat-150-cm-eden-27934.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27935', 'Komoda z szufladami i drzwiami dąb artisan / antracyt mat 118 cm Medan', 'Komody/Komody z szufladami i drzwiami', 979.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-artisan-antracyt-mat-118-cm-medan-27935.feed10009', 'Fontini ');
