-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27862', 'Szafka RTV czarna  mat 200 cm Harmony', 'Szafki RTV', 1095.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-harmony-27862.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27863', 'Komoda z drzwiami biała mat 200 cm Harmony', 'Komody/Komody z drzwiami', 1639.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-200-cm-harmony-27863.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27864', 'Komoda z drzwiami kaszmir mat 200 cm Harmony', 'Komody/Komody z drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-200-cm-harmony-27864.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27865', 'Komoda z drzwiami czarna mat 200 cm Harmony', 'Komody/Komody z drzwiami', 1649.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-harmony-27865.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27875', 'Witryna dwudrzwiowa z szufladami niebieska mat 100 x 183 cm Caracas', 'Witryny i kredensy/Witryny', 1999.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-niebieska-mat-100-x-183-cm-caracas-27875.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27876', 'Komoda z drzwiami granatowa mat 180 cm Caracas', 'Komody/Komody z drzwiami', 1529.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-granatowa-mat-180-cm-caracas-27876.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27877', 'Komoda z szufladami i drzwiami granatowa mat 120 cm Caracas', 'Komody/Komody z szufladami i drzwiami', 1369.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-granatowa-mat-120-cm-caracas-27877.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27878', 'Komplet szafek nocnych czarny mat 44 cm Fiori', 'Szafki nocne', 619.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-mat-44-cm-fiori-27878.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27879', 'Komplet szafek nocnych dąb wotan mat 44 cm Fiori', 'Szafki nocne', 619.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-dab-wotan-mat-44-cm-fiori-27879.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27880', 'Komplet szafek nocnych biały mat 44 cm Fiori', 'Szafki nocne', 699.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-bialy-mat-44-cm-fiori-27880.feed10009', 'High Glossy Furniture');
