-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28200', 'Komplet szafek nocnych beżowy mat 44 cm Aurelia', 'Szafki nocne', 659.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-bezowy-mat-44-cm-aurelia-28200.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28201', 'Szafka RTV beżowa mat 150 cm Aurelia', 'Szafki RTV', 819.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-bezowa-mat-150-cm-aurelia-28201.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28202', 'Komoda z szufladami beżowa mat 50 cm Aurelia', 'Komody/Komody z szufladami', 869.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-bezowa-mat-50-cm-aurelia-28202.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28203', 'Komoda z drzwiami beżowa mat 100 cm Aurelia', 'Komody/Komody z drzwiami', 1039.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-bezowa-mat-100-cm-aurelia-28203.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28204', 'Komoda z szufladami i drzwiami beżowa mat 100 cm Aurelia', 'Komody/Komody z szufladami i drzwiami', 879.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-bezowa-mat-100-cm-aurelia-28204.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28209', 'Komplet szafek nocnych biały mat 45 cm Modena', 'Szafki nocne', 649.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-bialy-mat-45-cm-modena-28209.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28210', 'Komplet szafek nocnych czarny mat 45 cm Modena', 'Szafki nocne', 669.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-mat-45-cm-modena-28210.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28211', 'Szafka RTV biała mat 200 cm Modena', 'Szafki RTV', 1119.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-200-cm-modena-28211.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28212', 'Szafka RTV czarna mat 200 cm Modena', 'Szafki RTV', 1139.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-modena-28212.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28213', 'Szafka RTV biała mat 150 cm Modena', 'Szafki RTV', 869.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-150-cm-modena-28213.feed10009', 'High Glossy Furniture');
