-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25896', 'Fotel obrotowy młodzieżowy siatka szary / czarny Dingo', 'Fotele/Fotele młodzieżowe', 209.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-siatka-szary-czarny-dingo-25896.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25897', 'Fotel obrotowy młodzieżowy siatka różowy Dingo', 'Fotele/Fotele młodzieżowe', 209.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-siatka-rozowy-dingo-25897.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25899', 'Fotel wypoczynkowy z funkcją masażu ekoskóra brązowy / beżowy Dopio', 'Fotele/Fotele wypoczynkowe', 2995.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-z-funkcja-masazu-ekoskora-brazowy-bezowy-dopio-25899.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25900', 'Fotel wypoczynkowy z funkcją masażu ekoskóra szary Dopio', 'Fotele/Fotele wypoczynkowe', 2995.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-z-funkcja-masazu-ekoskora-szary-dopio-25900.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25908', 'Fotel gabinetowy tapicerowany czarny / szary Drake', 'Fotele/Fotele do biurka', 769.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-czarny-szary-drake-25908.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25909', 'Fotel biurowy ekoskóra czarny Edison', 'Fotele/Fotele do biurka', 539.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-czarny-edison-25909.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25910', 'Stół rozkładany biały / dąb miodowy mat 120 - 200 x 100 cm Edward', 'Stoly/Stoły rozkładane', 1549.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-dab-miodowy-mat-120-200-x-100-cm-edward-25910.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25911', 'Stół rozkładany biały / dąb san remo mat 120 - 200 x 100 cm Edward', 'Stoly/Stoły rozkładane', 1549.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-dab-san-remo-mat-120-200-x-100-cm-edward-25911.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25916', 'Łóżko tapicerowane szare 160x200 cm Elanda', 'Łóżka i części/Łóżka', 1249.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-160x200-cm-elanda-25916.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25921', 'Stół okrągły czarny mat 120 cm Embos', 'Stoly/Stoły nierozkładane', 799.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-czarny-mat-120-cm-embos-25921.feed10009', 'HALMAR');
