-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23194', 'Stół do jadalni biały połysk 180 x 90 cm Vero', 'Pozostałe produkty', 1349.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-bialy-polysk-180-x-90-cm-vero-23194.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23196', 'Stół do jadalni antracyt połysk 180 x 90 cm Vero', 'Pozostałe produkty', 1379.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-antracyt-polysk-180-x-90-cm-vero-23196.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23202', 'Sofa 3-osobowa tapicerowana beżowa Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-bezowa-holly-23202.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23221', 'Forest szafka RTV 180 cm wotan/antracyt', 'Pozostałe produkty', 739.0, 'https://www.meblepumo.pl/pl/products/forest-szafka-rtv-180-cm-wotan-antracyt-23221.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23241', 'Komoda z drzwiami biała wysoki połysk 160 cm Basic', 'Pozostałe produkty', 1299.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-160-cm-basic-23241.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23247', 'Austin oświetlenie półkowe 4 szt białe zimne', 'Dodatki do mebli/Oświetlenie LED', 69.0, 'https://www.meblepumo.pl/pl/products/austin-oswietlenie-polkowe-4-szt-biale-zimne-23247.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23249', 'Regał loftowy drewno postarzane / szary mat 113 x 42 x 136 cm Factory', 'Regały', 822.0, 'https://www.meblepumo.pl/pl/products/regal-loftowy-drewno-postarzane-szary-mat-113-x-42-x-136-cm-factory-23249.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23252', 'Oświetlenie punktowe 4 szt białe zimne', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-punktowe-4-szt-biale-zimne-23252.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23254', 'Stolik kawowy loftowy drewno postarzane / szary mat 110 x 65 cm Factory', 'Stoliki kawowe i ławy/Stoliki kawowe', 699.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-drewno-postarzane-szary-mat-110-x-65-cm-factory-23254.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23259', 'Komoda z szufladami i drzwiami antracyt / ciemne drewno postarzane mat 119 cm Factory', 'Komody/Komody z szufladami i drzwiami', 953.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-antracyt-ciemne-drewno-postarzane-mat-119-cm-factory-23259.feed10009', 'TT-furniture');
