-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28425', 'Stolik kawowy okrągły zielony / naturalny mat 40 cm Gina', 'Stoliki kawowe i ławy/Stoliki kawowe', 209.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-zielony-naturalny-mat-40-cm-gina-28425.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28426', 'Stolik kawowy transparentny / szary 40 cm Ariana', 'Stoliki kawowe i ławy/Stoliki kawowe', 239.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-transparentny-szary-40-cm-ariana-28426.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28427', 'Łóżko jednoosobowe beżowe 90 x 200 cm Orso', 'Łóżka dziecięce', 999.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-bezowe-90-x-200-cm-orso-28427.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28429', 'Stolik kawowy prostokątny zielony połysk 120 x 60 cm Soraya', 'Stoliki kawowe i ławy/Stoliki kawowe', 749.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-zielony-polysk-120-x-60-cm-soraya-28429.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28430', 'Toaletka z lustrem biała mat 120 cm Megan', 'Toaletki i konsole/Toaletki', 529.0, 'https://www.meblepumo.pl/pl/products/toaletka-z-lustrem-biala-mat-120-cm-megan-28430.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28431', 'Biurko z szufladami i półkami dąb artisan mat 124 cm Bega', 'Biurka/Biurka narożne', 389.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-polkami-dab-artisan-mat-124-cm-bega-28431.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28433', 'Łóżko jednoosobowe różowe 90 x 200 cm Russo', 'Łóżka dziecięce', 1229.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-rozowe-90-x-200-cm-russo-28433.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28436', 'Fotel obrotowy młodzieżowy tapicerowany szary / czarny Orion', 'Fotele/Fotele młodzieżowe', 343.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-szary-czarny-orion-28436.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28437', 'Fotel obrotowy młodzieżowy tapicerowany szary / biały Orion 2', 'Fotele/Fotele młodzieżowe', 359.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-szary-bialy-orion-2-28437.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28438', 'Fotel obrotowy młodzieżowy tapicerowany różowy / biały Orion', 'Fotele/Fotele młodzieżowe', 359.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-rozowy-bialy-orion-28438.feed10009', 'HALMAR');
