-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25685', 'Stół rozkładany biały mat 140 - 180 x 90 cm Aspen', 'Stoly/Stoły rozkładane', 2059.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-140-180-x-90-cm-aspen-25685.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25689', 'Fotel wypoczynkowy tapicerowany antracyt Atlantis', 'Fotele/Fotele wypoczynkowe', 959.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-antracyt-atlantis-25689.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25691', 'Ława do salonu biała mat 115 x 80 cm Aurea', 'Stoliki kawowe i ławy/Ławy', 1079.0, 'https://www.meblepumo.pl/pl/products/lawa-do-salonu-biala-mat-115-x-80-cm-aurea-25691.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25698', 'Fotel wypoczynkowy tapicerowany szary Avatar', 'Fotele/Fotele wypoczynkowe', 644.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-avatar-25698.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25699', 'Stół okrągły szklany czarny mat 120 cm Avelar', 'Stoly/Stoły nierozkładane', 835.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-szklany-czarny-mat-120-cm-avelar-25699.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25712', 'Biurko z szufladą dąb sonoma / białe mat 120 cm B34', 'Biurka/Biurka z szufladami i drzwiami', 429.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-dab-sonoma-biale-mat-120-cm-b34-25712.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25716', 'Biurko gamingowe czarne / czerwone mat 100 cm B40', 'Biurka/Biurka gamingowe', 789.0, 'https://www.meblepumo.pl/pl/products/biurko-gamingowe-czarne-czerwone-mat-100-cm-b40-25716.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25718', 'Biurko loftowe dąb złoty / czarne mat 110 cm B43', 'Biurka/Biurka proste', 719.0, 'https://www.meblepumo.pl/pl/products/biurko-loftowe-dab-zloty-czarne-mat-110-cm-b43-25718.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25722', 'Biurko dwuosobowe dąb sonoma mat 139 cm  B48', 'Biurka/Biurka z szufladami i drzwiami', 749.0, 'https://www.meblepumo.pl/pl/products/biurko-dwuosobowe-dab-sonoma-mat-139-cm-b48-25722.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25723', 'Biurko gamingowe czarne / czerwone mat 122 cm B49', 'Biurka/Biurka gamingowe', 579.0, 'https://www.meblepumo.pl/pl/products/biurko-gamingowe-czarne-czerwone-mat-122-cm-b49-25723.feed10009', 'HALMAR');
