-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25410', 'Fotel ogrodowy Rasmus, jasny popiel, stelaż czarny', 'halmar tymczasowa', 1079.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-rasmus-jasny-popiel-stelaz-czarny-25410.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25415', 'Zestaw mebli ogrodowych Rocca ciemny popiel, tkanina jasny popiel', 'halmar tymczasowa', 3179.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-ogrodowych-rocca-ciemny-popiel-tkanina-jasny-popiel-25415.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25417', 'Łóżko tapicerowane szare 160x200 cm Scandino', 'Łóżka i części/Łóżka', 1599.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-160x200-cm-scandino-25417.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25421', 'Zestaw mebli ogrodowych Shark, tkanina cappuccino, nóżki czarne', 'halmar tymczasowa', 999.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-ogrodowych-shark-tkanina-cappuccino-nozki-czarne-25421.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25422', 'Fotel biurowy tapicerowany beżowy Talon', 'Fotele/Fotele do biurka', 499.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-bezowy-talon-25422.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25423', 'Fotel biurowy tapicerowany szary Talon', 'Fotele/Fotele do biurka', 499.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-szary-talon-25423.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25424', 'Fotel biurowy tapicerowany różowy Talon', 'Fotele/Fotele do biurka', 499.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-rozowy-talon-25424.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25425', 'Zestaw 2 puf owalnych ze schowkiem drewnianych tapicerowanych beżowych / naturalnych Tico', 'Pufy', 343.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-puf-owalnych-ze-schowkiem-drewnianych-tapicerowanych-bezowych-naturalnych-tico-25425.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25428', 'Stolik kawowy okrągły biały marmur / złoty mat 50 cm Tribeca', 'Stoliki kawowe i ławy/Stoliki kawowe', 729.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bialy-marmur-zloty-mat-50-cm-tribeca-25428.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25429', 'Stolik kawowy okrągły czarny marmur / złoty mat 50 cm Tribeca', 'Stoliki kawowe i ławy/Stoliki kawowe', 729.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-czarny-marmur-zloty-mat-50-cm-tribeca-25429.feed10009', 'HALMAR');
