-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28170', 'Wieszak ścienny czarny 40 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 99.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-czarny-40-cm-soline-28170.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28171', 'Wieszak ścienny czarny 80 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 139.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-czarny-80-cm-soline-28171.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28172', 'Konsola z szufladami dąb / czarna mat 100 cm Liva', 'Toaletki i konsole/Konsole ', 999.0, 'https://www.meblepumo.pl/pl/products/konsola-z-szufladami-dab-czarna-mat-100-cm-liva-28172.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28173', 'Wieszak ścienny z półką dąb / czarny 120 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 529.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-z-polka-dab-czarny-120-cm-soline-28173.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28174', 'Wieszak ścienny z półką dąb / czarny 150 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 659.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-z-polka-dab-czarny-150-cm-soline-28174.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28175', 'Wieszak ścienny dąb / czarny 120 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 439.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-czarny-120-cm-soline-28175.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28176', 'Wieszak ścienny wąski dąb 120 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 219.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-waski-dab-120-cm-soline-28176.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28177', 'Wieszak ścienny dąb 135 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 379.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-135-cm-soline-28177.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28178', 'Ławka z półką dąb olejowany 60 cm Soline', 'Ławki do przedpokoju', 495.0, 'https://www.meblepumo.pl/pl/products/lawka-z-polka-dab-olejowany-60-cm-soline-28178.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28179', 'Ławka z półką dąb olejowany 100 cm Soline', 'Ławki do przedpokoju', 659.0, 'https://www.meblepumo.pl/pl/products/lawka-z-polka-dab-olejowany-100-cm-soline-28179.feed10009', 'Fato Luxmeble');
