-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25971', 'Zestaw 2 ław biała, naturalna, okrągła', 'Stoliki kawowe i ławy/Stoliki kawowe', 259.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-law-biala-naturalna-okragla-25971.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25972', 'Zestaw 2 stolików kawowych okrągłych naturalny / czarny mat 40 cm, 33 cm Folla', 'Stoliki kawowe i ławy/Stoliki kawowe', 259.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-naturalny-czarny-mat-40-cm-33-cm-folla-25972.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25974', 'Stół okrągły czarny mat 80 cm Fondi', 'Stoly/Stoły nierozkładane', 299.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-czarny-mat-80-cm-fondi-25974.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25975', 'Zestaw 2 stolików kawowych okrągłych biały marmur / czarny mat 80 cm, 60 cm Formosa', 'Stoliki kawowe i ławy/Stoliki kawowe', 933.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-bialy-marmur-czarny-mat-80-cm-60-cm-formosa-25975.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25976', 'Fotel gabinetowy skórzany brazowy Foster', 'Fotele/Fotele do biurka', 1535.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-skorzany-brazowy-foster-25976.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25977', 'Fotel gabinetowy skórzany czarny Foster', 'Fotele/Fotele do biurka', 1535.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-skorzany-czarny-foster-25977.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25979', 'Łóżko tapicerowane szare 160x200 cm Francesca', 'Łóżka i części/Łóżka', 1389.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-160x200-cm-francesca-25979.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25986', 'Ława kawowa biała połysk 105 x 58 cm Futura', 'Stoliki kawowe i ławy/Ławy', 599.0, 'https://www.meblepumo.pl/pl/products/lawa-kawowa-biala-polysk-105-x-58-cm-futura-25986.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25994', 'Fotel obrotowy młodzieżowy tapicerowany biały / czarny / zielony Gol', 'Fotele/Fotele młodzieżowe', 275.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-bialy-czarny-zielony-gol-25994.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26006', 'Zestaw 2 puf okrągłych ze schowkiem tapicerowanych niebieskich Grado', 'Pufy', 389.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-puf-okraglych-ze-schowkiem-tapicerowanych-niebieskich-grado-26006.feed10009', 'HALMAR');
