-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16515', 'Narożnik 3-osobowy lewostronny tapicerowany beżowy Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-lewostronny-tapicerowany-bezowy-sampras-16515.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16516', 'Narożnik 3-osobowy prawostronny tapicerowany beżowy Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-prawostronny-tapicerowany-bezowy-sampras-16516.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16743', 'Witryna dwudrzwiowa z szufladami biała mat / połysk 80 x 192 cm Simple', 'Witryny i kredensy/Witryny', 1199.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-biala-mat-polysk-80-x-192-cm-simple-16743.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16746', 'Witryna dwudrzwiowa z szufladami czarna mat / połysk 80 x 192 cm Simple', 'Witryny i kredensy/Witryny', 1199.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-czarna-mat-polysk-80-x-192-cm-simple-16746.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16748', 'Komoda z drzwiami biała mat / wysoki połysk 120 cm Simple', 'Komody/Komody z drzwiami', 749.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-wysoki-polysk-120-cm-simple-16748.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16751', 'Komoda z drzwiami czarna mat / wysoki połysk 120 cm Simple', 'Komody/Komody z drzwiami', 749.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-wysoki-polysk-120-cm-simple-16751.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16761', 'Stelaż do łóżka 140x200 cm Natura NV', 'Stelaże', 379.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-140x200-cm-natura-nv-16761.feed10009', 'Fra-Mar');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16794', 'LED klejony czerwony + zasilacz High Gloss Furniture', 'Dodatki do mebli/Oświetlenie LED', 79.0, 'https://www.meblepumo.pl/pl/products/led-klejony-czerwony-zasilacz-high-gloss-furniture-16794.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16795', 'LED klejony biały zimny + zasilacz High Gloss Furniture', 'Dodatki do mebli/Oświetlenie LED', 79.0, 'https://www.meblepumo.pl/pl/products/led-klejony-bialy-zimny-zasilacz-high-gloss-furniture-16795.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16796', 'LED klejony zielony + zasilacz High Gloss Furniture', 'Dodatki do mebli/Oświetlenie LED', 69.0, 'https://www.meblepumo.pl/pl/products/led-klejony-zielony-zasilacz-high-gloss-furniture-16796.feed10009', 'High Glossy Furniture');
