-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25441', 'Stolik kawowy z półką szary mat 110 x 60 cm Asensio', 'Stoliki kawowe i ławy/Stoliki kawowe', 569.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-szary-mat-110-x-60-cm-asensio-25441.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25442', 'Szafka RTV szara mat 180 cm Asensio', 'Szafki RTV', 789.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-szara-mat-180-cm-asensio-25442.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25443', 'Witryna jednodrzwiowa szara mat 50 x 180 cm Asensio', 'Witryny i kredensy/Witryny', 896.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-szara-mat-50-x-180-cm-asensio-25443.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25450', 'Ławostół rozkładany dąb artisan / czarny mat 130 - 170 x 65 cm Baretti', 'Stoliki kawowe i ławy/Ławostoły', 1699.0, 'https://www.meblepumo.pl/pl/products/lawostol-rozkladany-dab-artisan-czarny-mat-130-170-x-65-cm-baretti-25450.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25452', 'BORNEO KM-1 komoda dąb artisan/czarny', 'halmar tymczasowa', 999.0, 'https://www.meblepumo.pl/pl/products/borneo-km-1-komoda-dab-artisan-czarny-25452.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25453', 'BORNEO KM-2 komoda dąb artisan/czarny', 'halmar tymczasowa', 848.0, 'https://www.meblepumo.pl/pl/products/borneo-km-2-komoda-dab-artisan-czarny-25453.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25454', 'BORNEO LAW-1 ława dąb artisan/czarny', 'halmar tymczasowa', 488.0, 'https://www.meblepumo.pl/pl/products/borneo-law-1-lawa-dab-artisan-czarny-25454.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25456', 'BORNEO REG-1 regał dąb artisan/czarny', 'halmar tymczasowa', 689.0, 'https://www.meblepumo.pl/pl/products/borneo-reg-1-regal-dab-artisan-czarny-25456.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25457', 'BORNEO RTV-1 stolik RTV dąb artisan/czarny', 'halmar tymczasowa', 542.0, 'https://www.meblepumo.pl/pl/products/borneo-rtv-1-stolik-rtv-dab-artisan-czarny-25457.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25461', 'BULLET KM-1 komoda czarny, nogi: złoty', 'halmar tymczasowa', 999.0, 'https://www.meblepumo.pl/pl/products/bullet-km-1-komoda-czarny-nogi-zloty-25461.feed10009', 'HALMAR');
