-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12065', 'Szafka RTV biała / dąb mat 175 cm Ramona', 'Szafki RTV', 2159.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-mat-175-cm-ramona-12065.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12066', 'Szafka RTV z szufladami biała / dąb mat 175 cm Ramona', 'Szafki RTV', 2399.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-szufladami-biala-dab-mat-175-cm-ramona-12066.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12067', 'Komoda z szufladami biała / dąb mat 73 cm Ramona', 'Komody/Komody z szufladami', 1799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-dab-mat-73-cm-ramona-12067.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12068', 'Komoda z drzwiami biała / dąb mat 120 cm Ramona', 'Komody/Komody z drzwiami', 2099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-dab-mat-120-cm-ramona-12068.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12069', 'Komoda z szufladami i drzwiami biała / dąb mat 150 cm Ramona', 'Komody/Komody z szufladami i drzwiami', 2499.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-mat-150-cm-ramona-12069.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12070', 'Komoda z drzwiami biała / dąb mat 175 cm Ramona', 'Komody/Komody z drzwiami', 2799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-dab-mat-175-cm-ramona-12070.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12071', 'Komoda z drzwiami biała / dąb mat 200 cm Ramona', 'Komody/Komody z drzwiami', 3069.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-dab-mat-200-cm-ramona-12071.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12072', 'Komoda z szufladami biała / dąb mat 120 cm Ramona', 'Komody/Komody z szufladami', 2259.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-dab-mat-120-cm-ramona-12072.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12167', 'Stół do jadalni biały połysk 180 x 90 cm Amaretto', 'Stoly/Stoły nierozkładane', 1129.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-bialy-polysk-180-x-90-cm-amaretto-12167.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('12171', 'Lustro w ramie białej 170 x 75 cm', 'Lustra', 420.0, 'https://www.meblepumo.pl/pl/products/lustro-w-ramie-bialej-170-x-75-cm-12171.feed10009', 'Italia Trend');
