-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26793', 'Fotel rozkładany z funkcją masażu ekoskóra czarny Pulsar', 'Fotele/Fotele rozkładane', 1359.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-ekoskora-czarny-pulsar-26793.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26794', 'Fotel rozkładany z funkcją masażu ekoskóra szary Pulsar', 'Fotele/Fotele rozkładane', 1359.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-ekoskora-szary-pulsar-26794.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26806', 'Fotel wypoczynkowy tapicerowany zielony Ravel', 'Fotele/Fotele wypoczynkowe', 827.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-ravel-26806.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26807', 'Fotel wypoczynkowy tapicerowany granatowy Ravel', 'Fotele/Fotele wypoczynkowe', 827.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-granatowy-ravel-26807.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26809', 'Stół okrągły transparentny / chrom mat 100 cm Raymond', 'Stoly/Stoły nierozkładane', 534.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-transparentny-chrom-mat-100-cm-raymond-26809.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26810', 'Stół okrągły transparentny / złoty mat / połysk 100 cm Raymond', 'Stoly/Stoły nierozkładane', 599.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-transparentny-zloty-mat-polysk-100-cm-raymond-26810.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26811', 'Regał drewniany naturalny / szary mat 28 x 26 x 83 cm REG10', 'Regały', 149.0, 'https://www.meblepumo.pl/pl/products/regal-drewniany-naturalny-szary-mat-28-x-26-x-83-cm-reg10-26811.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26813', 'Regał loftowy dąb sonoma / czarny mat 90 x 30 x 190 cm REG19', 'Regały', 485.0, 'https://www.meblepumo.pl/pl/products/regal-loftowy-dab-sonoma-czarny-mat-90-x-30-x-190-cm-reg19-26813.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26816', 'Fotel gabinetowy tapicerowany szary Relax 2', 'Fotele/Fotele do biurka', 449.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-szary-relax-2-26816.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26817', 'Fotel gabinetowy ekoskóra beżowy Relax', 'Fotele/Fotele do biurka', 449.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-bezowy-relax-26817.feed10009', 'HALMAR');
