-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27258', 'Komoda z szufladami biała mat / wysoki połysk 40 cm Lima', 'Komody/Komody z szufladami', 495.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-mat-wysoki-polysk-40-cm-lima-27258.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27259', 'Komoda z szufladami dąb sonoma / biała mat / wysoki połysk 40 cm Lima', 'Komody/Komody z szufladami', 455.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-dab-sonoma-biala-mat-wysoki-polysk-40-cm-lima-27259.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27262', 'Komoda z szufladami i drzwiami biała mat / wysoki połysk 116 cm Lima', 'Komody/Komody z szufladami i drzwiami', 639.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-mat-wysoki-polysk-116-cm-lima-27262.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27263', 'Komoda z szufladami i drzwiami dąb sonoma / biała mat / wysoki połysk 40 cm Lima', 'Komody/Komody z szufladami i drzwiami', 591.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-sonoma-biala-mat-wysoki-polysk-40-cm-lima-27263.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27264', 'Komoda z szufladami i drzwiami dąb sonoma mat 40 cm Lima', 'Komody/Komody z szufladami i drzwiami', 591.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-sonoma-mat-40-cm-lima-27264.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27266', 'Łóżko jednoosobowe białe 120x200 cm Lima', 'Łóżka i części/Łóżka', 653.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-biale-120x200-cm-lima-27266.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27267', 'Łóżko jednoosobowe dąb sonoma 120x200 cm Lima', 'Łóżka i części/Łóżka', 579.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-dab-sonoma-120x200-cm-lima-27267.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27268', 'Łóżko jednoosobowe białe 90x200 cm Lima', 'Łóżka i części/Łóżka', 571.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-biale-90x200-cm-lima-27268.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27269', 'Łóżko jednoosobowe dąb sonoma 90x200 cm Lima', 'Łóżka i części/Łóżka', 499.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-dab-sonoma-90x200-cm-lima-27269.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27270', 'Regał do salonu biały połysk 60 x 40 x 200 cm Lima', 'Regały', 657.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-bialy-polysk-60-x-40-x-200-cm-lima-27270.feed10009', 'HALMAR');
