-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28530', 'Stolik kawowy z półką dąb Meringa/dąb Cadiz mat 110 x 68 cm Avina', 'Stoliki kawowe i ławy/Stoliki kawowe', 979.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-meringa-dab-cadiz-mat-110-x-68-cm-avina-28530.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28531', 'Stół rozkładany dąb Meringa/dąb Cadiz mat 137 - 185 x 90 cm Avina', 'Stoly/Stoły rozkładane', 1119.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-meringa-dab-cadiz-mat-137-185-x-90-cm-avina-28531.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28532', 'Stół do jadalni dąb Cadiz / czarny mat 180 x 90 cm Avina', 'Stoly/Stoły nierozkładane', 1129.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-dab-cadiz-czarny-mat-180-x-90-cm-avina-28532.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28538', 'Krzesło do jadalni drewniane tapicerowane szare / czarne Hylo', 'Krzesła/Krzesła do jadalni', 419.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-czarne-hylo-28538.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28539', 'Krzesło do jadalni drewniane tapicerowane beżowe / czarne Hylo', 'Krzesła/Krzesła do jadalni', 419.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-bezowe-czarne-hylo-28539.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28545', 'Stół okrągły orzech mat 120 cm Caldo', 'Stoly/Stoły nierozkładane', 1759.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-orzech-mat-120-cm-caldo-28545.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28547', 'Szafka RTV wisząca kaszmir mat 150 cm Luvio', 'Szafki RTV', 539.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-kaszmir-mat-150-cm-luvio-28547.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28548', 'Szafka RTV wisząca kaszmir mat 190 cm Luvio', 'Szafki RTV', 619.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-kaszmir-mat-190-cm-luvio-28548.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28549', 'Witryna wisząca przeszklona kaszmir mat 35 x 163 cm Luvio', 'Witryny i kredensy/Witryny', 679.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-przeszklona-kaszmir-mat-35-x-163-cm-luvio-28549.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28550', 'Witryna wisząca kaszmir mat 35 x 163 cm Luvio', 'Witryny i kredensy/Witryny', 569.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-kaszmir-mat-35-x-163-cm-luvio-28550.feed10009', 'High Glossy Furniture');
