-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25292', 'Krzesło do jadalni tapicerowane beżowe K332', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k332-25292.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25295', 'Krzesło do jadalni tapicerowane czarne K416', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k416-25295.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25296', 'Krzesło do jadalni tapicerowane musztardowe K416', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k416-25296.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25297', 'Krzesło do jadalni tapicerowane beżowe K417', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k417-25297.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25300', 'Krzesło do jadalni tapicerowane beżowe K450', 'Krzesła/Krzesła do jadalni', 235.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k450-25300.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25301', 'Krzesło do jadalni tapicerowane beżowe K453', 'Krzesła/Krzesła do jadalni', 242.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k453-25301.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25302', 'Krzesło do jadalni tapicerowane czarne K453', 'Krzesła/Krzesła do jadalni', 242.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k453-25302.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25303', 'Krzesło do jadalni tapicerowane beżowe K460', 'Krzesła/Krzesła do jadalni', 316.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k460-25303.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25304', 'Krzesło do jadalni tapicerowane czarne K460', 'Krzesła/Krzesła do jadalni', 316.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k460-25304.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25305', 'Krzesło do jadalni tapicerowane beżowe / złote K493', 'Krzesła/Krzesła do jadalni', 423.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-zlote-k493-25305.feed10009', 'HALMAR');
