-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20099', 'Łóżko jednoosobowe białe 90x200 cm Soft Line', 'Łóżka i części/Łóżka', 563.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-biale-90x200-cm-soft-line-20099.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20100', 'Łóżko dwuosobowe białe 140x200 cm Soft Line', 'Łóżka i części/Łóżka', 743.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-biale-140x200-cm-soft-line-20100.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20112', 'Witryna jednodrzwiowa z szufladami dąb / antracyt mat 54 x 190 cm Brooklyn', 'Witryny i kredensy/Witryny', 650.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-dab-antracyt-mat-54-x-190-cm-brooklyn-20112.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20114', 'Szafka RTV dąb / antracyt mat 140 cm Brooklyn', 'Szafki RTV', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-antracyt-mat-140-cm-brooklyn-20114.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20115', 'Stolik kawowy loftowy dąb / antracyt mat 100 x 60 cm Brooklyn', 'Stoliki kawowe i ławy/Stoliki kawowe', 285.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-dab-antracyt-mat-100-x-60-cm-brooklyn-20115.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20166', 'Sofa tapicerowana Leya, 3 osobowa, bordowa, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-bordowa-nozki-wenge-20166.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20167', 'Sofa 3-osobowa tapicerowana granatowa Leya', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-granatowa-leya-20167.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20168', 'Stolik kawowy kwadratowy biały mat 75 x 75 xm Marika', 'Stoliki kawowe i ławy/Stoliki kawowe', 969.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-bialy-mat-75-x-75-xm-marika-20168.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20203', 'Komoda szeroka z drzwiami biała wysoki połysk 241 cm Prestige', 'Pozostałe produkty', 1749.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-biala-wysoki-polysk-241-cm-prestige-20203.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20204', 'Komoda szeroka z drzwiami antracyt wysoki połysk 241 cm Prestige', 'Pozostałe produkty', 1899.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-antracyt-wysoki-polysk-241-cm-prestige-20204.feed10009', 'Italia Trend');
