-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24611', 'Komoda wysoka z szufladami i drzwiami antracyt / dekor bambus mat 175 cm Sumatra', 'Komody/Komody z szufladami', 1499.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-i-drzwiami-antracyt-dekor-bambus-mat-175-cm-sumatra-24611.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24613', 'Stolik kawowy z szufladą antracyt / dekor bambus mat 108 x 60 cm Sumatra', 'Stoliki kawowe i ławy/Stoliki kawowe', 699.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-antracyt-dekor-bambus-mat-108-x-60-cm-sumatra-24613.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24614', 'Szafka RTV antracyt / dekor bambus mat 160 cm Sumatra', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-antracyt-dekor-bambus-mat-160-cm-sumatra-24614.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24616', 'Komoda z szufladami biała / dąb sonoma mat 120 cm Göteborg', 'Komody/Komody z szufladami', 1369.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-dab-sonoma-mat-120-cm-goteborg-24616.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24617', 'Komoda z szufladami biała / dąb sonoma mat 80 cm Göteborg', 'Komody/Komody z szufladami', 929.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-dab-sonoma-mat-80-cm-goteborg-24617.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24619', 'Komoda z szufladami i drzwiami biała / dąb sonoma mat 180 cm Göteborg', 'Komody/Komody z szufladami i drzwiami', 1659.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-sonoma-mat-180-cm-goteborg-24619.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24620', 'Komoda z szufladami i drzwiami biała / dąb sonoma mat 100 cm Göteborg', 'Komody/Komody z szufladami i drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-sonoma-mat-100-cm-goteborg-24620.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24621', 'Witryna dwudrzwiowa z szufladami biała / dąb sonoma mat 100 x 185 cm Göteborg', 'Witryny i kredensy/Witryny', 2349.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-biala-dab-sonoma-mat-100-x-185-cm-goteborg-24621.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24622', 'Szafka RTV biała / dąb sonoma mat 160 cm Göteborg', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-sonoma-mat-160-cm-goteborg-24622.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24623', 'Komoda z drzwiami i szufladami biała / dąb sonoma mat 120 cm Göteborg', 'Komody/Komody z szufladami i drzwiami', 1359.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-biala-dab-sonoma-mat-120-cm-goteborg-24623.feed10009', 'Fontini ');
