-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28551', 'Półka wisząca kaszmir mat 160 x 20 cm Luvio', 'Półki wiszące', 389.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-kaszmir-mat-160-x-20-cm-luvio-28551.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28552', 'Regał do salonu czarny mat 100 x 40 x 175 cm Milo', 'Regały', 1099.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-czarny-mat-100-x-40-x-175-cm-milo-28552.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28553', 'Regał do salonu beżowy mat 100 x 40 x 175 cm Milo', 'Regały', 1129.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-bezowy-mat-100-x-40-x-175-cm-milo-28553.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28554', 'Witryna jednodrzwiowa czarna mat 60 x 180 cm Milo', 'Witryny i kredensy/Witryny', 1159.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-czarna-mat-60-x-180-cm-milo-28554.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28555', 'Witryna jednodrzwiowa beżowa mat 60 x 180 cm Milo', 'Witryny i kredensy/Witryny', 1159.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-bezowa-mat-60-x-180-cm-milo-28555.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28556', 'Stolik kawowy prostokątny czarny mat 100 x 57 cm Milo', 'Stoliki kawowe i ławy/Stoliki kawowe', 489.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-czarny-mat-100-x-57-cm-milo-28556.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28558', 'Stolik kawowy prostokątny beżowy mat 100 x 57 cm Milo', 'Stoliki kawowe i ławy/Stoliki kawowe', 489.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bezowy-mat-100-x-57-cm-milo-28558.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28559', 'Toaletka z lustrem wisząca czarna mat 70 cm Milo', 'Toaletki i konsole/Toaletki', 569.0, 'https://www.meblepumo.pl/pl/products/toaletka-z-lustrem-wiszaca-czarna-mat-70-cm-milo-28559.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28560', 'Toaletka z lustrem wisząca beżowa mat 70 cm Milo', 'Toaletki i konsole/Toaletki', 569.0, 'https://www.meblepumo.pl/pl/products/toaletka-z-lustrem-wiszaca-bezowa-mat-70-cm-milo-28560.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28561', 'Komoda z drzwiami granatowa mat 200 cm Verno', 'Komody/Komody z drzwiami', 1599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-granatowa-mat-200-cm-verno-28561.feed10009', 'High Glossy Furniture');
