-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24684', 'Komoda wysoka z drzwiami biała / klon Pero wysoki połysk / mat 108 cm Verden', 'Komody/Komody z drzwiami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-klon-pero-wysoki-polysk-mat-108-cm-verden-24684.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24685', 'Materac sprężynowy kieszeniowy 200x200 cm Set', 'Materace/Materace sprężynowe kieszeniowe', 2199.0, 'https://www.meblepumo.pl/pl/products/materac-sprezynowy-kieszeniowy-200x200-cm-set-24685.feed10009', 'PumoSen');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24686', 'Szafka RTV wisząca czarna połysk 200 cm Skin', 'Szafki RTV', 869.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-czarna-polysk-200-cm-skin-24686.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24731', 'Komoda z drzwiami czarna mat 200 cm Latina', 'Komody/Komody z drzwiami', 989.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-latina-24731.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24922', 'Komoda z drzwiami biała mat 200 cm Latina', 'Komody/Komody z drzwiami', 989.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-200-cm-latina-24922.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24924', 'Komoda z drzwiami biała mat 150 cm Latina', 'Komody/Komody z drzwiami', 859.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-150-cm-latina-24924.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24927', 'Komoda z szufladami szara mat 100 cm From', 'Komody/Komody z szufladami', 1349.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-szara-mat-100-cm-from-24927.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24930', 'Szafa do pokoju dziecięcego szara mat 100 x 184 cm From', 'Szafy/Szafy uchylne', 1379.0, 'https://www.meblepumo.pl/pl/products/szafa-do-pokoju-dzieciecego-szara-mat-100-x-184-cm-from-24930.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24931', 'Szafka nocna szara mat 50 cm From', 'Szafki nocne', 569.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-szara-mat-50-cm-from-24931.feed10009', 'KidsBox');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24932', 'Łóżko dziecięce szare 80x180 cm From', 'Łóżka dziecięce', 929.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-szare-80x180-cm-from-24932.feed10009', 'KidsBox');
