-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23776', 'Łóżko tapicerowane z szufladą szare 160x200 cm Evora', 'Łóżka i części/Łóżka', 2719.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-evora-23776.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23777', 'Łóżko tapicerowane szare 160x200 cm Padva', 'Łóżka i części/Łóżka', 1939.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-160x200-cm-padva-23777.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23779', 'Łóżko tapicerowane z szufladą szare 160x200 cm Betina', 'Łóżka i części/Łóżka', 1659.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-betina-23779.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23781', 'Łóżko tapicerowane z szufladą szare 160x200 cm Modena', 'Łóżka i części/Łóżka', 2619.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-modena-23781.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23783', 'Łóżko tapicerowane z szufladą szare 160x200 cm Merida', 'Łóżka i części/Łóżka', 1619.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-merida-23783.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23789', 'Biurko gamingowe czarne mat 120 cm Racing 5', 'Biurka/Biurka gamingowe', 586.0, 'https://www.meblepumo.pl/pl/products/biurko-gamingowe-czarne-mat-120-cm-racing-5-23789.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23790', 'Biurko gamingowe czarne mat 120 cm Racing 4', 'Biurka/Biurka gamingowe', 703.0, 'https://www.meblepumo.pl/pl/products/biurko-gamingowe-czarne-mat-120-cm-racing-4-23790.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23792', 'Biurko gamingowe czarne mat 120 cm Racing 2', 'Biurka/Biurka gamingowe', 562.0, 'https://www.meblepumo.pl/pl/products/biurko-gamingowe-czarne-mat-120-cm-racing-2-23792.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23803', 'Biurko z regałem dąb wotan / antracyt mat 122 cm Fino', 'Biurka/Biurka z szufladami i drzwiami', 259.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regalem-dab-wotan-antracyt-mat-122-cm-fino-23803.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23807', 'Biurko z regałem dąb sonoma / czarne mat 120 cm Narvik B1', 'Biurka/Biurka z szufladami i drzwiami', 299.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regalem-dab-sonoma-czarne-mat-120-cm-narvik-b1-23807.feed10009', 'HALMAR');
