-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25596', 'Szafka RTV czarna mat 200 cm Lukka', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-lukka-25596.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25597', 'Komoda z drzwiami czarna mat 200 cm Lukka', 'Komody/Komody z drzwiami', 1629.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-lukka-25597.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25604', 'Stolik kawowy okrągły szklany lustro / złoty połysk 90 cm Afina', 'Stoliki kawowe i ławy/Stoliki kawowe', 1179.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-szklany-lustro-zloty-polysk-90-cm-afina-25604.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25605', 'Fotel rozkładany velvet zielony Agustin 2', 'Fotele/Fotele rozkładane', 1159.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-zielony-agustin-2-25605.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25606', 'Fotel rozkładany velvet czarny Agustin 2', 'Fotele/Fotele rozkładane', 1159.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-czarny-agustin-2-25606.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25607', 'Fotel rozkładany tapicerowany granatowy Agustin 2', 'Fotele/Fotele rozkładane', 1159.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-tapicerowany-granatowy-agustin-2-25607.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25608', 'Fotel rozkładany tapicerowany żólty Agustin 2', 'Fotele/Fotele rozkładane', 1159.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-tapicerowany-zolty-agustin-2-25608.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25609', 'Fotel rozkładany velvet szary Agustin 2', 'Fotele/Fotele rozkładane', 1159.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-velvet-szary-agustin-2-25609.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25630', 'Fotel wypoczynkowy velvet różowy Almond', 'Fotele/Fotele wypoczynkowe', 999.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-rozowy-almond-25630.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25631', 'Łóżko tapicerowane z szufladą zielone 90x200 cm Aloha', 'Łóżka i części/Łóżka', 1729.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-zielone-90x200-cm-aloha-25631.feed10009', 'HALMAR');
