-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27980', 'Krzesło ogrodowe plastikowe białe K529', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-biale-k529-27980.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27981', 'Krzesło ogrodowe plastikowe białe / naturalne K529', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-biale-naturalne-k529-27981.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27982', 'Zestaw mebli ogrodowych Conor, popielaty ', 'halmar tymczasowa', 599.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-ogrodowych-conor-popielaty-27982.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27983', 'Stół ogrodowy miętowy mat 60 x 73 cm Calvo', 'Stoly/Stoły ogrodowe', 265.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-mietowy-mat-60-x-73-cm-calvo-27983.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27984', 'Stół ogrodowy khaki mat 60 x 73 cm Calvo', 'Stoly/Stoły ogrodowe', 265.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-khaki-mat-60-x-73-cm-calvo-27984.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27986', 'Stół ogrodowy biały mat 60 x 73 cm Calvo', 'Stoly/Stoły ogrodowe', 265.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-bialy-mat-60-x-73-cm-calvo-27986.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27992', 'Krzesło ogrodowe plastikowe białe K532', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-biale-k532-27992.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27993', 'Krzesło ogrodowe plastikowe czarne K532', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-czarne-k532-27993.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27994', 'Krzesło ogrodowe plastikowe khaki K532', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-khaki-k532-27994.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27995', 'Krzesło ogrodowe plastikowe miętowe K532', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-mietowe-k532-27995.feed10009', 'HALMAR');
