-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24674', 'Komoda z drzwiami biała / szara wysoki połysk / mat 146 cm Verden', 'Komody/Komody z drzwiami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-szara-wysoki-polysk-mat-146-cm-verden-24674.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24675', 'Szafka RTV biała / szara mat / połysk 184 cm Verden', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-szara-mat-polysk-184-cm-verden-24675.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24676', 'Meblościanka do salonu biała / szara mat / połysk 219 cm Verden', 'Meblościanki', 1749.0, 'https://www.meblepumo.pl/pl/products/mebloscianka-do-salonu-biala-szara-mat-polysk-219-cm-verden-24676.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24677', 'Meblościanka do salonu biała / szara mat / połysk 277 cm Verden', 'Meblościanki', 2359.0, 'https://www.meblepumo.pl/pl/products/mebloscianka-do-salonu-biala-szara-mat-polysk-277-cm-verden-24677.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24678', 'Komoda wysoka z drzwiami biała / szara wysoki połysk / mat 108 cm Verden', 'Komody/Komody z drzwiami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-szara-wysoki-polysk-mat-108-cm-verden-24678.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24679', 'Meblościanka do salonu biała / klon mat / połysk 219 cm Verden', 'Meblościanki', 1749.0, 'https://www.meblepumo.pl/pl/products/mebloscianka-do-salonu-biala-klon-mat-polysk-219-cm-verden-24679.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24680', 'Meblościanka do salonu biała / klon mat / połysk 277 cm Verden', 'Meblościanki', 2359.0, 'https://www.meblepumo.pl/pl/products/mebloscianka-do-salonu-biala-klon-mat-polysk-277-cm-verden-24680.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24681', 'Komoda z drzwiami biała / klon Pero wysoki połysk / mat 184 cm Verden', 'Komody/Komody z drzwiami', 1239.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-klon-pero-wysoki-polysk-mat-184-cm-verden-24681.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24682', 'Komoda z drzwiami biała / klon Pero wysoki połysk / mat 146 cm Verden', 'Komody/Komody z drzwiami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-klon-pero-wysoki-polysk-mat-146-cm-verden-24682.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24683', 'Szafka RTV biała / klon mat / połysk 184 cm Verden', 'Szafki RTV', 699.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-klon-mat-polysk-184-cm-verden-24683.feed10009', 'Italia Trend');
