-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25391', 'Stół okrągły czarny marmur / złoty mat 59 cm Molina', 'Stoly/Stoły nierozkładane', 855.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-czarny-marmur-zloty-mat-59-cm-molina-25391.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25392', 'Stolik kawowy kwadratowy biały marmur mat 80 x 80 cm Monolit', 'Stoliki kawowe i ławy/Stoliki kawowe', 573.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-bialy-marmur-mat-80-x-80-cm-monolit-25392.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25393', 'Stolik kawowy kwadratowy czarny marmur mat 80 x 80 cm Monolit', 'Stoliki kawowe i ławy/Stoliki kawowe', 573.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-czarny-marmur-mat-80-x-80-cm-monolit-25393.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25394', 'Stół okrągły biały marmur / złoty mat 79 x 74 cm Morata', 'Stoly/Stoły nierozkładane', 999.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-bialy-marmur-zloty-mat-79-x-74-cm-morata-25394.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25395', 'Stolik kawowy okrągły zielony marmur / czarny mat 50 cm Morena', 'Stoliki kawowe i ławy/Stoliki kawowe', 649.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-zielony-marmur-czarny-mat-50-cm-morena-25395.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25397', 'Fotel obrotowy młodzieżowy siatka różowy Nani', 'Fotele/Fotele młodzieżowe', 313.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-siatka-rozowy-nani-25397.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25398', 'Stół okrągły orzech / czarny mat 90 cm Olmo', 'Stoly/Stoły nierozkładane', 599.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-orzech-czarny-mat-90-cm-olmo-25398.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25400', 'Fotel ogrodowy Oskar. rattan syntetyczny naturalny, tkanina jasny popiel, nóżki czarne', 'halmar tymczasowa', 789.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-oskar-rattan-syntetyczny-naturalny-tkanina-jasny-popiel-nozki-czarne-25400.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25405', 'Zestaw 2 stolików kawowych okrągłych biały marmur / srebrny mat 60 cm, 38 cm Paola', 'Stoliki kawowe i ławy/Stoliki kawowe', 289.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-bialy-marmur-srebrny-mat-60-cm-38-cm-paola-25405.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25409', 'Ława prostokątna czarny marmur / orzech mat 121 x 61 cm Ramona', 'Stoliki kawowe i ławy/Ławy', 743.0, 'https://www.meblepumo.pl/pl/products/lawa-prostokatna-czarny-marmur-orzech-mat-121-x-61-cm-ramona-25409.feed10009', 'HALMAR');
