-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25430', 'Fotel biurowy siatka czarny Valdez 2', 'Fotele/Fotele do biurka', 429.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-czarny-valdez-2-25430.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25432', 'Fotel wypoczynkowy na płozie czarny / naturalny Whisper', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-na-plozie-czarny-naturalny-whisper-25432.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25433', 'Fotel rozkładany z funkcją kołyski velvet beżowy Wonder', 'Fotele/Fotele rozkładane', 1199.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-kolyski-velvet-bezowy-wonder-25433.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25434', 'Fotel rozkładany z funkcją kołyski velvet zielony Wonder', 'Fotele/Fotele rozkładane', 1199.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-kolyski-velvet-zielony-wonder-25434.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25435', 'Fotel rozkładany z funkcją kołyski velvet szary Wonder', 'Fotele/Fotele rozkładane', 1199.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-kolyski-velvet-szary-wonder-25435.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25436', 'Wieszak stojący na ubrania naturalny / beżowy / złoty mat 166 cm WU31', 'Wieszaki na ubrania/Wieszaki stojące', 309.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-na-ubrania-naturalny-bezowy-zloty-mat-166-cm-wu31-25436.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25437', 'Wieszak stojący na ubrania czarny / naturalny mat 165 cm WU32', 'Wieszaki na ubrania/Wieszaki stojące', 179.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-na-ubrania-czarny-naturalny-mat-165-cm-wu32-25437.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25438', 'Wieszak stojący na ubrania naturalny mat 168 cm WU33', 'Wieszaki na ubrania/Wieszaki stojące', 379.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-na-ubrania-naturalny-mat-168-cm-wu33-25438.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25439', 'Komoda z drzwiami szara mat 150 cm Asensio', 'Komody/Komody z drzwiami', 1019.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-szara-mat-150-cm-asensio-25439.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25440', 'Komoda z drzwiami szara mat 100 cm Asensio', 'Komody/Komody z drzwiami', 976.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-szara-mat-100-cm-asensio-25440.feed10009', 'HALMAR');
