-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23548', 'Sofa 3-osobowa tapicerowana jasnoszara Holly', 'Sofy i narożniki/Sofy 3-osobowe', 2599.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-jasnoszara-holly-23548.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23559', 'Szafka na buty mała dwudrzwiowa biała mat 70 cm Roma', 'Szafki na buty', 329.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-mala-dwudrzwiowa-biala-mat-70-cm-roma-23559.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23560', 'Szafka na buty mała dwudrzwiowa czarna mat 70 cm Roma', 'Szafki na buty', 349.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-mala-dwudrzwiowa-czarna-mat-70-cm-roma-23560.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23564', 'Szafka na buty mała czterodrzwiowa biała mat 70 cm Roma', 'Szafki na buty', 549.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-mala-czterodrzwiowa-biala-mat-70-cm-roma-23564.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23566', 'Szafka na buty mała czterodrzwiowa czarna mat 70 cm Roma', 'Szafki na buty', 599.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-mala-czterodrzwiowa-czarna-mat-70-cm-roma-23566.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23570', 'Szafka na buty dwudrzwiowa biała mat 70 cm Roma', 'Szafki na buty', 369.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-dwudrzwiowa-biala-mat-70-cm-roma-23570.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23572', 'Szafka na buty dwudrzwiowa czarna mat 70 cm Roma', 'Szafki na buty', 399.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-dwudrzwiowa-czarna-mat-70-cm-roma-23572.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23573', 'Szafka na buty biała mat 70 cm Roma', 'Szafki na buty', 489.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-biala-mat-70-cm-roma-23573.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23574', 'Szafka na buty trzydrzwiowa dąb sonoma / biała mat 70 cm Roma', 'Szafki na buty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-trzydrzwiowa-dab-sonoma-biala-mat-70-cm-roma-23574.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23575', 'Szafka na buty trzydrzwiowa czarna mat 70 cm Roma', 'Szafki na buty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-trzydrzwiowa-czarna-mat-70-cm-roma-23575.feed10009', 'Tvilum');
