-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28180', 'Ławka z półką dąb olejowany 80 cm Soline', 'Ławki do przedpokoju', 499.0, 'https://www.meblepumo.pl/pl/products/lawka-z-polka-dab-olejowany-80-cm-soline-28180.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28181', 'Ławka z półką dąb olejowany 60 cm Soline', 'Ławki do przedpokoju', 449.0, 'https://www.meblepumo.pl/pl/products/lawka-z-polka-dab-olejowany-60-cm-soline-28181.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28182', 'Wieszak ścienny wąski czarny 120 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 209.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-waski-czarny-120-cm-soline-28182.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28183', 'Wieszak ścienny dąb olejowany 80 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 139.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-olejowany-80-cm-soline-28183.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28184', 'Wieszak ścienny dąb olejowany 40 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 99.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-olejowany-40-cm-soline-28184.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28185', 'Wieszak ścienny dąb olejowany 30 cm Soline', 'Wieszaki na ubrania/Wieszaki ścienne', 89.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-dab-olejowany-30-cm-soline-28185.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28186', 'Konsola z szufladami dąb / czarna 100 cm Lars', 'Toaletki i konsole/Konsole ', 979.0, 'https://www.meblepumo.pl/pl/products/konsola-z-szufladami-dab-czarna-100-cm-lars-28186.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28187', 'Szafka na buty beż mat 74 cm Lugo', 'Szafki na buty', 1959.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-bez-mat-74-cm-lugo-28187.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28188', 'Szafka na buty biała mat 74 cm Lugo', 'Szafki na buty', 1959.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-biala-mat-74-cm-lugo-28188.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28189', 'Szafka na buty dąb artisan 74 cm Lugo', 'Szafki na buty', 1959.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-dab-artisan-74-cm-lugo-28189.feed10009', 'Fontini ');
