-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26495', 'Krzesło do jadalni tapicerowane bordowe / złote K66', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bordowe-zlote-k66-26495.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26496', 'Krzesło do jadalni tapicerowane niebieskie / srebrne K66S', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-niebieskie-srebrne-k66s-26496.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26499', 'Krzesło do jadalni ekoskóra białe K70', 'Krzesła/Krzesła do jadalni', 126.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-biale-k70-26499.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26500', 'Krzesło do jadalni ekoskóra ciemnobrązowe / szare K70', 'Krzesła/Krzesła do jadalni', 126.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-ciemnobrazowe-szare-k70-26500.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26501', 'Krzesło do jadalni ekoskóra czarne K70', 'Krzesła/Krzesła do jadalni', 126.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-czarne-k70-26501.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26502', 'Krzesło do jadalni ekoskóra jasnobrązowe / szare K70', 'Krzesła/Krzesła do jadalni', 126.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-jasnobrazowe-szare-k70-26502.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26511', 'Stolik kawowy okrągłe dąb naturalny / czarny mat 45 cm Karida-S', 'Stoliki kawowe i ławy/Stoliki kawowe', 239.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragle-dab-naturalny-czarny-mat-45-cm-karida-s-26511.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26512', 'Łóżko tapicerowane z szufladą beżowe 160x200 cm Kayleon', 'Łóżka i części/Łóżka', 2429.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-bezowe-160x200-cm-kayleon-26512.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26516', 'Krzesło do jadalni ekoskóra ciemnobrązowe / wenge Kerry Bis', 'Krzesła/Krzesła do jadalni', 239.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-ciemnobrazowe-wenge-kerry-bis-26516.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26519', 'Fotel gabinetowy velvet czarny King', 'Fotele/Fotele do biurka', 749.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-velvet-czarny-king-26519.feed10009', 'HALMAR');
