-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24568', 'Oświetlenie do komody Sally 4S białe', 'Dodatki do mebli/Oświetlenie LED', 119.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-komody-sally-4s-biale-24568.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24570', 'Oświetlenie do szafek nocnych Sally niebieskie', 'Dodatki do mebli/Oświetlenie LED', 149.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafek-nocnych-sally-niebieskie-24570.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24571', 'Oświetlenie do szafek nocnych Sally białe', 'Dodatki do mebli/Oświetlenie LED', 149.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafek-nocnych-sally-biale-24571.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24572', 'Stolik kawowy okrągły dąb naturalny / czarny mat 80 cm Florence', 'Stoliki kawowe i ławy/Stoliki kawowe', 499.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dab-naturalny-czarny-mat-80-cm-florence-24572.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24579', 'Łóżko dwuosobowe szare / naturalne 160x200 cm Margarita', 'Łóżka i części/Łóżka', 2049.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-szare-naturalne-160x200-cm-margarita-24579.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24582', 'Hoker z oparciem tapicerowany szary / czarny H89', 'Hokery', 242.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h89-24582.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24583', 'Witryna dwudrzwiowa dąb wotan / antracyt mat 60 x 183 cm North', 'Witryny i kredensy/Witryny', 899.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-dab-wotan-antracyt-mat-60-x-183-cm-north-24583.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24584', 'Komplet szafek nocnych dąb wotan / antracyt 40 cm North', 'Szafki nocne', 629.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-dab-wotan-antracyt-40-cm-north-24584.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24585', 'Komplet szafek nocnych różowy mat 44 cm Ikon', 'Szafki nocne', 819.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-rozowy-mat-44-cm-ikon-24585.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24586', 'Komplet szafek nocnych biała mat 44 cm Ikon', 'Szafki nocne', 799.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-biala-mat-44-cm-ikon-24586.feed10009', 'High Glossy Furniture');
