-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25557', 'Stół rozkładany czarny mat 102 - 142 x 102 cm Ringo', 'Stoly/Stoły rozkładane', 705.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-czarny-mat-102-142-x-102-cm-ringo-25557.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25561', 'Stół rozkładany dąb craft mat 140 - 220 x 80 cm Tiago 2', 'Stoly/Stoły rozkładane', 1189.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-craft-mat-140-220-x-80-cm-tiago-2-25561.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25566', 'Zestaw mebli kuchennych dąb sonoma / szary 240 cm Elizabeth', 'Zestawy mebli/Zestawy mebli kuchennych', 2199.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-dab-sonoma-szary-240-cm-elizabeth-25566.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25567', 'FLEX system szaf modułowych - FRONT F1 dąb artisan', 'halmar tymczasowa', 141.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-front-f1-dab-artisan-25567.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25569', 'FLEX system szaf modułowych - FRONT F1 ciemny popiel', 'halmar tymczasowa', 141.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-front-f1-ciemny-popiel-25569.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25572', 'FLEX system szaf modułowych - FRONT F2 ciemny popiel', 'halmar tymczasowa', 199.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-front-f2-ciemny-popiel-25572.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25573', 'FLEX system szaf modułowych - FRONT F3 z lustrem dąb artisan', 'halmar tymczasowa', 485.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-front-f3-z-lustrem-dab-artisan-25573.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25575', 'FLEX system szaf modułowych - FRONT F3 z lustrem ciemny popiel', 'halmar tymczasowa', 485.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-front-f3-z-lustrem-ciemny-popiel-25575.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25577', 'FLEX system szaf modułowych - KORPUS K1 biały', 'halmar tymczasowa', 513.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-korpus-k1-bialy-25577.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25578', 'FLEX system szaf modułowych - KORPUS K2 dąb artisan', 'halmar tymczasowa', 551.0, 'https://www.meblepumo.pl/pl/products/flex-system-szaf-modulowych-korpus-k2-dab-artisan-25578.feed10009', 'HALMAR');
