-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18120', 'Komoda z drzwiami i szufladami biała / dąb sonoma mat 110 cm Livorno', 'Komody/Komody z szufladami i drzwiami', 1119.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-biala-dab-sonoma-mat-110-cm-livorno-18120.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18121', 'Witryna dwudrzwiowa z szufladami biała / dąb sonoma mat 120 cm Livorno', 'Witryny i kredensy/Witryny', 1359.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-biala-dab-sonoma-mat-120-cm-livorno-18121.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18140', 'Komoda z szufladami czarna mat 51 cm Baroque', 'Pozostałe produkty', 499.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-mat-51-cm-baroque-18140.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18163', 'Komoda z szufladami czarna mat 81 cm Softline', 'Pozostałe produkty', 399.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-mat-81-cm-softline-18163.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18244', 'LED 2 klejony biały zimny + zasilacz High Gloss Furniture', 'Dodatki do mebli/Oświetlenie LED', 109.0, 'https://www.meblepumo.pl/pl/products/led-2-klejony-bialy-zimny-zasilacz-high-gloss-furniture-18244.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18247', 'Narożnik 3-osobowy lewostronny tapicerowany zielony Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-lewostronny-tapicerowany-zielony-sampras-18247.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18248', 'Narożnik 3-osobowy prawostronny tapicerowany zielony Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-prawostronny-tapicerowany-zielony-sampras-18248.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18249', 'Narożnik 3-osobowy lewostronny tapicerowany szary Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-lewostronny-tapicerowany-szary-sampras-18249.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18250', 'Narożnik 3-osobowy prawostronny tapicerowany szary Sampras', 'Sofy i narożniki/Narożniki', 2759.0, 'https://www.meblepumo.pl/pl/products/naroznik-3-osobowy-prawostronny-tapicerowany-szary-sampras-18250.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18251', 'Stelaż do łóżka 140x190 cm Futura NV', 'Łóżka i części/Stelaże do łóżek', 619.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-140x190-cm-futura-nv-18251.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
