-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26666', 'Stół rozkładany biały / szary połysk 160 - 220 x 90 cm Monaco', 'Stoly/Stoły rozkładane', 1999.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-szary-polysk-160-220-x-90-cm-monaco-26666.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26669', 'Zestaw 2 puf okrągłych ze schowkiem tapicerowanych granatowych Monty', 'Pufy', 279.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-puf-okraglych-ze-schowkiem-tapicerowanych-granatowych-monty-26669.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26672', 'Stół rozkładany dąb złoty / czarny mat 118 - 148 x 118 cm Moretti', 'Stoly/Stoły rozkładane', 1579.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-zloty-czarny-mat-118-148-x-118-cm-moretti-26672.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26680', 'Stół okrągły dąb złoty / czarny mat 120 x 75 cm Mozambik', 'Stoly/Stoły nierozkładane', 964.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-dab-zloty-czarny-mat-120-x-75-cm-mozambik-26680.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26685', 'Biurko z regałem dąb sonoma / białe mat 120 cm Narvik', 'Biurka/Biurka z szufladami i drzwiami', 299.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regalem-dab-sonoma-biale-mat-120-cm-narvik-26685.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26690', 'Regał na książki czarny / dąb sonoma mat 34 x 32 x 148 cm Narvik', 'Regały', 162.0, 'https://www.meblepumo.pl/pl/products/regal-na-ksiazki-czarny-dab-sonoma-mat-34-x-32-x-148-cm-narvik-26690.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26691', 'Regał na książki biały / dąb sonoma mat 60 x 32 x 148 cm Narvik', 'Regały', 199.0, 'https://www.meblepumo.pl/pl/products/regal-na-ksiazki-bialy-dab-sonoma-mat-60-x-32-x-148-cm-narvik-26691.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26701', 'Zestaw 2 stolików kawowych loftowych dąb złoty / czarny mat 60 x 60 cm, 40 x 40 cm Nicea 2', 'Stoliki kawowe i ławy/Stoliki kawowe', 287.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-loftowych-dab-zloty-czarny-mat-60-x-60-cm-40-x-40-cm-nicea-2-26701.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26704', 'Kontenerek pod biurko sosna mat 36 x 40 x 65 cm Nils', 'Kontenerki', 267.0, 'https://www.meblepumo.pl/pl/products/kontenerek-pod-biurko-sosna-mat-36-x-40-x-65-cm-nils-26704.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26705', 'Ława szklana transparentny / biały mat 130 x 70 cm Nina 3 H', 'Stoliki kawowe i ławy/Ławy', 779.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-bialy-mat-130-x-70-cm-nina-3-h-26705.feed10009', 'HALMAR');
