-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26770', 'Stół okrągły biały / czarny mat 120 cm Pixel', 'Stoly/Stoły nierozkładane', 999.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-bialy-czarny-mat-120-cm-pixel-26770.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26771', 'Stolik kawowy kwadratowy naturalny / czarny mat 85 x 80 cm Podium', 'Stoliki kawowe i ławy/Stoliki kawowe', 993.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-naturalny-czarny-mat-85-x-80-cm-podium-26771.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26772', 'Zestaw 2 puf okrągłych ze schowkiem tapicerowanych bordowych Polly', 'Pufy', 369.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-puf-okraglych-ze-schowkiem-tapicerowanych-bordowych-polly-26772.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26773', 'Zestaw 2 puf okrągłych ze schowkiem tapicerowanych zielonych Polly', 'Pufy', 369.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-puf-okraglych-ze-schowkiem-tapicerowanych-zielonych-polly-26773.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26775', 'Fotel biurowy ekoskóra biały Porto 2', 'Fotele/Fotele do biurka', 399.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-bialy-porto-2-26775.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26780', 'Fotel gabinetowy ekoskóra czarny Preston', 'Fotele/Fotele do biurka', 669.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-czarny-preston-26780.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26789', 'Fotel rozkładany z funkcją masażu tapicerowany beżowy Pulsar 2', 'Fotele/Fotele rozkładane', 1389.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-tapicerowany-bezowy-pulsar-2-26789.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26790', 'Fotel rozkładany z funkcją masażu tapicerowany szary Pulsar 2', 'Fotele/Fotele rozkładane', 1389.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-tapicerowany-szary-pulsar-2-26790.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26791', 'Fotel rozkładany z funkcją masażu ekoskóra beżowy Pulsar', 'Fotele/Fotele rozkładane', 1359.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-ekoskora-bezowy-pulsar-26791.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26792', 'Fotel rozkładany z funkcją masażu ekoskóra cappuccino Pulsar', 'Fotele/Fotele rozkładane', 1359.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-ekoskora-cappuccino-pulsar-26792.feed10009', 'HALMAR');
