-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16487', 'Sofa 2-osobowa tapicerowana zielona Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2499.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-zielona-gryf-16487.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16488', 'Sofa 2-osobowa tapicerowana miodowa Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2499.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-miodowa-gryf-16488.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16489', 'Sofa 3-osobowa tapicerowana beżowa Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-bezowa-gryf-16489.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16490', 'Sofa 3-osobowa tapicerowana czarna Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-czarna-gryf-16490.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16491', 'Sofa 3-osobowa tapicerowana bordowa Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-bordowa-gryf-16491.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16492', 'Sofa 3-osobowa tapicerowana fioletowa Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-fioletowa-gryf-16492.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16493', 'Sofa 3-osobowa tapicerowana turkusowa Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-turkusowa-gryf-16493.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16494', 'Sofa 3-osobowa tapicerowana zielona Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-zielona-gryf-16494.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16495', 'Sofa 3-osobowa tapicerowana miodowa Gryf', 'Sofy i narożniki/Sofy 3-osobowe', 2799.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-miodowa-gryf-16495.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16503', 'Sofa 2-osobowa tapicerowana różowa Sampras', 'Sofy i narożniki/Sofy 2-osobowe', 1649.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-rozowa-sampras-16503.feed10009', 'Scandinavian Style Design');
