-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26603', 'Fotel wypoczynkowy tapicerowany żółty Marvel', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zolty-marvel-26603.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26607', 'Fotel rozkładany z funkcją masażu ekoskóra beżowy Matador', 'Fotele/Fotele rozkładane', 1183.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-ekoskora-bezowy-matador-26607.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26608', 'Fotel rozkładany z funkcją masażu ekoskóra czarny Matador', 'Fotele/Fotele rozkładane', 1183.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-z-funkcja-masazu-ekoskora-czarny-matador-26608.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26611', 'Fotel obrotowy młodzieżowy tapicerowany ekoskóra biały / szary Matrix 3', 'Fotele/Fotele młodzieżowe', 286.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-ekoskora-bialy-szary-matrix-3-26611.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26614', 'Fotel obrotowy młodzieżowy tapicerowany ekoskóra biały / szary Matrix', 'Fotele/Fotele młodzieżowe', 299.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-ekoskora-bialy-szary-matrix-26614.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26619', 'Fotel bujany na płozie wenge / wielokolorowy Max 2', 'Fotele/Fotele bujane', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-na-plozie-wenge-wielokolorowy-max-2-26619.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26620', 'Fotel bujany na płozie biały / szary Max Bis Plus', 'Fotele/Fotele bujane', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-na-plozie-bialy-szary-max-bis-plus-26620.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26621', 'Fotel bujany na płozie olcha / brązowy Max Bis Plus', 'Fotele/Fotele bujane', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-na-plozie-olcha-brazowy-max-bis-plus-26621.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26622', 'Fotel bujany na płozie wenge / brązowy Max Bis Plus', 'Fotele/Fotele bujane', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-na-plozie-wenge-brazowy-max-bis-plus-26622.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26625', 'Stolik kawowy owalny dąb sonoma / biały mat / połysk 90 x 50 cm Medea', 'Stoliki kawowe i ławy/Stoliki kawowe', 239.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-owalny-dab-sonoma-bialy-mat-polysk-90-x-50-cm-medea-26625.feed10009', 'HALMAR');
