-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25050', 'Szafka RTV czarna mat / połysk 190 cm Glamour', 'Szafki RTV', 1059.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-polysk-190-cm-glamour-25050.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25056', 'Komoda z drzwiami biała mat / wysoki połysk 160 cm Blend', 'Komody/Komody z drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-wysoki-polysk-160-cm-blend-25056.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25057', 'Szafka RTV biała mat / połysk 190 cm Blend', 'Szafki RTV', 839.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-polysk-190-cm-blend-25057.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25058', 'Stolik kawowy prostokątny biały połysk 120 x 55 cm Blend', 'Stoliki kawowe i ławy/Stoliki kawowe', 749.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bialy-polysk-120-x-55-cm-blend-25058.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25068', 'Szafka RTV czarna mat / połysk 190 cm Blend', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-polysk-190-cm-blend-25068.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25069', 'Komoda z dzwiami czarna mat / wysoki połysk 160 cm Blend', 'Komody/Komody z drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-z-dzwiami-czarna-mat-wysoki-polysk-160-cm-blend-25069.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25070', 'Stolik kawowy prostokątny czarny połysk 120 x 55 cm Blend', 'Stoliki kawowe i ławy/Stoliki kawowe', 769.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-czarny-polysk-120-x-55-cm-blend-25070.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25085', 'Komoda z szufladami i drzwiami biała / dąb wotan mat / wysoki połysk 160 cm Image', 'Komody/Komody z szufladami i drzwiami', 949.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-wotan-mat-wysoki-polysk-160-cm-image-25085.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25086', 'Szafka RTV biała / dąb wotan mat / połysk 180 cm Image', 'Szafki RTV', 699.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-wotan-mat-polysk-180-cm-image-25086.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25087', 'Witryna dwudrzwiowa biała / dąb wotan mat / połysk 60 x 180 cm Image', 'Witryny i kredensy/Witryny', 849.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-biala-dab-wotan-mat-polysk-60-x-180-cm-image-25087.feed10009', 'designoo');
