-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23629', 'Witryna jednodrzwiowa z szufladami dąb lefkas mat 60 x 192 cm Simple', 'Witryny i kredensy/Witryny', 929.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-dab-lefkas-mat-60-x-192-cm-simple-23629.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23673', 'Komoda z szufladami i drzwiami czarna / orzech mat 150 cm Ryan', 'Komody/Komody z szufladami i drzwiami', 785.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-czarna-orzech-mat-150-cm-ryan-23673.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23675', 'Komoda z szufladami i drzwiami biała mat 102 cm Ryan', 'Komody/Komody z szufladami i drzwiami', 540.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-mat-102-cm-ryan-23675.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23676', 'Komoda z szufladami i drzwiami czarna / orzech mat 102 cm Ryan', 'Komody/Komody z szufladami i drzwiami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-czarna-orzech-mat-102-cm-ryan-23676.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23677', 'Witryna dwudrzwiowa z szufladą czarna / orzech mat 102 x 162 cm Ryan', 'Witryny i kredensy/Witryny', 964.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szuflada-czarna-orzech-mat-102-x-162-cm-ryan-23677.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23679', 'Stolik kawowy z szufladą czarny / orzech mat 102 x 48 cm Ryan', 'Stoliki kawowe i ławy/Stoliki kawowe', 1069.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-czarny-orzech-mat-102-x-48-cm-ryan-23679.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23686', 'Szafka RTV biała / czarna mat 150 cm Ryan', 'Szafki RTV', 1149.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-czarna-mat-150-cm-ryan-23686.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23687', 'Szafka RTV czarna / orzech mat 150 cm Ryan', 'Szafki RTV', 1329.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-orzech-mat-150-cm-ryan-23687.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23698', 'Szafka RTV dąb wotan / antracyt mat 185 cm North', 'Szafki RTV', 969.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-wotan-antracyt-mat-185-cm-north-23698.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23699', 'Komoda z szufladami i drzwiami dąb wotan / antracyt mat 138 cm North', 'Komody/Komody z szufladami i drzwiami', 1079.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-wotan-antracyt-mat-138-cm-north-23699.feed10009', 'High Glossy Furniture');
