-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23812', 'Konsola prosta dąb złoty / czarna mat 90 cm Bolivar KN1', 'Toaletki i konsole/Konsole ', 219.0, 'https://www.meblepumo.pl/pl/products/konsola-prosta-dab-zloty-czarna-mat-90-cm-bolivar-kn1-23812.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23813', 'Biurko z szufladą orzech miodowy mat 110 cm B39', 'Biurka/Biurka z szufladami i drzwiami', 519.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-orzech-miodowy-mat-110-cm-b39-23813.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23821', 'Fotel wypoczynkowy tapicerowany szary Castel', 'Fotele/Fotele wypoczynkowe', 765.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-castel-23821.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23822', 'Fotel ogrodowy rattanowy naturalny Indiana', 'Fotele/Fotele ogrodowe', 629.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-rattanowy-naturalny-indiana-23822.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23828', 'Krzesło do jadalni ekoskora brązowa K338', 'Krzesła/Krzesła do jadalni', 449.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-brazowa-k338-23828.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23830', 'Szafka wysoka biała mat 50 cm Glory', 'Regały', 909.0, 'https://www.meblepumo.pl/pl/products/szafka-wysoka-biala-mat-50-cm-glory-23830.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23832', 'Komoda wysoka dwudrzwiowa z połkami biała mat 100 x 149 cm Glory', 'Komody/Komody z drzwiami', 1314.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-dwudrzwiowa-z-polkami-biala-mat-100-x-149-cm-glory-23832.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23833', 'Szafka RTV biała / czarna mat 214 cm Glory', 'Szafki RTV', 1735.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-czarna-mat-214-cm-glory-23833.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23853', 'Krzesło do jadalni tapicerowane zielone K386', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k386-23853.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23854', 'Krzesło do jadalni tapicerowane szare K386', 'Krzesła/Krzesła do jadalni', 359.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k386-23854.feed10009', 'HALMAR');
