-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26255', 'Krzesło do jadalni tapicerowane bordowe K332', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bordowe-k332-26255.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26258', 'Krzesło do jadalni tapicerowane czarne K332', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k332-26258.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26259', 'Krzesło do jadalni tapicerowane granatowe K332', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k332-26259.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26260', 'Krzesło do jadalni tapicerowane musztardowe K332', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k332-26260.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26261', 'Krzesło do jadalni tapicerowane różowe K332', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-rozowe-k332-26261.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26262', 'Krzesło do jadalni tapicerowane turkusowe K332', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-turkusowe-k332-26262.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26263', 'Krzesło do jadalni tapicerowane szare K333', 'Krzesła/Krzesła do jadalni', 425.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k333-26263.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26273', 'Krzesło na płozie tapicerowane szare K349', 'Krzesła/Krzesła na płozie', 229.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-szare-k349-26273.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26280', 'Krzesło do jadalni tapicerowane beżowe K360', 'Krzesła/Krzesła do jadalni', 269.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k360-26280.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26281', 'Krzesło do jadalni tapicerowane musztardowe K360', 'Krzesła/Krzesła do jadalni', 269.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k360-26281.feed10009', 'HALMAR');
