-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27645', 'Zestaw mebli kuchennych beżowy / dąb sonoma / biały 200 cm Marija', 'Zestawy mebli/Zestawy mebli kuchennych', 949.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-bezowy-dab-sonoma-bialy-200-cm-marija-27645.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27647', 'Biurko z szufladami dąb wotan / antracyt mat 210 cm Sergio', 'Biurka/Biurka z szufladami i drzwiami', 829.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-wotan-antracyt-mat-210-cm-sergio-27647.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27651', 'VENTO blat 1340/28 mm dąb craft (1p=1szt)', 'halmar tymczasowa', 247.0, 'https://www.meblepumo.pl/pl/products/vento-blat-1340-28-mm-dab-craft-1p-1szt-27651.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27654', 'Cokół meblowy biały mat 10 cm Vento', 'Dodatki do mebli/Części do mebli', 20.0, 'https://www.meblepumo.pl/pl/products/cokol-meblowy-bialy-mat-10-cm-vento-27654.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27655', 'Cokół meblowy dąb craft mat 10 cm Vento', 'Dodatki do mebli/Części do mebli', 22.0, 'https://www.meblepumo.pl/pl/products/cokol-meblowy-dab-craft-mat-10-cm-vento-27655.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27656', 'Szafka dolna otwarta biała mat 15 cm Vento', 'Szafki kuchenne', 109.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-otwarta-biala-mat-15-cm-vento-27656.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27665', 'Szafka dolna biała / dąb miodowy mat / wysoki połysk 30 cm Vento', 'Szafki kuchenne', 204.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-biala-dab-miodowy-mat-wysoki-polysk-30-cm-vento-27665.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27670', 'Szafka dolna z szufladami biała / dąb miodowy mat 40 cm Vento', 'Szafki kuchenne', 527.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-z-szufladami-biala-dab-miodowy-mat-40-cm-vento-27670.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27671', 'Szafka dolna z szufladami biała / jasnoszara mat / wysoki połysk 40 cm Vento', 'Szafki kuchenne', 527.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-z-szufladami-biala-jasnoszara-mat-wysoki-polysk-40-cm-vento-27671.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27672', 'Szafka dolna z szufladami antracyt mat 60 cm Vento', 'Szafki kuchenne', 624.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-z-szufladami-antracyt-mat-60-cm-vento-27672.feed10009', 'HALMAR');
