-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25356', 'Krzesło ogrodowe plastikowe miętowe K514', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-mietowe-k514-25356.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25357', 'Krzesło ogrodowe plastikowe pomarańczowe K514', 'Krzesła/Krzesła ogrodowe', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-pomaranczowe-k514-25357.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25360', 'Krzesło do jadalni tapicerowane szare K516', 'Krzesła/Krzesła do jadalni', 399.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k516-25360.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25364', 'Krzesło do jadalni tapicerowane zielone K519', 'Krzesła/Krzesła do jadalni', 329.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k519-25364.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25365', 'Krzesło do jadalni tapicerowane czarne K519', 'Krzesła/Krzesła do jadalni', 329.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k519-25365.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25366', 'Krzesło do jadalni tapicerowane szare K519', 'Krzesła/Krzesła do jadalni', 329.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k519-25366.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25368', 'Krzesło do jadalni tapicerowane zielone K520', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k520-25368.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25369', 'Krzesło do jadalni tapicerowane czarne K520', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k520-25369.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25370', 'Krzesło do jadalni tapicerowane zielone K521', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k521-25370.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25371', 'Krzesło do jadalni tapicerowane czarne K521', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-czarne-k521-25371.feed10009', 'HALMAR');
