-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28510', 'Nadstawka na szafę antracyt / grafit mat 134 x 55 cm Teo', 'Szafy/Nadstawki na szafę', 429.0, 'https://www.meblepumo.pl/pl/products/nadstawka-na-szafe-antracyt-grafit-mat-134-x-55-cm-teo-28510.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28511', 'Nadstawka na szafę antracyt / grafit mat 179 x 55 cm Teo', 'Szafy/Nadstawki na szafę', 499.0, 'https://www.meblepumo.pl/pl/products/nadstawka-na-szafe-antracyt-grafit-mat-179-x-55-cm-teo-28511.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28512', 'Komoda wysoka z drzwiami dąb artisan / czarna mat 100 cm Arden', 'Komody/Komody z drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-dab-artisan-czarna-mat-100-cm-arden-28512.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28513', 'Komoda z drzwiami dąb artisan / czarna mat 150 cm Arden', 'Komody/Komody z drzwiami', 929.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-artisan-czarna-mat-150-cm-arden-28513.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28514', 'Komoda z drzwiami dąb artisan / czarna mat 200 cm Arden', 'Komody/Komody z drzwiami', 1159.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-artisan-czarna-mat-200-cm-arden-28514.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28515', 'Stolik kawowy z półką dąb artisan / czarny mat 100 x 55 cm Arden', 'Stoliki kawowe i ławy/Stoliki kawowe', 569.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-artisan-czarny-mat-100-x-55-cm-arden-28515.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28516', 'Komplet szafek nocnych dąb artisan / czarny mat 44 cm Arden', 'Szafki nocne', 679.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-dab-artisan-czarny-mat-44-cm-arden-28516.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28517', 'Szafka RTV dąb artisan / czarna mat 200 cm Arden', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-artisan-czarna-mat-200-cm-arden-28517.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28518', 'Półka wisząca dąb artisan / czarna mat 110 x 20 cm Arden', 'Półki wiszące', 199.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-dab-artisan-czarna-mat-110-x-20-cm-arden-28518.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28519', 'Szafa dwudrzwiowa dąb artisan / czarny mat 90 x 184 cm Arden', 'Szafy/Szafy uchylne', 1299.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-dab-artisan-czarny-mat-90-x-184-cm-arden-28519.feed10009', 'High Glossy Furniture');
