-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25221', 'Stół rozkładany dąb naturalny / czarny mat 150 - 210 x 90 cm Dickson 2', 'Stoly/Stoły rozkładane', 1459.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-czarny-mat-150-210-x-90-cm-dickson-2-25221.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25222', 'Fotel gamingowy tapicerowany ekoskóra czarny / czerwony Drake', 'Fotele/Fotele do biurka', 769.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-tapicerowany-ekoskora-czarny-czerwony-drake-25222.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25223', 'Fotel wypoczynkowy  velvet szary Enrico', 'Fotele/Fotele wypoczynkowe', 1023.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-szary-enrico-25223.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25224', 'Fotel wypoczynkowy  velvet zielony Enrico', 'Fotele/Fotele wypoczynkowe', 1023.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-zielony-enrico-25224.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25226', 'Fotel gabinetowy siatka czarny Fabio', 'Fotele/Fotele do biurka', 435.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-siatka-czarny-fabio-25226.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25227', 'Łóżko dziecięce białe 90x200 cm Fabrizia', 'Łóżka dziecięce', 799.0, 'https://www.meblepumo.pl/pl/products/lozko-dzieciece-biale-90x200-cm-fabrizia-25227.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25230', 'Fotel biurowy velvet szary Fidel', 'Fotele/Fotele do biurka', 389.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-velvet-szary-fidel-25230.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25232', 'Fotel ogrodowy rattanowy naturalny Foden 2', 'Fotele/Fotele ogrodowe', 813.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-rattanowy-naturalny-foden-2-25232.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25233', 'Fotel wypoczynkowy drewniany czarny / naturalny Foden', 'Fotele/Fotele wypoczynkowe', 755.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-drewniany-czarny-naturalny-foden-25233.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25234', 'Stół rozkładany biały mat 160 - 200 x 90 cm Galardo', 'Stoly/Stoły rozkładane', 3399.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-160-200-x-90-cm-galardo-25234.feed10009', 'HALMAR');
