-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16986', 'Szezlong lewostronny tapicerowany grafitowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-grafitowy-lily-16986.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16987', 'Szezlong prawostronny tapicerowany granatowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-granatowy-lily-16987.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16988', 'Szezlong lewostronny tapicerowany granatowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-granatowy-lily-16988.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16989', 'Szezlong prawostronny tapicerowany szary Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-szary-lily-16989.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16990', 'Szezlong lewostronny tapicerowany szary Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-szary-lily-16990.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16991', 'Szezlong prawostronny tapicerowany oliwkowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-oliwkowy-lily-16991.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16992', 'Szezlong lewostronny tapicerowany oliwkowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-oliwkowy-lily-16992.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17013', 'Sofa tapicerowana Leya, 3 osobowa, żółta, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-zolta-nozki-wenge-17013.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17014', 'Sofa tapicerowana Leya, 3 osobowa, grafitowa, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-grafitowa-nozki-wenge-17014.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17015', 'Sofa tapicerowana Leya, 3 osobowa, turkusowa, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-turkusowa-nozki-wenge-17015.feed10009', 'Scandinavian Style Design');
