-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27722', 'Front do zabudowy zmywarki dąb miodowy mat 45 cm Vento', 'Dodatki do mebli/Części do mebli', 99.0, 'https://www.meblepumo.pl/pl/products/front-do-zabudowy-zmywarki-dab-miodowy-mat-45-cm-vento-27722.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27724', 'Front do zabudowy zmywarki antracyt mat 60 cm Vento', 'Dodatki do mebli/Części do mebli', 128.0, 'https://www.meblepumo.pl/pl/products/front-do-zabudowy-zmywarki-antracyt-mat-60-cm-vento-27724.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27725', 'Front do zabudowy zmywarki beżowy wysoki połysk 60 cm Vento', 'Dodatki do mebli/Części do mebli', 128.0, 'https://www.meblepumo.pl/pl/products/front-do-zabudowy-zmywarki-bezowy-wysoki-polysk-60-cm-vento-27725.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27727', 'Front do zabudowy zmywarki dąb miodowy mat 60 cm Vento', 'Dodatki do mebli/Części do mebli', 128.0, 'https://www.meblepumo.pl/pl/products/front-do-zabudowy-zmywarki-dab-miodowy-mat-60-cm-vento-27727.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27728', 'Front do zabudowy zmywarki szary wysoki połysk 60 cm Vento', 'Dodatki do mebli/Części do mebli', 128.0, 'https://www.meblepumo.pl/pl/products/front-do-zabudowy-zmywarki-szary-wysoki-polysk-60-cm-vento-27728.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27732', 'Szafka szafka dolna narożna biała / dąb miodowy mat 80 cm Vento', 'Szafki kuchenne', 366.0, 'https://www.meblepumo.pl/pl/products/szafka-szafka-dolna-narozna-biala-dab-miodowy-mat-80-cm-vento-27732.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27733', 'Szafka szafka dolna narożna biała / jasny szary mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 366.0, 'https://www.meblepumo.pl/pl/products/szafka-szafka-dolna-narozna-biala-jasny-szary-mat-wysoki-polysk-80-cm-vento-27733.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27735', 'Szafka szafka dolna wysoka biała / beżowa mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 755.0, 'https://www.meblepumo.pl/pl/products/szafka-szafka-dolna-wysoka-biala-bezowa-mat-wysoki-polysk-60-cm-vento-27735.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27737', 'Szafka szafka dolna wysoka biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 755.0, 'https://www.meblepumo.pl/pl/products/szafka-szafka-dolna-wysoka-biala-dab-miodowy-mat-60-cm-vento-27737.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27743', 'Szafka dolna pod zabudowę piekarnik biała / jasnoszara mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 230.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-pod-zabudowe-piekarnik-biala-jasnoszara-mat-wysoki-polysk-60-cm-vento-27743.feed10009', 'HALMAR');
