-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20439', 'Łóżko tapicerowane białe 160x200 cm Sandy', 'Łóżka i części/Łóżka', 1499.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-biale-160x200-cm-sandy-20439.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20441', 'Łóżko tapicerowane z szufladą szare 160x200 cm Valery', 'Łóżka i części/Łóżka', 1999.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-valery-20441.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20442', 'Łóżko jednoosobowe białe 90x200 cm Sumatra', 'Łóżka i części/Łóżka', 799.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-biale-90x200-cm-sumatra-20442.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('21459', 'Sekretarzyk z szufladami dąb sękaty mat 110 cm Derby', 'Biurka/Biurka z szufladami i drzwiami', 1399.0, 'https://www.meblepumo.pl/pl/products/sekretarzyk-z-szufladami-dab-sekaty-mat-110-cm-derby-21459.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23124', 'Witryna Glare 2D czarna wysoki połysk tkanina czarno-biała', 'Pozostałe produkty', 2349.0, 'https://www.meblepumo.pl/pl/products/witryna-glare-2d-czarna-wysoki-polysk-tkanina-czarno-biala-23124.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23131', 'Stolik kawowy okrągły biały mat 70 cm Bonn', 'Pozostałe produkty', 589.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bialy-mat-70-cm-bonn-23131.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23151', 'Komoda z drzwiami biała mat 210 cm Tuscany', 'Pozostałe produkty', 1439.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-210-cm-tuscany-23151.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23154', 'Komoda z drzwiami biała mat 138 cm Tuscany', 'Pozostałe produkty', 1079.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-138-cm-tuscany-23154.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23155', 'Komoda z drzwiami biała mat 110 cm Tuscany', 'Komody/Komody z drzwiami', 1499.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-110-cm-tuscany-23155.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23156', 'Szafka RTV biała mat 138 cm Tuscany', 'Szafki RTV', 819.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-138-cm-tuscany-23156.feed10009', 'Italia Trend');
