-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27334', 'Mata ochronna pod krzesło mleczna 125 x 100 cm', 'Dodatki do mebli/Akcesoria ', 139.0, 'https://www.meblepumo.pl/pl/products/mata-ochronna-pod-krzeslo-mleczna-125-x-100-cm-27334.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27335', 'Mata ochronna pod krzesło mleczna 140 x 100 cm', 'Dodatki do mebli/Akcesoria ', 79.0, 'https://www.meblepumo.pl/pl/products/mata-ochronna-pod-krzeslo-mleczna-140-x-100-cm-27335.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27336', 'Stół rozkładany biały mat 118 - 158 x 75 cm Maurycy', 'Stoly/Stoły rozkładane', 617.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-118-158-x-75-cm-maurycy-27336.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27337', 'Stół rozkładany ciemny orzech mat 118 - 158 x 75 cm Maurycy', 'Stoly/Stoły rozkładane', 617.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-ciemny-orzech-mat-118-158-x-75-cm-maurycy-27337.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27338', 'Stół rozkładany dąb sonoma mat 118 - 158 x 75 cm Maurycy', 'Stoly/Stoły rozkładane', 617.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-sonoma-mat-118-158-x-75-cm-maurycy-27338.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27339', 'Stół rozkładany dąb sonoma / biały mat 118 - 158 x 75 cm Maurycy', 'Stoly/Stoły rozkładane', 617.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-sonoma-bialy-mat-118-158-x-75-cm-maurycy-27339.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27343', 'Stół okrągły dąb naturalny / czarny mat 120 cm Miyaki', 'Stoly/Stoły nierozkładane', 2335.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-dab-naturalny-czarny-mat-120-cm-miyaki-27343.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27422', 'Krzesło do jadalni drewniane tapicerowane szare / czarne Azul', 'Krzesła/Krzesła do jadalni', 425.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-czarne-azul-27422.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27424', 'Hoker z oparciem tapicerowany biały / beżowy Borys Low', 'Hokery', 409.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-bialy-bezowy-borys-low-27424.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27426', 'Hoker z oparciem tapicerowany dąb sonoma / beżowy Borys Low', 'Hokery', 409.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-dab-sonoma-bezowy-borys-low-27426.feed10009', 'HALMAR');
