-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16966', 'Szezlong lewostronny tapicerowany zielony Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-zielony-lily-16966.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16967', 'Szezlong prawostronny tapicerowany żółty Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-zolty-lily-16967.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16968', 'Szezlong lewostronny tapicerowany żółty Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-zolty-lily-16968.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16972', 'Szezlong prawostronny tapicerowany beżowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-bezowy-lily-16972.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16973', 'Szezlong lewostronny tapicerowany beżowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-bezowy-lily-16973.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16981', 'Szezlong prawostronny tapicerowany czerwony Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-czerwony-lily-16981.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16982', 'Szezlong lewostronny tapicerowany czerwony Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-czerwony-lily-16982.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16983', 'Szezlong prawostronny tapicerowany fioletowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-fioletowy-lily-16983.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16984', 'Szezlong lewostronny tapicerowany fioletowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-lewostronny-tapicerowany-fioletowy-lily-16984.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16985', 'Szezlong prawostronny tapicerowany grafitowy Lily', 'Szezlongi', 2499.0, 'https://www.meblepumo.pl/pl/products/szezlong-prawostronny-tapicerowany-grafitowy-lily-16985.feed10009', 'Scandinavian Style Design');
