-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27798', 'Szafka górna z ociekaczem biała / dąb miodowy mat 80 cm Vento', 'Szafki kuchenne', 393.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-z-ociekaczem-biala-dab-miodowy-mat-80-cm-vento-27798.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27799', 'Szafka górna z ociekaczem biała / jasnoszara mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 393.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-z-ociekaczem-biala-jasnoszara-mat-wysoki-polysk-80-cm-vento-27799.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27800', 'Szafka górna narożna dąb craft / antracyt mat 60 cm Vento', 'Szafki kuchenne', 316.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-narozna-dab-craft-antracyt-mat-60-cm-vento-27800.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27803', 'Szafka górna narożna biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 316.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-narozna-biala-dab-miodowy-mat-60-cm-vento-27803.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27804', 'Szafka górna narożna biała / jasnoszara mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 316.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-narozna-biala-jasnoszara-mat-wysoki-polysk-60-cm-vento-27804.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27805', 'Szafka górna dąb craft / antracyt mat 50 cm Vento', 'Szafki kuchenne', 151.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-dab-craft-antracyt-mat-50-cm-vento-27805.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27808', 'Szafka górna biała / dąb miodowy mat 50 cm Vento', 'Szafki kuchenne', 151.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-dab-miodowy-mat-50-cm-vento-27808.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27811', 'Szafka górna okapowa biała / beż mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 167.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-okapowa-biala-bez-mat-wysoki-polysk-60-cm-vento-27811.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27813', 'Szafka górna okapowa biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 167.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-okapowa-biala-dab-miodowy-mat-60-cm-vento-27813.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27814', 'Szafka górna biała / jasnoszara mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 167.0, 'https://www.meblepumo.pl/pl/products/szafka-gorna-biala-jasnoszara-mat-wysoki-polysk-60-cm-vento-27814.feed10009', 'HALMAR');
