-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26902', 'Fotel gamingowy tapicerowany szary / czarny Sonic', 'Fotele/Fotele do biurka', 599.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-tapicerowany-szary-czarny-sonic-26902.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26907', 'Ławka na buty tapicerowana szara / biała 81 cm ST11', 'Ławki do przedpokoju', 289.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-tapicerowana-szara-biala-81-cm-st11-26907.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26908', 'Ławka na buty tapicerowana czarna / naturalna 81 cm ST11', 'Ławki do przedpokoju', 289.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-tapicerowana-czarna-naturalna-81-cm-st11-26908.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26910', 'Ławka na buty ze schowkiem szara / naturalna 100 cm ST13', 'Ławki do przedpokoju', 319.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-ze-schowkiem-szara-naturalna-100-cm-st13-26910.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26911', 'Ławka na buty tapicerowana szara / naturalna 60 cm ST14', 'Ławki do przedpokoju', 149.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-tapicerowana-szara-naturalna-60-cm-st14-26911.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26912', 'Ławka na buty tapicerowana szara / naturalna 100 cm ST15', 'Ławki do przedpokoju', 184.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-tapicerowana-szara-naturalna-100-cm-st15-26912.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26914', 'Ławka na buty tapicerowana kremowa / wenge 81 cm ST3', 'Ławki do przedpokoju', 289.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-tapicerowana-kremowa-wenge-81-cm-st3-26914.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26916', 'Stojak na buty ST8, 53 x 26 x 65 cm, drewno lite naturalne', 'Szafki na buty', 111.0, 'https://www.meblepumo.pl/pl/products/stojak-na-buty-st8-53-x-26-x-65-cm-drewno-lite-naturalne-26916.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26917', 'Stojak na buty drewniany naturalny 69 cm ST9', 'Szafki na buty', 76.0, 'https://www.meblepumo.pl/pl/products/stojak-na-buty-drewniany-naturalny-69-cm-st9-26917.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26918', 'Stół rozkładany biały połysk 130 - 250 x 80 cm Stanford XL', 'Stoly/Stoły rozkładane', 2325.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-polysk-130-250-x-80-cm-stanford-xl-26918.feed10009', 'HALMAR');
