-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28562', 'Komoda z drzwiami pomarańczowa mat 200 cm Verno', 'Komody/Komody z drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-pomaranczowa-mat-200-cm-verno-28562.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28563', 'Komoda z drzwiami kaszmir mat 200 cm Verno', 'Komody/Komody z drzwiami', 1599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-200-cm-verno-28563.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28564', 'Szafka RTV granatowa mat 200 cm Verno', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-granatowa-mat-200-cm-verno-28564.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28565', 'Szafka RTV pomarańczowa mat 200 cm Verno', 'Szafki RTV', 1279.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-pomaranczowa-mat-200-cm-verno-28565.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28566', 'Szafka RTV kaszmir mat 200 cm Verno', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-200-cm-verno-28566.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28567', 'Szafka RTV granatowa mat 200 cm Verno', 'Szafki RTV', 1359.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-granatowa-mat-200-cm-verno-28567.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28568', 'Szafka RTV pomarańczowa mat 200 cm Verno', 'Szafki RTV', 1429.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-pomaranczowa-mat-200-cm-verno-28568.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28569', 'Szafka RTV kaszmir mat 200 cm Verno', 'Szafki RTV', 1359.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-200-cm-verno-28569.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28570', 'Stolik kawowy szklany szary / dąb olejowany 70 x 70 cm Quadro', 'Stoliki kawowe i ławy/Stoliki kawowe', 1459.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-szary-dab-olejowany-70-x-70-cm-quadro-28570.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28571', 'Stolik kawowy szklany szary / dąb olejowany 105 x 65 cm Selvo', 'Stoliki kawowe i ławy/Stoliki kawowe', 1599.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-szary-dab-olejowany-105-x-65-cm-selvo-28571.feed10009', 'Fato Luxmeble');
