-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26521', 'Fotel młodzieżowy Kitty 2 biały, różowy z regulacją wysokości', 'Fotele/Fotele młodzieżowe', 369.0, 'https://www.meblepumo.pl/pl/products/fotel-mlodziezowy-kitty-2-bialy-rozowy-z-regulacja-wysokosci-26521.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26526', 'Konsola szklana srebrna 120 cm KN5', 'Toaletki i konsole/Konsole ', 999.0, 'https://www.meblepumo.pl/pl/products/konsola-szklana-srebrna-120-cm-kn5-26526.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26528', 'Stół do jadalni czarny marmur / złoty mat / połysk 160 x 90 cm Konami', 'Stoly/Stoły nierozkładane', 1569.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-czarny-marmur-zloty-mat-polysk-160-x-90-cm-konami-26528.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26529', 'Kółko kauczukowe do krzesła biurowego czarne', 'Dodatki do mebli/Części do mebli', 5.0, 'https://www.meblepumo.pl/pl/products/kolko-kauczukowe-do-krzesla-biurowego-czarne-26529.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26535', 'LANCE zestaw: stół + 2 krzesła, biały', 'Zestawy mebli/Zestawy mebli do jadalni', 379.0, 'https://www.meblepumo.pl/pl/products/lance-zestaw-stol-2-krzesla-bialy-26535.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26537', 'LANCE zestaw stół + 2 krzesła wenge', 'Zestawy mebli/Zestawy mebli do jadalni', 379.0, 'https://www.meblepumo.pl/pl/products/lance-zestaw-stol-2-krzesla-wenge-26537.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26538', 'Stolik kawowy okrągły naturalny / czarny mat 50 cm Lanipa', 'Stoliki kawowe i ławy/Stoliki kawowe', 369.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-naturalny-czarny-mat-50-cm-lanipa-26538.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26542', 'Stolik kawowy prostokątny dąb złoty / czarny mat 110 x 60 cm Lavida', 'Stoliki kawowe i ławy/Stoliki kawowe', 569.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-dab-zloty-czarny-mat-110-x-60-cm-lavida-26542.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26544', 'Łóżko tapicerowane szare 160x200 cm Levanter', 'Łóżka i części/Łóżka', 1939.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-160x200-cm-levanter-26544.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26545', 'Szafka nocna tapicerowana szara 40 cm Levanter', 'Szafki nocne', 519.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-tapicerowana-szara-40-cm-levanter-26545.feed10009', 'HALMAR');
