-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25725', 'Stół rozkładany dąb naturalny / czarny mat 160 - 220 x 90 cm Bacardi', 'Stoly/Stoły rozkładane', 1839.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-czarny-mat-160-220-x-90-cm-bacardi-25725.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25726', 'Fotel biurowy ekoskóra czarny / czerwony Baffin', 'Fotele/Fotele do biurka', 524.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-czarny-czerwony-baffin-25726.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25728', 'Stół okrągły szary / czarny mat 100 cm Balrog', 'Stoly/Stoły nierozkładane', 575.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-szary-czarny-mat-100-cm-balrog-25728.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25735', 'Fotel rozkładany tapicerowany niebieski Bard', 'Fotele/Fotele rozkładane', 1309.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-tapicerowany-niebieski-bard-25735.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25736', 'Fotel rozkładany tapicerowany szary Bard', 'Fotele/Fotele rozkładane', 1309.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-tapicerowany-szary-bard-25736.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25744', 'Fotel wypoczynkowy velvet zielony  Belton', 'Fotele/Fotele wypoczynkowe', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-zielony-belton-25744.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25745', 'Fotel wypoczynkowy velvet szary Belton', 'Fotele/Fotele wypoczynkowe', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-szary-belton-25745.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25746', 'Fotel wypoczynkowy velvet żółty Belton', 'Fotele/Fotele wypoczynkowe', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-zolty-belton-25746.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25747', 'Fotel bujany tapicerowany czarny Ben', 'Fotele/Fotele bujane', 399.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-tapicerowany-czarny-ben-25747.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25748', 'Fotel bujany rattanowy brązowy Ben', 'Fotele/Fotele bujane', 409.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-rattanowy-brazowy-ben-25748.feed10009', 'HALMAR');
