-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25112', 'Stolik kawowy okrągły naturalny / czarny mat 42 cm Bonobo', 'Stoliki kawowe i ławy/Stoliki kawowe', 89.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-naturalny-czarny-mat-42-cm-bonobo-25112.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25113', 'Stolik kawowy okrągły naturalny / biały mat 42 cm Bonobo', 'Stoliki kawowe i ławy/Stoliki kawowe', 89.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-naturalny-bialy-mat-42-cm-bonobo-25113.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25114', 'Komoda z drzwiami czarna mat 206 cm Brassy', 'Komody/Komody z drzwiami', 1619.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-206-cm-brassy-25114.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25115', 'Szafka RTV z frezowanym frontem czarna mat 190 cm Cave', 'Szafki RTV', 1089.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-frezowanym-frontem-czarna-mat-190-cm-cave-25115.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25116', 'Komoda z drzwiami czarna mat 190 cm Cave', 'Komody/Komody z drzwiami', 1339.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-190-cm-cave-25116.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25117', 'Komoda z drzwiami czarna mat 150 cm Nero', 'Komody/Komody z drzwiami', 899.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-150-cm-nero-25117.feed10009', 'f o r m y');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25118', 'Komoda z drzwiami czarna mat 200 cm Nero', 'Komody/Komody z drzwiami', 1199.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-nero-25118.feed10009', 'f o r m y');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25119', 'Szafka RTV czarna mat 200 cm Nero', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-nero-25119.feed10009', 'f o r m y');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25122', 'Komoda z drzwiami czarna mat 150 cm Adoro', 'Komody/Komody z drzwiami', 699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-150-cm-adoro-25122.feed10009', 'f o r m y');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25123', 'Komoda z drzwiami czarna mat 152 cm Cave', 'Komody/Komody z drzwiami', 1269.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-152-cm-cave-25123.feed10009', 'High Glossy Furniture');
