-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26153', 'Krzesło do jadalni tapicerowane szare K202', 'Krzesła/Krzesła do jadalni', 129.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k202-26153.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26155', 'Krzesło do jadalni ekoskóra beżowe K209', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-bezowe-k209-26155.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26156', 'Krzesło do jadalni ekoskóra białe K209', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-biale-k209-26156.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26157', 'Krzesło do jadalni ekoskóra czarne K209', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-czarne-k209-26157.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26158', 'Krzesło do jadalni ekoskóra szare K209', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-szare-k209-26158.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26160', 'Krzesło na płozie ekoskóra beżowe K211', 'Krzesła/Krzesła na płozie', 229.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-bezowe-k211-26160.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26161', 'Krzesło na płozie ekoskóra białe K211', 'Krzesła/Krzesła na płozie', 229.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-biale-k211-26161.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26162', 'Krzesło na płozie ekoskóra czarne K211', 'Krzesła/Krzesła na płozie', 229.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-czarne-k211-26162.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26163', 'Krzesło na płozie ekoskóra szare K211', 'Krzesła/Krzesła na płozie', 229.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-szare-k211-26163.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26179', 'Krzesło tapicerowane K237 ekoskóra brązowa, nóżki czarne', 'Krzesła/Krzesła do jadalni', 419.0, 'https://www.meblepumo.pl/pl/products/krzeslo-tapicerowane-k237-ekoskora-brazowa-nozki-czarne-26179.feed10009', 'HALMAR');
