-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25236', 'Fotel gabinetowy ekoskóra szary / czarny Gandalf', 'Fotele/Fotele do biurka', 699.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-szary-czarny-gandalf-25236.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25237', 'Zestaw 2 stolików kawowych okrągłych dąb złoty / czarny mat 70 cm, 50 cm Garmina', 'Stoliki kawowe i ławy/Stoliki kawowe', 599.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-dab-zloty-czarny-mat-70-cm-50-cm-garmina-25237.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25240', 'Fotel obrotowy młodzieżowy ekoskóra różowy Gasly', 'Fotele/Fotele młodzieżowe', 319.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-ekoskora-rozowy-gasly-25240.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25241', 'Fotel bujany tapicerowany szary / czarny Gatto', 'Fotele/Fotele bujane', 629.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-tapicerowany-szary-czarny-gatto-25241.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25243', 'Stolik kawowy okrągły biały marmur / orzech mat 50 cm Genesis S', 'Stoliki kawowe i ławy/Stoliki kawowe', 589.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bialy-marmur-orzech-mat-50-cm-genesis-s-25243.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25244', 'Stolik kawowy okrągły biały marmur / orzech mat 70 cm Genesis', 'Stoliki kawowe i ławy/Stoliki kawowe', 869.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bialy-marmur-orzech-mat-70-cm-genesis-25244.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25246', 'Fotel gabinetowy siatka czarny Gilberto', 'Fotele/Fotele do biurka', 999.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-siatka-czarny-gilberto-25246.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25247', 'Stół okrągły czarny mat 120 cm Ginter', 'Stoly/Stoły nierozkładane', 1149.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-czarny-mat-120-cm-ginter-25247.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25249', 'Fotel gabinetowy siatka czarny Goliat', 'Fotele/Fotele do biurka', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-siatka-czarny-goliat-25249.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25251', 'Fotel gabinetowy siatka czarny Gotard', 'Fotele/Fotele do biurka', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-siatka-czarny-gotard-25251.feed10009', 'HALMAR');
