-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27040', 'Wieszak drewniany stojący czarny mat 185 cm W13', 'Wieszaki na ubrania/Wieszaki stojące', 199.0, 'https://www.meblepumo.pl/pl/products/wieszak-drewniany-stojacy-czarny-mat-185-cm-w13-27040.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27043', 'Wieszak drewniany stojący biały mat 188 cm W30', 'Wieszaki na ubrania/Wieszaki stojące', 196.0, 'https://www.meblepumo.pl/pl/products/wieszak-drewniany-stojacy-bialy-mat-188-cm-w30-27043.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27046', 'Wieszak drewniany stojący wenge mat 188 cm W30', 'Wieszaki na ubrania/Wieszaki stojące', 196.0, 'https://www.meblepumo.pl/pl/products/wieszak-drewniany-stojacy-wenge-mat-188-cm-w30-27046.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27050', 'Wieszak stojący czarny mat 180 cm W35', 'Wieszaki na ubrania/Wieszaki stojące', 265.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-czarny-mat-180-cm-w35-27050.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27054', 'Wieszak stojący biały mat 179 cm W50', 'Wieszaki na ubrania/Wieszaki stojące', 349.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-bialy-mat-179-cm-w50-27054.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27055', 'Wieszak stojący czarny mat 179 cm W50', 'Wieszaki na ubrania/Wieszaki stojące', 349.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-czarny-mat-179-cm-w50-27055.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27060', 'Wieszak stojący nikiel mat 170 cm W60', 'Wieszaki na ubrania/Wieszaki stojące', 243.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-nikiel-mat-170-cm-w60-27060.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27062', 'Wieszak stojący naturalny mat 177 cm W63', 'Wieszaki na ubrania/Wieszaki stojące', 209.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-naturalny-mat-177-cm-w63-27062.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27079', 'Stolik kawowy okrągły naturalny mat 80 cm Woody', 'Stoliki kawowe i ławy/Stoliki kawowe', 919.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-naturalny-mat-80-cm-woody-27079.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27080', 'Stolik kawowy okrągły naturalny mat 40 cm Woody-S', 'Stoliki kawowe i ławy/Stoliki kawowe', 559.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-naturalny-mat-40-cm-woody-s-27080.feed10009', 'HALMAR');
