-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18310', 'Zestaw szuflad pod łóżko czarny 94x66x17 cm Naia', 'Łóżka i części/Części do łóżek', 349.0, 'https://www.meblepumo.pl/pl/products/zestaw-szuflad-pod-lozko-czarny-94x66x17-cm-naia-18310.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18311', 'Zestaw szuflad pod łóżko czarny 99x67x18 cm Naia', 'Łóżka i części/Części do łóżek', 369.0, 'https://www.meblepumo.pl/pl/products/zestaw-szuflad-pod-lozko-czarny-99x67x18-cm-naia-18311.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18313', 'Zagłówek do łóżka czarny 160x200 cm Naia', 'Łóżka i części/Części do łóżek', 679.0, 'https://www.meblepumo.pl/pl/products/zaglowek-do-lozka-czarny-160x200-cm-naia-18313.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18317', 'Łóżko dwuosobowe czarne 140x90 cm Naia', 'Łóżka i części/Łóżka', 929.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-czarne-140x90-cm-naia-18317.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18318', 'Łóżko dwuosobowe czarne 160x200 cm Naia', 'Łóżka i części/Łóżka', 1129.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-czarne-160x200-cm-naia-18318.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18406', 'Sofa 2-osobowa z funkcją spania tapicerowana czerwona Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-czerwona-derry-18406.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18408', 'Sofa 2-osobowa z funkcją spania tapicerowana jasnozielona Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-jasnozielona-derry-18408.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18414', 'Sofa 2-osobowa z funkcją spania tapicerowana beżowa Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-bezowa-derry-18414.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18416', 'Sofa 2-osobowa z funkcją spania tapicerowana czarna Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-czarna-derry-18416.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18424', 'Sofa 2-osobowa z funkcją spania tapicerowana ciemnobrązowa Derry', 'Sofy i narożniki/Sofy 2-osobowe', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-ciemnobrazowa-derry-18424.feed10009', 'Meble tapicerowane');
