-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23275', 'Witryna dwudrzwiowa biała połysk 121 x 166 cm Solo', 'Witryny i kredensy/Witryny', 1959.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-biala-polysk-121-x-166-cm-solo-23275.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23276', 'Witryna dwudrzwiowa antracyt połysk 121 x 166 cm Solo', 'Witryny i kredensy/Witryny', 2119.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-antracyt-polysk-121-x-166-cm-solo-23276.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23277', 'Szafka RTV biała połysk 181 cm Solo', 'Szafki RTV', 1229.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-181-cm-solo-23277.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23278', 'Szafka RTV antracyt połysk 181 cm Solo', 'Szafki RTV', 1309.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-antracyt-polysk-181-cm-solo-23278.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23280', 'Szafka RTV antracyt połysk 121 cm Solo', 'Pozostałe produkty', 969.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-antracyt-polysk-121-cm-solo-23280.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23281', 'Stolik kawowy prostokątny antracyt połysk 122 x 65 cm Solo', 'Stoliki kawowe i ławy/Stoliki kawowe', 769.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-antracyt-polysk-122-x-65-cm-solo-23281.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23302', 'Oświetlenie punktowe 3 szt białe zimne', 'Dodatki do mebli/Oświetlenie LED', 109.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-punktowe-3-szt-biale-zimne-23302.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23323', 'Stół rozkładany ciemny orzech mat 137 - 185 x 90 cm Fondi', 'Stoly/Stoły rozkładane', 626.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-ciemny-orzech-mat-137-185-x-90-cm-fondi-23323.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23376', 'Biurko z szufladą i drzwiami czarne mat 110 cm Function Plus', 'Pozostałe produkty', 649.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-i-drzwiami-czarne-mat-110-cm-function-plus-23376.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23378', 'Biurko z szufladą czarne / dąb sonoma mat 130 cm Function Plus', 'Biurka/Biurka z szufladami i drzwiami', 300.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-czarne-dab-sonoma-mat-130-cm-function-plus-23378.feed10009', 'Tvilum');
