-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26396', 'Krzesło do jadalni tapicerowane  szare K432', 'Krzesła/Krzesła do jadalni', 314.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k432-26396.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26400', 'Krzesło do jadalni tapicerowane  zielone K436', 'Krzesła/Krzesła do jadalni', 469.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k436-26400.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26402', 'Krzesło do jadalni tapicerowane  szare K436', 'Krzesła/Krzesła do jadalni', 469.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k436-26402.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26403', 'Krzesło do jadalni tapicerowane  zielone K437', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k437-26403.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26405', 'Krzesło do jadalni tapicerowane  zielone K438', 'Krzesła/Krzesła do jadalni', 199.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k438-26405.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26408', 'Krzesło do jadalni tapicerowane  szare K438', 'Krzesła/Krzesła do jadalni', 199.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k438-26408.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26414', 'Krzesło na płozie tapicerowane zielone K442', 'Krzesła/Krzesła na płozie', 439.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-zielone-k442-26414.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26416', 'Krzesło na płozie tapicerowane musztardowe K442', 'Krzesła/Krzesła na płozie', 439.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-musztardowe-k442-26416.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26417', 'Krzesło na płozie tapicerowane szare K442', 'Krzesła/Krzesła na płozie', 439.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-szare-k442-26417.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26418', 'Krzesło do jadalni tapicerowane zielone K443', 'Krzesła/Krzesła do jadalni', 328.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k443-26418.feed10009', 'HALMAR');
