-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28613', 'Witryna jednodrzwiowa z szufladami dąb cremona mat 60 x 185 cm Linoa', 'Witryny i kredensy/Witryny', 1599.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-dab-cremona-mat-60-x-185-cm-linoa-28613.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28614', 'Biurko z regałemi białe / dąb Cadiz wysoki połysk / mat 138 cm Verden', 'Biurka/Biurka z szufladami i drzwiami', 869.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regalemi-biale-dab-cadiz-wysoki-polysk-mat-138-cm-verden-28614.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28615', 'Regał biurowy z drzwiami biały / dąb Cadiz wysoki połysk / mat 50 x 33 x 189 cm Verden', 'Regały', 999.0, 'https://www.meblepumo.pl/pl/products/regal-biurowy-z-drzwiami-bialy-dab-cadiz-wysoki-polysk-mat-50-x-33-x-189-cm-verden-28615.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28616', 'Stolik kawowy okrągły zielony połysk 50 cm Loca', 'Stoliki kawowe i ławy/Stoliki kawowe', 335.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-zielony-polysk-50-cm-loca-28616.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28617', 'Stolik kawowy okrągły musztardowy połysk 50 cm Loca', 'Stoliki kawowe i ławy/Stoliki kawowe', 335.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-musztardowy-polysk-50-cm-loca-28617.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28619', 'Stolik kawowy okrągły musztardowy połysk 80 cm Soraya', 'Stoliki kawowe i ławy/Stoliki kawowe', 669.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-musztardowy-polysk-80-cm-soraya-28619.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28621', 'Stolik kawowy okrągły trawertyn / orzech mat 50 cm Dorotea S', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-trawertyn-orzech-mat-50-cm-dorotea-s-28621.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28622', 'Stolik kawowy okrągły beżowy / orzech mat 80 cm Carina', 'Stoliki kawowe i ławy/Stoliki kawowe', 539.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bezowy-orzech-mat-80-cm-carina-28622.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28623', 'Stolik kawowy okrągły beżowy / orzech mat 50 cm Carina', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bezowy-orzech-mat-50-cm-carina-28623.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28625', 'Stół okrągły trawertyn / orzech mat 120 cm Pireus', 'Stoly/Stoły nierozkładane', 1599.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-trawertyn-orzech-mat-120-cm-pireus-28625.feed10009', 'HALMAR');
