-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24318', 'Komoda z szufladami dąb sonoma mat 80 cm Bali', 'Komody/Komody z szufladami', 769.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-dab-sonoma-mat-80-cm-bali-24318.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24320', 'Komoda z szufladami i drzwiami dąb sonoma mat 101 cm Bali', 'Komody/Komody z szufladami i drzwiami', 1899.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-sonoma-mat-101-cm-bali-24320.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24321', 'Komoda z drzwiami dąb sonoma mat 101 cm Bali', 'Komody/Komody z drzwiami', 1049.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-sonoma-mat-101-cm-bali-24321.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24326', 'Ławka na buty dąb 108 cm Maggie', 'Ławki do przedpokoju', 1029.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-dab-108-cm-maggie-24326.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24329', 'Lustro w ramie czarnej 30 x 125 cm Maggie', 'Lustra', 255.0, 'https://www.meblepumo.pl/pl/products/lustro-w-ramie-czarnej-30-x-125-cm-maggie-24329.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24348', 'Szafka RTV biała połysk 180 cm Move', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-180-cm-move-24348.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24349', 'Szafka RTV czarna połysk 180 cm Move', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-polysk-180-cm-move-24349.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24350', 'Szafka RTV grafitowa połysk 180 cm Move', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-grafitowa-polysk-180-cm-move-24350.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24352', 'Komoda z szufladami i drzwiami dąb / antracyt mat 184 cm Caro', 'Komody/Komody z szufladami i drzwiami', 1309.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-antracyt-mat-184-cm-caro-24352.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24353', 'Regał do salonu dąb / antracyt mat 50 x 40 x 165 cm Caro', 'Regały', 746.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-dab-antracyt-mat-50-x-40-x-165-cm-caro-24353.feed10009', 'Fato Luxmeble');
