-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24222', 'Szafka nocna czarna / orzech mat 43 cm Ryan', 'Szafki nocne', 779.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-czarna-orzech-mat-43-cm-ryan-24222.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24223', 'Szafka nocna biała mat 43 cm Ryan', 'Szafki nocne', 679.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-mat-43-cm-ryan-24223.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24224', 'Szafa trzydrzwiowa z szufladami czarna / orzech mat 150 x 200 cm Ryan', 'Szafy/Szafy uchylne', 3099.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-z-szufladami-czarna-orzech-mat-150-x-200-cm-ryan-24224.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24227', 'Komoda z szufladami orzech / czarna mat 102 cm Ryan', 'Komody/Komody z szufladami', 1359.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-orzech-czarna-mat-102-cm-ryan-24227.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24229', 'Komoda z szufladami orzech / czarna mat 150 cm Ryan', 'Komody/Komody z szufladami', 1799.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-orzech-czarna-mat-150-cm-ryan-24229.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24230', 'Komoda z szufladami czarna mat 159 cm Madrid', 'Komody/Komody z szufladami', 1299.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-mat-159-cm-madrid-24230.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24231', 'Komoda wysoka z szufladami czarna mat 82 cm Madrid', 'Komody/Komody z szufladami', 899.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-czarna-mat-82-cm-madrid-24231.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24232', 'Szafka nocna czarna mat 44 cm Madrid', 'Szafki nocne', 379.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-czarna-mat-44-cm-madrid-24232.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24233', 'Szafa trzydrzwiowa czarna mat 150 x 199 cm Madrid', 'Szafy/Szafy uchylne', 1849.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-czarna-mat-150-x-199-cm-madrid-24233.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24234', 'Szafa dwudrzwiowa czarna mat 102 x 199 cm Madrid', 'Szafy/Szafy uchylne', 1549.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-czarna-mat-102-x-199-cm-madrid-24234.feed10009', 'Tvilum');
