-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16837', 'Szafka RTV biała / dąb sonoma mat 140 cm Livorno', 'Szafki RTV', 669.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-sonoma-mat-140-cm-livorno-16837.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16838', 'Szafka RTV biała / dąb sonoma mat 160 cm Livorno', 'Szafki RTV', 549.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-sonoma-mat-160-cm-livorno-16838.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16840', 'Szafka RTV biała / dąb sonoma mat 180 cm Livorno', 'Szafki RTV', 869.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-sonoma-mat-180-cm-livorno-16840.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16842', 'Komoda z drzwiami biała / dąb sonoma mat 150 cm Livorno', 'Komody/Komody z drzwiami', 545.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-dab-sonoma-mat-150-cm-livorno-16842.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16848', 'Komplet nóg do biurka biały mat 5 cm Prima', 'Biurka/Części do biurek', 249.0, 'https://www.meblepumo.pl/pl/products/komplet-nog-do-biurka-bialy-mat-5-cm-prima-16848.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16935', 'Zestaw szuflad pod łóżko biały 99x67x18 cm Naia', 'Łóżka i części/Części do łóżek', 349.0, 'https://www.meblepumo.pl/pl/products/zestaw-szuflad-pod-lozko-bialy-99x67x18-cm-naia-16935.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16939', 'Zagłówek do łóżka biały 140x190 cm Naia', 'Łóżka i części/Części do łóżek', 789.0, 'https://www.meblepumo.pl/pl/products/zaglowek-do-lozka-bialy-140x190-cm-naia-16939.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16950', 'Sofa 3-osobowa tapicerowana grafitowa Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-grafitowa-lily-16950.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16953', 'Sofa 3-osobowa tapicerowana granatowa Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-granatowa-lily-16953.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16954', 'Sofa 3-osobowa tapicerowana czerwona Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-czerwona-lily-16954.feed10009', 'Scandinavian Style Design');
