-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28299', 'Komoda z szufladami i drzwiami kaszmir mat 151 cm Madrid', 'Komody/Komody z szufladami i drzwiami', 1179.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-mat-151-cm-madrid-28299.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28300', 'Komoda z szufladami kaszmir mat 159 cm Madrid', 'Komody/Komody z szufladami', 1479.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-kaszmir-mat-159-cm-madrid-28300.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28301', 'Komoda wysoka z szufladami kaszmir mat 82 cm Madrid', 'Komody/Komody z szufladami', 1029.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-kaszmir-mat-82-cm-madrid-28301.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28302', 'Komoda z szufladami kaszmir mat 82 cm Madrid', 'Komody/Komody z szufladami', 759.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-kaszmir-mat-82-cm-madrid-28302.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28303', 'Szafka nocna jackson kaszmir mat 44 cm Madrid', 'Szafki nocne', 559.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-jackson-kaszmir-mat-44-cm-madrid-28303.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28304', 'Szafka nocna kaszmir mat 44 cm Madrid', 'Szafki nocne', 439.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-kaszmir-mat-44-cm-madrid-28304.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28305', 'Regał do salonu kaszmir mat 100 x 40 x 170 cm Ardea', 'Regały', 1049.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-kaszmir-mat-100-x-40-x-170-cm-ardea-28305.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28306', 'Regał do salonu czarny mat 100 x 40 x 170 cm Ardea', 'Regały', 1049.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-czarny-mat-100-x-40-x-170-cm-ardea-28306.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28308', 'Regał do salonu biały mat 100 x 40 x 170 cm Ardea', 'Regały', 999.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-bialy-mat-100-x-40-x-170-cm-ardea-28308.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28309', 'Komoda z drzwiami kaszmir mat 200 cm Ardea', 'Komody/Komody z drzwiami', 1179.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-200-cm-ardea-28309.feed10009', 'High Glossy Furniture');
