-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19454', 'Krzesło biurowe ekoskóra czarne Prestige Skid', 'Krzesła/Krzesła biurowe', 439.0, 'https://www.meblepumo.pl/pl/products/krzeslo-biurowe-ekoskora-czarne-prestige-skid-19454.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19527', 'Lustro do przedpokoju białe 90 x 68 cm Ramona', 'Lustra', 359.0, 'https://www.meblepumo.pl/pl/products/lustro-do-przedpokoju-biale-90-x-68-cm-ramona-19527.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19529', 'Ławka na buty z szufladami biała / dąb 91 cm Ramona', 'Ławki do przedpokoju', 999.0, 'https://www.meblepumo.pl/pl/products/lawka-na-buty-z-szufladami-biala-dab-91-cm-ramona-19529.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19530', 'Szafa dwudrzwiowa z szufladami biała / dąb mat 91 x 198 cm Ramona', 'Szafy/Szafy uchylne', 2479.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-z-szufladami-biala-dab-mat-91-x-198-cm-ramona-19530.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19697', 'Biurko z szufladami dąb sękaty olejowany mat 120 cm Dalia', 'Biurka/Biurka z szufladami i drzwiami', 1249.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-sekaty-olejowany-mat-120-cm-dalia-19697.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19699', 'Biurko proste dąb sękaty mat 140 cm Penno', 'Biurka/Biurka proste', 1082.0, 'https://www.meblepumo.pl/pl/products/biurko-proste-dab-sekaty-mat-140-cm-penno-19699.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19701', 'Biurko z szufladami białe mat 150 cm Kelly', 'Biurka/Biurka z szufladami i drzwiami', 1239.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-biale-mat-150-cm-kelly-19701.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19702', 'Biurko z szufladami dąb sękaty mat 150 cm Kelly', 'Biurka/Biurka z szufladami i drzwiami', 1599.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-sekaty-mat-150-cm-kelly-19702.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19715', 'Fotel obrotowy młodzieżowy tapicerowany ekoskóra czarny / turkusowy Matrix', 'Fotele/Fotele młodzieżowe', 299.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-tapicerowany-ekoskora-czarny-turkusowy-matrix-19715.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19730', 'Biurko z szufladami dąb sonoma mat 120 cm B33', 'Biurka/Biurka z szufladami i drzwiami', 815.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-sonoma-mat-120-cm-b33-19730.feed10009', 'HALMAR');
