-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28603', 'Komoda z drzwiami dąb cremona mat 200 cm Linoa', 'Komody/Komody z drzwiami', 1379.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-cremona-mat-200-cm-linoa-28603.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28604', 'Komoda z drzwiami kaszmir mat 150 cm Linoa', 'Komody/Komody z drzwiami', 1119.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-150-cm-linoa-28604.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28605', 'Komoda z drzwiami dąb cremona mat 150 cm Linoa', 'Komody/Komody z drzwiami', 1119.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-cremona-mat-150-cm-linoa-28605.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28606', 'Komoda z szufladami i drzwiami kaszmir mat 100 cm Linoa', 'Komody/Komody z szufladami i drzwiami', 1059.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-mat-100-cm-linoa-28606.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28607', 'Komoda z szufladami i drzwiami dąb cremona mat 100 cm Linoa', 'Komody/Komody z szufladami i drzwiami', 1059.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-cremona-mat-100-cm-linoa-28607.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28608', 'Szafka RTV kaszmir mat 200 cm Linoa', 'Szafki RTV', 1159.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-200-cm-linoa-28608.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28609', 'Szafka RTV dąb cremona mat 200 cm Linoa', 'Szafki RTV', 1159.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-cremona-mat-200-cm-linoa-28609.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28610', 'Szafka RTV kaszmir mat 180 cm Linoa', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-180-cm-linoa-28610.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28611', 'Szafka RTV dąb cremona mat 180 cm Linoa', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-cremona-mat-180-cm-linoa-28611.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28612', 'Witryna jednodrzwiowa z szufladami kaszmir mat 60 x 185 cm Linoa', 'Witryny i kredensy/Witryny', 1599.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-kaszmir-mat-60-x-185-cm-linoa-28612.feed10009', 'High Glossy Furniture');
