-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15956', 'Komoda wysoka z szufladami biała wysoki połysk 40 cm Naia', 'Komody/Komody z szufladami', 769.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-szufladami-biala-wysoki-polysk-40-cm-naia-15956.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15957', 'Komoda z szufladami biała wysoki połysk 154 cm Naia', 'Komody/Komody z szufladami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-wysoki-polysk-154-cm-naia-15957.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15958', 'Komoda z szufladami biała wysoki połysk 77 cm Naia', 'Komody/Komody z szufladami', 599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-wysoki-polysk-77-cm-naia-15958.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15959', 'Komoda z szufladami biała wysoki połysk 40 cm Naia', 'Komody/Komody z szufladami', 429.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-wysoki-polysk-40-cm-naia-15959.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15960', 'Komoda z szufladą i drzwiami biała wysoki połysk 80 cm Naia', 'Komody/Komody z szufladami i drzwiami', 699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szuflada-i-drzwiami-biala-wysoki-polysk-80-cm-naia-15960.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15961', 'Komoda z szufladami i drzwiami biała wysoki połysk 121 cm Naia', 'Komody/Komody z szufladami i drzwiami', 1139.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-121-cm-naia-15961.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15962', 'Szafka nocna z szufladami biała wysoki połysk 40 cm Naia', 'Szafki nocne', 349.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-z-szufladami-biala-wysoki-polysk-40-cm-naia-15962.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15963', 'Szafka nocna biała wysoki połysk 40 cm Naia', 'Szafki nocne', 269.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-wysoki-polysk-40-cm-naia-15963.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15964', 'Zagłówek do łóżka biały 160x200 cm Naia', 'Łóżka i części/Części do łóżek', 819.0, 'https://www.meblepumo.pl/pl/products/zaglowek-do-lozka-bialy-160x200-cm-naia-15964.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15991', 'Łóżko dwuosobowe białe 160x200 cm Naia', 'Łóżka i części/Łóżka', 1139.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-biale-160x200-cm-naia-15991.feed10009', 'Tvilum');
