-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18706', 'Stolik kawowy prostokątny dąb sonoma / biały mat / połysk 120 x 60 cm Tucson', 'Pozostałe produkty', 459.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-dab-sonoma-bialy-mat-polysk-120-x-60-cm-tucson-18706.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18768', 'Stelaż do łóżka 80x200 cm Natura Slim', 'Łóżka i części/Stelaże do łóżek', 150.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-80x200-cm-natura-slim-18768.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18818', 'Fotel kubełkowy tapicerowany szary Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-szary-tana-18818.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18819', 'Fotel kubełkowy tapicerowany beżowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-bezowy-tana-18819.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18820', 'Fotel kubełkowy tapicerowany ciemnozielony Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-ciemnozielony-tana-18820.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18823', 'Fotel kubełkowy tapicerowany zielony Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-zielony-tana-18823.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18824', 'Komoda z drzwiami szara mat / wysoki połysk 120 cm Simple', 'Komody/Komody z drzwiami', 749.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-szara-mat-wysoki-polysk-120-cm-simple-18824.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18825', 'Komoda z szufladami i drzwiami szara mat / wysoki połysk 132 cm Simple', 'Komody/Komody z szufladami i drzwiami', 1039.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-szara-mat-wysoki-polysk-132-cm-simple-18825.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18827', 'Fotel kubełkowy tapicerowany różowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-rozowy-tana-18827.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('18834', 'Szafka RTV szara mat / połysk 180 cm Simple', 'Pozostałe produkty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-szara-mat-polysk-180-cm-simple-18834.feed10009', 'High Glossy Furniture');
