-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27606', 'Stół rozkładany biały mat 140 - 220 x 80 cm Tiago 2', 'Stoly/Stoły rozkładane', 1189.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-140-220-x-80-cm-tiago-2-27606.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27609', 'Stół rozkładany dąb craft / czarny mat 140 - 220 x 80 cm Tiago', 'Stoly/Stoły rozkładane', 1259.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-craft-czarny-mat-140-220-x-80-cm-tiago-27609.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27610', 'Stół rozkładany dąb lancelot / biały mat 140 - 220 x 80 cm Tiago', 'Stoly/Stoły rozkładane', 1259.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-lancelot-bialy-mat-140-220-x-80-cm-tiago-27610.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27617', 'Stół rozkładany dąb wotan / czarny mat 135 - 185 x 85 cm Venom', 'Stoly/Stoły rozkładane', 1549.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-wotan-czarny-mat-135-185-x-85-cm-venom-27617.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27628', 'Stół rozkładany jasny dąb / czarny mat 160 - 250 x 90 cm Xavier', 'Stoly/Stoły rozkładane', 2749.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-jasny-dab-czarny-mat-160-250-x-90-cm-xavier-27628.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27635', 'Zestaw mebli kuchennych dąb sonoma / biały 240 cm Daria', 'Zestawy mebli/Zestawy mebli kuchennych', 1279.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-dab-sonoma-bialy-240-cm-daria-27635.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27636', 'Zestaw mebli kuchennych biały / dąb sonoma 240 cm Elizabeth', 'Zestawy mebli/Zestawy mebli kuchennych', 2199.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-bialy-dab-sonoma-240-cm-elizabeth-27636.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27642', 'Zestaw mebli kuchennych antracyt / dąb craft 180 cm Idea', 'Zestawy mebli/Zestawy mebli kuchennych', 2059.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-antracyt-dab-craft-180-cm-idea-27642.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27643', 'Zestaw mebli kuchennych biały / beżowy / dąb san marino 220 cm Katia', 'Zestawy mebli/Zestawy mebli kuchennych', 1269.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-bialy-bezowy-dab-san-marino-220-cm-katia-27643.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27644', 'Zestaw mebli kuchennych biały / dąb sonoma 200 cm Marija', 'Zestawy mebli/Zestawy mebli kuchennych', 1259.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-bialy-dab-sonoma-200-cm-marija-27644.feed10009', 'HALMAR');
