-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25635', 'Fotel biurowy z podnóżkiem ekoskóra czarny Alvin', 'Fotele/Fotele do biurka', 689.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-z-podnozkiem-ekoskora-czarny-alvin-25635.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25637', 'Fotel biurowy siatka czarny Ambasador', 'Fotele/Fotele do biurka', 1119.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-czarny-ambasador-25637.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25644', 'Sofa dwuosobowa tapicerowana różowa Amorinito XL', 'Sofy i narożniki/Sofy 2-osobowe', 1169.0, 'https://www.meblepumo.pl/pl/products/sofa-dwuosobowa-tapicerowana-rozowa-amorinito-xl-25644.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25646', 'Fotel wypoczynkowy tapicerowany zielony Amorinito', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-amorinito-25646.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25648', 'Fotel wypoczynkowy tapicerowany różowy Amorinito', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-rozowy-amorinito-25648.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25649', 'Fotel wypoczynkowy tapicerowany szary Amorinito', 'Fotele/Fotele wypoczynkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-amorinito-25649.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25650', 'Komplet nóżek metalowych czarnych Amorinito', 'Fotele/Fotele wypoczynkowe', 73.0, 'https://www.meblepumo.pl/pl/products/komplet-nozek-metalowych-czarnych-amorinito-25650.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25656', 'Fotel biurowy siatka czarny Andy', 'Fotele/Fotele do biurka', 376.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-czarny-andy-25656.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25659', 'Fotel biurowy siatka różowy / szary Andy', 'Fotele/Fotele do biurka', 376.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-rozowy-szary-andy-25659.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25660', 'Fotel wypoczynkowy velvet zielony Angelo', 'Fotele/Fotele wypoczynkowe', 814.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-zielony-angelo-25660.feed10009', 'HALMAR');
