-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20258', 'Fotel wypoczynkowy tapicerowany grafitowy Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-grafitowy-vabi-20258.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20259', 'Fotel wypoczynkowy tapicerowany beżowy Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-bezowy-vabi-20259.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20260', 'Fotel wypoczynkowy tapicerowany brązowy Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-brazowy-vabi-20260.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20261', 'Fotel wypoczynkowy tapicerowany czerwony Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-czerwony-vabi-20261.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20262', 'Fotel wypoczynkowy tapicerowany granatowy Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-granatowy-vabi-20262.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20263', 'Fotel wypoczynkowy tapicerowany turkusowy Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-turkusowy-vabi-20263.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20264', 'Fotel wypoczynkowy tapicerowany szary Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-vabi-20264.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20265', 'Fotel wypoczynkowy tapicerowany czarny Vabi', 'Fotele/Fotele wypoczynkowe', 1799.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-czarny-vabi-20265.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20363', 'Szafka RTV wisząca biała połysk 200 cm Skid', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-biala-polysk-200-cm-skid-20363.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20429', 'Austin oświetlenie półkowe 1 szt białe', 'Dodatki do mebli/Oświetlenie LED', 39.0, 'https://www.meblepumo.pl/pl/products/austin-oswietlenie-polkowe-1-szt-biale-20429.feed10009', 'TT-furniture');
