-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24634', 'Nóżka do mebli czarna 12 cm Malia', 'Dodatki do mebli/Części do mebli', 15.0, 'https://www.meblepumo.pl/pl/products/nozka-do-mebli-czarna-12-cm-malia-24634.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24636', 'Komoda z drzwiami czarna mat 180 cm Charm', 'Pozostałe produkty', 2339.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-180-cm-charm-24636.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24638', 'Komoda z drzwiami biała / dąb mat 160 cm Menorca', 'Komody/Komody z drzwiami', 599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-dab-mat-160-cm-menorca-24638.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24648', 'Szafka RTV dąb wotan / czarna mat 150 cm Stor', 'Szafki RTV', 699.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-wotan-czarna-mat-150-cm-stor-24648.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24650', 'Półka wisząca dąb wotan / czarny mat 180 x 20 cm Stor', 'Półki wiszące', 209.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-dab-wotan-czarny-mat-180-x-20-cm-stor-24650.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24651', 'Półka wisząca dąb wotan / czarny mat 150 x 20 cm Stor', 'Półki wiszące', 199.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-dab-wotan-czarny-mat-150-x-20-cm-stor-24651.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24652', 'Stolik kawowy kwadratowy dąb wotan / czarny mat 92 x 50 cm Stor', 'Stoliki kawowe i ławy/Stoliki kawowe', 329.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-dab-wotan-czarny-mat-92-x-50-cm-stor-24652.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24657', 'Szafka RTV dąb artisan / czarna mat 150 cm Lenon', 'Szafki RTV', 959.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-artisan-czarna-mat-150-cm-lenon-24657.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24660', 'Regał do salonu dąb naturalny mat 117 x 37 x 153 cm Clever', 'Regały', 3149.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-dab-naturalny-mat-117-x-37-x-153-cm-clever-24660.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24661', 'Komoda z szufladami i drzwiami dąb naturalny 167 cm Clever', 'Komody/Komody z szufladami i drzwiami', 4739.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-naturalny-167-cm-clever-24661.feed10009', 'Style Furniture');
