-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16324', 'Fotel biurowy siatka biały Vire', 'Fotele/Fotele do biurka', 325.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-bialy-vire-16324.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16339', 'Fotel biurowy siatka szary / czarny / biały Franklin', 'Fotele/Fotele do biurka', 483.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-szary-czarny-bialy-franklin-16339.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16343', 'Fotel biurowy ekoskóra biały Aurelius', 'Fotele/Fotele do biurka', 639.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-bialy-aurelius-16343.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16347', 'Fotel biurowy tapicerowany niebieski / czarny Voyager', 'Fotele/Fotele do biurka', 509.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-niebieski-czarny-voyager-16347.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16353', 'Sofa 2-osobowa z funkcją spania tapicerowana miękka brązowa Derry', 'Pozostałe produkty', 3699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-miekka-brazowa-derry-16353.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16423', 'Sofa 2-osobowa z funkcją spania tapicerowana ciemnoszara Derry', 'Pozostałe produkty', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-ciemnoszara-derry-16423.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16431', 'Sofa tapicerowana Leya, 3 osobowa, czarna, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-czarna-nozki-wenge-16431.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16432', 'Sofa tapicerowana Leya, 3 osobowa, fioletowa, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-fioletowa-nozki-wenge-16432.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16433', 'Sofa tapicerowana Leya, 3 osobowa, zielona, nóżki wenge', 'Sofy i narożniki/Sofy 3-osobowe', 3029.0, 'https://www.meblepumo.pl/pl/products/sofa-tapicerowana-leya-3-osobowa-zielona-nozki-wenge-16433.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16476', 'Fotel wypoczynkowy welurowy beżowy Gryf', 'Fotele/Fotele wypoczynkowe', 1769.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-welurowy-bezowy-gryf-16476.feed10009', 'Scandinavian Style Design');
