-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24991', 'Fotel obrotowy młodzieżowy velvet różowy Fresco', 'Fotele/Fotele młodzieżowe', 449.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-mlodziezowy-velvet-rozowy-fresco-24991.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24997', 'Stelaż  do mebli złoty 194 x 20 cm Malia', 'Dodatki do mebli/Części do mebli', 279.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-mebli-zloty-194-x-20-cm-malia-24997.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25000', 'Stelaż  do mebli czarny 194 x 20 cm Malia', 'Dodatki do mebli/Części do mebli', 279.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-mebli-czarny-194-x-20-cm-malia-25000.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25002', 'Stelaż  do mebli złoty 144 x 20 cm Malia', 'Dodatki do mebli/Części do mebli', 269.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-mebli-zloty-144-x-20-cm-malia-25002.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25005', 'Stelaż  do mebli czarny 144 x 20 cm Malia', 'Dodatki do mebli/Części do mebli', 269.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-mebli-czarny-144-x-20-cm-malia-25005.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25016', 'Stolik kawowy z gazetnikiem biały marmur / czarny mat 115 x 58 cm Atalaya', 'Stoliki kawowe i ławy/Stoliki kawowe', 715.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-gazetnikiem-bialy-marmur-czarny-mat-115-x-58-cm-atalaya-25016.feed10009', 'Actona');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25034', 'Stolik kawowy kwadratowy dąb dziki mat 80 x 80 cm Seaford', 'Stoliki kawowe i ławy/Stoliki kawowe', 349.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-dab-dziki-mat-80-x-80-cm-seaford-25034.feed10009', 'Actona');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25035', 'Stolik kawowy z gazetnikiem dąb dziki / czarny mat 110 x 60 cm Seaford', 'Stoliki kawowe i ławy/Stoliki kawowe', 299.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-gazetnikiem-dab-dziki-czarny-mat-110-x-60-cm-seaford-25035.feed10009', 'Actona');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25043', 'Toaletka z lustrem wisząca biała mat 80 cm Malia', 'Toaletki i konsole/Toaletki', 559.0, 'https://www.meblepumo.pl/pl/products/toaletka-z-lustrem-wiszaca-biala-mat-80-cm-malia-25043.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25044', 'Toaletka z lustrem wisząca czarna mat 80 cm Malia', 'Toaletki i konsole/Toaletki', 569.0, 'https://www.meblepumo.pl/pl/products/toaletka-z-lustrem-wiszaca-czarna-mat-80-cm-malia-25044.feed10009', 'High Glossy Furniture');
