-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10430', 'Oświetlenie LED 3 punktowe czerwone, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 79.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-3-punktowe-czerwone-high-glossy-furniture-10430.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10431', 'Oświetlenie LED 3 punktowe zielone, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 79.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-3-punktowe-zielone-high-glossy-furniture-10431.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10432', 'Oświetlenie LED 3 punktowe białe, High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 79.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-3-punktowe-biale-high-glossy-furniture-10432.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10433', 'Oświetlenie 4 LED białe High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 89.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-4-led-biale-high-glossy-furniture-10433.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10434', 'Oświetlenie 4 LED zielone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 89.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-4-led-zielone-high-glossy-furniture-10434.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10435', 'Oświetlenie 4 LED czerwone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 89.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-4-led-czerwone-high-glossy-furniture-10435.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10436', 'Oświetlenie 4 LED niebieskie High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 89.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-4-led-niebieskie-high-glossy-furniture-10436.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10437', 'Oświetlenie 5 LED niebieskie High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 109.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-5-led-niebieskie-high-glossy-furniture-10437.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10438', 'Oświetlenie 5 LED czerwone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 109.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-5-led-czerwone-high-glossy-furniture-10438.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10439', 'Oświetlenie 5 LED zielone High Glossy Furniture', 'Dodatki do mebli/Oświetlenie LED', 109.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-5-led-zielone-high-glossy-furniture-10439.feed10009', 'High Glossy Furniture');
