-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25306', 'Krzesło do jadalni tapicerowane szare K489', 'Krzesła/Krzesła do jadalni', 423.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k489-25306.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25307', 'Krzesło ogrodowe plastikowe białe K490', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-biale-k490-25307.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25308', 'Krzesło ogrodowe plastikowe czarne K490', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-czarne-k490-25308.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25309', 'Krzesło ogrodowe plastikowe miętowe K490', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-mietowe-k490-25309.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25310', 'Krzesło ogrodowe plastikowe białe K491', 'Krzesła/Krzesła ogrodowe', 218.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-biale-k491-25310.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25311', 'Krzesło ogrodowe plastikowe czarne K491', 'Krzesła/Krzesła ogrodowe', 218.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-czarne-k491-25311.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25312', 'Krzesło ogrodowe plastikowe musztardowe K491', 'Krzesła/Krzesła ogrodowe', 218.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-musztardowe-k491-25312.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25313', 'Krzesło ogrodowe plastikowe białe K492', 'Krzesła/Krzesła ogrodowe', 219.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-biale-k492-25313.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25314', 'Krzesło ogrodowe plastikowe czarne K492', 'Krzesła/Krzesła ogrodowe', 219.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-czarne-k492-25314.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25315', 'Krzesło ogrodowe plastikowe szare K492', 'Krzesła/Krzesła ogrodowe', 219.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-plastikowe-szare-k492-25315.feed10009', 'HALMAR');
