-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28371', 'Komoda wysoka z drzwiami biała wysoki połysk 120 cm Sorelle', 'Komody/Komody z drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-wysoki-polysk-120-cm-sorelle-28371.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28372', 'Komoda wysoka z drzwiami dąb mercure 120 cm Sorelle', 'Komody/Komody z drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-dab-mercure-120-cm-sorelle-28372.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28373', 'Stół do jadalni dąb mercure 180 x 90 cm Sorelle', 'Stoly/Stoły nierozkładane', 1129.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-dab-mercure-180-x-90-cm-sorelle-28373.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28374', 'Stół rozkładany dąb mercure 137 - 185 x 90 cm Sorelle', 'Stoly/Stoły rozkładane', 1119.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-mercure-137-185-x-90-cm-sorelle-28374.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28375', 'Lustro w ramie dąb mercure 170 x 75 cm Sorelle', 'Lustra', 629.0, 'https://www.meblepumo.pl/pl/products/lustro-w-ramie-dab-mercure-170-x-75-cm-sorelle-28375.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28378', 'Łóżko tapicerowane szare 90x200 cm Happy', 'Łóżka i części/Łóżka', 1329.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-90x200-cm-happy-28378.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28379', 'Łóżko tapicerowane z pojemnikiem szare 160x200 cm Duo', 'Łóżka i części/Łóżka', 1799.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-pojemnikiem-szare-160x200-cm-duo-28379.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28380', 'Toaletka z lustrem biała mat 100 cm Image', 'Toaletki i konsole/Toaletki', 659.0, 'https://www.meblepumo.pl/pl/products/toaletka-z-lustrem-biala-mat-100-cm-image-28380.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28381', 'Szafka na buty granatowa mat 70 cm Vigo', 'Szafki na buty', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-granatowa-mat-70-cm-vigo-28381.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28382', 'Szafka na buty terracota mat 70 cm Vigo', 'Szafki na buty', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-terracota-mat-70-cm-vigo-28382.feed10009', 'Fontini ');
