-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19757', 'Szafka wisząca biała mat 37 cm Rock', 'Szafki modułowe', 359.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-biala-mat-37-cm-rock-19757.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19758', 'Szafka wisząca dąb wotan / antracyt mat 37 cm Rock', 'Szafki modułowe', 249.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-dab-wotan-antracyt-mat-37-cm-rock-19758.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19759', 'Szafka wisząca otwarta czarna mat 37 cm Rock', 'Szafki modułowe', 159.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-otwarta-czarna-mat-37-cm-rock-19759.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19760', 'Szafka wisząca otwarta biała mat 37 cm Rock', 'Szafki modułowe', 229.0, 'https://www.meblepumo.pl/pl/products/szafka-wiszaca-otwarta-biala-mat-37-cm-rock-19760.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19824', 'Zestaw 2 stolików kawowych drewnianych dąb sękaty mat 50 x 45 cm, 40 x 40 cm Kiley', 'Stoliki kawowe i ławy/Stoliki kawowe', 369.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-drewnianych-dab-sekaty-mat-50-x-45-cm-40-x-40-cm-kiley-19824.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19842', 'Łóżko jednoosobowe czarne 90x190 cm Naia', 'Łóżka i części/Łóżka', 619.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-czarne-90x190-cm-naia-19842.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19873', 'Komoda szeroka z drzwiami biała wysoki połysk 241 cm Vero', 'Komody/Komody z drzwiami', 1749.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-biala-wysoki-polysk-241-cm-vero-19873.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19874', 'Komoda szeroka z drzwiami dąb sonoma mat 241 cm Vero', 'Komody/Komody z drzwiami', 1669.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-dab-sonoma-mat-241-cm-vero-19874.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19875', 'Komoda szeroka z drzwiami antracyt wysoki połysk 241 cm Vero', 'Komody/Komody z drzwiami', 1899.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-antracyt-wysoki-polysk-241-cm-vero-19875.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19876', 'Komoda szeroka z drzwiami i szufladami biała wysoki połysk 241 cm Vero', 'Komody/Komody z szufladami i drzwiami', 1999.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-i-szufladami-biala-wysoki-polysk-241-cm-vero-19876.feed10009', 'Italia Trend');
