-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25139', 'Szafa jednodrzwiowa biała mat 45 x 198 cm Malia', 'Szafy/Szafy uchylne', 1199.0, 'https://www.meblepumo.pl/pl/products/szafa-jednodrzwiowa-biala-mat-45-x-198-cm-malia-25139.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25140', 'Nadstawka na szafę biała mat 45 x 45 cm Malia', 'Szafy/Nadstawki na szafę', 314.0, 'https://www.meblepumo.pl/pl/products/nadstawka-na-szafe-biala-mat-45-x-45-cm-malia-25140.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25141', 'Nadstawka na szafę czarna mat 45 x 45 cm Malia', 'Szafy/Nadstawki na szafę', 328.0, 'https://www.meblepumo.pl/pl/products/nadstawka-na-szafe-czarna-mat-45-x-45-cm-malia-25141.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25198', 'Konsola z szufladami biała / czarna mat 80 cm Agnes', 'Toaletki i konsole/Konsole ', 459.0, 'https://www.meblepumo.pl/pl/products/konsola-z-szufladami-biala-czarna-mat-80-cm-agnes-25198.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25209', 'Stół okrągły biały marmur / orzech mat 120 cm Bruno', 'Stoly/Stoły nierozkładane', 1879.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-bialy-marmur-orzech-mat-120-cm-bruno-25209.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25212', 'Stół rozkładany dąb złoty mat 180 - 240 x 90 cm Capital', 'Stoly/Stoły rozkładane', 1769.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-zloty-mat-180-240-x-90-cm-capital-25212.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25214', 'Fotel gamingowy tapicerowany czarny / czerwony Cayman', 'Fotele/Fotele do biurka', 729.0, 'https://www.meblepumo.pl/pl/products/fotel-gamingowy-tapicerowany-czarny-czerwony-cayman-25214.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25216', 'Stolik kawowy okrągły biały marmur / czarny mat 73 cm Cecilia S', 'Stoliki kawowe i ławy/Stoliki kawowe', 765.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-bialy-marmur-czarny-mat-73-cm-cecilia-s-25216.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25217', 'Fotel gabinetowy tapicerowany ekoskóra szary / czarny Chrono', 'Fotele/Fotele do biurka', 599.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-ekoskora-szary-czarny-chrono-25217.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25218', 'Stolik kawowy szklany dymiony / naturalny mat 60 x 45 cm Dakota', 'Stoliki kawowe i ławy/Stoliki kawowe', 326.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-dymiony-naturalny-mat-60-x-45-cm-dakota-25218.feed10009', 'HALMAR');
