-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28626', 'Szafa do przedpokoju biała połysk 78 x 187 cm Basic', 'Szafy/Szafy uchylne', 999.0, 'https://www.meblepumo.pl/pl/products/szafa-do-przedpokoju-biala-polysk-78-x-187-cm-basic-28626.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28627', 'Szafka na buty biała połysk 78 cm Basic', 'Szafki na buty', 849.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-biala-polysk-78-cm-basic-28627.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28628', 'Szafka na buty z siedziskiem biała 91 cm Basic', 'Szafki na buty', 599.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-z-siedziskiem-biala-91-cm-basic-28628.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28629', 'Wieszak ścienny biały połysk 31 cm Basic', 'Wieszaki na ubrania/Wieszaki ścienne', 209.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-bialy-polysk-31-cm-basic-28629.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28630', 'Lustro do przedpokoju 50 x 110 cm Basic', 'Lustra', 245.0, 'https://www.meblepumo.pl/pl/products/lustro-do-przedpokoju-50-x-110-cm-basic-28630.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28633', 'Łóżko dwuosobowe szare / orzech 140x200 cm Cassidy', 'Łóżka i części/Łóżka', 1859.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-szare-orzech-140x200-cm-cassidy-28633.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28635', 'Stół do jadalni orzech mat 160 x 90 cm Miguel', 'Stoly/Stoły nierozkładane', 1149.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-orzech-mat-160-x-90-cm-miguel-28635.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28637', 'Stół rozkładany dąb naturalny mat 160 - 240 x 90 cm Edmondo', 'Stoly/Stoły rozkładane', 2869.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-mat-160-240-x-90-cm-edmondo-28637.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28638', 'Krzesło do jadalni drewniane tapicerowane szare / naturalne Cadiz', 'Krzesła/Krzesła do jadalni', 609.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-szare-naturalne-cadiz-28638.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28639', 'Fotel wypoczynkowy tapicerowany cynamonowy Hazard', 'Fotele/Fotele wypoczynkowe', 719.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-cynamonowy-hazard-28639.feed10009', 'HALMAR');
