-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28394', 'Szafa z lustrem dwudrzwiowa kaszmir mat 100 x 200 cm Sento', 'Szafy/Szafy uchylne', 971.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-dwudrzwiowa-kaszmir-mat-100-x-200-cm-sento-28394.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28395', 'Szafa z lustrem trzydrzwiowa biała mat 150 x 200 cm Sento', 'Szafy/Szafy uchylne', 1214.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-trzydrzwiowa-biala-mat-150-x-200-cm-sento-28395.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28396', 'Szafa z lustrem trzydrzwiowa kaszmir mat 150 x 200 cm Sento', 'Szafy/Szafy uchylne', 1259.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-trzydrzwiowa-kaszmir-mat-150-x-200-cm-sento-28396.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28397', 'Szafka RTV biała / dąb artisan mat 175 cm Arona', 'Szafki RTV', 1099.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-dab-artisan-mat-175-cm-arona-28397.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28398', 'Stolik kawowy beżowy / brązowy 40 cm Ariana', 'Stoliki kawowe i ławy/Stoliki kawowe', 239.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-bezowy-brazowy-40-cm-ariana-28398.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28399', 'Komoda z szufladami i drzwiami biała / dąb artisan mat 135 cm Arona', 'Komody/Komody z szufladami i drzwiami', 1499.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-artisan-mat-135-cm-arona-28399.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28400', 'Komoda z szufladami i drzwiami biała / dąb artisan mat 175 cm Arona', 'Komody/Komody z szufladami i drzwiami', 2059.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-dab-artisan-mat-175-cm-arona-28400.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28401', 'Komoda z drzwiami biała / dąb artisan mat 90 cm Arona', 'Komody/Komody z szufladami i drzwiami', 979.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-dab-artisan-mat-90-cm-arona-28401.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28402', 'Komoda wysoka z drzwiami i szufladami biała / dąb artisan  mat 90 cm Arona', 'Komody/Komody z szufladami i drzwiami', 1739.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-i-szufladami-biala-dab-artisan-mat-90-cm-arona-28402.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28403', 'Stolik kawowy z szufladami biały / dąb mat 94 x 55 cm Arona', 'Stoliki kawowe i ławy/Stoliki kawowe', 759.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szufladami-bialy-dab-mat-94-x-55-cm-arona-28403.feed10009', 'Fontini ');
