-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17415', 'Biurko z szufladami białe mat 126 cm Function', 'Pozostałe produkty', 849.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-biale-mat-126-cm-function-17415.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17424', 'Biurko z szufladą białe / szare mat 75 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 379.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-biale-szare-mat-75-cm-function-17424.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17428', 'Biurko z regałem dąb sonoma / białe mat 163 cm Function Plus', 'Biurka/Biurka z szufladami i drzwiami', 949.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regalem-dab-sonoma-biale-mat-163-cm-function-plus-17428.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17430', 'Biurko z szufladami dąb sonoma / białe mat 120 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 459.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-sonoma-biale-mat-120-cm-function-17430.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17438', 'Biurko z szufladami białe mat 110 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-biale-mat-110-cm-function-17438.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17439', 'Biurko z szufladami dąb sonoma mat 110 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-sonoma-mat-110-cm-function-17439.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17441', 'Biurko z szufladami dąb sonoma mat 110 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 529.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-sonoma-mat-110-cm-function-17441.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17501', 'Biurko z szufladami dąb sonoma mat 120 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 459.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-dab-sonoma-mat-120-cm-function-17501.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17502', 'Stół drewniany dąb lity bassano mat 180 x 100 cm Zamek', 'Pozostałe produkty', 3959.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-lity-bassano-mat-180-x-100-cm-zamek-17502.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('17503', 'Stół drewniany dąb lity bassano mat 200 x 100 cm Zamek', 'Pozostałe produkty', 4159.0, 'https://www.meblepumo.pl/pl/products/stol-drewniany-dab-lity-bassano-mat-200-x-100-cm-zamek-17503.feed10009', 'Fato Luxmeble');
