-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26025', 'Hoker z oparciem tapicerowany zielony / czarny H103', 'Hokery', 394.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-czarny-h103-26025.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26027', 'Hoker z oparciem tapicerowany szary / czarny H103', 'Hokery', 394.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h103-26027.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26031', 'Hoker z oparciem tapicerowany zielony / czarny / złoty H106', 'Hokery', 359.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-czarny-zloty-h106-26031.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26032', 'Hoker z oparciem tapicerowany szary / czarny / złoty H106', 'Hokery', 359.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-zloty-h106-26032.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26035', 'Hoker z oparciem ekoskóra czarny / srebrny H15', 'Hokery', 284.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-czarny-srebrny-h15-26035.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26036', 'Hoker z oparciem ekoskóra beżowy / srebrny H15', 'Hokery', 284.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-bezowy-srebrny-h15-26036.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26037', 'Hoker z oparciem ekoskóra szary / srebrny H15', 'Hokery', 284.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-szary-srebrny-h15-26037.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26047', 'Hoker z oparciem ekoskóra kremowy / orzech / srebrny H44', 'Hokery', 474.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-kremowy-orzech-srebrny-h44-26047.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26048', 'Hoker z oparciem ekoskóra czarny / dąb / srebrny H45', 'Hokery', 449.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-czarny-dab-srebrny-h45-26048.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26049', 'Hoker z oparciem ekoskóra biały / czarny / srebrny H46', 'Hokery', 409.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-bialy-czarny-srebrny-h46-26049.feed10009', 'HALMAR');
