-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26068', 'Hoker z oparciem tapicerowany zielony / czarny H96', 'Hokery', 259.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-czarny-h96-26068.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26069', 'Hoker z oparciem tapicerowany granatowy / czarny H96', 'Hokery', 259.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-granatowy-czarny-h96-26069.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26070', 'Hoker z oparciem tapicerowany szary / czarny H96', 'Hokery', 259.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h96-26070.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26072', 'Hoker z oparciem rattanowy naturalny / czarny H97', 'Hokery', 269.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-rattanowy-naturalny-czarny-h97-26072.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26076', 'Stół loftowy szary / czarny mat 160 x 90 cm Halifax', 'Stoly/Stoły nierozkładane', 999.0, 'https://www.meblepumo.pl/pl/products/stol-loftowy-szary-czarny-mat-160-x-90-cm-halifax-26076.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26077', 'Fotel gabinetowy ekoskóra czarny Hamilton', 'Fotele/Fotele do biurka', 479.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-czarny-hamilton-26077.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26079', 'Fotel biurowy ekoskóra / siatka czarny / szary Hasel', 'Fotele/Fotele do biurka', 649.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-siatka-czarny-szary-hasel-26079.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26084', 'Fotel biurowy ekoskóra brazowy Hilton', 'Fotele/Fotele do biurka', 589.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-brazowy-hilton-26084.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26086', 'Stół rozkładany brązowy / czarny mat 120 - 180 x 85 cm Horizon', 'Stoly/Stoły rozkładane', 2699.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-brazowy-czarny-mat-120-180-x-85-cm-horizon-26086.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26092', 'Fotel gabinetowy tapicerowany ekoskóra czarny / orzech Ignazio', 'Fotele/Fotele do biurka', 799.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-ekoskora-czarny-orzech-ignazio-26092.feed10009', 'HALMAR');
