-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15992', 'Zestaw szuflad pod łóżko biały 94x66x17 cm Naia', 'Łóżka i części/Części do łóżek', 319.0, 'https://www.meblepumo.pl/pl/products/zestaw-szuflad-pod-lozko-bialy-94x66x17-cm-naia-15992.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('15994', 'Szafa dwudrzwiowa z szufladami biała połysk 99 x 200 cm Naia', 'Szafy/Szafy uchylne', 1359.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-z-szufladami-biala-polysk-99-x-200-cm-naia-15994.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16076', 'Stelaż do łóżka 70x200 cm Futura NV', 'Łóżka i części/Stelaże do łóżek', 399.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-70x200-cm-futura-nv-16076.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16199', 'Sofa 2-osobowa z funkcją spania tapicerowana granatowa Derry', 'Pozostałe produkty', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-granatowa-derry-16199.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16212', 'Sofa 2-osobowa z funkcją spania tapicerowana fioletowa Derry', 'Pozostałe produkty', 3599.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-fioletowa-derry-16212.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16214', 'Sofa 3-osobowa tapicerowana beżowa Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-bezowa-lily-16214.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16215', 'Sofa 2-osobowa tapicerowana beżowa Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-bezowa-lily-16215.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16219', 'Sofa 3-osobowa tapicerowana zielona Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-zielona-lily-16219.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16220', 'Sofa 3-osobowa tapicerowana turkusowa Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-turkusowa-lily-16220.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16221', 'Sofa 3-osobowa tapicerowana welurowa czerwona Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-welurowa-czerwona-lily-16221.feed10009', 'Scandinavian Style Design');
