-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27705', 'Szafka zlewozmywakowa biała / beżowa mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 338.0, 'https://www.meblepumo.pl/pl/products/szafka-zlewozmywakowa-biala-bezowa-mat-wysoki-polysk-80-cm-vento-27705.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27708', 'Szafka zlewozmywakowa biała / jasny szary mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 338.0, 'https://www.meblepumo.pl/pl/products/szafka-zlewozmywakowa-biala-jasny-szary-mat-wysoki-polysk-80-cm-vento-27708.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27709', 'Szafka zlewozmywakowa antracyt mat 80 cm Vento', 'Szafki kuchenne', 332.0, 'https://www.meblepumo.pl/pl/products/szafka-zlewozmywakowa-antracyt-mat-80-cm-vento-27709.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27712', 'Szafka zlewozmywakowa biała / dąb miodowy mat 80 cm Vento', 'Szafki kuchenne', 332.0, 'https://www.meblepumo.pl/pl/products/szafka-zlewozmywakowa-biala-dab-miodowy-mat-80-cm-vento-27712.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27713', 'Szafka zlewozmywakowa narożna biała / jasny szary mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 332.0, 'https://www.meblepumo.pl/pl/products/szafka-zlewozmywakowa-narozna-biala-jasny-szary-mat-wysoki-polysk-80-cm-vento-27713.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27714', 'Szafka dolna wysoka antracyt mat 60 cm Vento', 'Szafki kuchenne', 692.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-wysoka-antracyt-mat-60-cm-vento-27714.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27715', 'Szafka dolna wysoka biała / beżowa mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 692.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-wysoka-biala-bezowa-mat-wysoki-polysk-60-cm-vento-27715.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27717', 'Szafka dolna wysoka biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 692.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-wysoka-biala-dab-miodowy-mat-60-cm-vento-27717.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27718', 'Szafka dolna wysoka biała / jasnoszara mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 692.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-wysoka-biala-jasnoszara-mat-wysoki-polysk-60-cm-vento-27718.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27719', 'Front do zabudowy zmywarki antracyt mat 45 cm Vento', 'Dodatki do mebli/Części do mebli', 99.0, 'https://www.meblepumo.pl/pl/products/front-do-zabudowy-zmywarki-antracyt-mat-45-cm-vento-27719.feed10009', 'HALMAR');
