-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26352', 'Krzesło do jadalni tapicerowane szare K409', 'Krzesła/Krzesła do jadalni', 349.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k409-26352.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26353', 'Krzesło do jadalni tapicerowane zielone K410', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k410-26353.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26355', 'Krzesło do jadalni tapicerowane musztardowe K410', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k410-26355.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26356', 'Krzesło do jadalni tapicerowane szare K410', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k410-26356.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26357', 'Krzesło do jadalni tapicerowane różowe K410', 'Krzesła/Krzesła do jadalni', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-rozowe-k410-26357.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26360', 'Krzesło do jadalni tapicerowane zielone K416', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k416-26360.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26361', 'Krzesło do jadalni tapicerowane granatowe K416', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k416-26361.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26362', 'Krzesło do jadalni tapicerowane szare K416', 'Krzesła/Krzesła do jadalni', 179.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k416-26362.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26363', 'Krzesło do jadalni tapicerowane zielone K417', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k417-26363.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26364', 'Krzesło do jadalni tapicerowane granatowe K417', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-granatowe-k417-26364.feed10009', 'HALMAR');
