-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28404', 'Stolik kawowy prostokątny bordowy połysk 120 x 60 cm Soraya', 'Stoliki kawowe i ławy/Stoliki kawowe', 749.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bordowy-polysk-120-x-60-cm-soraya-28404.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28405', 'Biurko z szufladami, drzwiami kaszmir mat 120 cm Mono', 'Biurka/Biurka z szufladami i drzwiami', 399.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-drzwiami-kaszmir-mat-120-cm-mono-28405.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28406', 'Biurko z szufladami, drzwiami białe mat 120 cm Mono', 'Biurka/Biurka z szufladami i drzwiami', 369.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-drzwiami-biale-mat-120-cm-mono-28406.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28407', 'Biurko narożne białe / dąb artisan mat 129 cm Filo 2', 'Biurka/Biurka narożne', 749.0, 'https://www.meblepumo.pl/pl/products/biurko-narozne-biale-dab-artisan-mat-129-cm-filo-2-28407.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28408', 'Biurko z szufladami białe / dąb artisan mat 138 cm Filo 3', 'Biurka/Biurka narożne', 459.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-biale-dab-artisan-mat-138-cm-filo-3-28408.feed10009', 'Vivaladesign');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28409', 'Witryna dwudrzwiowa z szufladami capuccino mat 90 x 185 cm Arona', 'Witryny i kredensy/Witryny', 2699.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-capuccino-mat-90-x-185-cm-arona-28409.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28410', 'Witryna dwudrzwiowa z szufladami biała / dąb artisan mat 90 x 185 cm Arona', 'Witryny i kredensy/Witryny', 2699.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-biala-dab-artisan-mat-90-x-185-cm-arona-28410.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28411', 'Stół okrągły lastryko / biały mat 120 cm Aramis', 'Stoly/Stoły rozkładane', 799.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-lastryko-bialy-mat-120-cm-aramis-28411.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28412', 'Komoda z szufladami i drzwiami kaszmir / dąb mat 197 cm Avolo', 'Komody/Komody z szufladami i drzwiami', 1199.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-dab-mat-197-cm-avolo-28412.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28413', 'Komoda z szufladami i drzwiami kaszmir / dąb mat 154 cm Avolo', 'Komody/Komody z szufladami i drzwiami', 1119.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-dab-mat-154-cm-avolo-28413.feed10009', 'TT-furniture');
