-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20206', 'Komoda szeroka z drzwiami i szufladami biała wysoki połysk 241 cm Prestige', 'Komody/Komody z szufladami i drzwiami', 1999.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-i-szufladami-biala-wysoki-polysk-241-cm-prestige-20206.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20207', 'Komoda szeroka z drzwiami i szufladami antracyt wysoki połysk 241 cm Prestige', 'Komody/Komody z szufladami i drzwiami', 2149.0, 'https://www.meblepumo.pl/pl/products/komoda-szeroka-z-drzwiami-i-szufladami-antracyt-wysoki-polysk-241-cm-prestige-20207.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20209', 'Komoda z szufladami i drzwiami biała wysoki połysk 181 cm Prestige', 'Pozostałe produkty', 1479.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-181-cm-prestige-20209.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20210', 'Komoda z szufladami i drzwiami antracyt wysoki połysk 181 cm Prestige', 'Pozostałe produkty', 1599.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-antracyt-wysoki-polysk-181-cm-prestige-20210.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20212', 'Komoda z drzwiami biała wysoki połysk 182 cm Prestige', 'Pozostałe produkty', 1249.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-182-cm-prestige-20212.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20215', 'Komoda wysoka z drzwiami biała wysoki połysk 121 cm Prestige', 'Pozostałe produkty', 1299.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-wysoki-polysk-121-cm-prestige-20215.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20219', 'Witryna dwudrzwiowa antracyt połysk 121 x 166 cm Prestige', 'Pozostałe produkty', 2129.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-antracyt-polysk-121-x-166-cm-prestige-20219.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20221', 'Szafka RTV biała połysk 181 cm Prestige', 'Szafki RTV', 1219.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-181-cm-prestige-20221.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20222', 'Szafka RTV antracyt połysk 181 cm Prestige', 'Szafki RTV', 1279.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-antracyt-polysk-181-cm-prestige-20222.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20224', 'Stół rozkładany biały połysk 137 - 185 x 90 cm Prestige', 'Stoly/Stoły rozkładane', 1419.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-polysk-137-185-x-90-cm-prestige-20224.feed10009', 'Italia Trend');
