-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16477', 'Fotel wypoczynkowy welurowy czarny Gryf', 'Fotele/Fotele wypoczynkowe', 1769.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-welurowy-czarny-gryf-16477.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16478', 'Fotel wypoczynkowy welurowy czerwony Gryf', 'Fotele/Fotele wypoczynkowe', 1769.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-welurowy-czerwony-gryf-16478.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16479', 'Fotel wypoczynkowy welurowy fioletowy Gryf', 'Fotele/Fotele wypoczynkowe', 1769.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-welurowy-fioletowy-gryf-16479.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16480', 'Fotel wypoczynkowy welurowy turkusowy Gryf', 'Fotele/Fotele wypoczynkowe', 1769.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-welurowy-turkusowy-gryf-16480.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16481', 'Fotel wypoczynkowy welurowy zielony Gryf', 'Fotele/Fotele wypoczynkowe', 1769.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-welurowy-zielony-gryf-16481.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16482', 'Sofa 2-osobowa tapicerowana beżowa Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2499.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-bezowa-gryf-16482.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16483', 'Sofa 2-osobowa tapicerowana czarna Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2499.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-czarna-gryf-16483.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16484', 'Sofa 2-osobowa tapicerowana bordowa Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2499.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-bordowa-gryf-16484.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16485', 'Sofa 2-osobowa tapicerowana fioletowa Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2499.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-fioletowa-gryf-16485.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16486', 'Sofa 2-osobowa tapicerowana turkusowa Gryf', 'Sofy i narożniki/Sofy 2-osobowe', 2499.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-turkusowa-gryf-16486.feed10009', 'Scandinavian Style Design');
