-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27226', 'Zestaw mebli kuchennych dąb artisan / szary / dąb wotan 260 cm Perła', 'Zestawy mebli/Zestawy mebli kuchennych', 1699.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-dab-artisan-szary-dab-wotan-260-cm-perla-27226.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27227', 'Zestaw mebli kuchennych dąb sonoma / szary 260 cm Perła', 'Zestawy mebli/Zestawy mebli kuchennych', 1649.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-kuchennych-dab-sonoma-szary-260-cm-perla-27227.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27228', 'Stół do jadalni biały mat 120 x 68 cm Ksawery', 'Stoly/Stoły nierozkładane', 446.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-bialy-mat-120-x-68-cm-ksawery-27228.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27229', 'Stół do jadalni dąb sonoma mat 120 x 68 cm Ksawery', 'Stoly/Stoły nierozkładane', 446.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-dab-sonoma-mat-120-x-68-cm-ksawery-27229.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27230', 'Stół do jadalni dąb sonoma / biały mat 120 x 68 cm Ksawery', 'Stoly/Stoły nierozkładane', 446.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-dab-sonoma-bialy-mat-120-x-68-cm-ksawery-27230.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27247', 'Biurko z szufladami i drzwiami białe wysoki połysk 120 cm Lima', 'Biurka/Biurka z szufladami i drzwiami', 434.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-drzwiami-biale-wysoki-polysk-120-cm-lima-27247.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27248', 'Biurko z szufladami i drzwiami dąb sonoma / białe mat / wysoki połysk 120 cm Lima', 'Biurka/Biurka z szufladami i drzwiami', 368.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-drzwiami-dab-sonoma-biale-mat-wysoki-polysk-120-cm-lima-27248.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27249', 'Biurko z szufladami i drzwiami dąb sonoma mat 120 cm Lima', 'Biurka/Biurka z szufladami i drzwiami', 368.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-drzwiami-dab-sonoma-mat-120-cm-lima-27249.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27252', 'Komoda z drzwiami i szufladami dąb sonoma mat 40 cm Lima', 'Komody/Komody z szufladami i drzwiami', 391.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-i-szufladami-dab-sonoma-mat-40-cm-lima-27252.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27254', 'Komoda z szufladami i drzwiami biała mat / wysoki połysk 77 cm Lima', 'Komody/Komody z szufladami i drzwiami', 528.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-mat-wysoki-polysk-77-cm-lima-27254.feed10009', 'HALMAR');
