-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25779', 'Stół rozkładany biały / dąb san remo mat 160 - 200 x 90 cm Caliber', 'Stoly/Stoły rozkładane', 1339.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-dab-san-remo-mat-160-200-x-90-cm-caliber-25779.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25781', 'Fotel gabinetowy ekoskóra brązowy Calvano', 'Fotele/Fotele do biurka', 1119.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-brazowy-calvano-25781.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25782', 'Fotel rozkładany ekoskóra czarny / czerwony Camaro', 'Fotele/Fotele rozkładane', 1299.0, 'https://www.meblepumo.pl/pl/products/fotel-rozkladany-ekoskora-czarny-czerwony-camaro-25782.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25784', 'Stolik kawowy okrągły dąb złoty / czarny mat 80 cm Camila', 'Stoliki kawowe i ławy/Stoliki kawowe', 539.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dab-zloty-czarny-mat-80-cm-camila-25784.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25785', 'Stolik kawowy szklany transparetny / chrom mat 45 x 45 cm Canaria', 'Stoliki kawowe i ławy/Stoliki kawowe', 114.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-transparetny-chrom-mat-45-x-45-cm-canaria-25785.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25791', 'Fotel gabinetowy ekoskóra czarny Carlos', 'Fotele/Fotele do biurka', 659.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-czarny-carlos-25791.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25792', 'Fotel gabinetowy ekoskóra brązowy Carlos', 'Fotele/Fotele do biurka', 599.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-brazowy-carlos-25792.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25794', 'Stół okrągły orzech / czarny mat 100 cm Carmelo', 'Stoly/Stoły nierozkładane', 769.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-orzech-czarny-mat-100-cm-carmelo-25794.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25795', 'Krzesło do jadalni ekoskóra beżowa Caro', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-bezowa-caro-25795.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25796', 'Stolik kawowy owalny dąb złoty / czarny mat 120 x 60 cm Carolina', 'Stoliki kawowe i ławy/Stoliki kawowe', 653.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-owalny-dab-zloty-czarny-mat-120-x-60-cm-carolina-25796.feed10009', 'HALMAR');
