-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28583', 'Witryna dwudrzwiowa biała połysk 121 x 166 cm Corda', 'Witryny i kredensy/Witryny', 2229.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-biala-polysk-121-x-166-cm-corda-28583.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28584', 'Witryna jednodrzwiowa biała połysk 60 x 187 cm Corda', 'Witryny i kredensy/Witryny', 1439.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-biala-polysk-60-x-187-cm-corda-28584.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28585', 'Komoda z drzwiami biała połysk 241 cm Corda', 'Komody/Komody z drzwiami', 1949.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-polysk-241-cm-corda-28585.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28586', 'Komoda z drzwiami biała połysk 181 cm Corda', 'Komody/Komody z drzwiami', 1519.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-polysk-181-cm-corda-28586.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28587', 'Komoda z szufladami i drzwiami biała połysk 181 cm Corda', 'Komody/Komody z szufladami i drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-polysk-181-cm-corda-28587.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28588', 'Komoda wysoka z drzwiami biała połysk 121 cm Corda', 'Komody/Komody z drzwiami', 1529.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-polysk-121-cm-corda-28588.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28589', 'Szafka RTV biała połysk 184 cm Corda', 'Szafki RTV', 1129.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-184-cm-corda-28589.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28590', 'Szafka RTV biała połysk 122 cm Corda', 'Szafki RTV', 1059.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-polysk-122-cm-corda-28590.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28591', 'Meblościanka do salonu biała połysk 300 cm Corda', 'Meblościanki', 2599.0, 'https://www.meblepumo.pl/pl/products/mebloscianka-do-salonu-biala-polysk-300-cm-corda-28591.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28592', 'Łóżko tapicerowane antracyt / grafit mat 160x200 cm Teo', 'Łóżka i części/Łóżka', 1519.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-antracyt-grafit-mat-160x200-cm-teo-28592.feed10009', 'MiroMark');
