-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26183', 'Krzesło do jadalni plastikowe transparentne / białe K246', 'Krzesła/Krzesła do jadalni', 249.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-plastikowe-transparentne-biale-k246-26183.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26199', 'Krzesło do jadalni ekoskóra szare K279', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-szare-k279-26199.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26202', 'Krzesło do jadalni tapicerowane  beżowe K282', 'Krzesła/Krzesła do jadalni', 253.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k282-26202.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26206', 'Krzesło do jadalni tapicerowane  szare K283', 'Krzesła/Krzesła do jadalni', 309.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k283-26206.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26209', 'Krzesło do jadalni tapicerowane  szare K285', 'Krzesła/Krzesła do jadalni', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k285-26209.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26216', 'Krzesło do jadalni tapicerowane szare K290', 'Krzesła/Krzesła do jadalni', 409.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k290-26216.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26230', 'Krzesło do jadalni ekoskóra szare / brązowe K304', 'Krzesła/Krzesła do jadalni', 485.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-szare-brazowe-k304-26230.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26240', 'Krzesło do jadalni tapicerowane ciemnoszare K309', 'Krzesła/Krzesła do jadalni', 175.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-ciemnoszare-k309-26240.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26241', 'Krzesło do jadalni tapicerowane beżowe K309', 'Krzesła/Krzesła do jadalni', 175.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k309-26241.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26242', 'Krzesło do jadalni tapicerowane szare K309', 'Krzesła/Krzesła do jadalni', 175.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k309-26242.feed10009', 'HALMAR');
