-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25125', 'Komoda z drzwiami biała mat 190 cm Cave', 'Komody/Komody z drzwiami', 1339.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-190-cm-cave-25125.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25126', 'Komoda z drzwiami biała mat 152 cm Cave', 'Komody/Komody z drzwiami', 1269.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-152-cm-cave-25126.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25127', 'Szafka RTV czarna / dąb craft mat 200 cm Amaro', 'Szafki RTV', 1199.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-dab-craft-mat-200-cm-amaro-25127.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25128', 'Szafa dwudrzwiowa biała mat 90 x 199 cm Malia', 'Szafy/Szafy uchylne', 1639.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-biala-mat-90-x-199-cm-malia-25128.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25129', 'Nadstawka na szafę biała mat 90 x 45 cm Malia', 'Szafy/Nadstawki na szafę', 629.0, 'https://www.meblepumo.pl/pl/products/nadstawka-na-szafe-biala-mat-90-x-45-cm-malia-25129.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25130', 'Szafa dwudrzwiowa czarna mat 90 x 199 cm Malia', 'Szafy/Szafy uchylne', 1709.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-czarna-mat-90-x-199-cm-malia-25130.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25133', 'Nadstawka na szafę czarna mat 90 x 45 cm Malia', 'Szafy/Nadstawki na szafę', 649.0, 'https://www.meblepumo.pl/pl/products/nadstawka-na-szafe-czarna-mat-90-x-45-cm-malia-25133.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25134', 'Fotel ogrodowy wiszący rattanowy tapicerowany szary / czarny Eggy', 'Fotele/Fotele ogrodowe', 1129.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-wiszacy-rattanowy-tapicerowany-szary-czarny-eggy-25134.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25136', 'Stelaż do łóżka 180x200 cm Natura NV', 'Stelaże', 399.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-180x200-cm-natura-nv-25136.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25138', 'Szafa jednodrzwiowa czarna mat 45 x 198 cm Malia', 'Szafy/Szafy uchylne', 1239.0, 'https://www.meblepumo.pl/pl/products/szafa-jednodrzwiowa-czarna-mat-45-x-198-cm-malia-25138.feed10009', 'High Glossy Furniture');
