-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28361', 'Komoda z szufladami i drzwiami biała wysoki połysk 182 cm Sorelle', 'Komody/Komody z szufladami i drzwiami', 1579.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-182-cm-sorelle-28361.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28362', 'Komoda z szufladami i drzwiami dąb mercure 182 cm Sorelle', 'Komody/Komody z szufladami i drzwiami', 1579.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-mercure-182-cm-sorelle-28362.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28363', 'Komoda z drzwiami biała wysoki połysk 182 cm Sorelle', 'Komody/Komody z drzwiami', 1349.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-182-cm-sorelle-28363.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28364', 'Komoda z drzwiami dąb mercure 182 cm Sorelle', 'Komody/Komody z drzwiami', 1349.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-mercure-182-cm-sorelle-28364.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28365', 'Komoda z drzwiami biała wysoki połysk 120 cm Sorelle', 'Komody/Komody z drzwiami', 1029.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-wysoki-polysk-120-cm-sorelle-28365.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28366', 'Komoda z drzwiami dąb mercure 120 cm Sorelle', 'Komody/Komody z drzwiami', 1029.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-mercure-120-cm-sorelle-28366.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28367', 'Szafka RTV biała wysoki połysk 182 cm Sorelle', 'Szafki RTV', 1299.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-wysoki-polysk-182-cm-sorelle-28367.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28368', 'Szafka RTV dąb mercure 182 cm Sorelle', 'Szafki RTV', 1299.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-mercure-182-cm-sorelle-28368.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28369', 'Szafka RTV biała wysoki połysk 182 cm Sorelle', 'Szafki RTV', 1169.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-wysoki-polysk-182-cm-sorelle-28369.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28370', 'Szafka RTV dąb mercure 182 cm Sorelle', 'Szafki RTV', 1169.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-mercure-182-cm-sorelle-28370.feed10009', 'Italia Trend');
