-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23606', 'Sofa 3-osobowa tapicerowana turkusowa Cavan', 'Sofy i narożniki/Sofy 3-osobowe', 2999.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-turkusowa-cavan-23606.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23607', 'Sofa 3-osobowa tapicerowana niebieska Cavan', 'Sofy i narożniki/Sofy 3-osobowe', 2999.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-niebieska-cavan-23607.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23608', 'Sofa 3-osobowa tapicerowana czerwona Cavan', 'Sofy i narożniki/Sofy 3-osobowe', 2999.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-czerwona-cavan-23608.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23609', 'Sofa 3-osobowa tapicerowana fioletowa Cavan', 'Sofy i narożniki/Sofy 3-osobowe', 2999.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-fioletowa-cavan-23609.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23622', 'Szafka RTV dąb / czarna mat 140 cm Simple', 'Pozostałe produkty', 479.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-czarna-mat-140-cm-simple-23622.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23624', 'Witryna wisząca przeszklona dąb lefkas mat 60 x 112 cm Simple', 'Pozostałe produkty', 439.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-przeszklona-dab-lefkas-mat-60-x-112-cm-simple-23624.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23625', 'Witryna dwudrzwiowa z szufladami dąb lefkas mat 80 x 192 cm Simple', 'Witryny i kredensy/Witryny', 1169.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-dab-lefkas-mat-80-x-192-cm-simple-23625.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23626', 'Komoda z szufladami i drzwiami dąb lefkas mat 132 cm Simple', 'Komody/Komody z szufladami i drzwiami', 1039.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-lefkas-mat-132-cm-simple-23626.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23627', 'Komoda z szufladami i drzwiami dąb lefkas mat 120 cm Simple', 'Komody/Komody z szufladami i drzwiami', 729.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-lefkas-mat-120-cm-simple-23627.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23628', 'Zestaw 2 półek wiszących dąb lefkas / czarna mat 125 x 20 cm Simple', 'Pozostałe produkty', 199.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-polek-wiszacych-dab-lefkas-czarna-mat-125-x-20-cm-simple-23628.feed10009', 'High Glossy Furniture');
