-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28573', 'Stolik kawowy okrągły dąb olejowany / czarny mat 75 cm Trunk 1', 'Stoliki kawowe i ławy/Stoliki kawowe', 1269.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dab-olejowany-czarny-mat-75-cm-trunk-1-28573.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28574', 'Witryna dwudrzwiowa kaszmir mat 121 x 166 cm Corda', 'Witryny i kredensy/Witryny', 2229.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-kaszmir-mat-121-x-166-cm-corda-28574.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28575', 'Witryna jednodrzwiowa kaszmir mat 60 x 187 cm Corda', 'Witryny i kredensy/Witryny', 1439.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-kaszmir-mat-60-x-187-cm-corda-28575.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28576', 'Komoda z drzwiami kaszmir mat 241 cm Corda', 'Komody/Komody z drzwiami', 1949.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-241-cm-corda-28576.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28577', 'Komoda z drzwiami kaszmir mat 181 cm Corda', 'Komody/Komody z drzwiami', 1519.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-181-cm-corda-28577.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28578', 'Komoda z szufladami i drzwiami kaszmir mat 181 cm Corda', 'Komody/Komody z szufladami i drzwiami', 1699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-mat-181-cm-corda-28578.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28579', 'Komoda wysoka z drzwiami kaszmir mat 121 cm Corda', 'Komody/Komody z drzwiami', 1529.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-kaszmir-mat-121-cm-corda-28579.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28580', 'Szafka RTV kaszmir mat 184 cm Corda', 'Szafki RTV', 1129.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-184-cm-corda-28580.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28581', 'Szafka RTV kaszmir mat 122 cm Corda', 'Szafki RTV', 1059.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-122-cm-corda-28581.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28582', 'Meblościanka do salonu kaszmir mat 300 cm Corda', 'Meblościanki', 2599.0, 'https://www.meblepumo.pl/pl/products/mebloscianka-do-salonu-kaszmir-mat-300-cm-corda-28582.feed10009', 'Italia Trend');
