-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10282', 'Biurko z szufladami białe wysoki połysk 102 cm Function', 'Pozostałe produkty', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-biale-wysoki-polysk-102-cm-function-10282.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10292', 'Sofa 2-osobowa z funkcją spania tapicerowana brązowa Derry', 'Pozostałe produkty', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-brazowa-derry-10292.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10293', 'Sofa 2-osobowa z funkcją spania tapicerowana szara Derry', 'Pozostałe produkty', 3459.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-z-funkcja-spania-tapicerowana-szara-derry-10293.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10361', 'Szafka RTV biała mat / połysk 180 cm Simple', 'Pozostałe produkty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-polysk-180-cm-simple-10361.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10394', 'Szafka RTV czarna mat / połysk 180 cm Simple', 'Pozostałe produkty', 479.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-polysk-180-cm-simple-10394.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10397', 'Szafka RTV biała mat / połysk 140 cm Simple', 'Pozostałe produkty', 479.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-polysk-140-cm-simple-10397.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10400', 'Szafka RTV czarna mat / połysk 140 cm Simple', 'Pozostałe produkty', 479.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-polysk-140-cm-simple-10400.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10403', 'Witryna jednodrzwiowa z szufladami biała mat / połysk 60 x 192 cm Simple', 'Witryny i kredensy/Witryny', 929.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-biala-mat-polysk-60-x-192-cm-simple-10403.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10405', 'Witryna jednodrzwiowa z szufladami czarna mat / połysk 60 x 192 cm Simple', 'Witryny i kredensy/Witryny', 929.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-z-szufladami-czarna-mat-polysk-60-x-192-cm-simple-10405.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('10412', 'SOHO półka wisząca', 'Pozostałe produkty', 160.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-polek-wiszacych-bialych-mat-125-x-20-cm-simple-10412.feed10009', 'High Glossy Furniture');
