-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28310', 'Komoda z drzwiami czarna mat 200 cm Ardea', 'Komody/Komody z drzwiami', 1179.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-200-cm-ardea-28310.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28311', 'Komoda z drzwiami biała mat 200 cm Ardea', 'Komody/Komody z drzwiami', 1139.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-200-cm-ardea-28311.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28312', 'Szafka RTV kaszmir mat 150 cm Ardea', 'Szafki RTV', 789.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-150-cm-ardea-28312.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28313', 'Szafka RTV czarna mat 150 cm Ardea', 'Szafki RTV', 789.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-150-cm-ardea-28313.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28314', 'Szafka RTV biała mat 150 cm Ardea', 'Szafki RTV', 729.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-150-cm-ardea-28314.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28315', 'Szafka RTV kaszmir mat 200 cm Ardea', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-kaszmir-mat-200-cm-ardea-28315.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28316', 'Szafka RTV czarna mat 200 cm Ardea', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-mat-200-cm-ardea-28316.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28317', 'Szafka RTV biała mat 200 cm Ardea', 'Szafki RTV', 929.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-biala-mat-200-cm-ardea-28317.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28318', 'Witryna jednodrzwiowa kaszmir mat 60 x 178 cm Ardea', 'Witryny i kredensy/Witryny', 979.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-kaszmir-mat-60-x-178-cm-ardea-28318.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28319', 'Witryna jednodrzwiowa czarna mat 60 x 178 cm Ardea', 'Witryny i kredensy/Witryny', 979.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-czarna-mat-60-x-178-cm-ardea-28319.feed10009', 'High Glossy Furniture');
