-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25749', 'Fotel gabinetowy tapicerowany ekoskóra czarny / czerwony Berkel', 'Fotele/Fotele do biurka', 386.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-tapicerowany-ekoskora-czarny-czerwony-berkel-25749.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25751', 'Stół rozkładany orzech mat 140 - 180 x 85 cm Berlin', 'Stoly/Stoły rozkładane', 1199.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-orzech-mat-140-180-x-85-cm-berlin-25751.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25753', 'Stół rozkładany antracyt / orzech mat 160 - 200 x 90 cm Bilotti', 'Stoly/Stoły rozkładane', 3215.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-antracyt-orzech-mat-160-200-x-90-cm-bilotti-25753.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25756', 'Stół rozkładany dąb złoty mat 160 - 220 x 90 cm Blacky', 'Stoly/Stoły rozkładane', 2089.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-zloty-mat-160-220-x-90-cm-blacky-25756.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25757', 'Stolik kawowy prostokątny biały marmur / czarny mat 110 x 60 cm Blanca', 'Stoliki kawowe i ławy/Stoliki kawowe', 499.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bialy-marmur-czarny-mat-110-x-60-cm-blanca-25757.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25760', 'Regał loftowy dąb złoty / czarny mat 100 x 30 x 120 cm Boliver', 'Regały', 399.0, 'https://www.meblepumo.pl/pl/products/regal-loftowy-dab-zloty-czarny-mat-100-x-30-x-120-cm-boliver-25760.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25761', 'Regał loftowy dąb złoty / czarny mat 100 x 30 x 155 cm Boliver', 'Regały', 499.0, 'https://www.meblepumo.pl/pl/products/regal-loftowy-dab-zloty-czarny-mat-100-x-30-x-155-cm-boliver-25761.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25762', 'BOLIVAR zestaw stół + 6 krzeseł dąb złoty / czarny (1p=1szt)', 'Zestawy mebli/Zestawy mebli do jadalni', 1128.0, 'https://www.meblepumo.pl/pl/products/bolivar-zestaw-stol-6-krzesel-dab-zloty-czarny-1p-1szt-25762.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25765', 'Pufa okrągła ze schowkiem tapicerowana szara Bono', 'Pufy', 369.0, 'https://www.meblepumo.pl/pl/products/pufa-okragla-ze-schowkiem-tapicerowana-szara-bono-25765.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25773', 'Stół okrągły biały marmur / czarny mat 110 cm Brodway', 'Stoly/Stoły nierozkładane', 788.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-bialy-marmur-czarny-mat-110-cm-brodway-25773.feed10009', 'HALMAR');
