-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24382', 'Zestaw 2 stolików kawowych drewnianych dąb lity sękaty / czarny mat 50 x 40 cm, 45 x 35 cm Seku', 'Stoliki kawowe i ławy/Stoliki kawowe', 489.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-drewnianych-dab-lity-sekaty-czarny-mat-50-x-40-cm-45-x-35-cm-seku-24382.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24387', 'Komoda wysoka z drzwiami biała wysoki połysk 100 cm Ferrada', 'Komody/Komody z drzwiami', 1219.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-wysoki-polysk-100-cm-ferrada-24387.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24392', 'Oświetlenie LED z plastikową listwą do szafki RTV Varazze', 'Dodatki do mebli/Oświetlenie LED', 209.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-z-plastikowa-listwa-do-szafki-rtv-varazze-24392.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24393', 'Oświetlenie LED z plastikową listwą do komody Varazze 3D', 'Dodatki do mebli/Oświetlenie LED', 175.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-z-plastikowa-listwa-do-komody-varazze-3d-24393.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24394', 'Oświetlenie LED z plastikową listwą do komody Varazze 4D', 'Dodatki do mebli/Oświetlenie LED', 192.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-led-z-plastikowa-listwa-do-komody-varazze-4d-24394.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24408', 'Szafka RTV wisząca czarna / dąb wotan mat 180 cm Vidago', 'Szafki RTV', 549.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-czarna-dab-wotan-mat-180-cm-vidago-24408.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24409', 'Szafka RTV wisząca czarna / dąb wotan mat 140 cm Vidago', 'Szafki RTV', 479.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-wiszaca-czarna-dab-wotan-mat-140-cm-vidago-24409.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24414', 'Witryna wisząca przeszklona czarna / dąb wotan mat 40 x 180 cm Vidago', 'Witryny i kredensy/Witryny', 469.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-przeszklona-czarna-dab-wotan-mat-40-x-180-cm-vidago-24414.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24415', 'Witryna wisząca czarna / dąb wotan mat 35 x 90 cm Vidago', 'Witryny i kredensy/Witryny', 339.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-czarna-dab-wotan-mat-35-x-90-cm-vidago-24415.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24416', 'Witryna wisząca przeszklona czarna / dąb wotan mat 35 x 90 cm Vidago', 'Witryny i kredensy/Witryny', 399.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-przeszklona-czarna-dab-wotan-mat-35-x-90-cm-vidago-24416.feed10009', 'High Glossy Furniture');
