-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27081', 'Wieszak stojący na ubrania czarny / srebrny mat 142 cm WU11', 'Wieszaki na ubrania/Wieszaki stojące', 155.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-na-ubrania-czarny-srebrny-mat-142-cm-wu11-27081.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27082', 'Wieszak stojący srebrny / biały mat 117 cm WU13', 'Wieszaki na ubrania/Wieszaki stojące', 259.0, 'https://www.meblepumo.pl/pl/products/wieszak-stojacy-srebrny-bialy-mat-117-cm-wu13-27082.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27102', 'Fotel biurowy siatka szary / czarny Zoom', 'Fotele/Fotele do biurka', 399.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-szary-czarny-zoom-27102.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27103', 'Materac piankowy 90x200 cm Neapol', 'Materace/Materace piankowe', 239.0, 'https://www.meblepumo.pl/pl/products/materac-piankowy-90x200-cm-neapol-27103.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27104', 'Materac piankowy 80x160 cm Turyn', 'Materace/Materace piankowe', 228.0, 'https://www.meblepumo.pl/pl/products/materac-piankowy-80x160-cm-turyn-27104.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27108', 'Taboret kuchenny metalowy czarny Chico', 'Krzesła/Krzesła do jadalni', 91.0, 'https://www.meblepumo.pl/pl/products/taboret-kuchenny-metalowy-czarny-chico-27108.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27109', 'Taboret kuchenny metalowy kremowy Chico', 'Krzesła/Krzesła do jadalni', 91.0, 'https://www.meblepumo.pl/pl/products/taboret-kuchenny-metalowy-kremowy-chico-27109.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27110', 'Taboret kuchenny metalowy jasnobrązowy Chico', 'Krzesła/Krzesła do jadalni', 91.0, 'https://www.meblepumo.pl/pl/products/taboret-kuchenny-metalowy-jasnobrazowy-chico-27110.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27113', 'Krzesło konferencyjne tapicerowane beżowe / srebrny Iso', 'Krzesła/Krzesła biurowe', 199.0, 'https://www.meblepumo.pl/pl/products/krzeslo-konferencyjne-tapicerowane-bezowe-srebrny-iso-27113.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27120', 'Fotel pracowniczy Pop zielony, czarny z regulacją wysokości', 'Fotele/Fotele do biurka', 1459.0, 'https://www.meblepumo.pl/pl/products/fotel-pracowniczy-pop-zielony-czarny-z-regulacja-wysokosci-27120.feed10009', 'HALMAR');
