-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24556', 'Stolik kawowy loftowy dąb wotan / antracyt mat 120 x 55 cm Forest', 'Stoliki kawowe i ławy/Stoliki kawowe', 399.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-dab-wotan-antracyt-mat-120-x-55-cm-forest-24556.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24557', 'Szafka RTV dąb wotan / antracyt mat 170 cm North', 'Szafki RTV', 649.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-wotan-antracyt-mat-170-cm-north-24557.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24558', 'Stolik kawowy prostokątny dąb wotan / antracyt mat 120 x 60 cm Zoja', 'Stoliki kawowe i ławy/Stoliki kawowe', 389.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-dab-wotan-antracyt-mat-120-x-60-cm-zoja-24558.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24559', 'Stolik kawowy prostokątny dąb wotan / czarny mat 120 x 60 cm Zoja', 'Stoliki kawowe i ławy/Stoliki kawowe', 389.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-dab-wotan-czarny-mat-120-x-60-cm-zoja-24559.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24561', 'Oświetlenie do komody Sally 2D niebieskie', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-komody-sally-2d-niebieskie-24561.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24562', 'Oświetlenie do komody Sally 2D białe', 'Dodatki do mebli/Oświetlenie LED', 129.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-komody-sally-2d-biale-24562.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24563', 'Szafka RTV czarna połysk 184 cm Sally', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-polysk-184-cm-sally-24563.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24564', 'Oświetlenie do szafki RTV Sally niebieskie', 'Dodatki do mebli/Oświetlenie LED', 179.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafki-rtv-sally-niebieskie-24564.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24565', 'Oświetlenie do szafki RTV Sally białe', 'Dodatki do mebli/Oświetlenie LED', 179.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-szafki-rtv-sally-biale-24565.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24567', 'Oświetlenie do komody Sally 4S niebieskie', 'Dodatki do mebli/Oświetlenie LED', 119.0, 'https://www.meblepumo.pl/pl/products/oswietlenie-do-komody-sally-4s-niebieskie-24567.feed10009', 'High Glossy Furniture');
