-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26126', 'Krzesło na płozie ekoskóra białe K108', 'Krzesła/Krzesła na płozie', 329.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-biale-k108-26126.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26130', 'Krzesło na płozie ekoskóra białe K147', 'Krzesła/Krzesła na płozie', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-biale-k147-26130.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26131', 'Krzesło na płozie ekoskóra czarne K147', 'Krzesła/Krzesła na płozie', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-czarne-k147-26131.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26132', 'Krzesło na płozie ekoskóra szare K147', 'Krzesła/Krzesła na płozie', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-szare-k147-26132.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26136', 'Krzesło do jadalni ekoskóra czarne / białe K186', 'Krzesła/Krzesła do jadalni', 264.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-czarne-biale-k186-26136.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26140', 'Krzesło na płozie ekoskóra białe K188', 'Krzesła/Krzesła na płozie', 429.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-biale-k188-26140.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26142', 'Krzesło na płozie ekoskóra czarne K188', 'Krzesła/Krzesła na płozie', 429.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-czarne-k188-26142.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26144', 'Krzesło na płozie ekoskóra czarne K194', 'Krzesła/Krzesła na płozie', 499.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-ekoskora-czarne-k194-26144.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26150', 'Krzesło do jadalni ekoskóra cappuccino K202', 'Krzesła/Krzesła do jadalni', 129.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-cappuccino-k202-26150.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26152', 'Krzesło do jadalni ekoskóra kremowe K202', 'Krzesła/Krzesła do jadalni', 129.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-ekoskora-kremowe-k202-26152.feed10009', 'HALMAR');
