-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25881', 'Ława szklana transparentny / biały mat / połysk 110 x 60 cm Diana H', 'Stoliki kawowe i ławy/Ławy', 419.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-bialy-mat-polysk-110-x-60-cm-diana-h-25881.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25882', 'Ława szklana transparentny / czarny mat / połysk 110 x 60 cm Diana H', 'Stoliki kawowe i ławy/Ławy', 419.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-czarny-mat-polysk-110-x-60-cm-diana-h-25882.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25883', 'Ława szklana transparentny / dąb sonoma mat 110 x 60 cm Diana H', 'Stoliki kawowe i ławy/Ławy', 379.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-dab-sonoma-mat-110-x-60-cm-diana-h-25883.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25884', 'Ława szklana transparentny / szklany mat 100 x 60 cm Diana Intro', 'Stoliki kawowe i ławy/Ławy', 329.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-szklany-mat-100-x-60-cm-diana-intro-25884.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25885', 'Ława szklana transparentny / biały mat / połysk 100 x 60 cm Diana Intro', 'Stoliki kawowe i ławy/Ławy', 325.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-bialy-mat-polysk-100-x-60-cm-diana-intro-25885.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25889', 'Ława szklana transparentny / czarny mat / połysk 60 x 60 cm Diana H', 'Stoliki kawowe i ławy/Ławy', 349.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-czarny-mat-polysk-60-x-60-cm-diana-h-25889.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25890', 'Ława szklana transparentny / dąb sonoma mat 60 x 60 cm Diana H', 'Stoliki kawowe i ławy/Ławy', 299.0, 'https://www.meblepumo.pl/pl/products/lawa-szklana-transparentny-dab-sonoma-mat-60-x-60-cm-diana-h-25890.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25891', 'Stół rozkładany dąb naturalny / czarny mat 120 - 180 x 80 cm Dickson', 'Stoly/Stoły rozkładane', 1189.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-czarny-mat-120-180-x-80-cm-dickson-25891.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25892', 'Stół rozkładany dąb naturalny / czarny mat 150 - 210 x 90 cm Dickson', 'Stoly/Stoły rozkładane', 1339.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-czarny-mat-150-210-x-90-cm-dickson-25892.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25893', 'Stół rozkładany biały marmur / czarny mat 160 - 200 x 90 cm Diesel', 'Stoly/Stoły rozkładane', 1979.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-marmur-czarny-mat-160-200-x-90-cm-diesel-25893.feed10009', 'HALMAR');
