-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24028', 'Pudełko do przechowywania deska 32 x 32 x 31 cm Max', 'Pozostałe produkty', 19.0, 'https://www.meblepumo.pl/pl/products/pudelko-do-przechowywania-deska-32-x-32-x-31-cm-max-24028.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24030', 'Biurko narożne białe / szare mat 145 cm Function', 'Biurka/Biurka narożne', 829.0, 'https://www.meblepumo.pl/pl/products/biurko-narozne-biale-szare-mat-145-cm-function-24030.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24033', 'Biurko z szufladami i drzwiami białe mat 110 cm Function', 'Pozostałe produkty', 499.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-i-drzwiami-biale-mat-110-cm-function-24033.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24037', 'Biurko z szufladą i drzwiami białe / szare połysk 110 cm Function Plus', 'Pozostałe produkty', 749.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-i-drzwiami-biale-szare-polysk-110-cm-function-plus-24037.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24043', 'Regał do biurka dąb sonoma / biały mat 79 x 30 x 152 cm Function Plus', 'Regały', 399.0, 'https://www.meblepumo.pl/pl/products/regal-do-biurka-dab-sonoma-bialy-mat-79-x-30-x-152-cm-function-plus-24043.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24050', 'Szafa do przedpokoju biała / dąb mat 85 x 196 cm Malmo', 'Szafy/Szafy uchylne', 1799.0, 'https://www.meblepumo.pl/pl/products/szafa-do-przedpokoju-biala-dab-mat-85-x-196-cm-malmo-24050.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24051', 'Szafka na buty z siedziskiem biała / dąb 97 cm Malmo', 'Szafki na buty', 849.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-z-siedziskiem-biala-dab-97-cm-malmo-24051.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24052', 'Wieszak ścienny z półką biały / dąb mat 97 cm Malmo', 'Wieszaki na ubrania/Wieszaki ścienne', 375.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-z-polka-bialy-dab-mat-97-cm-malmo-24052.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24053', 'Wieszak ścienny biały / dąb mat 97 cm Malmo', 'Wieszaki na ubrania/Wieszaki ścienne', 189.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-bialy-dab-mat-97-cm-malmo-24053.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24054', 'Lustro do przedpokoju 85 x 60 cm Malmo', 'Lustra', 349.0, 'https://www.meblepumo.pl/pl/products/lustro-do-przedpokoju-85-x-60-cm-malmo-24054.feed10009', 'Fato Luxmeble');
