-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16222', 'Sofa 3-osobowa tapicerowana żółta Lily', 'Pozostałe produkty', 2899.0, 'https://www.meblepumo.pl/pl/products/sofa-3-osobowa-tapicerowana-zolta-lily-16222.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16233', 'Sofa 2-osobowa tapicerowana granatowa Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-granatowa-lily-16233.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16234', 'Sofa 2-osobowa tapicerowana grafitowa Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-grafitowa-lily-16234.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16235', 'Sofa 2-osobowa tapicerowana szara Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-szara-lily-16235.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16236', 'Sofa 2-osobowa tapicerowana oliwkowa Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-oliwkowa-lily-16236.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16237', 'Sofa 2-osobowa tapicerowana fioletowa Lily', 'Pozostałe produkty', 2699.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-fioletowa-lily-16237.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16255', 'Łóżko dwuosobowe białe 140x190 cm Naia', 'Łóżka i części/Łóżka', 999.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-biale-140x190-cm-naia-16255.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16257', 'Łóżko jednoosobowe białe 90x190 cm Naia', 'Łóżka i części/Łóżka', 729.0, 'https://www.meblepumo.pl/pl/products/lozko-jednoosobowe-biale-90x190-cm-naia-16257.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16294', 'Biurko z szufladami białe mat 120 cm Aspen 2', 'Biurka/Biurka z szufladami i drzwiami', 664.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-biale-mat-120-cm-aspen-2-16294.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('16299', 'Fotel biurowy siatka czarny / biały Ascot', 'Fotele/Fotele do biurka', 214.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-czarny-bialy-ascot-16299.feed10009', 'HALMAR');
