-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27171', 'Fotel wypoczynkowy tapicerowany granatowy Delgado', 'Fotele/Fotele wypoczynkowe', 1119.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-granatowy-delgado-27171.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27172', 'Fotel wypoczynkowy tapicerowany musztardowy Delgado', 'Fotele/Fotele wypoczynkowe', 1119.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-musztardowy-delgado-27172.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27173', 'Fotel wypoczynkowy tapicerowany szary Delgado', 'Fotele/Fotele wypoczynkowe', 1119.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-delgado-27173.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27174', 'Fotel wypoczynkowy tapicerowany różowy Delgado', 'Fotele/Fotele wypoczynkowe', 1119.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-rozowy-delgado-27174.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27187', 'Stół rozkładany biały mat 160 - 228 x 90 cm Florian', 'Stoly/Stoły rozkładane', 845.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-160-228-x-90-cm-florian-27187.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27192', 'Stół rozkładany dąb craft mat 160 - 240 x 90 cm Fryderyk', 'Stoly/Stoły rozkładane', 1229.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-craft-mat-160-240-x-90-cm-fryderyk-27192.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27193', 'Stół rozkładany biały mat 100 - 135 x 60 cm Gino', 'Stoly/Stoły rozkładane', 519.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-100-135-x-60-cm-gino-27193.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27194', 'Stół rozkładany dąb sonoma mat 100 - 135 x 60 cm Gino', 'Stoly/Stoły rozkładane', 519.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-sonoma-mat-100-135-x-60-cm-gino-27194.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27196', 'Stół rozkładany biały mat 80 - 160 x 80 cm Gracjan', 'Stoly/Stoły rozkładane', 624.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-mat-80-160-x-80-cm-gracjan-27196.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27200', 'Stół rozkładany dąb sonoma / biały mat 80 - 160 x 80 cm Gracjan', 'Stoly/Stoły rozkładane', 624.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-sonoma-bialy-mat-80-160-x-80-cm-gracjan-27200.feed10009', 'HALMAR');
