-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26313', 'Krzesło do jadalni tapicerowane zielone K384', 'Krzesła/Krzesła do jadalni', 242.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k384-26313.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26327', 'Krzesło na płozie tapicerowane kremowe / szare K390', 'Krzesła/Krzesła na płozie', 329.0, 'https://www.meblepumo.pl/pl/products/krzeslo-na-plozie-tapicerowane-kremowe-szare-k390-26327.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26331', 'Krzesło do jadalni drewniane tapicerowane jasny dąb / szare K396', 'Krzesła/Krzesła do jadalni', 519.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-jasny-dab-szare-k396-26331.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26332', 'Krzesło do jadalni drewniane tapicerowane orzech / czarne K396', 'Krzesła/Krzesła do jadalni', 519.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-orzech-czarne-k396-26332.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26342', 'Krzesło ogrodowe tapicerowane rattan czarne / szare K401', 'Krzesła/Krzesła ogrodowe', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-tapicerowane-rattan-czarne-szare-k401-26342.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26343', 'Krzesło ogrodowe tapicerowane rattan naturalne / czarne K401', 'Krzesła/Krzesła ogrodowe', 259.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-tapicerowane-rattan-naturalne-czarne-k401-26343.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26344', 'Krzesło do jadalni tapicerowane beżowe K402', 'Krzesła/Krzesła do jadalni', 194.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-bezowe-k402-26344.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26345', 'Krzesło do jadalni tapicerowane szare K402', 'Krzesła/Krzesła do jadalni', 194.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k402-26345.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26346', 'Krzesło do jadalni tapicerowane zielone K404', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k404-26346.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26347', 'Krzesło do jadalni tapicerowane szare K404', 'Krzesła/Krzesła do jadalni', 299.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k404-26347.feed10009', 'HALMAR');
