-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23855', 'Krzesło do jadalni tapicerowane zielone K365', 'Krzesła/Krzesła do jadalni', 349.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-zielone-k365-23855.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23856', 'Krzesło do jadalni tapicerowane szare K365', 'Krzesła/Krzesła do jadalni', 349.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k365-23856.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23857', 'Krzesło do jadalni tapicerowane szare K381', 'Krzesła/Krzesła do jadalni', 389.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k381-23857.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23863', 'Konsola z szufladami dąb / antracyt mat 100 cm Denver', 'Toaletki i konsole/Konsole ', 599.0, 'https://www.meblepumo.pl/pl/products/konsola-z-szufladami-dab-antracyt-mat-100-cm-denver-23863.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23864', 'Stolik kawowy z szufladą dąb artisan / antracyt mat 100 x 40 cm Denver', 'Stoliki kawowe i ławy/Stoliki kawowe', 759.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-dab-artisan-antracyt-mat-100-x-40-cm-denver-23864.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23867', 'Komoda z drzwiami dąb / antracyt mat 80 cm Denver', 'Komody/Komody z drzwiami', 499.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-antracyt-mat-80-cm-denver-23867.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23868', 'Sofa ogrodowa 2-osobowa naturalna / wielobarwna Gardena', 'Sofy i narożniki/Sofy ogrodowe', 1279.0, 'https://www.meblepumo.pl/pl/products/sofa-ogrodowa-2-osobowa-naturalna-wielobarwna-gardena-23868.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23871', 'Fotel ogrodowy rattanowy naturalny / czarny K400', 'Fotele/Fotele ogrodowe', 459.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-rattanowy-naturalny-czarny-k400-23871.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23873', 'Stół ogrodowy szklany brązowy mat 74 cm Midas', 'Stoly/Stoły ogrodowe', 389.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-szklany-brazowy-mat-74-cm-midas-23873.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23874', 'Krzesło ogrodowe rattanowe brązowe Midas', 'Krzesła/Krzesła ogrodowe', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-rattanowe-brazowe-midas-23874.feed10009', 'HALMAR');
