-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('4645', 'Kontenerek pod biurko dąb sonoma mat 48 x 49 x 68 cm Prima', 'Kontenerki', 699.0, 'https://www.meblepumo.pl/pl/products/kontenerek-pod-biurko-dab-sonoma-mat-48-x-49-x-68-cm-prima-4645.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('4860', 'Zagłówek do łóżka czarny 180x200 cm Style', 'Łóżka i części/Części do łóżek', 229.0, 'https://www.meblepumo.pl/pl/products/zaglowek-do-lozka-czarny-180x200-cm-style-4860.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('6463', 'Stelaż do łóżka 90x200 cm Natura NV', 'Stelaże', 299.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-90x200-cm-natura-nv-6463.feed10009', 'Fra-Mar');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('6652', 'Komoda z szufladami i drzwiami czarna mat / wysoki połysk 132 cm Simple', 'Komody/Komody z szufladami i drzwiami', 1229.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-czarna-mat-wysoki-polysk-132-cm-simple-6652.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('7881', 'Witryna wisząca biała / czarna połysk 90 x 35 cm Vilalba', 'Pozostałe produkty', 178.0, 'https://www.meblepumo.pl/pl/products/witryna-wiszaca-biala-czarna-polysk-90-x-35-cm-vilalba-7881.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8093', 'Stelaż do łóżka 80x200 cm Natura NV', 'Stelaże', 279.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-80x200-cm-natura-nv-8093.feed10009', 'Fra-Mar');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8094', 'Stelaż do łóżka 100x200 cm Natura NV', 'Stelaże', 329.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-100x200-cm-natura-nv-8094.feed10009', 'Fra-Mar');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8095', 'Stelaż do łóżka 120x200 cm Natura NV', 'Stelaże', 349.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-120x200-cm-natura-nv-8095.feed10009', 'Fra-Mar');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8096', 'Stelaż do łóżka 140x190 cm Natura NV', 'Stelaże', 369.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-140x190-cm-natura-nv-8096.feed10009', 'Fra-Mar');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('8097', 'Stelaż do łóżka 100x200 cm Futura NV', 'Łóżka i części/Stelaże do łóżek', 499.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-100x200-cm-futura-nv-8097.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
