-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25090', 'Komoda z szufladami czarna / dąb wotan mat / wysoki połysk 160 cm Image', 'Komody/Komody z szufladami i drzwiami', 949.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-czarna-dab-wotan-mat-wysoki-polysk-160-cm-image-25090.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25091', 'Szafka RTV czarna / dąb wotan mat / połysk 180 cm Image', 'Szafki RTV', 699.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-czarna-dab-wotan-mat-polysk-180-cm-image-25091.feed10009', 'designoo');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25092', 'Komoda z drzwiami dąb wotan mat 190 cm Fiori', 'Komody/Komody z drzwiami', 1339.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-wotan-mat-190-cm-fiori-25092.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25093', 'Szafka RTV z frezowanym frontem dąb wotan mat 190 cm Fiori', 'Szafki RTV', 1089.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-frezowanym-frontem-dab-wotan-mat-190-cm-fiori-25093.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25094', 'Komoda z drzwiami dąb wotan mat 152 cm Fiori', 'Komody/Komody z drzwiami', 1269.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-wotan-mat-152-cm-fiori-25094.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25095', 'Komoda z drzwiami czarna mat 190 cm Fiori', 'Komody/Komody z drzwiami', 1339.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-190-cm-fiori-25095.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25096', 'Szafka RTV z frezowanym frontem czarna mat 190 cm Fiori', 'Szafki RTV', 1089.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-frezowanym-frontem-czarna-mat-190-cm-fiori-25096.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25097', 'Komoda z drzwiami czarna mat 152 cm Fiori', 'Komody/Komody z drzwiami', 1269.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-czarna-mat-152-cm-fiori-25097.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25099', 'Szafka RTV z frezowanym frontem biała mat 190 cm Fiori', 'Szafki RTV', 899.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-frezowanym-frontem-biala-mat-190-cm-fiori-25099.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25100', 'Komoda z drzwiami biała mat 152 cm Fiori', 'Komody/Komody z drzwiami', 1269.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-mat-152-cm-fiori-25100.feed10009', 'High Glossy Furniture');
