-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28330', 'Łóżko tapicerowane szare 140x200 cm Nubo', 'Łóżka i części/Łóżka', 1999.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-140x200-cm-nubo-28330.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28331', 'Łóżko tapicerowane szare 180x200 cm Nubo', 'Łóżka i części/Łóżka', 2099.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-szare-180x200-cm-nubo-28331.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28332', 'Szafka nocna kaszmir mat 60 cm Bruno', 'Szafki nocne', 549.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-kaszmir-mat-60-cm-bruno-28332.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28333', 'Komoda z szufladami kaszmir mat 110 cm Bruno', 'Komody/Komody z szufladami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-kaszmir-mat-110-cm-bruno-28333.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28334', 'Łóżko tapicerowane beżowe 160x200 cm Bruno', 'Łóżka i części/Łóżka', 2199.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-bezowe-160x200-cm-bruno-28334.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28335', 'Szafa trzydrzwiowa kaszmir mat 138 x 242 cm Bruno', 'Szafy/Szafy uchylne', 1499.0, 'https://www.meblepumo.pl/pl/products/szafa-trzydrzwiowa-kaszmir-mat-138-x-242-cm-bruno-28335.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28336', 'Szafa czterodrzwiowa kaszmir mat 183 x 242 cm Bruno', 'Szafy/Szafy uchylne', 2199.0, 'https://www.meblepumo.pl/pl/products/szafa-czterodrzwiowa-kaszmir-mat-183-x-242-cm-bruno-28336.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28337', 'Lustro 90 x 60 cm Bruno', 'Lustra', 359.0, 'https://www.meblepumo.pl/pl/products/lustro-90-x-60-cm-bruno-28337.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28338', 'Komoda z szufladami i drzwiami biała wysoki połysk 200 cm Roma', 'Komody/Komody z szufladami', 1379.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-200-cm-roma-28338.feed10009', 'MiroMark');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28339', 'Komoda z szufladami i drzwiami biała wysoki połysk 160 cm Roma', 'Komody/Komody z szufladami', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-wysoki-polysk-160-cm-roma-28339.feed10009', 'MiroMark');
