-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28018', 'Półka wisząca zielona / dąb Evoke mat 156 x 22 cm Emerald', 'Półki wiszące', 189.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-zielona-dab-evoke-mat-156-x-22-cm-emerald-28018.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28019', 'Witryna jednodrzwiowa ciemnozielona / dąb evoke mat 69 x 198 cm Emerald', 'Witryny i kredensy/Witryny', 1269.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-ciemnozielona-dab-evoke-mat-69-x-198-cm-emerald-28019.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28020', 'Stolik kawowy z szufladą zielony / dąb mat 101 x 60 cm Emerald', 'Stoliki kawowe i ławy/Stoliki kawowe', 929.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-szuflada-zielony-dab-mat-101-x-60-cm-emerald-28020.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28021', 'Szafka na buty z siedziskiem zielona / dąb Evoke 77 cm Emerald', 'Szafki na buty', 499.0, 'https://www.meblepumo.pl/pl/products/szafka-na-buty-z-siedziskiem-zielona-dab-evoke-77-cm-emerald-28021.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28022', 'Komoda na buty Emerald, 77 x 39 x 102 cm, ciemny zielony, dąb Evoke', 'Szafki na buty', 819.0, 'https://www.meblepumo.pl/pl/products/komoda-na-buty-emerald-77-x-39-x-102-cm-ciemny-zielony-dab-evoke-28022.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28023', 'Wieszak ścienny z półką zielony / dąb Evoke mat 77 cm Emerald', 'Wieszaki na ubrania/Wieszaki ścienne', 599.0, 'https://www.meblepumo.pl/pl/products/wieszak-scienny-z-polka-zielony-dab-evoke-mat-77-cm-emerald-28023.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28024', 'Lustro w ramie zielonej / dąb Evoke 77 x 68 cm Emerald', 'Lustra', 309.0, 'https://www.meblepumo.pl/pl/products/lustro-w-ramie-zielonej-dab-evoke-77-x-68-cm-emerald-28024.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28025', 'Poduszka na ławkę szara 49 x 32 cm Emerald', 'Dodatki do mebli/Części do mebli', 79.0, 'https://www.meblepumo.pl/pl/products/poduszka-na-lawke-szara-49-x-32-cm-emerald-28025.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28026', 'Szafa z lustrem zielona / dąb mat 77 x 198 cm Emerald', 'Szafy/Szafy uchylne', 1299.0, 'https://www.meblepumo.pl/pl/products/szafa-z-lustrem-zielona-dab-mat-77-x-198-cm-emerald-28026.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28027', 'Komoda z drzwiami kaszmir mat 150 cm Silk', 'Komody/Komody z drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-kaszmir-mat-150-cm-silk-28027.feed10009', 'Vivaladesign');
