-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26629', 'Zestaw 2 stolików kawowych okrągłych dąb złoty / czarny mat 59 cm, 41 cm Mentona 2', 'Stoliki kawowe i ławy/Stoliki kawowe', 287.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-dab-zloty-czarny-mat-59-cm-41-cm-mentona-2-26629.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26630', 'Zestaw 2 stolików kawowych okrągłych dymiony / srebrny mat / połysk 80 cm, 60 cm Mercury', 'Stoliki kawowe i ławy/Stoliki kawowe', 1169.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-stolikow-kawowych-okraglych-dymiony-srebrny-mat-polysk-80-cm-60-cm-mercury-26630.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26631', 'Stół okrągły rozkładany dąb złoty / czarny mat 120 - 160 x 120 cm Mercy', 'Stoly/Stoły rozkładane', 2249.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-rozkladany-dab-zloty-czarny-mat-120-160-x-120-cm-mercy-26631.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26635', 'Regał na książki beżowy mat 105 x 29 x 142 cm Metro', 'Regały', 127.0, 'https://www.meblepumo.pl/pl/products/regal-na-ksiazki-bezowy-mat-105-x-29-x-142-cm-metro-26635.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26644', 'Stolik kawowy rozkładany dąb złoty / biały mat / połysk 80 cm Michelle', 'Stoliki kawowe i ławy/Stoliki kawowe', 1234.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-rozkladany-dab-zloty-bialy-mat-polysk-80-cm-michelle-26644.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26655', 'Stół rozkładany biały połysk 160 - 220 x 90 cm Mistral', 'Stoly/Stoły rozkładane', 2423.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-polysk-160-220-x-90-cm-mistral-26655.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26659', 'Stół ogrodowy szklany transparentny / brązowy mat 70 x 70 cm Mobil', 'Stoly/Stoły ogrodowe', 313.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-szklany-transparentny-brazowy-mat-70-x-70-cm-mobil-26659.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26663', 'Łóżko tapicerowane z szufladą białe 160x200 cm Modena 2', 'Łóżka i części/Łóżka', 2289.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-biale-160x200-cm-modena-2-26663.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26664', 'Łóżko tapicerowane z szufladą zielone 160x200 cm Modena 3', 'Łóżka i części/Łóżka', 2190.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-zielone-160x200-cm-modena-3-26664.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26665', 'Łóżko tapicerowane z szufladą szare 160x200 cm Modena 3', 'Łóżka i części/Łóżka', 2190.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-modena-3-26665.feed10009', 'HALMAR');
