-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25372', 'Krzesło do jadalni tapicerowane musztardowe K521', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-musztardowe-k521-25372.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25373', 'Krzesło do jadalni tapicerowane szare K521', 'Krzesła/Krzesła do jadalni', 189.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-tapicerowane-szare-k521-25373.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25375', 'Krzesło obrotowe do jadalni tapicerowane brązowe K523', 'Krzesła/Krzesła do jadalni', 599.0, 'https://www.meblepumo.pl/pl/products/krzeslo-obrotowe-do-jadalni-tapicerowane-brazowe-k523-25375.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25376', 'Krzesło obrotowe do jadalni tapicerowane szare K523', 'Krzesła/Krzesła do jadalni', 599.0, 'https://www.meblepumo.pl/pl/products/krzeslo-obrotowe-do-jadalni-tapicerowane-szare-k523-25376.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25382', 'Fotel bujany na płozie biały Liberto 3', 'Fotele/Fotele bujane', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-bujany-na-plozie-bialy-liberto-3-25382.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25383', 'Stół okrągły dąb naturalny mat 120 cm Lopez', 'Stoly/Stoły nierozkładane', 1719.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-dab-naturalny-mat-120-cm-lopez-25383.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25384', 'Stół rozkładany czarny marmur / orzech mat 140 - 200 x 82 cm Lozano', 'Stoly/Stoły rozkładane', 1699.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-czarny-marmur-orzech-mat-140-200-x-82-cm-lozano-25384.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25385', 'Fotel wypoczynkowy metalowy biały / szary Melby', 'Fotele/Fotele wypoczynkowe', 539.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-metalowy-bialy-szary-melby-25385.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25389', 'Fotel wypoczynkowy tapicerowany kremowy Merry', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-kremowy-merry-25389.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('25390', 'Fotel wypoczynkowy tapicerowany szary Merry', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-merry-25390.feed10009', 'HALMAR');
