-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23876', 'Stolik kawowy szklany czarny / dąb złoty mat 120 x 60 cm Zenga', 'Stoliki kawowe i ławy/Stoliki kawowe', 949.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-czarny-dab-zloty-mat-120-x-60-cm-zenga-23876.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23888', 'Łóżko dwuosobowe szare / orzech 160x200 cm Cassidy', 'Łóżka i części/Łóżka', 1939.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-szare-orzech-160x200-cm-cassidy-23888.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23889', 'Łóżko tapicerowane z szufladą zielone 160x200 cm Grace', 'Łóżka i części/Łóżka', 2379.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-zielone-160x200-cm-grace-23889.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23890', 'Łóżko tapicerowane z szufladą szare 160x200 cm Grace', 'Łóżka i części/Łóżka', 2379.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-z-szuflada-szare-160x200-cm-grace-23890.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23910', 'Komoda z szufladami biała / beton mat / wysoki połysk 154 cm Naia', 'Pozostałe produkty', 1099.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-beton-mat-wysoki-polysk-154-cm-naia-23910.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23911', 'Szafka nocna szary beton / biała mat / wysoki połysk 40 cm Naia', 'Szafki nocne', 349.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-szary-beton-biala-mat-wysoki-polysk-40-cm-naia-23911.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23912', 'Biurko z szufladą i drzwiami białe wysoki połysk 110 cm Function Plus', 'Pozostałe produkty', 689.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-i-drzwiami-biale-wysoki-polysk-110-cm-function-plus-23912.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23913', 'Fotel wypoczynkowy tapicerowany zielony Osso', 'Fotele/Fotele wypoczynkowe', 1899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-osso-23913.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23915', 'Fotel wypoczynkowy tapicerowany żólty Osso', 'Fotele/Fotele wypoczynkowe', 1899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zolty-osso-23915.feed10009', 'Meble tapicerowane');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('23916', 'Fotel wypoczynkowy tapicerowany szary Osso', 'Fotele/Fotele wypoczynkowe', 1899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-osso-23916.feed10009', 'Meble tapicerowane');
