-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19186', 'Fotel obrotowy ekoskóra czarny Luxor', 'Fotele/Fotele wypoczynkowe', 2129.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-ekoskora-czarny-luxor-19186.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19187', 'Fotel obrotowy ekoskóra czerwony Luxor', 'Fotele/Fotele wypoczynkowe', 2129.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-ekoskora-czerwony-luxor-19187.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19188', 'Fotel obrotowy ekoskóra zielony Luxor', 'Fotele/Fotele wypoczynkowe', 2129.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-ekoskora-zielony-luxor-19188.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19189', 'Fotel obrotowy ekoskóra brązowy Luxor', 'Fotele/Fotele wypoczynkowe', 2129.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-ekoskora-brazowy-luxor-19189.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19209', 'Fotel wypoczynkowy tapicerowany szary Candy', 'Fotele/Fotele wypoczynkowe', 729.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-candy-19209.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19210', 'Fotel wypoczynkowy tapicerowany szary Cotto', 'Fotele/Fotele wypoczynkowe', 729.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-cotto-19210.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19211', 'Fotel wypoczynkowy tapicerowany niebieski Cotto', 'Fotele/Fotele wypoczynkowe', 729.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-niebieski-cotto-19211.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19227', 'Fotel kubełkowy tapicerowany szary / czarny Soft 2', 'Fotele/Fotele kubełkowe', 819.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-szary-czarny-soft-2-19227.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19228', 'Sofa 2-osobowa tapicerowana szara Smooth 2', 'Sofy i narożniki/Sofy 2-osobowe', 1409.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-szara-smooth-2-19228.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19231', 'Fotel kubełkowy tapicerowany wielokolorowy Butterfly', 'Fotele/Fotele kubełkowe', 1229.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-wielokolorowy-butterfly-19231.feed10009', 'HALMAR');
