-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19098', 'Stolik kawowy loftowy dąb san remo mat 110 x 64 cm Capri', 'Stoliki kawowe i ławy/Stoliki kawowe', 485.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-dab-san-remo-mat-110-x-64-cm-capri-19098.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19103', 'Stolik kawowy loftowy dąb złoty mat 110 x 60 cm Emily', 'Stoliki kawowe i ławy/Stoliki kawowe', 569.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-dab-zloty-mat-110-x-60-cm-emily-19103.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19112', 'Fotel kubełkowy tapicerowany brązowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-brazowy-tana-19112.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19113', 'Sofa 2-osobowa tapicerowana brązowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-brazowa-tana-19113.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19114', 'Fotel kubełkowy tapicerowany turkusowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-turkusowy-tana-19114.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19115', 'Sofa 2-osobowa tapicerowana turkusowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-turkusowa-tana-19115.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19116', 'Sofa 2-osobowa tapicerowana granatowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-granatowa-tana-19116.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19117', 'Fotel kubełkowy tapicerowany granatowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-granatowy-tana-19117.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19118', 'Fotel kubełkowy tapicerowany grafitowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-grafitowy-tana-19118.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19119', 'Sofa 2-osobowa tapicerowana grafitowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-grafitowa-tana-19119.feed10009', 'Scandinavian Style Design');
