-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27936', 'Szafka RTV z lamelalami dąb artisan / antracyt mat 138 cm Medan', 'Szafki RTV', 999.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-z-lamelalami-dab-artisan-antracyt-mat-138-cm-medan-27936.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27937', 'Stolik kawowy z półką dąb artisan / antracyt mat 110 x 42 cm Medan', 'Stoliki kawowe i ławy/Stoliki kawowe', 727.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-artisan-antracyt-mat-110-x-42-cm-medan-27937.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27938', 'Komoda wysoka z drzwiami i szufladą dąb artisan / antracyt mat 80 cm Medan', 'Komody/Komody z szufladami i drzwiami', 1599.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-i-szuflada-dab-artisan-antracyt-mat-80-cm-medan-27938.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27939', 'Witryna dwudrzwiowa z szufladami dąb artisan / antracyt mat 92 x 198 cm Medan', 'Witryny i kredensy/Witryny', 2299.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-z-szufladami-dab-artisan-antracyt-mat-92-x-198-cm-medan-27939.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27940', 'Komoda z szufladami i drzwiami dąb artisan / antracyt mat 160 cm Medan', 'Komody/Komody z szufladami i drzwiami', 1739.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-dab-artisan-antracyt-mat-160-cm-medan-27940.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27941', 'Komoda z drzwiami dąb artisan / antracyt mat 80 cm Medan', 'Komody/Komody z drzwiami', 899.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-artisan-antracyt-mat-80-cm-medan-27941.feed10009', 'Fontini ');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27944', 'Szafka RTV dąb / szara mat 180 cm Luno', 'Szafki RTV', 829.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-szara-mat-180-cm-luno-27944.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27945', 'Komoda z drzwiami dąb pradawny / beton ciemny mat 180 cm Luno', 'Komody/Komody z drzwiami', 999.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-dab-pradawny-beton-ciemny-mat-180-cm-luno-27945.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27946', 'Półka wisząca dąb pradawny / szara mat 130 x 20 cm Luno', 'Półki wiszące', 149.0, 'https://www.meblepumo.pl/pl/products/polka-wiszaca-dab-pradawny-szara-mat-130-x-20-cm-luno-27946.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27947', 'Stolik kawowy z półką dąb / szary mat 90 x 50 cm Luno', 'Stoliki kawowe i ławy/Stoliki kawowe', 449.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-szary-mat-90-x-50-cm-luno-27947.feed10009', 'High Glossy Furniture');
