-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26007', 'Zestaw 2 puf okrągłych ze schowkiem tapicerowanych żółtych Grado', 'Pufy', 389.0, 'https://www.meblepumo.pl/pl/products/zestaw-2-puf-okraglych-ze-schowkiem-tapicerowanych-zoltych-grado-26007.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26012', 'Fotel wypoczynkowy tapicerowany kremowy Grifon 2', 'Fotele/Fotele wypoczynkowe', 753.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-kremowy-grifon-2-26012.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26013', 'Fotel wypoczynkowy tapicerowany kremowy Grifon', 'Fotele/Fotele wypoczynkowe', 765.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-kremowy-grifon-26013.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26016', 'Hoker z oparciem ekoskóra czarny / orzech / srebrny H100', 'Hokery', 539.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-ekoskora-czarny-orzech-srebrny-h100-26016.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26017', 'Hoker z oparciem tapicerowany zielony / czarny H101', 'Hokery', 249.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-czarny-h101-26017.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26019', 'Hoker z oparciem tapicerowany granatowy / czarny H101', 'Hokery', 249.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-granatowy-czarny-h101-26019.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26020', 'Hoker z oparciem tapicerowany szary / czarny H101', 'Hokery', 249.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-szary-czarny-h101-26020.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26021', 'Hoker z oparciem tapicerowany zielony / czarny H102', 'Hokery', 243.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-zielony-czarny-h102-26021.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26022', 'Hoker z oparciem tapicerowany czarny H102', 'Hokery', 243.0, 'https://www.meblepumo.pl/pl/products/hoker-z-oparciem-tapicerowany-czarny-h102-26022.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26024', 'Hoker do kuchni tapicerowany szary / czarny H102', 'Hokery', 243.0, 'https://www.meblepumo.pl/pl/products/hoker-do-kuchni-tapicerowany-szary-czarny-h102-26024.feed10009', 'HALMAR');
