-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27905', 'Szafka RTV szara / dąb mat 117 cm Bodo', 'Szafki RTV', 463.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-szara-dab-mat-117-cm-bodo-27905.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27906', 'Szafka nocna biała mat 50 cm Bodo', 'Szafki nocne', 349.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-biala-mat-50-cm-bodo-27906.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27907', 'Szafka nocna szara mat 50 cm Bodo', 'Szafki nocne', 369.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-szara-mat-50-cm-bodo-27907.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27908', 'Komoda z szufladami biała mat 99 cm Bodo', 'Komody/Komody z szufladami', 659.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-mat-99-cm-bodo-27908.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27909', 'Komoda z szufladami szara mat 99 cm Bodo', 'Komody/Komody z szufladami', 699.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-szara-mat-99-cm-bodo-27909.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27910', 'Komoda z szufladami biała mat 50 cm Bodo', 'Komody/Komody z szufladami', 649.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-biala-mat-50-cm-bodo-27910.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27911', 'Komoda z szufladami szara mat 50 cm Bodo', 'Komody/Komody z szufladami', 679.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-szara-mat-50-cm-bodo-27911.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27912', 'Szafa dwudrzwiowa z szufladami biała mat 99 x 200 cm Bodo', 'Szafy/Szafy uchylne', 1189.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-z-szufladami-biala-mat-99-x-200-cm-bodo-27912.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27913', 'Szafa dwudrzwiowa z szufladami szara mat 99 x 200 cm Bodo', 'Szafy/Szafy uchylne', 1279.0, 'https://www.meblepumo.pl/pl/products/szafa-dwudrzwiowa-z-szufladami-szara-mat-99-x-200-cm-bodo-27913.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27914', 'Biurko z regulacją wysokości elektryczne dąb wotan mat 121 cm Luna', 'Biurka/Biurka z regulacją wysokości', 1099.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-dab-wotan-mat-121-cm-luna-27914.feed10009', 'High Glossy Furniture');
