-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20225', 'Stół rozkładany antracyt połysk 137 - 185 x 90 cm Prestige', 'Stoly/Stoły rozkładane', 1459.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-antracyt-polysk-137-185-x-90-cm-prestige-20225.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20227', 'Stół do jadalni biały połysk 180 x 90 cm Prestige', 'Stoly/Stoły nierozkładane', 1359.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-bialy-polysk-180-x-90-cm-prestige-20227.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20228', 'Stół do jadalni antracyt połysk 180 x 90 cm Prestige', 'Stoly/Stoły nierozkładane', 1399.0, 'https://www.meblepumo.pl/pl/products/stol-do-jadalni-antracyt-polysk-180-x-90-cm-prestige-20228.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20230', 'Stolik kawowy prostokątny biały połysk 122 x 65 cm Prestige', 'Stoliki kawowe i ławy/Stoliki kawowe', 600.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-bialy-polysk-122-x-65-cm-prestige-20230.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20231', 'Stolik kawowy prostokątny antracyt połysk 122 x 65 cm Prestige', 'Stoliki kawowe i ławy/Stoliki kawowe', 899.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-antracyt-polysk-122-x-65-cm-prestige-20231.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20238', 'Komoda z drzwiami biała / orzech wysoki połysk / mat 110 cm Fondi', 'Pozostałe produkty', 549.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-orzech-wysoki-polysk-mat-110-cm-fondi-20238.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20240', 'Komoda wysoka z drzwiami biała / orzech wysoki połysk / mat 110 cm Fondi', 'Pozostałe produkty', 893.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-biala-orzech-wysoki-polysk-mat-110-cm-fondi-20240.feed10009', 'Italia Trend');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20245', 'Fotel biurowy ekoskóra brązowy Denzel', 'Fotele/Fotele do biurka', 329.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-brazowy-denzel-20245.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20246', 'Fotel biurowy ekoskóra czarny Denzel', 'Fotele/Fotele do biurka', 329.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-czarny-denzel-20246.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('20250', 'Lustro w ramie białej 170 x 75 cm Amaretto', 'Lustra', 739.0, 'https://www.meblepumo.pl/pl/products/lustro-w-ramie-bialej-170-x-75-cm-amaretto-20250.feed10009', 'Italia Trend');
