-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24662', 'Szafka RTV dąb mat 167 cm Clever', 'Szafki RTV', 2769.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-dab-mat-167-cm-clever-24662.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24663', 'Regał do salonu dąb naturalny mat 97 x 37 x 196 cm Clever', 'Regały', 3599.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-dab-naturalny-mat-97-x-37-x-196-cm-clever-24663.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24664', 'Krzesło do jadalni drewniane tapicerowane czarny / dąb naturalny Smart KR', 'Krzesła/Krzesła do jadalni', 659.0, 'https://www.meblepumo.pl/pl/products/krzeslo-do-jadalni-drewniane-tapicerowane-czarny-dab-naturalny-smart-kr-24664.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24665', 'Stół rozkładany dąb naturalny / czarny mat 170 - 250 x 100 cm Clever', 'Stoly/Stoły rozkładane', 4239.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-czarny-mat-170-250-x-100-cm-clever-24665.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24666', 'Biurko z szufladą dąb naturalny mat 117 cm Clever', 'Biurka/Biurka z szufladami i drzwiami', 2699.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szuflada-dab-naturalny-mat-117-cm-clever-24666.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24668', 'Stół ogrodowy szklany transparentny mat 150 x 90 x 72 cm Mosler', 'Stoly/Stoły ogrodowe', 489.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-szklany-transparentny-mat-150-x-90-x-72-cm-mosler-24668.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24669', 'Leżak ogrodowy siatka szary Mosler', 'Krzesła/Krzesła ogrodowe', 429.0, 'https://www.meblepumo.pl/pl/products/lezak-ogrodowy-siatka-szary-mosler-24669.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24670', 'Krzesło ogrodowe siatka szare Mosler', 'Krzesła/Krzesła ogrodowe', 139.0, 'https://www.meblepumo.pl/pl/products/krzeslo-ogrodowe-siatka-szare-mosler-24670.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24672', 'Fotel ogrodowy rattanowy naturalny Bari', 'Fotele/Fotele ogrodowe', 289.0, 'https://www.meblepumo.pl/pl/products/fotel-ogrodowy-rattanowy-naturalny-bari-24672.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('24673', 'Komoda z drzwiami biała / szara wysoki połysk / mat 184 cm Verden', 'Komody/Komody z drzwiami', 1059.0, 'https://www.meblepumo.pl/pl/products/komoda-z-drzwiami-biala-szara-wysoki-polysk-mat-184-cm-verden-24673.feed10009', 'Italia Trend');
