-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27948', 'Komoda wysoka z drzwiami dąb pradawny / beton ciemny mat 90 cm Luno', 'Komody/Komody z drzwiami', 659.0, 'https://www.meblepumo.pl/pl/products/komoda-wysoka-z-drzwiami-dab-pradawny-beton-ciemny-mat-90-cm-luno-27948.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27949', 'Regał do salonu dąb pradawny / beton ciemny mat 50 x 38 x 182 cm Luno', 'Regały', 679.0, 'https://www.meblepumo.pl/pl/products/regal-do-salonu-dab-pradawny-beton-ciemny-mat-50-x-38-x-182-cm-luno-27949.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27950', 'Biurko z regulacją wysokości elektryczne san sebastian mat 121 cm Luna', 'Biurka/Biurka z regulacją wysokości', 1099.0, 'https://www.meblepumo.pl/pl/products/biurko-z-regulacja-wysokosci-elektryczne-san-sebastian-mat-121-cm-luna-27950.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27952', 'Regał biurowy jackson hickory / biały mat 40 x 34 x 205 cm Sign', 'Regały', 559.0, 'https://www.meblepumo.pl/pl/products/regal-biurowy-jackson-hickory-bialy-mat-40-x-34-x-205-cm-sign-27952.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27953', 'Regał biurowy szary / jackson hickory mat 40 x 34 x 205 cm Sign', 'Regały', 589.0, 'https://www.meblepumo.pl/pl/products/regal-biurowy-szary-jackson-hickory-mat-40-x-34-x-205-cm-sign-27953.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27955', 'Blat do biurka jackson hickory 150 x 60 cm Sign', 'Biurka/Części do biurek', 279.0, 'https://www.meblepumo.pl/pl/products/blat-do-biurka-jackson-hickory-150-x-60-cm-sign-27955.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27956', 'Paski podporowe do blatów białe 150 cm Sign', 'Dodatki do mebli/Części do mebli', 239.0, 'https://www.meblepumo.pl/pl/products/paski-podporowe-do-blatow-biale-150-cm-sign-27956.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27957', 'Noga do biurka biała 60 x 71 cm Sign', 'Biurka/Części do biurek', 199.0, 'https://www.meblepumo.pl/pl/products/noga-do-biurka-biala-60-x-71-cm-sign-27957.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27959', 'Paski podporowe dla blatów do biurka Sign 150 x 6 x 2 cm, szary mat', 'Dodatki do mebli/Części do mebli', 239.0, 'https://www.meblepumo.pl/pl/products/paski-podporowe-dla-blatow-do-biurka-sign-150-x-6-x-2-cm-szary-mat-27959.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27961', 'Noga do biurka szara 60 x 71 cm Sign', 'Biurka/Części do biurek', 199.0, 'https://www.meblepumo.pl/pl/products/noga-do-biurka-szara-60-x-71-cm-sign-27961.feed10009', 'Tvilum');
