-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19120', 'Fotel kubełkowy tapicerowany fioletowy Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-fioletowy-tana-19120.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19121', 'Sofa 2-osobowa tapicerowana fioletowa Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-fioletowa-tana-19121.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19122', 'Fotel kubełkowy tapicerowany czarny Tana', 'Fotele/Fotele kubełkowe', 1349.0, 'https://www.meblepumo.pl/pl/products/fotel-kubelkowy-tapicerowany-czarny-tana-19122.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19123', 'Sofa 2-osobowa tapicerowana czarna Tana', 'Sofy i narożniki/Sofy 2-osobowe', 1749.0, 'https://www.meblepumo.pl/pl/products/sofa-2-osobowa-tapicerowana-czarna-tana-19123.feed10009', 'Scandinavian Style Design');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19133', 'Stolik kawowy z półką biały mat 110 x 65 cm Kwadro', 'Stoliki kawowe i ławy/Stoliki kawowe', 299.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-bialy-mat-110-x-65-cm-kwadro-19133.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19136', 'Stolik kawowy z półką dąb wotan mat 110 x 65 cm Kwadro', 'Stoliki kawowe i ławy/Stoliki kawowe', 299.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-wotan-mat-110-x-65-cm-kwadro-19136.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19140', 'Stolik kawowy z półką dąb sonoma mat 110 x 65 cm Kwadro', 'Stoliki kawowe i ławy/Stoliki kawowe', 299.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-z-polka-dab-sonoma-mat-110-x-65-cm-kwadro-19140.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19151', 'Stolik kawowy loftowy dąb naturalny / czarny mat 44 cm Rolo', 'Stoliki kawowe i ławy/Stoliki kawowe', 319.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-loftowy-dab-naturalny-czarny-mat-44-cm-rolo-19151.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19184', 'Szafka nocna szara mat 48 cm Huggle', 'Szafki nocne', 449.0, 'https://www.meblepumo.pl/pl/products/szafka-nocna-szara-mat-48-cm-huggle-19184.feed10009', 'Style Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('19185', 'Fotel obrotowy ekoskóra biały Luxor', 'Fotele/Fotele wypoczynkowe', 2129.0, 'https://www.meblepumo.pl/pl/products/fotel-obrotowy-ekoskora-bialy-luxor-19185.feed10009', 'HALMAR');
