-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27999', 'Stół ogrodowy biały mat 70 x 70 cm Bosco', 'Stoly/Stoły ogrodowe', 359.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-bialy-mat-70-x-70-cm-bosco-27999.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28000', 'Stół ogrodowy czarny mat 70 x 70 cm Bosco', 'Stoly/Stoły ogrodowe', 359.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-czarny-mat-70-x-70-cm-bosco-28000.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28002', 'Stół ogrodowy czarny mat 140 x 70 cm Bosco', 'Stoly/Stoły ogrodowe', 499.0, 'https://www.meblepumo.pl/pl/products/stol-ogrodowy-czarny-mat-140-x-70-cm-bosco-28002.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28004', 'Biurko Madrid, 120 x 48 x 76 cm, 3 szuflady, biały mat ', 'Biurka/Biurka z szufladami i drzwiami', 699.0, 'https://www.meblepumo.pl/pl/products/biurko-madrid-120-x-48-x-76-cm-3-szuflady-bialy-mat-28004.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28005', 'Biurko Madrid 120 x 48 x 76 cm, 3 szuflady, czarny mat ', 'Biurka/Biurka z szufladami i drzwiami', 829.0, 'https://www.meblepumo.pl/pl/products/biurko-madrid-120-x-48-x-76-cm-3-szuflady-czarny-mat-28005.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28008', 'Witryna dwudrzwiowa czarna mat 86 x 47 x 180 cm Aura', 'Witryny i kredensy/Witryny', 1539.0, 'https://www.meblepumo.pl/pl/products/witryna-dwudrzwiowa-czarna-mat-86-x-47-x-180-cm-aura-28008.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28014', 'Kredens z nadstawką Emerald, 146 x 45 x 198 cm, ciemno zielony, dąb Evoke ', 'Witryny i kredensy/Kredensy', 2869.0, 'https://www.meblepumo.pl/pl/products/kredens-z-nadstawka-emerald-146-x-45-x-198-cm-ciemno-zielony-dab-evoke-28014.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28015', 'Szafka RTV zielona / dąb mat 184 cm Emerald', 'Szafki RTV', 1499.0, 'https://www.meblepumo.pl/pl/products/szafka-rtv-zielona-dab-mat-184-cm-emerald-28015.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28016', 'Komoda Emerald 184 cm, 2 drzwi, 3 szuflady, ciemny zielony, dąb Evoke', 'Komody/Komody z szufladami i drzwiami', 1749.0, 'https://www.meblepumo.pl/pl/products/komoda-emerald-184-cm-2-drzwi-3-szuflady-ciemny-zielony-dab-evoke-28016.feed10009', 'TT-furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28017', 'Komoda Emerald 146 cm, 2 drzwi, 3 szuflady, ciemny zielony, dąb Evoke', 'Komody/Komody z szufladami i drzwiami', 1559.0, 'https://www.meblepumo.pl/pl/products/komoda-emerald-146-cm-2-drzwi-3-szuflady-ciemny-zielony-dab-evoke-28017.feed10009', 'TT-furniture');
