-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27675', 'Szafka dolna z szufladami biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 624.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-z-szufladami-biala-dab-miodowy-mat-60-cm-vento-27675.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27681', 'Szafka dolna z szufladami biała / jasnoszara mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 714.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-z-szufladami-biala-jasnoszara-mat-wysoki-polysk-80-cm-vento-27681.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27687', 'Szafka dolna biała / dąb miodowy mat 40 cm Vento', 'Szafki kuchenne', 233.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-biala-dab-miodowy-mat-40-cm-vento-27687.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27690', 'Szafka dolna biała / beżowa mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 313.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-biala-bezowa-mat-wysoki-polysk-60-cm-vento-27690.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27692', 'Szafka dolna biała / dąb miodowy mat 60 cm Vento', 'Szafki kuchenne', 313.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-biala-dab-miodowy-mat-60-cm-vento-27692.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27694', 'Szafka dolna antracyt mat 80 cm Vento', 'Szafki kuchenne', 399.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-antracyt-mat-80-cm-vento-27694.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27695', 'Szafka dolna biała / beżowa mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 399.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-biala-bezowa-mat-wysoki-polysk-80-cm-vento-27695.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27698', 'Szafka dolna biała / jasnoszara mat / wysoki połysk 80 cm Vento', 'Szafki kuchenne', 399.0, 'https://www.meblepumo.pl/pl/products/szafka-dolna-biala-jasnoszara-mat-wysoki-polysk-80-cm-vento-27698.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27699', 'Szafka zlewozmywakowa antracyt mat 60 cm Vento', 'Szafki kuchenne', 257.0, 'https://www.meblepumo.pl/pl/products/szafka-zlewozmywakowa-antracyt-mat-60-cm-vento-27699.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27700', 'Szafka zlewozmywakowa biała / beżowa mat / wysoki połysk 60 cm Vento', 'Szafki kuchenne', 257.0, 'https://www.meblepumo.pl/pl/products/szafka-zlewozmywakowa-biala-bezowa-mat-wysoki-polysk-60-cm-vento-27700.feed10009', 'HALMAR');
