-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26920', 'Fotel biurowy ekoskóra czarny Stanley', 'Fotele/Fotele do biurka', 549.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-czarny-stanley-26920.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26922', 'Zestaw mebli do jadalni wenge / espresso 110 x 72 cm New Starter 2', 'Zestawy mebli/Zestawy mebli do jadalni', 899.0, 'https://www.meblepumo.pl/pl/products/zestaw-mebli-do-jadalni-wenge-espresso-110-x-72-cm-new-starter-2-26922.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26926', 'Fotel biurowy ekoskóra czarny Stilo', 'Fotele/Fotele do biurka', 589.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-ekoskora-czarny-stilo-26926.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26927', 'Stół okrągły dąb złoty / biały mat / połysk 80 cm Sting', 'Stoly/Stoły nierozkładane', 409.0, 'https://www.meblepumo.pl/pl/products/stol-okragly-dab-zloty-bialy-mat-polysk-80-cm-sting-26927.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26943', 'Fotel wypoczynkowy velvet zielony Titan', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-zielony-titan-26943.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26944', 'Fotel wypoczynkowy velvet granatowy Titan', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-granatowy-titan-26944.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26945', 'Fotel wypoczynkowy velvet musztardowy Titan', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-musztardowy-titan-26945.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26946', 'Fotel wypoczynkowy velvet szary Titan', 'Fotele/Fotele wypoczynkowe', 899.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-velvet-szary-titan-26946.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26947', 'Stół rozkładany szary mat 160 - 210 x 76 cm Tiziano', 'Stoly/Stoły rozkładane', 2819.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-szary-mat-160-210-x-76-cm-tiziano-26947.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26955', 'Fotel biurowy siatka / ekoskóra czarny Torino', 'Fotele/Fotele do biurka', 485.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-ekoskora-czarny-torino-26955.feed10009', 'HALMAR');
