-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26876', 'Stolik kawowy okrągły naturalny / czarny mat 38 cm Sasha', 'Stoliki kawowe i ławy/Stoliki kawowe', 239.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-naturalny-czarny-mat-38-cm-sasha-26876.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26877', 'Fotel gabinetowy ekoskóra biały Saturn', 'Fotele/Fotele do biurka', 569.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-bialy-saturn-26877.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26878', 'Fotel gabinetowy ekoskóra czarny Saturn', 'Fotele/Fotele do biurka', 569.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-czarny-saturn-26878.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26879', 'Fotel gabinetowy ekoskóra szary Saturn', 'Fotele/Fotele do biurka', 569.0, 'https://www.meblepumo.pl/pl/products/fotel-gabinetowy-ekoskora-szary-saturn-26879.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26880', 'Stolik kawowy szklany transparentny / biały / czarny mat / połysk 110 x 60 cm Savana', 'Stoliki kawowe i ławy/Stoliki kawowe', 579.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-transparentny-bialy-czarny-mat-polysk-110-x-60-cm-savana-26880.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26884', 'Stolik kawowy szklany dymiony / chrom mat / połysk 55 cm Selena', 'Stoliki kawowe i ławy/Stoliki kawowe', 724.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-szklany-dymiony-chrom-mat-polysk-55-cm-selena-26884.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26887', 'Fotel biurowy tapicerowany czarny Sidney', 'Fotele/Fotele do biurka', 765.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-tapicerowany-czarny-sidney-26887.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26893', 'Łóżko tapicerowane białe 160x200 cm Sofia', 'Łóżka i części/Łóżka', 2015.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-biale-160x200-cm-sofia-26893.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26897', 'Fotel wypoczynkowy tapicerowany zielony Soft 3', 'Fotele/Fotele wypoczynkowe', 1035.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-zielony-soft-3-26897.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26900', 'Fotel biurowy siatka szary / czarny Solaris', 'Fotele/Fotele do biurka', 465.0, 'https://www.meblepumo.pl/pl/products/fotel-biurowy-siatka-szary-czarny-solaris-26900.feed10009', 'HALMAR');
