-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26986', 'Łóżko dwuosobowe czereśnia antyczna / czarny 160x200 cm Valentina', 'Łóżka i części/Łóżka', 1299.0, 'https://www.meblepumo.pl/pl/products/lozko-dwuosobowe-czeresnia-antyczna-czarny-160x200-cm-valentina-26986.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26995', 'Stół rozkładany dąb naturalny / czarny mat 160 - 200 x 90 cm Veldon', 'Stoly/Stoły rozkładane', 2222.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-dab-naturalny-czarny-mat-160-200-x-90-cm-veldon-26995.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('26999', 'Ławka tapicerowana różowa / złota 78 cm Velva', 'Ławki do przedpokoju', 269.0, 'https://www.meblepumo.pl/pl/products/lawka-tapicerowana-rozowa-zlota-78-cm-velva-26999.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27001', 'Stolik kawowy okrągły dymiony / srebrny mat / połysk 80 cm Venus', 'Stoliki kawowe i ławy/Stoliki kawowe', 899.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-okragly-dymiony-srebrny-mat-polysk-80-cm-venus-27001.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27004', 'Stół rozkładany czarny marmur mat 130 - 180 x 76 cm Vertigo', 'Stoly/Stoły rozkładane', 2829.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-czarny-marmur-mat-130-180-x-76-cm-vertigo-27004.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27006', 'Stolik kawowy prostokątny naturalny / czarny mat 100 x 60 cm Vespa', 'Stoliki kawowe i ławy/Stoliki kawowe', 309.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-prostokatny-naturalny-czarny-mat-100-x-60-cm-vespa-27006.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27030', 'Stół rozkładany biały / srebrny mat / połysk 160 - 200 x 90 cm Vision', 'Stoly/Stoły rozkładane', 1913.0, 'https://www.meblepumo.pl/pl/products/stol-rozkladany-bialy-srebrny-mat-polysk-160-200-x-90-cm-vision-27030.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27032', 'Fotel wypoczynkowy tapicerowany szary Volker', 'Fotele/Fotele wypoczynkowe', 1179.0, 'https://www.meblepumo.pl/pl/products/fotel-wypoczynkowy-tapicerowany-szary-volker-27032.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27033', 'Ława kawowa dąb złoty / czarna mat 113 x 63 cm Volta', 'Stoliki kawowe i ławy/Ławy', 513.0, 'https://www.meblepumo.pl/pl/products/lawa-kawowa-dab-zloty-czarna-mat-113-x-63-cm-volta-27033.feed10009', 'HALMAR');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('27037', 'Wieszak drewniany stojący biały mat 185 cm W13', 'Wieszaki na ubrania/Wieszaki stojące', 209.0, 'https://www.meblepumo.pl/pl/products/wieszak-drewniany-stojacy-bialy-mat-185-cm-w13-27037.feed10009', 'HALMAR');
