-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('609', 'Stelaż Power42 NV', 'Łóżka i części/Stelaże do łóżek', 400.0, 'https://www.meblepumo.pl/pl/products/stelaz-power42-nv-609.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('2080', 'Kieszenie do łóżka różowe 93x38 cm Steens', 'Łóżka i części/Części do łóżek', 40.0, 'https://www.meblepumo.pl/pl/products/kieszenie-do-lozka-rozowe-93x38-cm-steens-2080.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('2100', 'Łóżko pojedyncze Steens For Kids', 'Pozostałe produkty', 899.0, 'https://www.meblepumo.pl/pl/products/lozko-pojedyncze-steens-for-kids-2100.feed10009', 'Steens');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('2863', 'Ława kawowa śliwka mat 110 x 60 cm High Gloss Furniture', 'Pozostałe produkty', 399.0, 'https://www.meblepumo.pl/pl/products/lawa-kawowa-sliwka-mat-110-x-60-cm-high-gloss-furniture-2863.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('2864', 'Ława kawowa biały mat 110 x 60 cm High Gloss Furniture', 'Pozostałe produkty', 399.0, 'https://www.meblepumo.pl/pl/products/lawa-kawowa-bialy-mat-110-x-60-cm-high-gloss-furniture-2864.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('3167', 'Stelaż do łóżka 90x200 cm Futura NV', 'Łóżka i części/Stelaże do łóżek', 429.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-90x200-cm-futura-nv-3167.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('3168', 'Stelaż do łóżka 140x200 cm Futura NV', 'Łóżka i części/Stelaże do łóżek', 619.0, 'https://www.meblepumo.pl/pl/products/stelaz-do-lozka-140x200-cm-futura-nv-3168.feed10009', 'RECTICEL Komfort Snu Sp. z o.o.');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('3473', 'Biurko z szufladami białe mat 120 cm Function', 'Biurka/Biurka z szufladami i drzwiami', 459.0, 'https://www.meblepumo.pl/pl/products/biurko-z-szufladami-biale-mat-120-cm-function-3473.feed10009', 'Tvilum');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('3612', 'Lustro MARGO ML2', 'Lustra', 449.0, 'https://www.meblepumo.pl/pl/products/lustro-margo-ml2-3612.feed10009', 'AllHall');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('3962', 'Łóżko Style 140x200 cm', 'Łóżka i części/Łóżka', 1199.0, 'https://www.meblepumo.pl/pl/products/lozko-style-140x200-cm-3962.feed10009', 'Tvilum');
