-- Batch import SQL
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28320', 'Witryna jednodrzwiowa biała mat 60 x 178 cm Ardea', 'Witryny i kredensy/Witryny', 969.0, 'https://www.meblepumo.pl/pl/products/witryna-jednodrzwiowa-biala-mat-60-x-178-cm-ardea-28320.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28321', 'Komoda z szufladami i drzwiami kaszmir mat 150 cm Ardea', 'Komody/Komody z drzwiami', 1039.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-kaszmir-mat-150-cm-ardea-28321.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28322', 'Komoda z szufladami i drzwiami czarna mat 150 cm Ardea', 'Komody/Komody z drzwiami', 1039.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-czarna-mat-150-cm-ardea-28322.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28323', 'Komoda z szufladami i drzwiami biała mat 150 cm Ardea', 'Komody/Komody z drzwiami', 1019.0, 'https://www.meblepumo.pl/pl/products/komoda-z-szufladami-i-drzwiami-biala-mat-150-cm-ardea-28323.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28324', 'Komplet szafek nocnych kaszmir mat 45 cm Ardea', 'Szafki nocne', 599.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-kaszmir-mat-45-cm-ardea-28324.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28325', 'Komplet szafek nocnych czarny mat 45 cm Ardea', 'Szafki nocne', 599.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-czarny-mat-45-cm-ardea-28325.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28326', 'Komplet szafek nocnych biały mat 45 cm Ardea', 'Szafki nocne', 549.0, 'https://www.meblepumo.pl/pl/products/komplet-szafek-nocnych-bialy-mat-45-cm-ardea-28326.feed10009', 'High Glossy Furniture');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28327', 'Stolik kawowy kwadratowy dąb / czarny mat 70 x 70 cm Lift', 'Stoliki kawowe i ławy/Stoliki kawowe', 1229.0, 'https://www.meblepumo.pl/pl/products/stolik-kawowy-kwadratowy-dab-czarny-mat-70-x-70-cm-lift-28327.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28328', 'Łóżko tapicerowane beżowe 140x200 cm Nubo', 'Łóżka i części/Łóżka', 1999.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-bezowe-140x200-cm-nubo-28328.feed10009', 'Fato Luxmeble');
INSERT OR REPLACE INTO products (id, name, category, price, url, description) VALUES ('28329', 'Łóżko tapicerowane beżowe 180x200 cm Nubo', 'Łóżka i części/Łóżka', 2099.0, 'https://www.meblepumo.pl/pl/products/lozko-tapicerowane-bezowe-180x200-cm-nubo-28329.feed10009', 'Fato Luxmeble');
