# GitHub Actions Workflow - Deploy All Projects
# Deployment całego monorepo (wszystkie projekty)

name: Deploy All Projects

on:
  # Manualny trigger - użyj z GitHub UI
  workflow_dispatch:
  
  # Lub przy tagach release
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  deployments: write

env:
  NODE_VERSION: '18'

jobs:
  # Job 1: Deploy Main App
  deploy-main:
    name: Deploy Main App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install & Build & Deploy Main App
        working-directory: ./main-app
        run: |
          npm ci
          npm run build
      
      - name: Deploy Main App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=mybonzo-main-app --branch=main
          workingDirectory: ./main-app

  # Job 2: Deploy Subpage
  deploy-subpage:
    name: Deploy Subpage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install & Build Subpage
        working-directory: ./subpage
        run: |
          npm ci
          npm run build
      
      - name: Deploy Subpage
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=mybonzo-subpage --branch=main
          workingDirectory: ./subpage

  # Job 3: Deploy Worker Proxy
  # UWAGA: Deploy worker OSTATNI (po Pages)
  deploy-proxy:
    name: Deploy Proxy Worker
    runs-on: ubuntu-latest
    needs: [deploy-main, deploy-subpage]  # Czeka na Pages deployments
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Worker deps
        working-directory: ./worker-proxy
        run: npm ci
      
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy index.js
          workingDirectory: ./worker-proxy

  # Job 4: Summary
  deployment-summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [deploy-main, deploy-subpage, deploy-proxy]
    steps:
      - name: Print deployment summary
        run: |
          echo "🎉 All projects deployed successfully!"
          echo ""
          echo "📦 Deployed projects:"
          echo "  ✅ Main App: https://mybonzo-main-app.pages.dev"
          echo "  ✅ Subpage: https://mybonzo-subpage.pages.dev"
          echo "  ✅ Proxy Worker: mybonzo-proxy-worker"
          echo ""
          echo "🌐 Public URLs (via proxy):"
          echo "  🔗 Main: https://example.com"
          echo "  🔗 Subpage: https://example.com/subpage/"
          echo ""
          echo "📝 Tag/Commit: ${{ github.ref_name }}"
          echo "🕐 Time: $(date -u)"
