export const categoryMap: Record<string, string> = {
    "Biurka": "https://www.meblepumo.pl/pl/menu/meble/biurka-3619",
    "Dodatki do mebli": "https://www.meblepumo.pl/pl/menu/meble/dodatki-do-mebli-3875",
    "Fotele": "https://www.meblepumo.pl/pl/menu/meble/fotele-3591",
    "Hokery": "https://www.meblepumo.pl/pl/menu/meble/hokery-3594",
    "Komody": "https://www.meblepumo.pl/pl/menu/meble/komody-3271",
    "Kontenerki": "https://www.meblepumo.pl/pl/menu/meble/kontenerki-3620",
    "Krzesła": "https://www.meblepumo.pl/pl/menu/meble/krzesla-3598",
    "Lustra": "https://www.meblepumo.pl/pl/menu/meble/lustra-3608",
    "Ławki do przedpokoju": "https://www.meblepumo.pl/pl/menu/meble/lawki-do-przedpokoju-3623",
    "Łóżka": "https://www.meblepumo.pl/pl/menu/meble/lozka-i-czesci-3609",
    "Łóżka i części": "https://www.meblepumo.pl/pl/menu/meble/lozka-i-czesci-3609",
    "Łóżka dziecięce": "https://www.meblepumo.pl/pl/menu/meble/lozka-dzieciece-3621",
    "Materace": "https://www.meblepumo.pl/pl/menu/meble/materace-3610",
    "Meblościanki": "https://www.meblepumo.pl/pl/menu/meble/mebloscianki-3600",
    "Półki": "https://www.meblepumo.pl/pl/menu/meble/polki-wiszace-3602",
    "Półki wiszące": "https://www.meblepumo.pl/pl/menu/meble/polki-wiszace-3602",
    "Pufy": "https://www.meblepumo.pl/pl/menu/meble/pufy-3597",
    "Regały": "https://www.meblepumo.pl/pl/menu/meble/regaly-3603",
    "Sofy": "https://www.meblepumo.pl/pl/menu/meble/sofy-i-narozniki-3270",
    "Sofy i narożniki": "https://www.meblepumo.pl/pl/menu/meble/sofy-i-narozniki-3270",
    "Narożniki": "https://www.meblepumo.pl/pl/menu/meble/sofy-i-narozniki-3270",
    "Stoliki kawowe": "https://www.meblepumo.pl/pl/menu/meble/stoliki-kawowe-i-lawy-3599",
    "Stoliki kawowe i ławy": "https://www.meblepumo.pl/pl/menu/meble/stoliki-kawowe-i-lawy-3599",
    "Stoły": "https://www.meblepumo.pl/pl/menu/meble/stoly-3605",
    "Szafki RTV": "https://www.meblepumo.pl/pl/menu/meble/szafki-rtv-3829",
    "Szafki kuchenne": "https://www.meblepumo.pl/pl/menu/meble/szafki-kuchenne-3828",
    "Szafki na buty": "https://www.meblepumo.pl/pl/menu/meble/szafki-na-buty-3624",
    "Szafki nocne": "https://www.meblepumo.pl/pl/menu/meble/szafki-nocne-3614",
    "Szafki modułowe": "https://www.meblepumo.pl/pl/menu/meble/szafki-modulowe-3607",
    "Szafy": "https://www.meblepumo.pl/pl/menu/meble/szafy-3615",
    "Szezlongi": "https://www.meblepumo.pl/pl/menu/meble/szezlongi-3642",
    "Toaletki": "https://www.meblepumo.pl/pl/menu/meble/toaletki-i-konsole-3617",
    "Toaletki i konsole": "https://www.meblepumo.pl/pl/menu/meble/toaletki-i-konsole-3617",
    "Wieszaki": "https://www.meblepumo.pl/pl/menu/meble/wieszaki-na-ubrania-3625",
    "Wieszaki na ubrania": "https://www.meblepumo.pl/pl/menu/meble/wieszaki-na-ubrania-3625",
    "Witryny": "https://www.meblepumo.pl/pl/menu/meble/witryny-i-kredensy-3596",
    "Witryny i kredensy": "https://www.meblepumo.pl/pl/menu/meble/witryny-i-kredensy-3596",
    "Skrzynie": "https://www.meblepumo.pl/pl/menu/meble/skrzynie-3612",
    "Zestawy mebli": "https://www.meblepumo.pl/pl/menu/meble/zestawy-mebli-4847"
};

export function getCategoryUrl(categoryName: string): string {
    return categoryMap[categoryName] || "https://www.meblepumo.pl";
}
